/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.9e609a1b-c462-421a-8c76-4c9774ea7671.tasks;

public class FHelper {
    public static final  int[] bd;
    public static final  int[] be;
    public static final  int[] aX;
    public static final  int ay;
    public static final  int[] aY;
    public static final  int[] ba;
    public static final  int aw;
    public static final  int[] aR;
    public static final  int av;
    public static final  int[] aS;
    public static final  int[] bi;
    public static final  int ax;
    public static final  int ar;
    public static final  int[] bg;
    public static final  int[] aT;
    public static final  int[] bf;
    public static final  int az;
    public static final  int[] aV;
    public static final  int[] aZ;
    public static final  int aC;
    public static final  int aP;
    public static final  int ah;
    public static final  int[] bj;
    public static final  int[] bl;
    public static final  int aH;
    public static final  int aL;
    public static final  int ap;
    public static final  int aD;
    public static final  int[] bk;
    public static final  int[] bm;
    public static final  int aG;
    public static final  int aO;
    public static final  int an;
    public static final  int[] bc;
    public static final  int at;
    public static final  int[] bh;
    
    public static final  int aj;
    public static final  int aN;
    public static final  int aQ;
    public static final  int ao;
    public static final  int as;
    public static final  int aK;
    public static final  int aJ;
    public static final  int am;
    public static final  int ak;
    public static final  int aM;
    public static final  int[] aU;
    public static final  int aq;
    public static final  int au;
    public static final  int aB;
    public static final  int[] aW;
    public static final  int aA;
    public static final  int aI;
    public static final  int ai;
    public static final  int[] bb;
    public static final  int aE;
    public static final  int aF;
    public static final  int al;

    static {
        f.lIlIIllIlIIllII();
        aM = lIIIllllllIlI[0];
        ar = lIIIllllllIlI[1];
        aF = lIIIllllllIlI[2];
        aQ = lIIIllllllIlI[3];
        aG = lIIIllllllIlI[4];
        aE = lIIIllllllIlI[5];
        aN = lIIIllllllIlI[6];
        aw = lIIIllllllIlI[7];
        ax = lIIIllllllIlI[8];
        aL = lIIIllllllIlI[9];
        am = lIIIllllllIlI[10];
        as = lIIIllllllIlI[11];
        aB = lIIIllllllIlI[12];
        ah = lIIIllllllIlI[13];
        aA = lIIIllllllIlI[14];
        aD = lIIIllllllIlI[15];
        aP = lIIIllllllIlI[16];
        ai = lIIIllllllIlI[17];
        aK = lIIIllllllIlI[18];
        au = lIIIllllllIlI[19];
        aJ = lIIIllllllIlI[20];
        az = lIIIllllllIlI[21];
        ao = lIIIllllllIlI[22];
        ak = lIIIllllllIlI[23];
        an = lIIIllllllIlI[24];
        ap = lIIIllllllIlI[25];
        aq = lIIIllllllIlI[26];
        aO = lIIIllllllIlI[27];
        at = lIIIllllllIlI[28];
        ay = lIIIllllllIlI[29];
        aj = lIIIllllllIlI[30];
        aI = lIIIllllllIlI[31];
        aC = lIIIllllllIlI[32];
        av = lIIIllllllIlI[33];
        aH = lIIIllllllIlI[34];
        al = lIIIllllllIlI[35];
        int[] nArray = new int[lIIIllllllIlI[36]];
        nArray[f.lIIIllllllIlI[12]] = lIIIllllllIlI[10];
        nArray[f.lIIIllllllIlI[37]] = lIIIllllllIlI[24];
        nArray[f.lIIIllllllIlI[38]] = lIIIllllllIlI[16];
        aR = nArray;
        int[] nArray2 = new int[lIIIllllllIlI[39]];
        nArray2[f.lIIIllllllIlI[12]] = lIIIllllllIlI[22];
        nArray2[f.lIIIllllllIlI[37]] = lIIIllllllIlI[40];
        nArray2[f.lIIIllllllIlI[38]] = lIIIllllllIlI[41];
        nArray2[f.lIIIllllllIlI[36]] = lIIIllllllIlI[42];
        nArray2[f.lIIIllllllIlI[43]] = lIIIllllllIlI[44];
        nArray2[f.lIIIllllllIlI[45]] = lIIIllllllIlI[46];
        nArray2[f.lIIIllllllIlI[47]] = lIIIllllllIlI[48];
        nArray2[f.lIIIllllllIlI[49]] = lIIIllllllIlI[50];
        aS = nArray2;
        int[] nArray3 = new int[lIIIllllllIlI[51]];
        nArray3[f.lIIIllllllIlI[12]] = lIIIllllllIlI[52];
        nArray3[f.lIIIllllllIlI[37]] = lIIIllllllIlI[53];
        nArray3[f.lIIIllllllIlI[38]] = lIIIllllllIlI[54];
        nArray3[f.lIIIllllllIlI[36]] = lIIIllllllIlI[55];
        nArray3[f.lIIIllllllIlI[43]] = lIIIllllllIlI[56];
        nArray3[f.lIIIllllllIlI[45]] = lIIIllllllIlI[57];
        nArray3[f.lIIIllllllIlI[47]] = lIIIllllllIlI[58];
        nArray3[f.lIIIllllllIlI[49]] = lIIIllllllIlI[59];
        nArray3[f.lIIIllllllIlI[39]] = lIIIllllllIlI[59];
        aT = nArray3;
        int[] nArray4 = new int[lIIIllllllIlI[43]];
        nArray4[f.lIIIllllllIlI[12]] = lIIIllllllIlI[60];
        nArray4[f.lIIIllllllIlI[37]] = lIIIllllllIlI[61];
        nArray4[f.lIIIllllllIlI[38]] = lIIIllllllIlI[62];
        nArray4[f.lIIIllllllIlI[36]] = lIIIllllllIlI[63];
        aU = nArray4;
        int[] nArray5 = new int[lIIIllllllIlI[43]];
        nArray5[f.lIIIllllllIlI[12]] = lIIIllllllIlI[64];
        nArray5[f.lIIIllllllIlI[37]] = lIIIllllllIlI[65];
        nArray5[f.lIIIllllllIlI[38]] = lIIIllllllIlI[66];
        nArray5[f.lIIIllllllIlI[36]] = lIIIllllllIlI[67];
        aV = nArray5;
        int[] nArray6 = new int[lIIIllllllIlI[47]];
        nArray6[f.lIIIllllllIlI[12]] = lIIIllllllIlI[68];
        nArray6[f.lIIIllllllIlI[37]] = lIIIllllllIlI[69];
        nArray6[f.lIIIllllllIlI[38]] = lIIIllllllIlI[70];
        nArray6[f.lIIIllllllIlI[36]] = lIIIllllllIlI[71];
        nArray6[f.lIIIllllllIlI[43]] = lIIIllllllIlI[27];
        nArray6[f.lIIIllllllIlI[45]] = lIIIllllllIlI[72];
        aW = nArray6;
        int[] nArray7 = new int[lIIIllllllIlI[43]];
        nArray7[f.lIIIllllllIlI[12]] = lIIIllllllIlI[73];
        nArray7[f.lIIIllllllIlI[37]] = lIIIllllllIlI[74];
        nArray7[f.lIIIllllllIlI[38]] = lIIIllllllIlI[75];
        nArray7[f.lIIIllllllIlI[36]] = lIIIllllllIlI[76];
        aX = nArray7;
        int[] nArray8 = new int[lIIIllllllIlI[43]];
        nArray8[f.lIIIllllllIlI[12]] = lIIIllllllIlI[77];
        nArray8[f.lIIIllllllIlI[37]] = lIIIllllllIlI[78];
        nArray8[f.lIIIllllllIlI[38]] = lIIIllllllIlI[79];
        nArray8[f.lIIIllllllIlI[36]] = lIIIllllllIlI[80];
        aY = nArray8;
        int[] nArray9 = new int[lIIIllllllIlI[36]];
        nArray9[f.lIIIllllllIlI[12]] = lIIIllllllIlI[77];
        nArray9[f.lIIIllllllIlI[37]] = lIIIllllllIlI[78];
        nArray9[f.lIIIllllllIlI[38]] = lIIIllllllIlI[79];
        aZ = nArray9;
        int[] nArray10 = new int[lIIIllllllIlI[43]];
        nArray10[f.lIIIllllllIlI[12]] = lIIIllllllIlI[81];
        nArray10[f.lIIIllllllIlI[37]] = lIIIllllllIlI[82];
        nArray10[f.lIIIllllllIlI[38]] = lIIIllllllIlI[83];
        nArray10[f.lIIIllllllIlI[36]] = lIIIllllllIlI[84];
        ba = nArray10;
        int[] nArray11 = new int[lIIIllllllIlI[43]];
        nArray11[f.lIIIllllllIlI[12]] = lIIIllllllIlI[85];
        nArray11[f.lIIIllllllIlI[37]] = lIIIllllllIlI[86];
        nArray11[f.lIIIllllllIlI[38]] = lIIIllllllIlI[87];
        nArray11[f.lIIIllllllIlI[36]] = lIIIllllllIlI[88];
        bb = nArray11;
        int[] nArray12 = new int[lIIIllllllIlI[43]];
        nArray12[f.lIIIllllllIlI[12]] = lIIIllllllIlI[89];
        nArray12[f.lIIIllllllIlI[37]] = lIIIllllllIlI[90];
        nArray12[f.lIIIllllllIlI[38]] = lIIIllllllIlI[91];
        nArray12[f.lIIIllllllIlI[36]] = lIIIllllllIlI[92];
        bc = nArray12;
        int[] nArray13 = new int[lIIIllllllIlI[43]];
        nArray13[f.lIIIllllllIlI[12]] = lIIIllllllIlI[93];
        nArray13[f.lIIIllllllIlI[37]] = lIIIllllllIlI[94];
        nArray13[f.lIIIllllllIlI[38]] = lIIIllllllIlI[95];
        nArray13[f.lIIIllllllIlI[36]] = lIIIllllllIlI[96];
        bd = nArray13;
        int[] nArray14 = new int[lIIIllllllIlI[43]];
        nArray14[f.lIIIllllllIlI[12]] = lIIIllllllIlI[97];
        nArray14[f.lIIIllllllIlI[37]] = lIIIllllllIlI[98];
        nArray14[f.lIIIllllllIlI[38]] = lIIIllllllIlI[99];
        nArray14[f.lIIIllllllIlI[36]] = lIIIllllllIlI[100];
        be = nArray14;
        int[] nArray15 = new int[lIIIllllllIlI[45]];
        nArray15[f.lIIIllllllIlI[12]] = lIIIllllllIlI[101];
        nArray15[f.lIIIllllllIlI[37]] = lIIIllllllIlI[102];
        nArray15[f.lIIIllllllIlI[38]] = lIIIllllllIlI[103];
        nArray15[f.lIIIllllllIlI[36]] = lIIIllllllIlI[104];
        nArray15[f.lIIIllllllIlI[43]] = lIIIllllllIlI[105];
        bf = nArray15;
        int[] nArray16 = new int[lIIIllllllIlI[43]];
        nArray16[f.lIIIllllllIlI[12]] = lIIIllllllIlI[106];
        nArray16[f.lIIIllllllIlI[37]] = lIIIllllllIlI[107];
        nArray16[f.lIIIllllllIlI[38]] = lIIIllllllIlI[108];
        nArray16[f.lIIIllllllIlI[36]] = lIIIllllllIlI[109];
        bg = nArray16;
        int[] nArray17 = new int[lIIIllllllIlI[43]];
        nArray17[f.lIIIllllllIlI[12]] = lIIIllllllIlI[110];
        nArray17[f.lIIIllllllIlI[37]] = lIIIllllllIlI[111];
        nArray17[f.lIIIllllllIlI[38]] = lIIIllllllIlI[112];
        nArray17[f.lIIIllllllIlI[36]] = lIIIllllllIlI[113];
        bh = nArray17;
        int[] nArray18 = new int[lIIIllllllIlI[43]];
        nArray18[f.lIIIllllllIlI[12]] = lIIIllllllIlI[114];
        nArray18[f.lIIIllllllIlI[37]] = lIIIllllllIlI[115];
        nArray18[f.lIIIllllllIlI[38]] = lIIIllllllIlI[116];
        nArray18[f.lIIIllllllIlI[36]] = lIIIllllllIlI[117];
        bi = nArray18;
        int[] nArray19 = new int[lIIIllllllIlI[36]];
        nArray19[f.lIIIllllllIlI[12]] = lIIIllllllIlI[31];
        nArray19[f.lIIIllllllIlI[37]] = lIIIllllllIlI[34];
        nArray19[f.lIIIllllllIlI[38]] = lIIIllllllIlI[4];
        bj = nArray19;
        int[] nArray20 = new int[lIIIllllllIlI[45]];
        nArray20[f.lIIIllllllIlI[12]] = lIIIllllllIlI[25];
        nArray20[f.lIIIllllllIlI[37]] = lIIIllllllIlI[118];
        nArray20[f.lIIIllllllIlI[38]] = lIIIllllllIlI[119];
        nArray20[f.lIIIllllllIlI[36]] = lIIIllllllIlI[120];
        nArray20[f.lIIIllllllIlI[43]] = lIIIllllllIlI[121];
        bk = nArray20;
        int[] nArray21 = new int[lIIIllllllIlI[36]];
        nArray21[f.lIIIllllllIlI[12]] = lIIIllllllIlI[122];
        nArray21[f.lIIIllllllIlI[37]] = lIIIllllllIlI[123];
        nArray21[f.lIIIllllllIlI[38]] = lIIIllllllIlI[124];
        bl = nArray21;
        int[] nArray22 = new int[lIIIllllllIlI[43]];
        nArray22[f.lIIIllllllIlI[12]] = lIIIllllllIlI[125];
        nArray22[f.lIIIllllllIlI[37]] = lIIIllllllIlI[126];
        nArray22[f.lIIIllllllIlI[38]] = lIIIllllllIlI[127];
        nArray22[f.lIIIllllllIlI[36]] = lIIIllllllIlI[128];
        bm = nArray22;
    }
}

