/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.quest.tasks;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

public final class GameEnum15
extends Enum<a> {
    public static final  /* enum */ a QUEST_WITCHS_POTION;
    public static final  /* enum */ a QUEST_TEMPLE_OF_IKOV;
    public static final  /* enum */ a QUEST_MOURNINGS_END_PART_I;
    public static final  /* enum */ a QUEST_SHEEP_HERDER;
    public static final  /* enum */ a QUEST_ELEMENTAL_WORKSHOP_I;
    public static final  /* enum */ a QUEST_SHILO_VILLAGE;
    public static final  /* enum */ a QUEST_SHIELD_OF_ARRAV_STATE_146;
    public static final  /* enum */ a QUEST_THE_RESTLESS_GHOST;
    public static final  /* enum */ a QUEST_HAZEEL_CULT;
    public static final  /* enum */ a QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
    public static final  /* enum */ a QUEST_OBSERVATORY_QUEST;
    private final  int id;
    public static final  /* enum */ a QUEST_TAI_BWO_WANNAI_TRIO;
    public static final  /* enum */ a QUEST_FIGHT_ARENA;
    public static final  /* enum */ a QUEST_SHIELD_OF_ARRAV;
    public static final  /* enum */ a QUEST_THE_MAGE_ARENA;
    public static final  /* enum */ a QUEST_ROMEO_AND_JULIET;
    public static final  /* enum */ a QUEST_CLOCK_TOWER;
    public static final  /* enum */ a QUEST_JUNGLE_POTION;
    public static final  /* enum */ a QUEST_RUNE_MYSTERIES;
    public static final  /* enum */ a QUEST_MONKEY_MADNESS_I;
    public static final  /* enum */ a QUEST_LEGENDS_QUEST;
    
    public static final  /* enum */ a QUEST_BIOHAZARD;
    public static final  /* enum */ a QUEST_EADGARS_RUSE;
    public static final  /* enum */ a QUEST_SCORPION_CATCHER;
    public static final  /* enum */ a QUEST_ONE_SMALL_FAVOUR;
    public static final  /* enum */ a QUEST_THE_KNIGHTS_SWORD;
    public static final  /* enum */ a QUEST_HEROES_QUEST;
    public static final  /* enum */ a QUEST_WITCHS_HOUSE;
    public static final  /* enum */ a QUEST_ERNEST_THE_CHICKEN;
    public static final  /* enum */ a QUEST_MURDER_MYSTERY;
    public static final  /* enum */ a QUEST_DWARF_CANNON;
    public static final  /* enum */ a QUEST_LOST_CITY;
    public static final  /* enum */ a QUEST_GERTRUDES_CAT;
    public static final  /* enum */ a QUEST_SEA_SLUG;
    public static final  /* enum */ a QUEST_NATURE_SPIRIT;
    public static final  /* enum */ a QUEST_THE_FREMENNIK_TRIALS;
    private static final  a[] $VALUES;
    public static final  /* enum */ a QUEST_REGICIDE;
    public static final  /* enum */ a QUEST_ENTER_THE_ABYSS;
    public static final  /* enum */ a QUEST_FISHING_CONTEST;
    public static final  /* enum */ a QUEST_ROVING_ELVES;
    public static final  /* enum */ a QUEST_WATCHTOWER;
    public static final  /* enum */ a QUEST_VAMPYRE_SLAYER;
    public static final  /* enum */ a QUEST_COOKS_ASSISTANT;
    public static final  /* enum */ a QUEST_RAG_AND_BONE_MAN_II;
    public static final  /* enum */ a QUEST_PRIEST_IN_PERIL;
    public static final  /* enum */ a QUEST_TRIBAL_TOTEM;
    public static final  /* enum */ a QUEST_PIRATES_TREASURE;
    public static final  /* enum */ a QUEST_THE_GRAND_TREE;
    public static final  /* enum */ a QUEST_WATERFALL_QUEST;
    public static final  /* enum */ a QUEST_DORICS_QUEST;
    public static final  /* enum */ a QUEST_UNDERGROUND_PASS;
    public static final  /* enum */ a QUEST_CREATURE_OF_FENKENSTRAIN;
    public static final  /* enum */ a QUEST_IMP_CATCHER;
    public static final  /* enum */ a QUEST_BLACK_KNIGHTS_FORTRESS;
    public static final  /* enum */ a QUEST_CABIN_FEVER;
    public static final  /* enum */ a QUEST_DRAGON_SLAYER_I;
    public static final  /* enum */ a QUEST_MERLINS_CRYSTAL;
    public static final  /* enum */ a QUEST_BIG_CHOMPY_BIRD_HUNTING;
    public static final  /* enum */ a QUEST_UNDERGROUND_PASS_STATE_162;
    public static final  /* enum */ a QUEST_THE_DIG_SITE;
    public static final  /* enum */ a QUEST_RAG_AND_BONE_MAN_I;
    public static final  /* enum */ a QUEST_SHEEP_SHEARER;
    public static final  /* enum */ a QUEST_SHADES_OF_MORTTON;
    public static final  /* enum */ a QUEST_IN_SEARCH_OF_THE_MYREQUE;
    public static final  /* enum */ a QUEST_HAUNTED_MINE;
    public static final  /* enum */ a QUEST_DRUIDIC_RITUAL;
    public static final  /* enum */ a QUEST_FAMILY_CREST;
    public static final  /* enum */ a QUEST_PRINCE_ALI_RESCUE;
    public static final  /* enum */ a QUEST_THE_TOURIST_TRAP;
    public static final  /* enum */ a QUEST_THE_GREAT_BRAIN_ROBBERY;
    public static final  /* enum */ a QUEST_DEATH_PLATEAU;
    public static final  /* enum */ a QUEST_RUM_DEAL;
    public static final  /* enum */ a QUEST_TROLL_ROMANCE;
    public static final  /* enum */ a QUEST_TREE_GNOME_VILLAGE;
    
    public static final  /* enum */ a QUEST_HOLY_GRAIL;
    public static final  /* enum */ a QUEST_TROLL_STRONGHOLD;
    public static final  /* enum */ a QUEST_MONKS_FRIEND;
    public static final  /* enum */ a QUEST_ALFRED_GRIMHANDS_BARCRAWL;
    public static final  /* enum */ a QUEST_THRONE_OF_MISCELLANIA;
    public static final  /* enum */ a QUEST_PLAGUE_CITY;

    static {
        a.lIlIIIllIIIlIII();
        a.lIlIIIllIIIIlll();
        QUEST_BLACK_KNIGHTS_FORTRESS = new GameEnum15(lIIIllIllIIll[1]);
        QUEST_COOKS_ASSISTANT = new GameEnum15(lIIIllIllIIll[3]);
        QUEST_DORICS_QUEST = new GameEnum15(lIIIllIllIIll[5]);
        QUEST_DRAGON_SLAYER_I = new GameEnum15(lIIIllIllIIll[7]);
        QUEST_ERNEST_THE_CHICKEN = new GameEnum15(lIIIllIllIIll[9]);
        QUEST_IMP_CATCHER = new GameEnum15(lIIIllIllIIll[11]);
        QUEST_THE_KNIGHTS_SWORD = new GameEnum15(lIIIllIllIIll[13]);
        QUEST_PIRATES_TREASURE = new GameEnum15(lIIIllIllIIll[15]);
        QUEST_PRINCE_ALI_RESCUE = new GameEnum15(lIIIllIllIIll[17]);
        QUEST_THE_RESTLESS_GHOST = new GameEnum15(lIIIllIllIIll[19]);
        QUEST_ROMEO_AND_JULIET = new GameEnum15(lIIIllIllIIll[21]);
        QUEST_RUNE_MYSTERIES = new GameEnum15(lIIIllIllIIll[23]);
        QUEST_SHEEP_SHEARER = new GameEnum15(lIIIllIllIIll[25]);
        QUEST_SHIELD_OF_ARRAV = new GameEnum15(lIIIllIllIIll[27]);
        QUEST_SHIELD_OF_ARRAV_STATE_146 = new GameEnum15(lIIIllIllIIll[29]);
        QUEST_VAMPYRE_SLAYER = new GameEnum15(lIIIllIllIIll[31]);
        QUEST_WITCHS_POTION = new GameEnum15(lIIIllIllIIll[33]);
        QUEST_BIG_CHOMPY_BIRD_HUNTING = new GameEnum15(lIIIllIllIIll[35]);
        QUEST_BIOHAZARD = new GameEnum15(lIIIllIllIIll[37]);
        QUEST_CABIN_FEVER = new GameEnum15(lIIIllIllIIll[39]);
        QUEST_CLOCK_TOWER = new GameEnum15(lIIIllIllIIll[20]);
        QUEST_CREATURE_OF_FENKENSTRAIN = new GameEnum15(lIIIllIllIIll[42]);
        QUEST_DEATH_PLATEAU = new GameEnum15(lIIIllIllIIll[44]);
        QUEST_THE_DIG_SITE = new GameEnum15(lIIIllIllIIll[46]);
        QUEST_DRUIDIC_RITUAL = new GameEnum15(lIIIllIllIIll[48]);
        QUEST_DWARF_CANNON = new GameEnum15(lIIIllIllIIll[0]);
        QUEST_EADGARS_RUSE = new GameEnum15(lIIIllIllIIll[51]);
        QUEST_ELEMENTAL_WORKSHOP_I = new GameEnum15(lIIIllIllIIll[53]);
        QUEST_FAMILY_CREST = new GameEnum15(lIIIllIllIIll[55]);
        QUEST_FIGHT_ARENA = new GameEnum15(lIIIllIllIIll[34]);
        QUEST_FISHING_CONTEST = new GameEnum15(lIIIllIllIIll[22]);
        QUEST_THE_FREMENNIK_TRIALS = new GameEnum15(lIIIllIllIIll[57]);
        QUEST_WATERFALL_QUEST = new GameEnum15(lIIIllIllIIll[58]);
        QUEST_GERTRUDES_CAT = new GameEnum15(lIIIllIllIIll[60]);
        QUEST_THE_GRAND_TREE = new GameEnum15(lIIIllIllIIll[62]);
        QUEST_HAUNTED_MINE = new GameEnum15(lIIIllIllIIll[64]);
        QUEST_HAZEEL_CULT = new GameEnum15(lIIIllIllIIll[66]);
        QUEST_HEROES_QUEST = new GameEnum15(lIIIllIllIIll[68]);
        QUEST_HOLY_GRAIL = new GameEnum15(lIIIllIllIIll[10]);
        QUEST_IN_SEARCH_OF_THE_MYREQUE = new GameEnum15(lIIIllIllIIll[71]);
        QUEST_JUNGLE_POTION = new GameEnum15(lIIIllIllIIll[73]);
        QUEST_LEGENDS_QUEST = new GameEnum15(lIIIllIllIIll[75]);
        QUEST_LOST_CITY = new GameEnum15(lIIIllIllIIll[77]);
        QUEST_MERLINS_CRYSTAL = new GameEnum15(lIIIllIllIIll[28]);
        QUEST_MONKEY_MADNESS_I = new GameEnum15(lIIIllIllIIll[80]);
        QUEST_MONKS_FRIEND = new GameEnum15(lIIIllIllIIll[56]);
        QUEST_MOURNINGS_END_PART_I = new GameEnum15(lIIIllIllIIll[83]);
        QUEST_MURDER_MYSTERY = new GameEnum15(lIIIllIllIIll[85]);
        QUEST_NATURE_SPIRIT = new GameEnum15(lIIIllIllIIll[87]);
        QUEST_OBSERVATORY_QUEST = new GameEnum15(lIIIllIllIIll[89]);
        QUEST_ONE_SMALL_FAVOUR = new GameEnum15(lIIIllIllIIll[91]);
        QUEST_PLAGUE_CITY = new GameEnum15(lIIIllIllIIll[93]);
        QUEST_PRIEST_IN_PERIL = new GameEnum15(lIIIllIllIIll[95]);
        QUEST_RAG_AND_BONE_MAN_I = new GameEnum15(lIIIllIllIIll[97]);
        QUEST_REGICIDE = new GameEnum15(lIIIllIllIIll[99]);
        QUEST_ROVING_ELVES = new GameEnum15(lIIIllIllIIll[101]);
        QUEST_RUM_DEAL = new GameEnum15(lIIIllIllIIll[103]);
        QUEST_SCORPION_CATCHER = new GameEnum15(lIIIllIllIIll[105]);
        QUEST_SEA_SLUG = new GameEnum15(lIIIllIllIIll[107]);
        QUEST_SHADES_OF_MORTTON = new GameEnum15(lIIIllIllIIll[109]);
        QUEST_SHEEP_HERDER = new GameEnum15(lIIIllIllIIll[110]);
        QUEST_SHILO_VILLAGE = new GameEnum15(lIIIllIllIIll[112]);
        QUEST_TAI_BWO_WANNAI_TRIO = new GameEnum15(lIIIllIllIIll[114]);
        QUEST_TEMPLE_OF_IKOV = new GameEnum15(lIIIllIllIIll[50]);
        QUEST_THRONE_OF_MISCELLANIA = new GameEnum15(lIIIllIllIIll[116]);
        QUEST_THE_TOURIST_TRAP = new GameEnum15(lIIIllIllIIll[117]);
        QUEST_WITCHS_HOUSE = new GameEnum15(lIIIllIllIIll[119]);
        QUEST_TREE_GNOME_VILLAGE = new GameEnum15(lIIIllIllIIll[120]);
        QUEST_TRIBAL_TOTEM = new GameEnum15(lIIIllIllIIll[121]);
        QUEST_TROLL_ROMANCE = new GameEnum15(lIIIllIllIIll[123]);
        QUEST_TROLL_STRONGHOLD = new GameEnum15(lIIIllIllIIll[125]);
        QUEST_UNDERGROUND_PASS = new GameEnum15(lIIIllIllIIll[126]);
        QUEST_UNDERGROUND_PASS_STATE_162 = new GameEnum15(lIIIllIllIIll[128]);
        QUEST_WATCHTOWER = new GameEnum15(lIIIllIllIIll[130]);
        QUEST_THE_GREAT_BRAIN_ROBBERY = new GameEnum15(lIIIllIllIIll[132]);
        QUEST_RAG_AND_BONE_MAN_II = new GameEnum15(lIIIllIllIIll[97]);
        QUEST_ENTER_THE_ABYSS = new GameEnum15(lIIIllIllIIll[134]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL = new GameEnum15(lIIIllIllIIll[135]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76 = new GameEnum15(lIIIllIllIIll[105]);
        QUEST_THE_MAGE_ARENA = new GameEnum15(lIIIllIllIIll[138]);
        a[] aArray = new a[lIIIllIllIIll[48]];
        aArray[a.lIIIllIllIIll[0]] = QUEST_BLACK_KNIGHTS_FORTRESS;
        aArray[a.lIIIllIllIIll[2]] = QUEST_COOKS_ASSISTANT;
        aArray[a.lIIIllIllIIll[4]] = QUEST_DORICS_QUEST;
        aArray[a.lIIIllIllIIll[6]] = QUEST_DRAGON_SLAYER_I;
        aArray[a.lIIIllIllIIll[8]] = QUEST_ERNEST_THE_CHICKEN;
        aArray[a.lIIIllIllIIll[10]] = QUEST_IMP_CATCHER;
        aArray[a.lIIIllIllIIll[12]] = QUEST_THE_KNIGHTS_SWORD;
        aArray[a.lIIIllIllIIll[14]] = QUEST_PIRATES_TREASURE;
        aArray[a.lIIIllIllIIll[16]] = QUEST_PRINCE_ALI_RESCUE;
        aArray[a.lIIIllIllIIll[18]] = QUEST_THE_RESTLESS_GHOST;
        aArray[a.lIIIllIllIIll[20]] = QUEST_ROMEO_AND_JULIET;
        aArray[a.lIIIllIllIIll[22]] = QUEST_RUNE_MYSTERIES;
        aArray[a.lIIIllIllIIll[24]] = QUEST_SHEEP_SHEARER;
        aArray[a.lIIIllIllIIll[26]] = QUEST_SHIELD_OF_ARRAV;
        aArray[a.lIIIllIllIIll[28]] = QUEST_SHIELD_OF_ARRAV_STATE_146;
        aArray[a.lIIIllIllIIll[30]] = QUEST_VAMPYRE_SLAYER;
        aArray[a.lIIIllIllIIll[32]] = QUEST_WITCHS_POTION;
        aArray[a.lIIIllIllIIll[34]] = QUEST_BIG_CHOMPY_BIRD_HUNTING;
        aArray[a.lIIIllIllIIll[36]] = QUEST_BIOHAZARD;
        aArray[a.lIIIllIllIIll[38]] = QUEST_CABIN_FEVER;
        aArray[a.lIIIllIllIIll[40]] = QUEST_CLOCK_TOWER;
        aArray[a.lIIIllIllIIll[41]] = QUEST_CREATURE_OF_FENKENSTRAIN;
        aArray[a.lIIIllIllIIll[43]] = QUEST_DEATH_PLATEAU;
        aArray[a.lIIIllIllIIll[45]] = QUEST_THE_DIG_SITE;
        aArray[a.lIIIllIllIIll[47]] = QUEST_DRUIDIC_RITUAL;
        aArray[a.lIIIllIllIIll[49]] = QUEST_DWARF_CANNON;
        aArray[a.lIIIllIllIIll[50]] = QUEST_EADGARS_RUSE;
        aArray[a.lIIIllIllIIll[52]] = QUEST_ELEMENTAL_WORKSHOP_I;
        aArray[a.lIIIllIllIIll[54]] = QUEST_FAMILY_CREST;
        aArray[a.lIIIllIllIIll[3]] = QUEST_FIGHT_ARENA;
        aArray[a.lIIIllIllIIll[56]] = QUEST_FISHING_CONTEST;
        aArray[a.lIIIllIllIIll[5]] = QUEST_THE_FREMENNIK_TRIALS;
        aArray[a.lIIIllIllIIll[9]] = QUEST_WATERFALL_QUEST;
        aArray[a.lIIIllIllIIll[59]] = QUEST_GERTRUDES_CAT;
        aArray[a.lIIIllIllIIll[61]] = QUEST_THE_GRAND_TREE;
        aArray[a.lIIIllIllIIll[63]] = QUEST_HAUNTED_MINE;
        aArray[a.lIIIllIllIIll[65]] = QUEST_HAZEEL_CULT;
        aArray[a.lIIIllIllIIll[67]] = QUEST_HEROES_QUEST;
        aArray[a.lIIIllIllIIll[69]] = QUEST_HOLY_GRAIL;
        aArray[a.lIIIllIllIIll[70]] = QUEST_IN_SEARCH_OF_THE_MYREQUE;
        aArray[a.lIIIllIllIIll[72]] = QUEST_JUNGLE_POTION;
        aArray[a.lIIIllIllIIll[74]] = QUEST_LEGENDS_QUEST;
        aArray[a.lIIIllIllIIll[76]] = QUEST_LOST_CITY;
        aArray[a.lIIIllIllIIll[78]] = QUEST_MERLINS_CRYSTAL;
        aArray[a.lIIIllIllIIll[79]] = QUEST_MONKEY_MADNESS_I;
        aArray[a.lIIIllIllIIll[81]] = QUEST_MONKS_FRIEND;
        aArray[a.lIIIllIllIIll[82]] = QUEST_MOURNINGS_END_PART_I;
        aArray[a.lIIIllIllIIll[84]] = QUEST_MURDER_MYSTERY;
        aArray[a.lIIIllIllIIll[86]] = QUEST_NATURE_SPIRIT;
        aArray[a.lIIIllIllIIll[88]] = QUEST_OBSERVATORY_QUEST;
        aArray[a.lIIIllIllIIll[90]] = QUEST_ONE_SMALL_FAVOUR;
        aArray[a.lIIIllIllIIll[92]] = QUEST_PLAGUE_CITY;
        aArray[a.lIIIllIllIIll[94]] = QUEST_PRIEST_IN_PERIL;
        aArray[a.lIIIllIllIIll[96]] = QUEST_RAG_AND_BONE_MAN_I;
        aArray[a.lIIIllIllIIll[98]] = QUEST_REGICIDE;
        aArray[a.lIIIllIllIIll[100]] = QUEST_ROVING_ELVES;
        aArray[a.lIIIllIllIIll[102]] = QUEST_RUM_DEAL;
        aArray[a.lIIIllIllIIll[104]] = QUEST_SCORPION_CATCHER;
        aArray[a.lIIIllIllIIll[106]] = QUEST_SEA_SLUG;
        aArray[a.lIIIllIllIIll[108]] = QUEST_SHADES_OF_MORTTON;
        aArray[a.lIIIllIllIIll[110]] = QUEST_SHEEP_HERDER;
        aArray[a.lIIIllIllIIll[111]] = QUEST_SHILO_VILLAGE;
        aArray[a.lIIIllIllIIll[113]] = QUEST_TAI_BWO_WANNAI_TRIO;
        aArray[a.lIIIllIllIIll[23]] = QUEST_TEMPLE_OF_IKOV;
        aArray[a.lIIIllIllIIll[115]] = QUEST_THRONE_OF_MISCELLANIA;
        aArray[a.lIIIllIllIIll[58]] = QUEST_THE_TOURIST_TRAP;
        aArray[a.lIIIllIllIIll[118]] = QUEST_WITCHS_HOUSE;
        aArray[a.lIIIllIllIIll[33]] = QUEST_TREE_GNOME_VILLAGE;
        aArray[a.lIIIllIllIIll[37]] = QUEST_TRIBAL_TOTEM;
        aArray[a.lIIIllIllIIll[122]] = QUEST_TROLL_ROMANCE;
        aArray[a.lIIIllIllIIll[124]] = QUEST_TROLL_STRONGHOLD;
        aArray[a.lIIIllIllIIll[15]] = QUEST_UNDERGROUND_PASS;
        aArray[a.lIIIllIllIIll[127]] = QUEST_UNDERGROUND_PASS_STATE_162;
        aArray[a.lIIIllIllIIll[129]] = QUEST_WATCHTOWER;
        aArray[a.lIIIllIllIIll[131]] = QUEST_THE_GREAT_BRAIN_ROBBERY;
        aArray[a.lIIIllIllIIll[133]] = QUEST_RAG_AND_BONE_MAN_II;
        aArray[a.lIIIllIllIIll[105]] = QUEST_ENTER_THE_ABYSS;
        aArray[a.lIIIllIllIIll[135]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL;
        aArray[a.lIIIllIllIIll[136]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
        aArray[a.lIIIllIllIIll[137]] = QUEST_THE_MAGE_ARENA;
        $VALUES = aArray;
    }

    private static boolean lIlIIIllIIIlIIl(int n2, int n3) {
        return n2 < n3;
    }

    public static a valueOf(String string) {
        return Enum.valueOf(GameEnum15.class, string);
    }

    private GameEnum15(int n3) {
        this.id = n3;
    }

    private static void lIlIIIllIIIIlll() {
        lIIIllIllIIlI = new String[lIIIllIllIIll[48]];
        a.lIIIllIllIIlI[a.lIIIllIllIIll[0]] = "QUEST_BLACK_KNIGHTS_FORTRESS";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[2]] = "QUEST_COOKS_ASSISTANT";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[4]] = "QUEST_DORICS_QUEST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[6]] = "QUEST_DRAGON_SLAYER_I";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[8]] = "QUEST_ERNEST_THE_CHICKEN";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[10]] = "QUEST_IMP_CATCHER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[12]] = "QUEST_THE_KNIGHTS_SWORD";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[14]] = "QUEST_PIRATES_TREASURE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[16]] = "QUEST_PRINCE_ALI_RESCUE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[18]] = "QUEST_THE_RESTLESS_GHOST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[20]] = "QUEST_ROMEO_AND_JULIET";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[22]] = "QUEST_RUNE_MYSTERIES";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[24]] = "QUEST_SHEEP_SHEARER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[26]] = "QUEST_SHIELD_OF_ARRAV";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[28]] = "QUEST_SHIELD_OF_ARRAV_STATE_146";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[30]] = "QUEST_VAMPYRE_SLAYER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[32]] = "QUEST_WITCHS_POTION";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[34]] = "QUEST_BIG_CHOMPY_BIRD_HUNTING";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[36]] = "QUEST_BIOHAZARD";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[38]] = "QUEST_CABIN_FEVER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[40]] = "QUEST_CLOCK_TOWER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[41]] = "QUEST_CREATURE_OF_FENKENSTRAIN";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[43]] = "QUEST_DEATH_PLATEAU";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[45]] = "QUEST_THE_DIG_SITE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[47]] = "QUEST_DRUIDIC_RITUAL";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[49]] = "QUEST_DWARF_CANNON";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[50]] = "QUEST_EADGARS_RUSE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[52]] = "QUEST_ELEMENTAL_WORKSHOP_I";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[54]] = "QUEST_FAMILY_CREST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[3]] = "QUEST_FIGHT_ARENA";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[56]] = "QUEST_FISHING_CONTEST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[5]] = "QUEST_THE_FREMENNIK_TRIALS";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[9]] = "QUEST_WATERFALL_QUEST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[59]] = "QUEST_GERTRUDES_CAT";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[61]] = "QUEST_THE_GRAND_TREE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[63]] = "QUEST_HAUNTED_MINE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[65]] = "QUEST_HAZEEL_CULT";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[67]] = "QUEST_HEROES_QUEST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[69]] = "QUEST_HOLY_GRAIL";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[70]] = "QUEST_IN_SEARCH_OF_THE_MYREQUE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[72]] = "QUEST_JUNGLE_POTION";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[74]] = "QUEST_LEGENDS_QUEST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[76]] = "QUEST_LOST_CITY";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[78]] = "QUEST_MERLINS_CRYSTAL";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[79]] = "QUEST_MONKEY_MADNESS_I";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[81]] = "QUEST_MONKS_FRIEND";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[82]] = "QUEST_MOURNINGS_END_PART_I";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[84]] = "QUEST_MURDER_MYSTERY";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[86]] = "QUEST_NATURE_SPIRIT";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[88]] = "QUEST_OBSERVATORY_QUEST";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[90]] = "QUEST_ONE_SMALL_FAVOUR";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[92]] = "QUEST_PLAGUE_CITY";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[94]] = "QUEST_PRIEST_IN_PERIL";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[96]] = "QUEST_RAG_AND_BONE_MAN_I";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[98]] = "QUEST_REGICIDE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[100]] = "QUEST_ROVING_ELVES";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[102]] = "QUEST_RUM_DEAL";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[104]] = "QUEST_SCORPION_CATCHER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[106]] = "QUEST_SEA_SLUG";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[108]] = "QUEST_SHADES_OF_MORTTON";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[110]] = "QUEST_SHEEP_HERDER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[111]] = "QUEST_SHILO_VILLAGE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[113]] = "QUEST_TAI_BWO_WANNAI_TRIO";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[23]] = "QUEST_TEMPLE_OF_IKOV";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[115]] = "QUEST_THRONE_OF_MISCELLANIA";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[58]] = "QUEST_THE_TOURIST_TRAP";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[118]] = "QUEST_WITCHS_HOUSE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[33]] = "QUEST_TREE_GNOME_VILLAGE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[37]] = "QUEST_TRIBAL_TOTEM";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[122]] = "QUEST_TROLL_ROMANCE";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[124]] = "QUEST_TROLL_STRONGHOLD";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[15]] = "QUEST_UNDERGROUND_PASS";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[127]] = "QUEST_UNDERGROUND_PASS_STATE_162";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[129]] = "QUEST_WATCHTOWER";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[131]] = "QUEST_THE_GREAT_BRAIN_ROBBERY";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[133]] = "QUEST_RAG_AND_BONE_MAN_II";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[105]] = "QUEST_ENTER_THE_ABYSS";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[135]] = "QUEST_ALFRED_GRIMHANDS_BARCRAWL";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[136]] = "QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76";
        a.lIIIllIllIIlI[a.lIIIllIllIIll[137]] = "QUEST_THE_MAGE_ARENA";
    }

        return String.valueOf(var1);
    }

    public int c() {
        return this.id;
    }

    public static a[] values() {
        return (a[])$VALUES.clone();
    }
}

