/*
 * Decompiled with CFR 0.152.
 */
package q.e.u.r.i.u.t.q.-.e.e.s.r.s;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

public final class a
extends Enum<a> {
    public static final /* synthetic */ /* enum */ a QUEST_WITCHS_POTION;
    public static final /* synthetic */ /* enum */ a QUEST_TEMPLE_OF_IKOV;
    public static final /* synthetic */ /* enum */ a QUEST_MOURNINGS_END_PART_I;
    public static final /* synthetic */ /* enum */ a QUEST_SHEEP_HERDER;
    public static final /* synthetic */ /* enum */ a QUEST_ELEMENTAL_WORKSHOP_I;
    public static final /* synthetic */ /* enum */ a QUEST_SHILO_VILLAGE;
    public static final /* synthetic */ /* enum */ a QUEST_SHIELD_OF_ARRAV_STATE_146;
    public static final /* synthetic */ /* enum */ a QUEST_THE_RESTLESS_GHOST;
    public static final /* synthetic */ /* enum */ a QUEST_HAZEEL_CULT;
    public static final /* synthetic */ /* enum */ a QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
    public static final /* synthetic */ /* enum */ a QUEST_OBSERVATORY_QUEST;
    private final /* synthetic */ int id;
    public static final /* synthetic */ /* enum */ a QUEST_TAI_BWO_WANNAI_TRIO;
    public static final /* synthetic */ /* enum */ a QUEST_FIGHT_ARENA;
    public static final /* synthetic */ /* enum */ a QUEST_SHIELD_OF_ARRAV;
    public static final /* synthetic */ /* enum */ a QUEST_THE_MAGE_ARENA;
    public static final /* synthetic */ /* enum */ a QUEST_ROMEO_AND_JULIET;
    public static final /* synthetic */ /* enum */ a QUEST_CLOCK_TOWER;
    public static final /* synthetic */ /* enum */ a QUEST_JUNGLE_POTION;
    public static final /* synthetic */ /* enum */ a QUEST_RUNE_MYSTERIES;
    public static final /* synthetic */ /* enum */ a QUEST_MONKEY_MADNESS_I;
    public static final /* synthetic */ /* enum */ a QUEST_LEGENDS_QUEST;
    private static /* synthetic */ String[] lIIIllIllIIlI;
    public static final /* synthetic */ /* enum */ a QUEST_BIOHAZARD;
    public static final /* synthetic */ /* enum */ a QUEST_EADGARS_RUSE;
    public static final /* synthetic */ /* enum */ a QUEST_SCORPION_CATCHER;
    public static final /* synthetic */ /* enum */ a QUEST_ONE_SMALL_FAVOUR;
    public static final /* synthetic */ /* enum */ a QUEST_THE_KNIGHTS_SWORD;
    public static final /* synthetic */ /* enum */ a QUEST_HEROES_QUEST;
    public static final /* synthetic */ /* enum */ a QUEST_WITCHS_HOUSE;
    public static final /* synthetic */ /* enum */ a QUEST_ERNEST_THE_CHICKEN;
    public static final /* synthetic */ /* enum */ a QUEST_MURDER_MYSTERY;
    public static final /* synthetic */ /* enum */ a QUEST_DWARF_CANNON;
    public static final /* synthetic */ /* enum */ a QUEST_LOST_CITY;
    public static final /* synthetic */ /* enum */ a QUEST_GERTRUDES_CAT;
    public static final /* synthetic */ /* enum */ a QUEST_SEA_SLUG;
    public static final /* synthetic */ /* enum */ a QUEST_NATURE_SPIRIT;
    public static final /* synthetic */ /* enum */ a QUEST_THE_FREMENNIK_TRIALS;
    private static final /* synthetic */ a[] $VALUES;
    public static final /* synthetic */ /* enum */ a QUEST_REGICIDE;
    public static final /* synthetic */ /* enum */ a QUEST_ENTER_THE_ABYSS;
    public static final /* synthetic */ /* enum */ a QUEST_FISHING_CONTEST;
    public static final /* synthetic */ /* enum */ a QUEST_ROVING_ELVES;
    public static final /* synthetic */ /* enum */ a QUEST_WATCHTOWER;
    public static final /* synthetic */ /* enum */ a QUEST_VAMPYRE_SLAYER;
    public static final /* synthetic */ /* enum */ a QUEST_COOKS_ASSISTANT;
    public static final /* synthetic */ /* enum */ a QUEST_RAG_AND_BONE_MAN_II;
    public static final /* synthetic */ /* enum */ a QUEST_PRIEST_IN_PERIL;
    public static final /* synthetic */ /* enum */ a QUEST_TRIBAL_TOTEM;
    public static final /* synthetic */ /* enum */ a QUEST_PIRATES_TREASURE;
    public static final /* synthetic */ /* enum */ a QUEST_THE_GRAND_TREE;
    public static final /* synthetic */ /* enum */ a QUEST_WATERFALL_QUEST;
    public static final /* synthetic */ /* enum */ a QUEST_DORICS_QUEST;
    public static final /* synthetic */ /* enum */ a QUEST_UNDERGROUND_PASS;
    public static final /* synthetic */ /* enum */ a QUEST_CREATURE_OF_FENKENSTRAIN;
    public static final /* synthetic */ /* enum */ a QUEST_IMP_CATCHER;
    public static final /* synthetic */ /* enum */ a QUEST_BLACK_KNIGHTS_FORTRESS;
    public static final /* synthetic */ /* enum */ a QUEST_CABIN_FEVER;
    public static final /* synthetic */ /* enum */ a QUEST_DRAGON_SLAYER_I;
    public static final /* synthetic */ /* enum */ a QUEST_MERLINS_CRYSTAL;
    public static final /* synthetic */ /* enum */ a QUEST_BIG_CHOMPY_BIRD_HUNTING;
    public static final /* synthetic */ /* enum */ a QUEST_UNDERGROUND_PASS_STATE_162;
    public static final /* synthetic */ /* enum */ a QUEST_THE_DIG_SITE;
    public static final /* synthetic */ /* enum */ a QUEST_RAG_AND_BONE_MAN_I;
    public static final /* synthetic */ /* enum */ a QUEST_SHEEP_SHEARER;
    public static final /* synthetic */ /* enum */ a QUEST_SHADES_OF_MORTTON;
    public static final /* synthetic */ /* enum */ a QUEST_IN_SEARCH_OF_THE_MYREQUE;
    public static final /* synthetic */ /* enum */ a QUEST_HAUNTED_MINE;
    public static final /* synthetic */ /* enum */ a QUEST_DRUIDIC_RITUAL;
    public static final /* synthetic */ /* enum */ a QUEST_FAMILY_CREST;
    public static final /* synthetic */ /* enum */ a QUEST_PRINCE_ALI_RESCUE;
    public static final /* synthetic */ /* enum */ a QUEST_THE_TOURIST_TRAP;
    public static final /* synthetic */ /* enum */ a QUEST_THE_GREAT_BRAIN_ROBBERY;
    public static final /* synthetic */ /* enum */ a QUEST_DEATH_PLATEAU;
    public static final /* synthetic */ /* enum */ a QUEST_RUM_DEAL;
    public static final /* synthetic */ /* enum */ a QUEST_TROLL_ROMANCE;
    public static final /* synthetic */ /* enum */ a QUEST_TREE_GNOME_VILLAGE;
    private static /* synthetic */ int[] lIIIllIllIIll;
    public static final /* synthetic */ /* enum */ a QUEST_HOLY_GRAIL;
    public static final /* synthetic */ /* enum */ a QUEST_TROLL_STRONGHOLD;
    public static final /* synthetic */ /* enum */ a QUEST_MONKS_FRIEND;
    public static final /* synthetic */ /* enum */ a QUEST_ALFRED_GRIMHANDS_BARCRAWL;
    public static final /* synthetic */ /* enum */ a QUEST_THRONE_OF_MISCELLANIA;
    public static final /* synthetic */ /* enum */ a QUEST_PLAGUE_CITY;

    private static void lIlIIIllIIIlIII() {
        lIIIllIllIIll = new int[139];
        a.lIIIllIllIIll[0] = (0x76 ^ 0x7D) & ~(0x4F ^ 0x44);
        a.lIIIllIllIIll[1] = 54 + 75 - 88 + 89;
        a.lIIIllIllIIll[2] = " ".length();
        a.lIIIllIllIIll[3] = 0xED ^ 0xAD ^ (0x2B ^ 0x76);
        a.lIIIllIllIIll[4] = "  ".length();
        a.lIIIllIllIIll[5] = 113 + 82 - 187 + 135 ^ 6 + 124 - 55 + 69;
        a.lIIIllIllIIll[6] = "   ".length();
        a.lIIIllIllIIll[7] = 18 + 33 - 47 + 124 + (0x18 ^ 0x46) - (0xA3 ^ 0x91) + (0xBF ^ 0xBB);
        a.lIIIllIllIIll[8] = 42 + 126 - 97 + 120 ^ 16 + 30 - -83 + 58;
        a.lIIIllIllIIll[9] = 73 + 126 - 186 + 125 ^ 149 + 1 - 116 + 136;
        a.lIIIllIllIIll[10] = 0x5A ^ 0x5F;
        a.lIIIllIllIIll[11] = (0xAE ^ 0xC5) + (44 + 43 - 69 + 127) - (106 + 6 - -27 + 107) + (46 + 17 - -47 + 44);
        a.lIIIllIllIIll[12] = 0x50 ^ 0x56;
        a.lIIIllIllIIll[13] = 0x31 ^ 0x68 ^ (0x54 ^ 0x77);
        a.lIIIllIllIIll[14] = 0xF5 ^ 0x90 ^ (0xFF ^ 0x9D);
        a.lIIIllIllIIll[15] = 27 + 110 - 31 + 104 ^ 99 + 22 - -17 + 11;
        a.lIIIllIllIIll[16] = 0x51 ^ 0x70 ^ (0x90 ^ 0xB9);
        a.lIIIllIllIIll[17] = 0xFFFFF959 & 0x7B7;
        a.lIIIllIllIIll[18] = 0x82 ^ 0x8B;
        a.lIIIllIllIIll[19] = 0xE7 ^ 0x8C;
        a.lIIIllIllIIll[20] = 0x64 ^ 0x40 ^ (0x89 ^ 0xA7);
        a.lIIIllIllIIll[21] = 49 + 67 - 30 + 52 + (0x69 ^ 0x31) - (198 + 14 - 107 + 96) + (0xC4 ^ 0xB3);
        a.lIIIllIllIIll[22] = 0x5F ^ 0x58 ^ (0x24 ^ 0x28);
        a.lIIIllIllIIll[23] = 0x87 ^ 0xB8;
        a.lIIIllIllIIll[24] = 0x67 ^ 0x6B;
        a.lIIIllIllIIll[25] = 13 + 17 - 22 + 171;
        a.lIIIllIllIIll[26] = 0xF ^ 2;
        a.lIIIllIllIIll[27] = 56 + 16 - 0 + 60 + (103 + 76 - 146 + 109) - (92 + 14 - -65 + 31) + (0x5F ^ 0x16);
        a.lIIIllIllIIll[28] = 0x22 ^ 0x2C;
        a.lIIIllIllIIll[29] = (0xE5 ^ 0x87) + (0xE ^ 0x69) - (138 + 40 - 74 + 35) + (0x49 ^ 0x1D);
        a.lIIIllIllIIll[30] = 0x40 ^ 0x17 ^ (0xFE ^ 0xA6);
        a.lIIIllIllIIll[31] = 1 + 118 - 0 + 59;
        a.lIIIllIllIIll[32] = 206 + 77 - 174 + 106 ^ 133 + 151 - 102 + 17;
        a.lIIIllIllIIll[33] = 180 + 47 - 104 + 84 ^ 129 + 102 - 122 + 31;
        a.lIIIllIllIIll[34] = 166 + 55 - 190 + 179 ^ 73 + 49 - 72 + 145;
        a.lIIIllIllIIll[35] = -(0xFFFFCDD7 & 0x7EE9) & (0xFFFFFFFD & 0x4DE7);
        a.lIIIllIllIIll[36] = 41 + 74 - -55 + 4 ^ 130 + 124 - 167 + 101;
        a.lIIIllIllIIll[37] = 0x61 ^ 0x26 ^ "   ".length();
        a.lIIIllIllIIll[38] = 0x19 ^ 0xA;
        a.lIIIllIllIIll[39] = 0xFFFFF2BF & 0xFCF;
        a.lIIIllIllIIll[40] = 0x9D ^ 0x89;
        a.lIIIllIllIIll[41] = 0xA ^ 0x1F;
        a.lIIIllIllIIll[42] = -(0xFFFFFE55 & 0x5BAB) & (0xFFFFFFBF & 0x5BCF);
        a.lIIIllIllIIll[43] = 0x33 ^ 0x62 ^ (0x44 ^ 3);
        a.lIIIllIllIIll[44] = -(0xFFFFFA7D & 0x7FC7) & (0xFFFFFFFF & 0x7B7E);
        a.lIIIllIllIIll[45] = 0xA6 ^ 0x8E ^ (0x7A ^ 0x45);
        a.lIIIllIllIIll[46] = 52 + 63 - 0 + 16;
        a.lIIIllIllIIll[47] = 0x44 ^ 0x5C;
        a.lIIIllIllIIll[48] = 0x10 ^ 0x40;
        a.lIIIllIllIIll[49] = 0x11 ^ 8;
        a.lIIIllIllIIll[50] = 0x7A ^ 0x60;
        a.lIIIllIllIIll[51] = 0xFFFFCB4F & 0x35FF;
        a.lIIIllIllIIll[52] = 0xE1 ^ 0xB8 ^ (0xE1 ^ 0xA3);
        a.lIIIllIllIIll[53] = 0xFFFF87FB & 0x792F;
        a.lIIIllIllIIll[54] = 0x7D ^ 0x61;
        a.lIIIllIllIIll[55] = 57 + 6 - -9 + 55 + (0x54 ^ 0x58) - (0xFC ^ 0x95) + (0xB7 ^ 0xC5);
        a.lIIIllIllIIll[56] = 11 + 69 - -38 + 23 ^ 93 + 57 - 147 + 144;
        a.lIIIllIllIIll[57] = -(0xFFFFFDE3 & 0x5E9D) & (0xFFFFDFFB & 0x7DDF);
        a.lIIIllIllIIll[58] = 0xD8 ^ 0x99;
        a.lIIIllIllIIll[59] = 0x6A ^ 0x4B;
        a.lIIIllIllIIll[60] = 40 + 175 - 91 + 56;
        a.lIIIllIllIIll[61] = 0x22 ^ 0;
        a.lIIIllIllIIll[62] = 24 + 4 - -92 + 30;
        a.lIIIllIllIIll[63] = 0 ^ 0x23;
        a.lIIIllIllIIll[64] = 0xFFFFDB7F & 0x25FE;
        a.lIIIllIllIIll[65] = 0 ^ 0x39 ^ (0xA6 ^ 0xBB);
        a.lIIIllIllIIll[66] = 222 + 22 - 190 + 169;
        a.lIIIllIllIIll[67] = 0x16 ^ 0x33;
        a.lIIIllIllIIll[68] = (0xAC ^ 0xA0) + (37 + 136 - 161 + 167) - (0xBE ^ 0xAD) + (0x27 ^ 0x37);
        a.lIIIllIllIIll[69] = 0x28 ^ 0xE;
        a.lIIIllIllIIll[70] = 0x57 ^ 0x70;
        a.lIIIllIllIIll[71] = 0xFFFF8FD7 & 0x71AB;
        a.lIIIllIllIIll[72] = (0x81 ^ 0x89) & ~(0x6D ^ 0x65) ^ (0x9D ^ 0xB5);
        a.lIIIllIllIIll[73] = 157 + 133 - 247 + 132;
        a.lIIIllIllIIll[74] = 0x4A ^ 0x63;
        a.lIIIllIllIIll[75] = 133 + 92 - 119 + 33;
        a.lIIIllIllIIll[76] = 0xD1 ^ 0xB9 ^ (0x74 ^ 0x36);
        a.lIIIllIllIIll[77] = (0x59 ^ 0x30) + (0x48 ^ 0x75) - (0x16 ^ 0x7C) + (0x92 ^ 0xC5);
        a.lIIIllIllIIll[78] = 0x97 ^ 0xBC;
        a.lIIIllIllIIll[79] = 0x71 ^ 0x5D;
        a.lIIIllIllIIll[80] = 0xFFFFD36F & 0x2DFD;
        a.lIIIllIllIIll[81] = 0x6E ^ 0x43;
        a.lIIIllIllIIll[82] = 0x1E ^ 0x30;
        a.lIIIllIllIIll[83] = -(0xFFFFDF7B & 0x6DFF) & (0xFFFFDFFF & 0x6F7F);
        a.lIIIllIllIIll[84] = 0x1E ^ 0x31;
        a.lIIIllIllIIll[85] = 142 + 182 - 143 + 11;
        a.lIIIllIllIIll[86] = 0x3D ^ 0xD;
        a.lIIIllIllIIll[87] = 0xFFFFCDF7 & 0x333B;
        a.lIIIllIllIIll[88] = 0x25 ^ 0x14;
        a.lIIIllIllIIll[89] = 0x32 ^ 0x5E ^ (0x31 ^ 0x2D);
        a.lIIIllIllIIll[90] = 0x4A ^ 0x78;
        a.lIIIllIllIIll[91] = 0xFFFF9DAE & 0x63F1;
        a.lIIIllIllIIll[92] = 1 ^ 0x32;
        a.lIIIllIllIIll[93] = 131 + 85 - 144 + 93;
        a.lIIIllIllIIll[94] = 0xEE ^ 0xC3 ^ (4 ^ 0x1D);
        a.lIIIllIllIIll[95] = -(0xFFFF9F32 & 0x7EDF) & (0xFFFF9F7F & 0x7FBF);
        a.lIIIllIllIIll[96] = 0x21 ^ 0x14;
        a.lIIIllIllIIll[97] = 0xFFFFDEEF & 0x23DA;
        a.lIIIllIllIIll[98] = 39 + 84 - 112 + 121 ^ 138 + 123 - 203 + 120;
        a.lIIIllIllIIll[99] = -(0xFFFF9E6C & 0x67B7) & (0xFFFF877F & 0x7FEB);
        a.lIIIllIllIIll[100] = 0x2A ^ 0x1D;
        a.lIIIllIllIIll[101] = 0xFFFFF7BA & 0x9D7;
        a.lIIIllIllIIll[102] = 86 + 116 - 77 + 5 ^ 16 + 29 - -41 + 100;
        a.lIIIllIllIIll[103] = 0xFFFFAEDB & 0x537C;
        a.lIIIllIllIIll[104] = 0x16 ^ 0x71 ^ (6 ^ 0x58);
        a.lIIIllIllIIll[105] = 48 + 15 - 12 + 144 ^ 52 + 73 - 49 + 67;
        a.lIIIllIllIIll[106] = 0x64 ^ 0x74 ^ (0x7E ^ 0x54);
        a.lIIIllIllIIll[107] = 140 + 113 - 143 + 49;
        a.lIIIllIllIIll[108] = 0x6B ^ 0x50;
        a.lIIIllIllIIll[109] = -(0xFFFFB731 & 0x5EEF) & (0xFFFFFF73 & 0x17FF);
        a.lIIIllIllIIll[110] = 0x81 ^ 0xBD;
        a.lIIIllIllIIll[111] = 0xFE ^ 0xC3;
        a.lIIIllIllIIll[112] = 0x6E ^ 0x1A;
        a.lIIIllIllIIll[113] = 0x7B ^ 0x45;
        a.lIIIllIllIIll[114] = -(0xFFFFFE3F & 0x27FD) & (0xFFFFEFFC & 0x377F);
        a.lIIIllIllIIll[115] = 0xF1 ^ 0xC1 ^ (0x19 ^ 0x69);
        a.lIIIllIllIIll[116] = -(0xFFFF9E55 & 0x7BAB) & (0xFFFFBBE7 & 0x5F7F);
        a.lIIIllIllIIll[117] = 55 + 131 - 44 + 55;
        a.lIIIllIllIIll[118] = 0x83 ^ 0xC1;
        a.lIIIllIllIIll[119] = 89 + 95 - 73 + 41 + (6 ^ 0xF) - (0x5D ^ 0xA) + (143 + 114 - 105 + 0);
        a.lIIIllIllIIll[120] = 99 + 183 - 184 + 127 ^ 76 + 70 - 6 + 2;
        a.lIIIllIllIIll[121] = 169 + 154 - 301 + 178;
        a.lIIIllIllIIll[122] = 0x59 ^ 0x35 ^ (0x6C ^ 0x45);
        a.lIIIllIllIIll[123] = -(0xFFFFEAE7 & 0x1F7B) & (0xFFFFABEB & 0x5FF7);
        a.lIIIllIllIIll[124] = 118 + 197 - 241 + 136 ^ 31 + 97 - 32 + 52;
        a.lIIIllIllIIll[125] = 0xFFFFEF7F & 0x11BD;
        a.lIIIllIllIIll[126] = (0xC4 ^ 0xB5) + (0x2C ^ 0x67) - (0x7D ^ 0x48) + (0x8E ^ 0x94);
        a.lIIIllIllIIll[127] = 0xC4 ^ 0x8C;
        a.lIIIllIllIIll[128] = (0x18 ^ 0x1E) + (75 + 37 - 30 + 45) - (0xFB ^ 0x8F) + (7 + 69 - 60 + 129);
        a.lIIIllIllIIll[129] = 118 + 104 - 26 + 37 ^ 139 + 138 - 136 + 19;
        a.lIIIllIllIIll[130] = 58 + 2 - -151 + 1;
        a.lIIIllIllIIll[131] = 3 ^ 0x59 ^ (0xB7 ^ 0xA7);
        a.lIIIllIllIIll[132] = 0xFFFF97DD & 0x6BF6;
        a.lIIIllIllIIll[133] = 0x57 ^ 0x1C;
        a.lIIIllIllIIll[134] = -(0xFFFFFB2F & 0x7ED3) & (0xFFFFFFEE & 0x7BFF);
        a.lIIIllIllIIll[135] = 0xC6 ^ 0x9A ^ (0xA6 ^ 0xB7);
        a.lIIIllIllIIll[136] = 0x77 ^ 0x3C ^ (0x3A ^ 0x3F);
        a.lIIIllIllIIll[137] = 73 + 70 - 2 + 111 ^ 52 + 110 - 151 + 168;
        a.lIIIllIllIIll[138] = 0xFFFF97FB & 0x690F;
    }

    static {
        a.lIlIIIllIIIlIII();
        a.lIlIIIllIIIIlll();
        QUEST_BLACK_KNIGHTS_FORTRESS = new a(lIIIllIllIIll[1]);
        QUEST_COOKS_ASSISTANT = new a(lIIIllIllIIll[3]);
        QUEST_DORICS_QUEST = new a(lIIIllIllIIll[5]);
        QUEST_DRAGON_SLAYER_I = new a(lIIIllIllIIll[7]);
        QUEST_ERNEST_THE_CHICKEN = new a(lIIIllIllIIll[9]);
        QUEST_IMP_CATCHER = new a(lIIIllIllIIll[11]);
        QUEST_THE_KNIGHTS_SWORD = new a(lIIIllIllIIll[13]);
        QUEST_PIRATES_TREASURE = new a(lIIIllIllIIll[15]);
        QUEST_PRINCE_ALI_RESCUE = new a(lIIIllIllIIll[17]);
        QUEST_THE_RESTLESS_GHOST = new a(lIIIllIllIIll[19]);
        QUEST_ROMEO_AND_JULIET = new a(lIIIllIllIIll[21]);
        QUEST_RUNE_MYSTERIES = new a(lIIIllIllIIll[23]);
        QUEST_SHEEP_SHEARER = new a(lIIIllIllIIll[25]);
        QUEST_SHIELD_OF_ARRAV = new a(lIIIllIllIIll[27]);
        QUEST_SHIELD_OF_ARRAV_STATE_146 = new a(lIIIllIllIIll[29]);
        QUEST_VAMPYRE_SLAYER = new a(lIIIllIllIIll[31]);
        QUEST_WITCHS_POTION = new a(lIIIllIllIIll[33]);
        QUEST_BIG_CHOMPY_BIRD_HUNTING = new a(lIIIllIllIIll[35]);
        QUEST_BIOHAZARD = new a(lIIIllIllIIll[37]);
        QUEST_CABIN_FEVER = new a(lIIIllIllIIll[39]);
        QUEST_CLOCK_TOWER = new a(lIIIllIllIIll[20]);
        QUEST_CREATURE_OF_FENKENSTRAIN = new a(lIIIllIllIIll[42]);
        QUEST_DEATH_PLATEAU = new a(lIIIllIllIIll[44]);
        QUEST_THE_DIG_SITE = new a(lIIIllIllIIll[46]);
        QUEST_DRUIDIC_RITUAL = new a(lIIIllIllIIll[48]);
        QUEST_DWARF_CANNON = new a(lIIIllIllIIll[0]);
        QUEST_EADGARS_RUSE = new a(lIIIllIllIIll[51]);
        QUEST_ELEMENTAL_WORKSHOP_I = new a(lIIIllIllIIll[53]);
        QUEST_FAMILY_CREST = new a(lIIIllIllIIll[55]);
        QUEST_FIGHT_ARENA = new a(lIIIllIllIIll[34]);
        QUEST_FISHING_CONTEST = new a(lIIIllIllIIll[22]);
        QUEST_THE_FREMENNIK_TRIALS = new a(lIIIllIllIIll[57]);
        QUEST_WATERFALL_QUEST = new a(lIIIllIllIIll[58]);
        QUEST_GERTRUDES_CAT = new a(lIIIllIllIIll[60]);
        QUEST_THE_GRAND_TREE = new a(lIIIllIllIIll[62]);
        QUEST_HAUNTED_MINE = new a(lIIIllIllIIll[64]);
        QUEST_HAZEEL_CULT = new a(lIIIllIllIIll[66]);
        QUEST_HEROES_QUEST = new a(lIIIllIllIIll[68]);
        QUEST_HOLY_GRAIL = new a(lIIIllIllIIll[10]);
        QUEST_IN_SEARCH_OF_THE_MYREQUE = new a(lIIIllIllIIll[71]);
        QUEST_JUNGLE_POTION = new a(lIIIllIllIIll[73]);
        QUEST_LEGENDS_QUEST = new a(lIIIllIllIIll[75]);
        QUEST_LOST_CITY = new a(lIIIllIllIIll[77]);
        QUEST_MERLINS_CRYSTAL = new a(lIIIllIllIIll[28]);
        QUEST_MONKEY_MADNESS_I = new a(lIIIllIllIIll[80]);
        QUEST_MONKS_FRIEND = new a(lIIIllIllIIll[56]);
        QUEST_MOURNINGS_END_PART_I = new a(lIIIllIllIIll[83]);
        QUEST_MURDER_MYSTERY = new a(lIIIllIllIIll[85]);
        QUEST_NATURE_SPIRIT = new a(lIIIllIllIIll[87]);
        QUEST_OBSERVATORY_QUEST = new a(lIIIllIllIIll[89]);
        QUEST_ONE_SMALL_FAVOUR = new a(lIIIllIllIIll[91]);
        QUEST_PLAGUE_CITY = new a(lIIIllIllIIll[93]);
        QUEST_PRIEST_IN_PERIL = new a(lIIIllIllIIll[95]);
        QUEST_RAG_AND_BONE_MAN_I = new a(lIIIllIllIIll[97]);
        QUEST_REGICIDE = new a(lIIIllIllIIll[99]);
        QUEST_ROVING_ELVES = new a(lIIIllIllIIll[101]);
        QUEST_RUM_DEAL = new a(lIIIllIllIIll[103]);
        QUEST_SCORPION_CATCHER = new a(lIIIllIllIIll[105]);
        QUEST_SEA_SLUG = new a(lIIIllIllIIll[107]);
        QUEST_SHADES_OF_MORTTON = new a(lIIIllIllIIll[109]);
        QUEST_SHEEP_HERDER = new a(lIIIllIllIIll[110]);
        QUEST_SHILO_VILLAGE = new a(lIIIllIllIIll[112]);
        QUEST_TAI_BWO_WANNAI_TRIO = new a(lIIIllIllIIll[114]);
        QUEST_TEMPLE_OF_IKOV = new a(lIIIllIllIIll[50]);
        QUEST_THRONE_OF_MISCELLANIA = new a(lIIIllIllIIll[116]);
        QUEST_THE_TOURIST_TRAP = new a(lIIIllIllIIll[117]);
        QUEST_WITCHS_HOUSE = new a(lIIIllIllIIll[119]);
        QUEST_TREE_GNOME_VILLAGE = new a(lIIIllIllIIll[120]);
        QUEST_TRIBAL_TOTEM = new a(lIIIllIllIIll[121]);
        QUEST_TROLL_ROMANCE = new a(lIIIllIllIIll[123]);
        QUEST_TROLL_STRONGHOLD = new a(lIIIllIllIIll[125]);
        QUEST_UNDERGROUND_PASS = new a(lIIIllIllIIll[126]);
        QUEST_UNDERGROUND_PASS_STATE_162 = new a(lIIIllIllIIll[128]);
        QUEST_WATCHTOWER = new a(lIIIllIllIIll[130]);
        QUEST_THE_GREAT_BRAIN_ROBBERY = new a(lIIIllIllIIll[132]);
        QUEST_RAG_AND_BONE_MAN_II = new a(lIIIllIllIIll[97]);
        QUEST_ENTER_THE_ABYSS = new a(lIIIllIllIIll[134]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL = new a(lIIIllIllIIll[135]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76 = new a(lIIIllIllIIll[105]);
        QUEST_THE_MAGE_ARENA = new a(lIIIllIllIIll[138]);
        a[] aArray = new a[lIIIllIllIIll[48]];
        aArray[a.lIIIllIllIIll[0]] = QUEST_BLACK_KNIGHTS_FORTRESS;
        aArray[a.lIIIllIllIIll[2]] = QUEST_COOKS_ASSISTANT;
        aArray[a.lIIIllIllIIll[4]] = QUEST_DORICS_QUEST;
        aArray[a.lIIIllIllIIll[6]] = QUEST_DRAGON_SLAYER_I;
        aArray[a.lIIIllIllIIll[8]] = QUEST_ERNEST_THE_CHICKEN;
        aArray[a.lIIIllIllIIll[10]] = QUEST_IMP_CATCHER;
        aArray[a.lIIIllIllIIll[12]] = QUEST_THE_KNIGHTS_SWORD;
        aArray[a.lIIIllIllIIll[14]] = QUEST_PIRATES_TREASURE;
        aArray[a.lIIIllIllIIll[16]] = QUEST_PRINCE_ALI_RESCUE;
        aArray[a.lIIIllIllIIll[18]] = QUEST_THE_RESTLESS_GHOST;
        aArray[a.lIIIllIllIIll[20]] = QUEST_ROMEO_AND_JULIET;
        aArray[a.lIIIllIllIIll[22]] = QUEST_RUNE_MYSTERIES;
        aArray[a.lIIIllIllIIll[24]] = QUEST_SHEEP_SHEARER;
        aArray[a.lIIIllIllIIll[26]] = QUEST_SHIELD_OF_ARRAV;
        aArray[a.lIIIllIllIIll[28]] = QUEST_SHIELD_OF_ARRAV_STATE_146;
        aArray[a.lIIIllIllIIll[30]] = QUEST_VAMPYRE_SLAYER;
        aArray[a.lIIIllIllIIll[32]] = QUEST_WITCHS_POTION;
        aArray[a.lIIIllIllIIll[34]] = QUEST_BIG_CHOMPY_BIRD_HUNTING;
        aArray[a.lIIIllIllIIll[36]] = QUEST_BIOHAZARD;
        aArray[a.lIIIllIllIIll[38]] = QUEST_CABIN_FEVER;
        aArray[a.lIIIllIllIIll[40]] = QUEST_CLOCK_TOWER;
        aArray[a.lIIIllIllIIll[41]] = QUEST_CREATURE_OF_FENKENSTRAIN;
        aArray[a.lIIIllIllIIll[43]] = QUEST_DEATH_PLATEAU;
        aArray[a.lIIIllIllIIll[45]] = QUEST_THE_DIG_SITE;
        aArray[a.lIIIllIllIIll[47]] = QUEST_DRUIDIC_RITUAL;
        aArray[a.lIIIllIllIIll[49]] = QUEST_DWARF_CANNON;
        aArray[a.lIIIllIllIIll[50]] = QUEST_EADGARS_RUSE;
        aArray[a.lIIIllIllIIll[52]] = QUEST_ELEMENTAL_WORKSHOP_I;
        aArray[a.lIIIllIllIIll[54]] = QUEST_FAMILY_CREST;
        aArray[a.lIIIllIllIIll[3]] = QUEST_FIGHT_ARENA;
        aArray[a.lIIIllIllIIll[56]] = QUEST_FISHING_CONTEST;
        aArray[a.lIIIllIllIIll[5]] = QUEST_THE_FREMENNIK_TRIALS;
        aArray[a.lIIIllIllIIll[9]] = QUEST_WATERFALL_QUEST;
        aArray[a.lIIIllIllIIll[59]] = QUEST_GERTRUDES_CAT;
        aArray[a.lIIIllIllIIll[61]] = QUEST_THE_GRAND_TREE;
        aArray[a.lIIIllIllIIll[63]] = QUEST_HAUNTED_MINE;
        aArray[a.lIIIllIllIIll[65]] = QUEST_HAZEEL_CULT;
        aArray[a.lIIIllIllIIll[67]] = QUEST_HEROES_QUEST;
        aArray[a.lIIIllIllIIll[69]] = QUEST_HOLY_GRAIL;
        aArray[a.lIIIllIllIIll[70]] = QUEST_IN_SEARCH_OF_THE_MYREQUE;
        aArray[a.lIIIllIllIIll[72]] = QUEST_JUNGLE_POTION;
        aArray[a.lIIIllIllIIll[74]] = QUEST_LEGENDS_QUEST;
        aArray[a.lIIIllIllIIll[76]] = QUEST_LOST_CITY;
        aArray[a.lIIIllIllIIll[78]] = QUEST_MERLINS_CRYSTAL;
        aArray[a.lIIIllIllIIll[79]] = QUEST_MONKEY_MADNESS_I;
        aArray[a.lIIIllIllIIll[81]] = QUEST_MONKS_FRIEND;
        aArray[a.lIIIllIllIIll[82]] = QUEST_MOURNINGS_END_PART_I;
        aArray[a.lIIIllIllIIll[84]] = QUEST_MURDER_MYSTERY;
        aArray[a.lIIIllIllIIll[86]] = QUEST_NATURE_SPIRIT;
        aArray[a.lIIIllIllIIll[88]] = QUEST_OBSERVATORY_QUEST;
        aArray[a.lIIIllIllIIll[90]] = QUEST_ONE_SMALL_FAVOUR;
        aArray[a.lIIIllIllIIll[92]] = QUEST_PLAGUE_CITY;
        aArray[a.lIIIllIllIIll[94]] = QUEST_PRIEST_IN_PERIL;
        aArray[a.lIIIllIllIIll[96]] = QUEST_RAG_AND_BONE_MAN_I;
        aArray[a.lIIIllIllIIll[98]] = QUEST_REGICIDE;
        aArray[a.lIIIllIllIIll[100]] = QUEST_ROVING_ELVES;
        aArray[a.lIIIllIllIIll[102]] = QUEST_RUM_DEAL;
        aArray[a.lIIIllIllIIll[104]] = QUEST_SCORPION_CATCHER;
        aArray[a.lIIIllIllIIll[106]] = QUEST_SEA_SLUG;
        aArray[a.lIIIllIllIIll[108]] = QUEST_SHADES_OF_MORTTON;
        aArray[a.lIIIllIllIIll[110]] = QUEST_SHEEP_HERDER;
        aArray[a.lIIIllIllIIll[111]] = QUEST_SHILO_VILLAGE;
        aArray[a.lIIIllIllIIll[113]] = QUEST_TAI_BWO_WANNAI_TRIO;
        aArray[a.lIIIllIllIIll[23]] = QUEST_TEMPLE_OF_IKOV;
        aArray[a.lIIIllIllIIll[115]] = QUEST_THRONE_OF_MISCELLANIA;
        aArray[a.lIIIllIllIIll[58]] = QUEST_THE_TOURIST_TRAP;
        aArray[a.lIIIllIllIIll[118]] = QUEST_WITCHS_HOUSE;
        aArray[a.lIIIllIllIIll[33]] = QUEST_TREE_GNOME_VILLAGE;
        aArray[a.lIIIllIllIIll[37]] = QUEST_TRIBAL_TOTEM;
        aArray[a.lIIIllIllIIll[122]] = QUEST_TROLL_ROMANCE;
        aArray[a.lIIIllIllIIll[124]] = QUEST_TROLL_STRONGHOLD;
        aArray[a.lIIIllIllIIll[15]] = QUEST_UNDERGROUND_PASS;
        aArray[a.lIIIllIllIIll[127]] = QUEST_UNDERGROUND_PASS_STATE_162;
        aArray[a.lIIIllIllIIll[129]] = QUEST_WATCHTOWER;
        aArray[a.lIIIllIllIIll[131]] = QUEST_THE_GREAT_BRAIN_ROBBERY;
        aArray[a.lIIIllIllIIll[133]] = QUEST_RAG_AND_BONE_MAN_II;
        aArray[a.lIIIllIllIIll[105]] = QUEST_ENTER_THE_ABYSS;
        aArray[a.lIIIllIllIIll[135]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL;
        aArray[a.lIIIllIllIIll[136]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
        aArray[a.lIIIllIllIIll[137]] = QUEST_THE_MAGE_ARENA;
        $VALUES = aArray;
    }

    private static boolean lIlIIIllIIIlIIl(int n2, int n3) {
        return n2 < n3;
    }

    private static String lIlIIIllIIIIlII(String lllllllllllllllIIIIlIIIIIlllIIll, String lllllllllllllllIIIIlIIIIIlllIIII) {
        try {
            SecretKeySpec lllllllllllllllIIIIlIIIIIlllIllI = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(lllllllllllllllIIIIlIIIIIlllIIII.getBytes(StandardCharsets.UTF_8)), lIIIllIllIIll[16]), "DES");
            Cipher lllllllllllllllIIIIlIIIIIlllIlIl = Cipher.getInstance("DES");
            lllllllllllllllIIIIlIIIIIlllIlIl.init(lIIIllIllIIll[4], lllllllllllllllIIIIlIIIIIlllIllI);
            return new String(lllllllllllllllIIIIlIIIIIlllIlIl.doFinal(Base64.getDecoder().decode(lllllllllllllllIIIIlIIIIIlllIIll.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lllllllllllllllIIIIlIIIIIlllIlII) {
            lllllllllllllllIIIIlIIIIIlllIlII.printStackTrace();
            return null;
        }
    }

    public static a valueOf(String string) {
        return Enum.valueOf(a.class, string);
    }

    private a(int n3) {
        this.id = n3;
    }

    private static void lIlIIIllIIIIlll() {
        lIIIllIllIIlI = new String[lIIIllIllIIll[48]];
        a.lIIIllIllIIlI[a.lIIIllIllIIll[0]] = a.lIlIIIllIIIIlII("HISomdqm/1f+g/nYxHq+MW4Re5axLFdW1iCbsXdlQo4=", "pdmMT");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[2]] = a.lIlIIIllIIIIlIl("MjLKShJO0mfz7GfqAIO73yXeA7O9ZnM6", "QuJiV");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[4]] = a.lIlIIIllIIIIllI("Fi8jBRwYPikEAQQpOQcdAiky", "GzfVH");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[6]] = a.lIlIIIllIIIIlII("BPIcvOj9Nv5De5/2MmS1I26BUnJ9hAuX", "NuYpw");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[8]] = a.lIlIIIllIIIIlII("5wu9pKFGrijLZg2e+xj+0FeSym6eN+wphRLuy6qhCrc=", "qeSSN");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[10]] = a.lIlIIIllIIIIllI("GyEMMQMVPQQyCAk1HSEfDyY=", "JtIbW");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[12]] = a.lIlIIIllIIIIlII("q7z9YO+nBMFObdJXOLKr2XPaDPT2P1+2", "zkEBJ");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[14]] = a.lIlIIIllIIIIlIl("JJe9wmPH+dF76ZfjdhNL6d9Pgzm5tyF4", "vgOpe");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[16]] = a.lIlIIIllIIIIllI("Pz4UHT8xOwMHJS0uDg8nJzQDCzgtPhQ=", "nkQNk");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[18]] = a.lIlIIIllIIIIllI("AT0DKhoPPA48EQItFS0CFTsVJgkYJxUt", "PhFyN");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[20]] = a.lIlIIIllIIIIlII("EMfQ3X3vYXghWN9RspoI3UMsoLSuZZsu", "doqpL");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[22]] = a.lIlIIIllIIIIllI("BSEmGAQLJjYFFQs5OhgEESYqDgM=", "TtcKP");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[24]] = a.lIlIIIllIIIIlIl("RfV8FYSPjoDFNOWWy+pISINFZIUBwXzy", "knVFG");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[26]] = a.lIlIIIllIIIIllI("Nx0yPzc5Gz8lJioMKCMlOQklPiIw", "fHwlc");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[28]] = a.lIlIIIllIIIIllI("NhMiBiA4FS8cMSsCOBoyOAc1BzUxGTQBNTMDOGRAUQ==", "gFgUt");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[30]] = a.lIlIIIllIIIIlII("efqmNIa0aZdBS7eAUXsY9fssURWvuIbC", "OJHwF");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[32]] = a.lIlIIIllIIIIlII("IEIWpxnyAWARZz/2MFpVW8Yj7lnuH0EQ", "yIQfK");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[34]] = a.lIlIIIllIIIIlIl("1C0aA+8neYm/8ty0FFPlp0VcQbfGLrInLjLQMRRCLTk=", "wlBIj");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[36]] = a.lIlIIIllIIIIllI("Iz8xGiwtKD0GMDMwNRs8", "rjtIx");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[38]] = a.lIlIIIllIIIIlII("wkAj3ANbxrVRU5E6tj6lEzNTWMXVTC6b", "wixtX");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[40]] = a.lIlIIIllIIIIlIl("Zy4+j77o46dw9nYjVx+sz4qcAPlDdUEx", "MQTLo");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[41]] = a.lIlIIIllIIIIlII("9XQkahbDMeZIb5Xlzw+JWCtDqst1yAFbakd/+vWZeG0=", "uLSbe");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[43]] = a.lIlIIIllIIIIllI("HCIMMRgSMwwjGAUoGS4NGTIINw==", "MwIbL");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[45]] = a.lIlIIIllIIIIlII("8var13aHNUiktePzQJvHcGV/iF9pnSCM", "nmBZH");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[47]] = a.lIlIIIllIIIIlII("F1+RHEQjy3WBZ0HXSxe6c+18/n00vawH", "wCEky");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[49]] = a.lIlIIIllIIIIllI("AjkuGCQMKDwKIhUzKAo+HSMl", "SlkKp");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[50]] = a.lIlIIIllIIIIllI("JgA1HRIoEDEKATYHIxEUIgY1", "wUpNF");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[52]] = a.lIlIIIllIIIIllI("PzkCMDUxKQsmLCsiEyItMTsIMSo9JAgzPic=", "nlGca");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[54]] = a.lIlIIIllIIIIlIl("JhxOdUmtLJ2zRfhhnUXT1IY67s7s4Jba", "QDMyr");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[3]] = a.lIlIIIllIIIIllI("HD4oOAASLSQsHBk0LDkRAyo=", "MkmkT");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[56]] = a.lIlIIIllIIIIlII("gAyuyLgEBHxroEbPxGXeCL5qDyhVXmqz", "KSiMC");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[5]] = a.lIlIIIllIIIIlII("YpRLTskdi+w5cf/MvlDxEXta//kfaPreciw4tBDbqIo=", "GEPnm");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[9]] = a.lIlIIIllIIIIllI("JSEpOi4rIy09PyYyLSU2KyU5LCkg", "ttliz");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[59]] = a.lIlIIIllIIIIlIl("dI0TjVxPLzm1xrRY5IdSolOT7TxXPTgH", "LXmJw");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[61]] = a.lIlIIIllIIIIllI("OyIcAzg1IxEVMy0lGB4oNSMLFSk=", "jwYPl");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[63]] = a.lIlIIIllIIIIlIl("RhyBmt28KOhLJ3UA0frUZW5tVBfDx7+7", "UrQVZ");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[65]] = a.lIlIIIllIIIIlIl("3nMAFm1BiD2NW1+6KYoE9TEpINfRvY2q", "LrRuG");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[67]] = a.lIlIIIllIIIIlII("WsXRKzt4WLm6VloCekk+FFHRJLBwVQs0", "mLmyt");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[69]] = a.lIlIIIllIIIIllI("BC0oCQQKMCIWCQo/PxsZGQ==", "UxmZP");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[70]] = a.lIlIIIllIIIIlIl("pRVFEPsXO4gTlwmFaw3/6bKWkYHLZ9ublZif1JWWTKE=", "jSvkz");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[72]] = a.lIlIIIllIIIIllI("AhQEGSwMCxQEPx8EHho3BwgOBA==", "SAAJx");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[74]] = a.lIlIIIllIIIIlIl("KfKaYnmQFCA/XCXdmApVLBwIMd2OcVMG", "wKKXW");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[76]] = a.lIlIIIllIIIIlII("tHEsjEHc39xT0edkWKTWXw==", "lBYvy");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[78]] = a.lIlIIIllIIIIlII("m7PalGTOaWiVZIRQunrbFZA4/cDkd8HM", "qUoRq");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[79]] = a.lIlIIIllIIIIlII("S1SSOHNdiq+ZyDBQFXdbobzw1nE2DfMD", "JfjSP");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[81]] = a.lIlIIIllIIIIlII("0hQ0tSHpgLlVbZD+UcEZv1Uqx+urqbrQ", "bpTXQ");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[82]] = a.lIlIIIllIIIIllI("NC8oPwE6NyI5ByszIysGOj8jKAo1Oz84Ciw=", "ezmlU");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[84]] = a.lIlIIIllIIIIllI("BxYQETIJDgAQIhMRCg8/BRcQED8=", "VCUBf");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[86]] = a.lIlIIIllIIIIlII("JLWSubfsWeFDW1EgUX131nV/Zxp8D17r", "IYUBB");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[88]] = a.lIlIIIllIIIIlII("weXyxP34udnJRD6SBo+gA2iOmo70oJQk", "KdiPu");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[90]] = a.lIlIIIllIIIIlII("OkXad7eXMHvZsD7WDD70oGmPe6OrubFd", "nbDul");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[92]] = a.lIlIIIllIIIIlII("wEUMcVzQG1YxeGm8yU4F8o4lQRMBBVmM", "wCFVM");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[94]] = a.lIlIIIllIIIIlII("M86Wi2jjiruhXrFSQCny8D3VypS+ALXu", "JaOZK");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[96]] = a.lIlIIIllIIIIlIl("mW2pP/GPWABuDkOkx/+fDsMW1uyhRyfsa4Ab7xzmWDA=", "YxkMO");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[98]] = a.lIlIIIllIIIIlII("wqSjN66fbi6XIXhFM19IAA==", "zrjsS");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[100]] = a.lIlIIIllIIIIllI("GA8qJwUWCCAiGAcdMDEdHx88", "IZotQ");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[102]] = a.lIlIIIllIIIIlIl("4UW/1v8OMeCFySGo7ZIF+Q==", "NARpf");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[104]] = a.lIlIIIllIIIIlII("CFJWyzkGkb17rheuSx2KmxAGg+oijQVR", "ZmUZk");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[106]] = a.lIlIIIllIIIIlIl("kot6LUHXGj1kyiphoBzY8g==", "TPRRX");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[108]] = a.lIlIIIllIIIIlIl("e9LCzhodkmyPtwxUTbgdDQ8K4bb6+3mx", "WmpVC");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[110]] = a.lIlIIIllIIIIllI("OSArFwc3JiYBFjgqJgEBLDA8", "hunDS");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[111]] = a.lIlIIIllIIIIlIl("rBRo9ukAjvDnAewQtdYYI09nQZw3MDoS", "bjIRO");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[113]] = a.lIlIIIllIIIIllI("GT0tAQQXPCkbDwo/Jw0HCSYmExkXPDobHw==", "HhhRP");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[23]] = a.lIlIIIllIIIIlII("YNq3ZoHfjFXCzp3Jg0qAPkPGWGq39CEP", "QqsBa");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[115]] = a.lIlIIIllIIIIlII("PLm0n/twuTpJUtJATJCZtAs2FiPY8oh68JalicgVrpY=", "KsFQe");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[58]] = a.lIlIIIllIIIIlIl("wP+XGsksORBOStJdIwK+wo6sKyIz2Imu", "KLBvo");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[118]] = a.lIlIIIllIIIIllI("JBAfHQQqEhMaEz0WBQYfIBYf", "uEZNP");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[33]] = a.lIlIIIllIIIIlIl("nEnneIaXZqoYHETW8HwgsVlH3CF74amw3bAcZ0/tFBQ=", "rWlHr");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[37]] = a.lIlIIIllIIIIlIl("QAWlJkoXfmxW25rX1jGoGBztXKIfIV2u", "IvWXO");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[122]] = a.lIlIIIllIIIIlIl("Q0md0FSoAg4iTVmDHU/eWYlzVpdNCQUS", "uFpDf");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[124]] = a.lIlIIIllIIIIllI("BSUCOxELJBUnCRgvFDwXGz4AIAoYNA==", "TpGhE");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[15]] = a.lIlIIIllIIIIlII("Etr2EMI4kJqIqY5YdruEZY1RbBkC7oNh", "zwgrT");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[127]] = a.lIlIIIllIIIIlIl("PNP8bhbvAC+ACqf8/EBTzsZxGuzczoALzDwtxGYufDkZ0dL665dmEw==", "uUuIb");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[129]] = a.lIlIIIllIIIIlII("t5EEc1uCXTl1cVGjaa+9wdCxQblPwtSd", "yImHx");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[131]] = a.lIlIIIllIIIIlIl("4vONN4rBnBn0kgsWyHhvBlOp5Pbl8msVPPXLnjLvRmc=", "jfPjv");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[133]] = a.lIlIIIllIIIIlII("UJ+we7kOCYoZ4LcJNG8361ZhD6e/KFKmPwVD3X3KScQ=", "CGLoi");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[105]] = a.lIlIIIllIIIIllI("HQEuBSQTESUCNR4LPx41ExUpDyMf", "LTkVp");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[135]] = a.lIlIIIllIIIIlII("tKRTagBqlUAAIWsB2cr+04KiyucI4VwXMawekHJulQo=", "mBsoE");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[136]] = a.lIlIIIllIIIIlIl("OoKOBxxPuqxTS81k2PiTxAZLgmhmneboS6cVpN89gRaqf1NutMkgM6K6bQWShap0", "eUGCM");
        a.lIIIllIllIIlI[a.lIIIllIllIIll[137]] = a.lIlIIIllIIIIlII("Dwe95K8hrrMUgWb5FxBdGcTlwgCdafi1", "HTdpB");
    }

    private static String lIlIIIllIIIIllI(String lllllllllllllllIIIIlIIIIlIIIIIll, String lllllllllllllllIIIIlIIIIlIIIIIlI) {
        lllllllllllllllIIIIlIIIIlIIIIIll = new String(Base64.getDecoder().decode(lllllllllllllllIIIIlIIIIlIIIIIll.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder lllllllllllllllIIIIlIIIIlIIIIllI = new StringBuilder();
        char[] lllllllllllllllIIIIlIIIIlIIIIlIl = lllllllllllllllIIIIlIIIIlIIIIIlI.toCharArray();
        int lllllllllllllllIIIIlIIIIlIIIIlII = lIIIllIllIIll[0];
        char[] lllllllllllllllIIIIlIIIIIllllllI = lllllllllllllllIIIIlIIIIlIIIIIll.toCharArray();
        int lllllllllllllllIIIIlIIIIIlllllIl = lllllllllllllllIIIIlIIIIIllllllI.length;
        int lllllllllllllllIIIIlIIIIIlllllII = lIIIllIllIIll[0];
        while (a.lIlIIIllIIIlIIl(lllllllllllllllIIIIlIIIIIlllllII, lllllllllllllllIIIIlIIIIIlllllIl)) {
            char lllllllllllllllIIIIlIIIIlIIIlIIl = lllllllllllllllIIIIlIIIIIllllllI[lllllllllllllllIIIIlIIIIIlllllII];
            lllllllllllllllIIIIlIIIIlIIIIllI.append((char)(lllllllllllllllIIIIlIIIIlIIIlIIl ^ lllllllllllllllIIIIlIIIIlIIIIlIl[lllllllllllllllIIIIlIIIIlIIIIlII % lllllllllllllllIIIIlIIIIlIIIIlIl.length]));
            "".length();
            ++lllllllllllllllIIIIlIIIIlIIIIlII;
            ++lllllllllllllllIIIIlIIIIIlllllII;
            "".length();
            if (((160 + 104 - 236 + 177 ^ 30 + 74 - 2 + 30) & (" ".length() ^ (0x69 ^ 0x21) ^ -" ".length())) == ((0xF5 ^ 0x8B ^ (4 ^ 0x47)) & (0x8A ^ 0x8C ^ (0xA5 ^ 0x9E) ^ -" ".length()))) continue;
            return null;
        }
        return String.valueOf(lllllllllllllllIIIIlIIIIlIIIIllI);
    }

    public int c() {
        return this.id;
    }

    private static String lIlIIIllIIIIlIl(String lllllllllllllllIIIIlIIIIlIIllIII, String lllllllllllllllIIIIlIIIIlIIlIlIl) {
        try {
            SecretKeySpec lllllllllllllllIIIIlIIIIlIIllIll = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(lllllllllllllllIIIIlIIIIlIIlIlIl.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher lllllllllllllllIIIIlIIIIlIIllIlI = Cipher.getInstance("Blowfish");
            lllllllllllllllIIIIlIIIIlIIllIlI.init(lIIIllIllIIll[4], lllllllllllllllIIIIlIIIIlIIllIll);
            return new String(lllllllllllllllIIIIlIIIIlIIllIlI.doFinal(Base64.getDecoder().decode(lllllllllllllllIIIIlIIIIlIIllIII.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lllllllllllllllIIIIlIIIIlIIllIIl) {
            lllllllllllllllIIIIlIIIIlIIllIIl.printStackTrace();
            return null;
        }
    }

    public static a[] values() {
        return (a[])$VALUES.clone();
    }
}

