/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap$Builder
 *  net.runelite.api.widgets.Widget
 *  net.runelite.api.widgets.WidgetInfo
 *  net.unethicalite.api.widgets.Widgets
 */
package -.-.k.r.-.b.a.g.c.d.o.c.u.t.e.-.o.l.i.d.i.c.u.c.w.n.e.n.l;

import com.google.common.collect.ImmutableMap;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import java.util.Map;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import net.runelite.api.widgets.Widget;
import net.runelite.api.widgets.WidgetInfo;
import net.unethicalite.api.widgets.Widgets;

public final class i
extends Enum<i> {
    public static final /* synthetic */ /* enum */ i CAMEL_5;
    public static final /* synthetic */ /* enum */ i SNAIL_5;
    public static final /* synthetic */ /* enum */ i KALPHITE_2;
    public static final /* synthetic */ /* enum */ i WYVERN_1;
    public static final /* synthetic */ /* enum */ i KALPHITE_4;
    public static final /* synthetic */ /* enum */ i SLUG_6;
    public static final /* synthetic */ /* enum */ i TORTOISE_3;
    public static final /* synthetic */ /* enum */ i TERRORBIRD_3;
    public static final /* synthetic */ /* enum */ i SNAIL_4;
    public static final /* synthetic */ /* enum */ i PENGUIN_5;
    public static final /* synthetic */ /* enum */ i MOLE_2;
    public static final /* synthetic */ /* enum */ i MOLE_4;
    public static final /* synthetic */ /* enum */ i LIZARD_3;
    public static final /* synthetic */ /* enum */ i LIZARD_2;
    public static final /* synthetic */ /* enum */ i TORTOISE_5;
    private static /* synthetic */ int[] llllllllI;
    public static final /* synthetic */ /* enum */ i KALPHITE_6;
    public static final /* synthetic */ /* enum */ i SNAKE_3;
    public static final /* synthetic */ /* enum */ i CAMEL_2;
    public static final /* synthetic */ /* enum */ i DRAGON_1;
    public static final /* synthetic */ /* enum */ i LIZARD_6;
    public static final /* synthetic */ /* enum */ i SLUG_4;
    public static final /* synthetic */ /* enum */ i SLUG_1;
    public static final /* synthetic */ /* enum */ i TORTOISE_1;
    public static final /* synthetic */ /* enum */ i PENGUIN_2;
    public static final /* synthetic */ /* enum */ i MONKEY_1;
    public static final /* synthetic */ /* enum */ i WYVERN_2;
    public static final /* synthetic */ /* enum */ i SLUG_3;
    public static final /* synthetic */ /* enum */ i LEECH_6;
    public static final /* synthetic */ /* enum */ i DRAGON_2;
    public static final /* synthetic */ /* enum */ i WYVERN_4;
    public static final /* synthetic */ /* enum */ i MONKEY_6;
    public static final /* synthetic */ /* enum */ i SNAIL_3;
    public static final /* synthetic */ /* enum */ i LEECH_5;
    public static final /* synthetic */ /* enum */ i PENGUIN_3;
    private final /* synthetic */ String question;
    private static /* synthetic */ String[] llllllIIl;
    public static final /* synthetic */ /* enum */ i CAMEL_4;
    public static final /* synthetic */ /* enum */ i DRAGON_3;
    public static final /* synthetic */ /* enum */ i PENGUIN_6;
    public static final /* synthetic */ /* enum */ i MONKEY_3;
    private static final /* synthetic */ i[] $VALUES;
    public static final /* synthetic */ /* enum */ i TORTOISE_2;
    public static final /* synthetic */ /* enum */ i LEECH_4;
    public static final /* synthetic */ /* enum */ i SNAIL_6;
    public static final /* synthetic */ /* enum */ i SLUG_2;
    public static final /* synthetic */ /* enum */ i CAMEL_6;
    public static final /* synthetic */ /* enum */ i PENGUIN_4;
    private final /* synthetic */ String answer;
    public static final /* synthetic */ /* enum */ i LEECH_3;
    public static final /* synthetic */ /* enum */ i TERRORBIRD_4;
    public static final /* synthetic */ /* enum */ i TERRORBIRD_5;
    public static final /* synthetic */ /* enum */ i SNAKE_2;
    public static final /* synthetic */ /* enum */ i WYVERN_5;
    public static final /* synthetic */ /* enum */ i LIZARD_1;
    public static final /* synthetic */ /* enum */ i TERRORBIRD_1;
    public static final /* synthetic */ /* enum */ i TORTOISE_4;
    public static final /* synthetic */ /* enum */ i LEECH_1;
    public static final /* synthetic */ /* enum */ i TERRORBIRD_6;
    public static final /* synthetic */ /* enum */ i KALPHITE_5;
    public static final /* synthetic */ /* enum */ i MOLE_6;
    public static final /* synthetic */ /* enum */ i LIZARD_4;
    public static final /* synthetic */ /* enum */ i MONKEY_4;
    public static final /* synthetic */ /* enum */ i SNAIL_1;
    public static final /* synthetic */ /* enum */ i TORTOISE_6;
    public static final /* synthetic */ /* enum */ i MOLE_5;
    public static final /* synthetic */ /* enum */ i KALPHITE_1;
    public static final /* synthetic */ /* enum */ i SNAIL_2;
    public static final /* synthetic */ /* enum */ i SNAKE_1;
    public static final /* synthetic */ /* enum */ i LEECH_2;
    public static final /* synthetic */ /* enum */ i DRAGON_5;
    public static final /* synthetic */ /* enum */ i DRAGON_4;
    public static final /* synthetic */ /* enum */ i LIZARD_5;
    public static final /* synthetic */ /* enum */ i DRAGON_6;
    public static final /* synthetic */ /* enum */ i MOLE_1;
    public static final /* synthetic */ /* enum */ i SNAKE_6;
    public static final /* synthetic */ /* enum */ i SNAKE_4;
    public static final /* synthetic */ /* enum */ i WYVERN_6;
    public static final /* synthetic */ /* enum */ i TERRORBIRD_2;
    public static final /* synthetic */ /* enum */ i CAMEL_1;
    public static final /* synthetic */ /* enum */ i MOLE_3;
    public static final /* synthetic */ /* enum */ i KALPHITE_3;
    public static final /* synthetic */ /* enum */ i SLUG_5;
    public static final /* synthetic */ /* enum */ i MONKEY_2;
    public static final /* synthetic */ /* enum */ i CAMEL_3;
    private static final /* synthetic */ Map<String, String> MATCHES;
    public static final /* synthetic */ /* enum */ i WYVERN_3;
    public static final /* synthetic */ /* enum */ i SNAKE_5;
    public static final /* synthetic */ /* enum */ i MONKEY_5;
    public static final /* synthetic */ /* enum */ i PENGUIN_1;

    public static i[] values() {
        return (i[])$VALUES.clone();
    }

    public String aa() {
        return this.question;
    }

    private static boolean llIllIIIllll(Object object) {
        return object != null;
    }

    /*
     * WARNING - void declaration
     */
    public static Widget a(String string, WidgetInfo ... widgetInfoArray) {
        void lIlIIlIIIllIl;
        String string2 = MATCHES.get(string);
        WidgetInfo[] widgetInfoArray2 = widgetInfoArray;
        int n2 = widgetInfoArray.length;
        int lIlIIlIIIllII = llllllllI[0];
        while (i.llIllIIIlllI(lIlIIlIIIllII, (int)lIlIIlIIIllIl)) {
            void lIlIIlIIIllll;
            void lIlIIlIIIlllI;
            void lIlIIlIIIlIll = lIlIIlIIIlllI[lIlIIlIIIllII];
            Widget lIlIIlIIIlIlI = Widgets.get((WidgetInfo)lIlIIlIIIlIll);
            if (i.llIllIIIllll(lIlIIlIIIlIlI) && i.llIllIIlIIII(lIlIIlIIIlIlI.getText().equals(lIlIIlIIIllll) ? 1 : 0)) {
                return lIlIIlIIIlIlI;
            }
            ++lIlIIlIIIllII;
            0;
            if ((0x22 ^ 0x79 ^ (0xFB ^ 0xA5)) > 0) continue;
            return null;
        }
        return null;
    }

    private static void llIllIIIllII() {
        llllllIIl = new String[llllllllI[252]];
        i.llllllIIl[i.llllllllI[0]] = i."LIZARD_1";
        i.llllllIIl[i.llllllllI[1]] = i."How does a lizard regulate body heat?";
        i.llllllIIl[i.llllllllI[2]] = i."Sunlight.";
        i.llllllIIl[i.llllllllI[3]] = i."LIZARD_2";
        i.llllllIIl[i.llllllllI[4]] = i."Who discovered how to kill lizards?";
        i.llllllIIl[i.llllllllI[5]] = i."The Slayer Masters.";
        i.llllllIIl[i.llllllllI[6]] = i."LIZARD_3";
        i.llllllIIl[i.llllllllI[7]] = i."How many eyes does a lizard have?";
        i.llllllIIl[i.llllllllI[8]] = i."Three.";
        i.llllllIIl[i.llllllllI[9]] = i."LIZARD_4";
        i.llllllIIl[i.llllllllI[10]] = i."What order do lizards belong to?";
        i.llllllIIl[i.llllllllI[11]] = i."Squamata.";
        i.llllllIIl[i.llllllllI[12]] = i."LIZARD_5";
        i.llllllIIl[i.llllllllI[13]] = i."What happens when a lizard becomes cold?";
        i.llllllIIl[i.llllllllI[14]] = i."It becomes sleepy.";
        i.llllllIIl[i.llllllllI[15]] = i."LIZARD_6";
        i.llllllIIl[i.llllllllI[16]] = i."Lizard skin is made of the same substance as?";
        i.llllllIIl[i.llllllllI[17]] = i."Hair.";
        i.llllllIIl[i.llllllllI[18]] = i."TORTOISE_1";
        i.llllllIIl[i.llllllllI[19]] = i."What is the name of the oldest tortoise ever recorded?";
        i.llllllIIl[i.llllllllI[20]] = i."Mibbiwocket.";
        i.llllllIIl[i.llllllllI[21]] = i."TORTOISE_2";
        i.llllllIIl[i.llllllllI[22]] = i."What is a tortoise's favourite food?";
        i.llllllIIl[i.llllllllI[23]] = i."Vegetables.";
        i.llllllIIl[i.llllllllI[24]] = i."TORTOISE_3";
        i.llllllIIl[i.llllllllI[25]] = i."Name the explorer who discovered the world's oldest tortoise.";
        i.llllllIIl[i.llllllllI[26]] = i."Admiral Bake.";
        i.llllllIIl[i.llllllllI[27]] = i."TORTOISE_4";
        i.llllllIIl[i.llllllllI[28]] = i."How does the tortoise protect itself?";
        i.llllllIIl[i.llllllllI[29]] = i."Hard shell.";
        i.llllllIIl[i.llllllllI[30]] = i."TORTOISE_5";
        i.llllllIIl[i.llllllllI[31]] = i."If a tortoise had twenty rings on its shell, how old would it be?";
        i.llllllIIl[i.llllllllI[32]] = i."Twenty years.";
        i.llllllIIl[i.llllllllI[33]] = i."TORTOISE_6";
        i.llllllIIl[i.llllllllI[34]] = i."Which race breeds tortoises for battle?";
        i.llllllIIl[i.llllllllI[35]] = i."Gnomes.";
        i.llllllIIl[i.llllllllI[36]] = i."DRAGON_1";
        i.llllllIIl[i.llllllllI[37]] = i."What is considered a delicacy by dragons?";
        i.llllllIIl[i.llllllllI[38]] = i."Runite.";
        i.llllllIIl[i.llllllllI[39]] = i."DRAGON_2";
        i.llllllIIl[i.llllllllI[40]] = i."What is the best defence against a dragon's attack?";
        i.llllllIIl[i.llllllllI[41]] = i."Anti dragon-breath shield.";
        i.llllllIIl[i.llllllllI[42]] = i."DRAGON_3";
        i.llllllIIl[i.llllllllI[43]] = i."How long do dragons live?";
        i.llllllIIl[i.llllllllI[44]] = i."Unknown.";
        i.llllllIIl[i.llllllllI[45]] = i."DRAGON_4";
        i.llllllIIl[i.llllllllI[46]] = i."Which of these is not a type of dragon?";
        i.llllllIIl[i.llllllllI[47]] = i."Elemental.";
        i.llllllIIl[i.llllllllI[48]] = i."DRAGON_5";
        i.llllllIIl[i.llllllllI[49]] = i."What is the favoured territory of a dragon?";
        i.llllllIIl[i.llllllllI[50]] = i."Old battle sites.";
        i.llllllIIl[i.llllllllI[51]] = i."DRAGON_6";
        i.llllllIIl[i.llllllllI[52]] = i."Approximately how many feet tall do dragons stand?";
        i.llllllIIl[i.llllllllI[53]] = i."Twelve.";
        i.llllllIIl[i.llllllllI[54]] = i."WYVERN_1";
        i.llllllIIl[i.llllllllI[55]] = i."How did the wyverns die out?";
        i.llllllIIl[i.llllllllI[56]] = i."Climate change.";
        i.llllllIIl[i.llllllllI[57]] = i."WYVERN_2";
        i.llllllIIl[i.llllllllI[58]] = i."How many legs does a wyvern have?";
        i.llllllIIl[i.llllllllI[59]] = i."Two.";
        i.llllllIIl[i.llllllllI[60]] = i."WYVERN_3";
        i.llllllIIl[i.llllllllI[61]] = i."Where have wyvern bones been found?";
        i.llllllIIl[i.llllllllI[62]] = i."Asgarnia.";
        i.llllllIIl[i.llllllllI[63]] = i."WYVERN_4";
        i.llllllIIl[i.llllllllI[64]] = i."Which genus does the wyvern theoretically belong to?";
        i.llllllIIl[i.llllllllI[65]] = i."Reptiles.";
        i.llllllIIl[i.llllllllI[66]] = i."WYVERN_5";
        i.llllllIIl[i.llllllllI[67]] = i."What are the wyverns' closest relations?";
        i.llllllIIl[i.llllllllI[68]] = i."Dragons.";
        i.llllllIIl[i.llllllllI[69]] = i."WYVERN_6";
        i.llllllIIl[i.llllllllI[70]] = i."What is the ambient temperature of wyvern bones?";
        i.llllllIIl[i.llllllllI[71]] = i."Below room temperature.";
        i.llllllIIl[i.llllllllI[72]] = i."SNAIL_1";
        i.llllllIIl[i.llllllllI[73]] = i."What is special about the shell of the giant Morytanian snail?";
        i.llllllIIl[i.llllllllI[74]] = i."It is resistant to acid.";
        i.llllllIIl[i.llllllllI[75]] = i."SNAIL_2";
        i.llllllIIl[i.llllllllI[76]] = i."How do Morytanian snails capture their prey?";
        i.llllllIIl[i.llllllllI[77]] = i."Spitting acid.";
        i.llllllIIl[i.llllllllI[78]] = i."SNAIL_3";
        i.llllllIIl[i.llllllllI[79]] = i."Which of these is a snail byproduct?";
        i.llllllIIl[i.llllllllI[80]] = i."Fireproof oil.";
        i.llllllIIl[i.llllllllI[81]] = i."SNAIL_4";
        i.llllllIIl[i.llllllllI[82]] = i."What does 'Achatina Acidia' mean?";
        i.llllllIIl[i.llllllllI[83]] = i."Acid-spitting snail.";
        i.llllllIIl[i.llllllllI[84]] = i."SNAIL_5";
        i.llllllIIl[i.llllllllI[85]] = i."How do snails move?";
        i.llllllIIl[i.llllllllI[86]] = i."Contracting and stretching.";
        i.llllllIIl[i.llllllllI[87]] = i."SNAIL_6";
        i.llllllIIl[i.llllllllI[88]] = i."What is the 'trapdoor', which snails use to cover the entrance to their shells called?";
        i.llllllIIl[i.llllllllI[89]] = i."An operculum.";
        i.llllllIIl[i.llllllllI[90]] = i."SNAKE_1";
        i.llllllIIl[i.llllllllI[91]] = i."What is snake venom adapted from?";
        i.llllllIIl[i.llllllllI[92]] = i."Stomach acid.";
        i.llllllIIl[i.llllllllI[93]] = i."SNAKE_2";
        i.llllllIIl[i.llllllllI[94]] = i."Aside from their noses, what do snakes use to smell?";
        i.llllllIIl[i.llllllllI[95]] = i."Tongue.";
        i.llllllIIl[i.llllllllI[96]] = i."SNAKE_3";
        i.llllllIIl[i.llllllllI[97]] = i."If a snake sticks its tongue out at you, what is it doing?";
        i.llllllIIl[i.llllllllI[98]] = i."Seeing how you smell.";
        i.llllllIIl[i.llllllllI[99]] = i."SNAKE_4";
        i.llllllIIl[i.llllllllI[100]] = i."If some snakes use venom to kill their prey, what do other snakes use?";
        i.llllllIIl[i.llllllllI[101]] = i."Constriction.";
        i.llllllIIl[i.llllllllI[102]] = i."SNAKE_5";
        i.llllllIIl[i.llllllllI[103]] = i."Lizards and snakes belong to the same order - what is it?";
        i.llllllIIl[i.llllllllI[104]] = i."Squamata.";
        i.llllllIIl[i.llllllllI[105]] = i."SNAKE_6";
        i.llllllIIl[i.llllllllI[106]] = i."Which habitat do snakes prefer?";
        i.llllllIIl[i.llllllllI[107]] = i."Anywhere.";
        i.llllllIIl[i.llllllllI[108]] = i."SLUG_1";
        i.llllllIIl[i.llllllllI[109]] = i."We assume that sea slugs have a stinging organ on their soft skin - what is it called?";
        i.llllllIIl[i.llllllllI[110]] = i."Nematocysts.";
        i.llllllIIl[i.llllllllI[111]] = i."SLUG_2";
        i.llllllIIl[i.llllllllI[112]] = i."Why has the museum never examined a live sea slug?";
        i.llllllIIl[i.llllllllI[113]] = i."The researchers keep vanishing.";
        i.llllllIIl[i.llllllllI[114]] = i."SLUG_3";
        i.llllllIIl[i.llllllllI[115]] = i."What do we think the sea slug feeds upon?";
        i.llllllIIl[i.llllllllI[116]] = i."Seaweed.";
        i.llllllIIl[i.llllllllI[117]] = i."SLUG_4";
        i.llllllIIl[i.llllllllI[118]] = i."What are the two fangs presumed to be used for?";
        i.llllllIIl[i.llllllllI[119]] = i."Defense or display.";
        i.llllllIIl[i.llllllllI[120]] = i."SLUG_5";
        i.llllllIIl[i.llllllllI[121]] = i."Off of which coastline would you find sea slugs?";
        i.llllllIIl[i.llllllllI[122]] = i."Ardougne.";
        i.llllllIIl[i.llllllllI[123]] = i."SLUG_6";
        i.llllllIIl[i.llllllllI[124]] = i."In what way are sea slugs similar to snails?";
        i.llllllIIl[i.llllllllI[125]] = i."They have a hard shell.";
        i.llllllIIl[i.llllllllI[126]] = i."MONKEY_1";
        i.llllllIIl[i.llllllllI[127]] = i."Which type of primates do monkeys belong to?";
        i.llllllIIl[i.llllllllI[128]] = i."Simian.";
        i.llllllIIl[i.llllllllI[129]] = i."MONKEY_2";
        i.llllllIIl[i.llllllllI[130]] = i."Which have the lighter colour: Karamjan or Harmless monkeys?";
        i.llllllIIl[i.llllllllI[131]] = i."Harmless.";
        i.llllllIIl[i.llllllllI[132]] = i."MONKEY_3";
        i.llllllIIl[i.llllllllI[133]] = i."Monkeys love bananas. What else do they like to eat?";
        i.llllllIIl[i.llllllllI[134]] = i."Bitternuts.";
        i.llllllIIl[i.llllllllI[135]] = i."MONKEY_4";
        i.llllllIIl[i.llllllllI[136]] = i."There are two known families of monkeys. One is Karamjan, the other is...?";
        i.llllllIIl[i.llllllllI[137]] = i."Harmless.";
        i.llllllIIl[i.llllllllI[138]] = i."MONKEY_5";
        i.llllllIIl[i.llllllllI[139]] = i."What colour mohawk do Karamjan monkeys have?";
        i.llllllIIl[i.llllllllI[140]] = i."Red.";
        i.llllllIIl[i.llllllllI[141]] = i."MONKEY_6";
        i.llllllIIl[i.llllllllI[142]] = i."What have Karamjan monkeys taken a deep dislike to?";
        i.llllllIIl[i.llllllllI[143]] = i."Seaweed.";
        i.llllllIIl[i.llllllllI[144]] = i."KALPHITE_1";
        i.llllllIIl[i.llllllllI[145]] = i."Kalphites are ruled by a...?";
        i.llllllIIl[i.llllllllI[146]] = i."Pasha.";
        i.llllllIIl[i.llllllllI[147]] = i."KALPHITE_2";
        i.llllllIIl[i.llllllllI[148]] = i."What is the lowest caste in kalphite society?";
        i.llllllIIl[i.llllllllI[149]] = i."Worker.";
        i.llllllIIl[i.llllllllI[150]] = i."KALPHITE_3";
        i.llllllIIl[i.llllllllI[151]] = i."What are the armoured plates on a kalphite called?";
        i.llllllIIl[i.llllllllI[152]] = i."Lamellae.";
        i.llllllIIl[i.llllllllI[153]] = i."KALPHITE_4";
        i.llllllIIl[i.llllllllI[154]] = i."Are kalphites carnivores, herbivores or omnivores?";
        i.llllllIIl[i.llllllllI[155]] = i."Carnivores.";
        i.llllllIIl[i.llllllllI[156]] = i."KALPHITE_5";
        i.llllllIIl[i.llllllllI[157]] = i."What are kalphites assumed to have evolved from?";
        i.llllllIIl[i.llllllllI[158]] = i."Scarab beetles.";
        i.llllllIIl[i.llllllllI[159]] = i."KALPHITE_6";
        i.llllllIIl[i.llllllllI[160]] = i."Name the prominent figure in kalphite mythology?";
        i.llllllIIl[i.llllllllI[161]] = i."Scabaras.";
        i.llllllIIl[i.llllllllI[162]] = i."TERRORBIRD_1";
        i.llllllIIl[i.llllllllI[163]] = i."What is a terrorbird's preferred food?";
        i.llllllIIl[i.llllllllI[164]] = i."Anything.";
        i.llllllIIl[i.llllllllI[165]] = i."TERRORBIRD_2";
        i.llllllIIl[i.llllllllI[166]] = i."Who use terrorbirds as mounts?";
        i.llllllIIl[i.llllllllI[167]] = i."Gnomes.";
        i.llllllIIl[i.llllllllI[168]] = i."TERRORBIRD_3";
        i.llllllIIl[i.llllllllI[169]] = i."Where do terrorbirds get most of their water?";
        i.llllllIIl[i.llllllllI[170]] = i."Eating plants.";
        i.llllllIIl[i.llllllllI[171]] = i."TERRORBIRD_4";
        i.llllllIIl[i.llllllllI[172]] = i."How many claws do terrorbirds have?";
        i.llllllIIl[i.llllllllI[173]] = i."Four.";
        i.llllllIIl[i.llllllllI[174]] = i."TERRORBIRD_5";
        i.llllllIIl[i.llllllllI[175]] = i."What do terrorbirds eat to aid digestion?";
        i.llllllIIl[i.llllllllI[176]] = i."Stones.";
        i.llllllIIl[i.llllllllI[177]] = i."TERRORBIRD_6";
        i.llllllIIl[i.llllllllI[178]] = i."How many teeth do terrorbirds have?";
        i.llllllIIl[i.llllllllI[179]] = i."0.";
        i.llllllIIl[i.llllllllI[180]] = i."PENGUIN_1";
        i.llllllIIl[i.llllllllI[181]] = i."Which sense do penguins rely on when hunting?";
        i.llllllIIl[i.llllllllI[182]] = i."Sight.";
        i.llllllIIl[i.llllllllI[183]] = i."PENGUIN_2";
        i.llllllIIl[i.llllllllI[184]] = i."Which skill seems unusual for the penguins to possess?";
        i.llllllIIl[i.llllllllI[185]] = i."Planning.";
        i.llllllIIl[i.llllllllI[186]] = i."PENGUIN_3";
        i.llllllIIl[i.llllllllI[187]] = i."How do penguins keep warm?";
        i.llllllIIl[i.llllllllI[188]] = i."A layer of fat.";
        i.llllllIIl[i.llllllllI[189]] = i."PENGUIN_4";
        i.llllllIIl[i.llllllllI[190]] = i."What is the preferred climate for penguins?";
        i.llllllIIl[i.llllllllI[191]] = i."Cold.";
        i.llllllIIl[i.llllllllI[192]] = i."PENGUIN_5";
        i.llllllIIl[i.llllllllI[193]] = i."Describe the behaviour of penguins?";
        i.llllllIIl[i.llllllllI[194]] = i."Social.";
        i.llllllIIl[i.llllllllI[195]] = i."PENGUIN_6";
        i.llllllIIl[i.llllllllI[196]] = i."When do penguins fast?";
        i.llllllIIl[i.llllllllI[197]] = i."During breeding.";
        i.llllllIIl[i.llllllllI[198]] = i."MOLE_1";
        i.llllllIIl[i.llllllllI[199]] = i."What habitat do moles prefer?";
        i.llllllIIl[i.llllllllI[200]] = i."Subterranean.";
        i.llllllIIl[i.llllllllI[201]] = i."MOLE_2";
        i.llllllIIl[i.llllllllI[202]] = i."Why are moles considered to be an agricultural pest?";
        i.llllllIIl[i.llllllllI[203]] = i."They dig holes.";
        i.llllllIIl[i.llllllllI[204]] = i."MOLE_3";
        i.llllllIIl[i.llllllllI[205]] = i."Who discovered giant moles?";
        i.llllllIIl[i.llllllllI[206]] = i."Wyson the Gardener.";
        i.llllllIIl[i.llllllllI[207]] = i."MOLE_4";
        i.llllllIIl[i.llllllllI[208]] = i."What would you call a group of young moles?";
        i.llllllIIl[i.llllllllI[209]] = i."A labour.";
        i.llllllIIl[i.llllllllI[210]] = i."MOLE_5";
        i.llllllIIl[i.llllllllI[211]] = i."What is a mole's favourite food?";
        i.llllllIIl[i.llllllllI[212]] = i."Insects and other invertebrates.";
        i.llllllIIl[i.llllllllI[213]] = i."MOLE_6";
        i.llllllIIl[i.llllllllI[214]] = i."Which family do moles belong to?";
        i.llllllIIl[i.llllllllI[215]] = i."The Talpidae family.";
        i.llllllIIl[i.llllllllI[216]] = i."CAMEL_1";
        i.llllllIIl[i.llllllllI[217]] = i."What is produced by feeding chilli to a camel?";
        i.llllllIIl[i.llllllllI[218]] = i."Toxic dung.";
        i.llllllIIl[i.llllllllI[219]] = i."CAMEL_2";
        i.llllllIIl[i.llllllllI[220]] = i."If an ugthanki has one, how many does a bactrian have?";
        i.llllllIIl[i.llllllllI[221]] = i."Two.";
        i.llllllIIl[i.llllllllI[222]] = i."CAMEL_3";
        i.llllllIIl[i.llllllllI[223]] = i."Camels: herbivore, carnivore or omnivore?";
        i.llllllIIl[i.llllllllI[224]] = i."Omnivore.";
        i.llllllIIl[i.llllllllI[225]] = i."CAMEL_4";
        i.llllllIIl[i.llllllllI[226]] = i."What is the usual mood for a camel?";
        i.llllllIIl[i.llllllllI[227]] = i."Annoyed.";
        i.llllllIIl[i.llllllllI[228]] = i."CAMEL_5";
        i.llllllIIl[i.llllllllI[229]] = i."Where would you find an ugthanki?";
        i.llllllIIl[i.llllllllI[230]] = i."Al Kharid.";
        i.llllllIIl[i.llllllllI[231]] = i."CAMEL_6";
        i.llllllIIl[i.llllllllI[232]] = i."Which camel byproduct is known to be very nutritious?";
        i.llllllIIl[i.llllllllI[233]] = i."Milk.";
        i.llllllIIl[i.llllllllI[234]] = i."LEECH_1";
        i.llllllIIl[i.llllllllI[235]] = i."What is the favoured habitat of leeches?";
        i.llllllIIl[i.llllllllI[236]] = i."Water.";
        i.llllllIIl[i.llllllllI[237]] = i."LEECH_2";
        i.llllllIIl[i.llllllllI[238]] = i."What shape is the inside of a leech's mouth?";
        i.llllllIIl[i.llllllllI[239]] = i."'Y'-shaped.";
        i.llllllIIl[i.llllllllI[240]] = i."LEECH_3";
        i.llllllIIl[i.llllllllI[241]] = i."Which of these is not eaten by leeches?";
        i.llllllIIl[i.llllllllI[242]] = i."Apples.";
        i.llllllIIl[i.llllllllI[243]] = i."LEECH_4";
        i.llllllIIl[i.llllllllI[244]] = i."What contributed to the giant growth of Morytanian leeches?";
        i.llllllIIl[i.llllllllI[245]] = i."Environment.";
        i.llllllIIl[i.llllllllI[246]] = i."LEECH_5";
        i.llllllIIl[i.llllllllI[247]] = i."What is special about Morytanian leeches?";
        i.llllllIIl[i.llllllllI[248]] = i."They attack by jumping.";
        i.llllllIIl[i.llllllllI[249]] = i."LEECH_6";
        i.llllllIIl[i.llllllllI[250]] = i."How does a leech change when it feeds?";
        i.llllllIIl[i.llllllllI[251]] = i."It doubles in size.";
    }

    private static boolean llIllIIIlllI(int n2, int n3) {
        return n2 < n3;
    }

    private static String llIlIlllIllI(String lIlIIIllllIII, String lIlIIIlllIlll) {
        try {
            SecretKeySpec lIlIIIllllIll = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(lIlIIIlllIlll.getBytes(StandardCharsets.UTF_8)), llllllllI[8]), "DES");
            Cipher lIlIIIllllIlI = Cipher.getInstance("DES");
            lIlIIIllllIlI.init(llllllllI[2], lIlIIIllllIll);
            return new String(lIlIIIllllIlI.doFinal(Base64.getDecoder().decode(lIlIIIllllIII.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lIlIIIllllIIl) {
            lIlIIIllllIIl.printStackTrace();
            return null;
        }
    }

    private static void llIllIIIllIl() {
        llllllllI = new int[253];
        i.llllllllI[0] = (0x68 ^ 0x19 ^ (0xD3 ^ 0x8D)) & (0xD8 ^ 0x86 ^ (0x17 ^ 0x66) ^ -1);
        i.llllllllI[1] = 1;
        i.llllllllI[2] = 2;
        i.llllllllI[3] = 3;
        i.llllllllI[4] = 0x94 ^ 0x90;
        i.llllllllI[5] = 0x70 ^ 0x75;
        i.llllllllI[6] = 128 + 75 - 122 + 56 ^ 81 + 65 - 78 + 75;
        i.llllllllI[7] = 62 + 147 - 200 + 143 ^ 14 + 154 - 48 + 39;
        i.llllllllI[8] = 0xA8 ^ 0xA0;
        i.llllllllI[9] = 0x35 ^ 0x73 ^ (0xD6 ^ 0x99);
        i.llllllllI[10] = 0x97 ^ 0xAF ^ (0x16 ^ 0x24);
        i.llllllllI[11] = 0x79 ^ 0x72;
        i.llllllllI[12] = 0x13 ^ 0x1F;
        i.llllllllI[13] = 7 ^ 0xA;
        i.llllllllI[14] = 13 + 154 - 39 + 57 ^ 23 + 141 - 46 + 65;
        i.llllllllI[15] = 0x93 ^ 0x9C;
        i.llllllllI[16] = 0xB1 ^ 0xA1;
        i.llllllllI[17] = 0x71 ^ 0x61 ^ 1;
        i.llllllllI[18] = 0xCC ^ 0x95 ^ (0x66 ^ 0x2D);
        i.llllllllI[19] = 0x7F ^ 0x6C;
        i.llllllllI[20] = 0xB8 ^ 0xAC;
        i.llllllllI[21] = 0xF5 ^ 0xA1 ^ (0xFE ^ 0xBF);
        i.llllllllI[22] = 8 ^ 0x1E;
        i.llllllllI[23] = 0x39 ^ 0x2E;
        i.llllllllI[24] = 0x46 ^ 0x7D ^ (0x80 ^ 0xA3);
        i.llllllllI[25] = 0x81 ^ 0x9F ^ (0x85 ^ 0x82);
        i.llllllllI[26] = 0x53 ^ 0x49;
        i.llllllllI[27] = 0x1D ^ 0x4A ^ (0xCE ^ 0x82);
        i.llllllllI[28] = 18 + 11 - -121 + 1 ^ 13 + 93 - 92 + 125;
        i.llllllllI[29] = 0xA5 ^ 0xB8;
        i.llllllllI[30] = 110 + 171 - 217 + 113 ^ 172 + 11 - 181 + 173;
        i.llllllllI[31] = 0x92 ^ 0xC7 ^ (0x3E ^ 0x74);
        i.llllllllI[32] = 1 ^ 0x21;
        i.llllllllI[33] = 0x66 ^ 0 ^ (0x4F ^ 8);
        i.llllllllI[34] = 0x70 ^ 0x52;
        i.llllllllI[35] = 0x72 ^ 0x51;
        i.llllllllI[36] = 3 ^ (0x9D ^ 0xBA);
        i.llllllllI[37] = 0xF1 ^ 0xB9 ^ (0x29 ^ 0x44);
        i.llllllllI[38] = 28 + 168 - 28 + 3 ^ 19 + 74 - -6 + 42;
        i.llllllllI[39] = 0x16 ^ 0x6F ^ (0x7C ^ 0x22);
        i.llllllllI[40] = 36 + 86 - 103 + 109 ^ 88 + 89 - 161 + 152;
        i.llllllllI[41] = 0x2C ^ 5;
        i.llllllllI[42] = 0x81 ^ 0xC2 ^ (0xC7 ^ 0xAE);
        i.llllllllI[43] = 0x9B ^ 0xB0;
        i.llllllllI[44] = 0xB ^ 0x7E ^ (0xC0 ^ 0x99);
        i.llllllllI[45] = 0x56 ^ 0x7B;
        i.llllllllI[46] = 26 + 101 - 100 + 133 ^ 36 + 4 - -15 + 87;
        i.llllllllI[47] = 0x1D ^ 0x32;
        i.llllllllI[48] = 0x2B ^ 0x1B;
        i.llllllllI[49] = 0xE8 ^ 0xC5 ^ (0x85 ^ 0x99);
        i.llllllllI[50] = 0x9E ^ 0xAC;
        i.llllllllI[51] = 0x18 ^ 0x2B;
        i.llllllllI[52] = 0x74 ^ 0x40;
        i.llllllllI[53] = 0x81 ^ 0xB4;
        i.llllllllI[54] = 55 + 81 - 23 + 48 ^ 54 + 107 - 154 + 144;
        i.llllllllI[55] = 0x98 ^ 0xAF;
        i.llllllllI[56] = 0x4F ^ 0x2E ^ (0xD5 ^ 0x8C);
        i.llllllllI[57] = 0x78 ^ 0x71 ^ (0x74 ^ 0x44);
        i.llllllllI[58] = 4 ^ 0x3E;
        i.llllllllI[59] = 0xFA ^ 0xC1;
        i.llllllllI[60] = 0x53 ^ 0x6F;
        i.llllllllI[61] = 0xD3 ^ 0x81 ^ (0xEB ^ 0x84);
        i.llllllllI[62] = 0x19 ^ 0x76 ^ (0x65 ^ 0x34);
        i.llllllllI[63] = 0x55 ^ 0x6A;
        i.llllllllI[64] = 0xE3 ^ 0xA3;
        i.llllllllI[65] = 0x48 ^ 9;
        i.llllllllI[66] = 0xB7 ^ 0x81 ^ (0x3E ^ 0x4A);
        i.llllllllI[67] = 0x1C ^ 0x23 ^ (0x29 ^ 0x55);
        i.llllllllI[68] = 125 + 150 - 110 + 60 ^ 92 + 92 - 82 + 63;
        i.llllllllI[69] = 0xE2 ^ 0xA7;
        i.llllllllI[70] = 0xD0 ^ 0x96;
        i.llllllllI[71] = 0x48 ^ 0x42 ^ (0xC5 ^ 0x88);
        i.llllllllI[72] = 0x3A ^ 6 ^ (0xEA ^ 0x9E);
        i.llllllllI[73] = 0x74 ^ 4 ^ (0xAD ^ 0x94);
        i.llllllllI[74] = 0xE2 ^ 0xA8;
        i.llllllllI[75] = 0x69 ^ 0x22;
        i.llllllllI[76] = 0x9C ^ 0x99 ^ (0x2E ^ 0x67);
        i.llllllllI[77] = 0x4E ^ 3;
        i.llllllllI[78] = 0x48 ^ 0xC ^ (0x1D ^ 0x17);
        i.llllllllI[79] = 0x2B ^ 0x64;
        i.llllllllI[80] = 0x2C ^ 0x18 ^ (0x21 ^ 0x45);
        i.llllllllI[81] = 0xD3 ^ 0x82;
        i.llllllllI[82] = 0x1D ^ 0x6E ^ (0x14 ^ 0x35);
        i.llllllllI[83] = 0xC ^ 0x78 ^ (7 ^ 0x20);
        i.llllllllI[84] = 67 + 69 - -35 + 63 ^ 100 + 92 - 151 + 149;
        i.llllllllI[85] = 0x68 ^ 0x3D;
        i.llllllllI[86] = 20 + 177 - 195 + 217 ^ 102 + 63 - 70 + 46;
        i.llllllllI[87] = 0x25 ^ 0x72;
        i.llllllllI[88] = 0x4F ^ 0x17;
        i.llllllllI[89] = 0xDE ^ 0x87;
        i.llllllllI[90] = 0x7B ^ 0x21;
        i.llllllllI[91] = 1 ^ 0x17 ^ (0xE5 ^ 0xA8);
        i.llllllllI[92] = 0x60 ^ 0x3C;
        i.llllllllI[93] = 6 ^ 0x5B;
        i.llllllllI[94] = 0xCC ^ 0x92;
        i.llllllllI[95] = 0x53 ^ 0xC;
        i.llllllllI[96] = 0x42 ^ 2 ^ (0x63 ^ 0x43);
        i.llllllllI[97] = 0xC9 ^ 0xA8;
        i.llllllllI[98] = 0x4B ^ 0x29;
        i.llllllllI[99] = 191 + 199 - 290 + 146 ^ 112 + 89 - 131 + 79;
        i.llllllllI[100] = 0xDC ^ 0xB8;
        i.llllllllI[101] = 0xFD ^ 0xA2 ^ (0x6D ^ 0x57);
        i.llllllllI[102] = 0xFC ^ 0xBC ^ (0x37 ^ 0x11);
        i.llllllllI[103] = 0xF7 ^ 0x90;
        i.llllllllI[104] = 118 + 125 - 176 + 101 ^ 2 + 127 - 62 + 125;
        i.llllllllI[105] = 0x56 ^ 0x3F;
        i.llllllllI[106] = 0x25 ^ 0x2A ^ (0xB ^ 0x6E);
        i.llllllllI[107] = 0xAC ^ 0xC7;
        i.llllllllI[108] = 0x69 ^ 0x56 ^ (0x24 ^ 0x77);
        i.llllllllI[109] = 3 ^ 0xF ^ (0x2B ^ 0x4A);
        i.llllllllI[110] = 0xF6 ^ 0x98;
        i.llllllllI[111] = 0x42 ^ 0x2D;
        i.llllllllI[112] = 3 ^ 0x73;
        i.llllllllI[113] = 0x76 ^ 7;
        i.llllllllI[114] = 0xE8 ^ 0x9A;
        i.llllllllI[115] = 71 + 204 - 157 + 105 ^ 72 + 28 - -30 + 42;
        i.llllllllI[116] = 0x27 ^ 0x47 ^ (0x29 ^ 0x3D);
        i.llllllllI[117] = 108 + 72 - 67 + 113 ^ 95 + 81 - 90 + 65;
        i.llllllllI[118] = 19 + 239 - 92 + 76 ^ 44 + 127 - 85 + 46;
        i.llllllllI[119] = 196 + 113 - 125 + 49 ^ 103 + 30 - -14 + 11;
        i.llllllllI[120] = 0x47 ^ 0x49 ^ (0x5C ^ 0x2A);
        i.llllllllI[121] = 0xC8 ^ 0xB1;
        i.llllllllI[122] = 0x37 ^ 0x65 ^ (0xB9 ^ 0x91);
        i.llllllllI[123] = 192 + 55 - 194 + 164 ^ 34 + 78 - -20 + 30;
        i.llllllllI[124] = 0x19 ^ 0x65;
        i.llllllllI[125] = 99 + 48 - -75 + 3 ^ 99 + 119 - 149 + 87;
        i.llllllllI[126] = 0x45 ^ 0x68 ^ (0xEE ^ 0xBD);
        i.llllllllI[127] = (0x29 ^ 0x6E) + (0x31 ^ 0x79) - (0x32 ^ 0x75) + (0x35 ^ 2);
        i.llllllllI[128] = 12 + 113 - 17 + 20;
        i.llllllllI[129] = 71 + 81 - 60 + 37;
        i.llllllllI[130] = (0xD3 ^ 0xC3) + (0x16 ^ 0x6D) - (0x1C ^ 0x38) + (0x7C ^ 0x67);
        i.llllllllI[131] = (0xD3 ^ 0x80) + (0x43 ^ 0x63) - (0x4A ^ 0x74) + (0x19 ^ 0x57);
        i.llllllllI[132] = (0xEC ^ 0xC4) + (0xFA ^ 0xB7) - (0xE ^ 0x1E) + (0xA0 ^ 0xBF);
        i.llllllllI[133] = (0x5B ^ 0x41) + (0x8D ^ 0x82) - -(0xF ^ 0x4E) + (0x40 ^ 0x5B);
        i.llllllllI[134] = 124 + 116 - 171 + 64 + (0x26 ^ 0x54) - (76 + 150 - 48 + 0) + (0xE0 ^ 0xA1);
        i.llllllllI[135] = (0xAB ^ 0x92) + (0x9F ^ 0xA3) - (0x17 ^ 0x3D) + (0x14 ^ 0x28);
        i.llllllllI[136] = 89 + 129 - 132 + 50;
        i.llllllllI[137] = 40 + 18 - -4 + 75;
        i.llllllllI[138] = 64 + 99 - 121 + 96;
        i.llllllllI[139] = (0xFC ^ 0xB8) + (74 + 92 - 53 + 21) - (0x75 ^ 0x24) + (0x32 ^ 0x20);
        i.llllllllI[140] = 64 + 20 - -44 + 12;
        i.llllllllI[141] = 14 + 36 - 20 + 97 + (0x7E ^ 0x18) - (114 + 85 - 97 + 73) + (0x24 ^ 0x73);
        i.llllllllI[142] = 34 + 85 - -5 + 18;
        i.llllllllI[143] = 139 + 29 - 141 + 116;
        i.llllllllI[144] = (0x3C ^ 0x7F) + (0xA6 ^ 0xC6) - (7 ^ 0x49) + (0x35 ^ 0xE);
        i.llllllllI[145] = 30 + 68 - 38 + 85;
        i.llllllllI[146] = (0x30 ^ 0x28) + (0xF9 ^ 0xB3) - (0xC0 ^ 0x87) + (0xD4 ^ 0xA3);
        i.llllllllI[147] = (0xCC ^ 0xA8) + (0x5C ^ 0x4F) - (0x13 ^ 0x16) + (0xA4 ^ 0x85);
        i.llllllllI[148] = 24 + 43 - -36 + 45;
        i.llllllllI[149] = (0x57 ^ 0x44) + (0xCF ^ 0xB2) - (0x53 ^ 0x40) + (0x44 ^ 0x5C);
        i.llllllllI[150] = (0x75 ^ 0x44) + (0x6E ^ 0x72) - -(0x99 ^ 0x82) + (0x3B ^ 0x15);
        i.llllllllI[151] = 66 + 25 - 14 + 74;
        i.llllllllI[152] = 101 + 6 - -16 + 27 + (0xD3 ^ 0xB8) - (189 + 112 - 146 + 89) + (38 + 136 - 162 + 127);
        i.llllllllI[153] = (0x76 ^ 0x46) + (0x56 ^ 0x14) - (0x4F ^ 0x59) + (0xFD ^ 0xC0);
        i.llllllllI[154] = 53 + 96 - 108 + 111 + (0xC ^ 0x20) - (0x7C ^ 9) + (0x33 ^ 0x78);
        i.llllllllI[155] = (0x81 ^ 0xBD) + (0x58 ^ 0x5E) - -(8 ^ 0x46) + (0x78 ^ 0x73);
        i.llllllllI[156] = 4 + 37 - -2 + 113;
        i.llllllllI[157] = (0x58 ^ 0x1F) + (0xDC ^ 0xAE) - (127 + 120 - 150 + 37) + (0xE6 ^ 0x8C);
        i.llllllllI[158] = 92 + 12 - 51 + 105;
        i.llllllllI[159] = 79 + 15 - -47 + 18;
        i.llllllllI[160] = 98 + 43 - -12 + 7;
        i.llllllllI[161] = 134 + 133 - 190 + 84;
        i.llllllllI[162] = (0xC ^ 0x33) + (0x28 ^ 0x5B) - (0x82 ^ 0x96) + (0xAC ^ 0xA8);
        i.llllllllI[163] = (0x52 ^ 0x57) + (24 + 78 - 84 + 121) - -(0x94 ^ 0x9B) + (0x16 ^ 0x12);
        i.llllllllI[164] = 6 + 41 - -113 + 4;
        i.llllllllI[165] = 127 + 58 - 126 + 106;
        i.llllllllI[166] = (0x91 ^ 0xBB) + 3 - -(0xB ^ 0x32) + (0x44 ^ 4);
        i.llllllllI[167] = 101 + 4 - 15 + 77;
        i.llllllllI[168] = (0x10 ^ 0x6A) + (59 + 113 - 92 + 87) - (85 + 148 - 54 + 28) + (0x4F ^ 0x19);
        i.llllllllI[169] = 3 + 150 - 9 + 25;
        i.llllllllI[170] = 63 + 74 - 42 + 75;
        i.llllllllI[171] = 165 + 39 - 70 + 37;
        i.llllllllI[172] = 137 + 44 - 20 + 11;
        i.llllllllI[173] = 7 + 169 - 128 + 125;
        i.llllllllI[174] = (0x62 ^ 0x69) + (0xA ^ 0x52) - -(0x14 ^ 1) + (0xB5 ^ 0x83);
        i.llllllllI[175] = 55 + 53 - 19 + 86;
        i.llllllllI[176] = 94 + 111 - 194 + 165;
        i.llllllllI[177] = (0x53 ^ 0x22) + (10 + 29 - -41 + 70) - (117 + 39 - 68 + 149) + (94 + 67 - 38 + 28);
        i.llllllllI[178] = 113 + 30 - 28 + 63;
        i.llllllllI[179] = 112 + 24 - 35 + 26 + (0x9F ^ 0x95) - -(0x68 ^ 0x76) + (0x16 ^ 0x1A);
        i.llllllllI[180] = (0x75 ^ 0x71) + (0x8A ^ 0xAA) - (0xC9 ^ 0xC7) + (34 + 7 - 32 + 149);
        i.llllllllI[181] = 64 + 68 - 45 + 94;
        i.llllllllI[182] = (0xFD ^ 0xB3) + (0xD1 ^ 0x83) - (80 + 109 - 133 + 73) + (1 + 102 - -26 + 22);
        i.llllllllI[183] = 57 + 56 - 105 + 175;
        i.llllllllI[184] = (0x35 ^ 0x4B) + (0xE7 ^ 0x9F) - (10 + 46 - -60 + 93) + (35 + 112 - 85 + 85);
        i.llllllllI[185] = 121 + 5 - -5 + 54;
        i.llllllllI[186] = 49 + 173 - 125 + 89;
        i.llllllllI[187] = 34 + 70 - -47 + 36;
        i.llllllllI[188] = (0x26 ^ 0x7D) + (51 + 79 - -31 + 16) - (37 + 173 - 192 + 179) + (0x13 ^ 0x66);
        i.llllllllI[189] = (0x6C ^ 0x2E) + (0xE5 ^ 0xA0) - (9 ^ 0x35) + (0x2D ^ 0x5F);
        i.llllllllI[190] = 141 + 82 - 54 + 21;
        i.llllllllI[191] = 64 + 119 - 92 + 100;
        i.llllllllI[192] = 46 + 44 - -46 + 56;
        i.llllllllI[193] = 118 + 66 - 155 + 164;
        i.llllllllI[194] = (0x7C ^ 0x48) + (0x49 ^ 0xF) - -(0x32 ^ 0x3E) + (0x8D ^ 0xB1);
        i.llllllllI[195] = 36 + 169 - 167 + 134 + (0x2D ^ 0x64) - (160 + 105 - 154 + 66) + (91 + 3 - -2 + 31);
        i.llllllllI[196] = 166 + 9 - 43 + 64;
        i.llllllllI[197] = 187 + 56 - 110 + 64;
        i.llllllllI[198] = 105 + 47 - 57 + 50 + (138 + 46 - 129 + 120) - (1 + 31 - -92 + 71) + (0xD1 ^ 0x98);
        i.llllllllI[199] = 61 + 179 - 178 + 137;
        i.llllllllI[200] = (0x7B ^ 0x4A) + (65 + 2 - 46 + 108) - (0x31 ^ 0x38) + (0x37 ^ 0x28);
        i.llllllllI[201] = 59 + 196 - 166 + 112;
        i.llllllllI[202] = 111 + 91 - 180 + 116 + (47 + 139 - 106 + 99) - (145 + 198 - 156 + 33) + (0xEE ^ 0x87);
        i.llllllllI[203] = 40 + 129 - 1 + 35;
        i.llllllllI[204] = 138 + 134 - 162 + 42 + (110 + 87 - 73 + 63) - (0xFFFFF70E & 0x9F3) + (0x5C ^ 0x27);
        i.llllllllI[205] = 96 + 93 - 157 + 173;
        i.llllllllI[206] = 188 + 161 - 331 + 188;
        i.llllllllI[207] = 108 + 117 - 95 + 77;
        i.llllllllI[208] = 162 + 34 - 158 + 170;
        i.llllllllI[209] = 29 + 43 - -11 + 80 + (0x87 ^ 0xA5) - (0x68 ^ 0x63) + (0x80 ^ 0x97);
        i.llllllllI[210] = (0xBA ^ 0xB3) + (0x4B ^ 0x2B) - (0x45 ^ 0x40) + (0xE6 ^ 0x88);
        i.llllllllI[211] = 182 + 163 - 227 + 93;
        i.llllllllI[212] = (0x2F ^ 0x6C) + 2 - -(0xA6 ^ 0xBD) + (0xF0 ^ 0x84);
        i.llllllllI[213] = 186 + 111 - 157 + 73;
        i.llllllllI[214] = 161 + 199 - 331 + 185;
        i.llllllllI[215] = 116 + 35 - 135 + 199;
        i.llllllllI[216] = 127 + 124 - 84 + 49;
        i.llllllllI[217] = 127 + 104 - 143 + 129;
        i.llllllllI[218] = 6 + 32 - -99 + 81;
        i.llllllllI[219] = (0x9A ^ 0xAA) + (98 + 143 - 66 + 5) - (0x2C ^ 0x4D) + (0xE9 ^ 0xB1);
        i.llllllllI[220] = 74 + 194 - 213 + 149 + (15 + 166 - 53 + 85) - (0xFFFFF5BD & 0xB6E) + (0xF6 ^ 0x91);
        i.llllllllI[221] = (0xCE ^ 0xB6) + (0x6B ^ 0xD) - (0x1A ^ 0x3F) + (0xE3 ^ 0xC7);
        i.llllllllI[222] = 97 + 131 - 82 + 76;
        i.llllllllI[223] = (0x39 ^ 0x6A) + (45 + 23 - -137 + 17) - (0xFFFF83DD & 0x7D37) + (127 + 99 - 45 + 14);
        i.llllllllI[224] = 134 + 159 - 113 + 44;
        i.llllllllI[225] = 110 + 142 - 137 + 104 + (103 + 143 - 183 + 155) - (0xFFFFC1BD & 0x3F4A) + (0x81 ^ 0xB5);
        i.llllllllI[226] = 127 + 19 - 41 + 69 + (72 + 24 - 95 + 156) - (6 + 53 - -131 + 27) + (0x41 ^ 0x31);
        i.llllllllI[227] = 184 + 141 - 188 + 90;
        i.llllllllI[228] = 227 + 114 - 120 + 7;
        i.llllllllI[229] = 14 + 23 - -182 + 10;
        i.llllllllI[230] = 204 + 154 - 259 + 131;
        i.llllllllI[231] = 43 + 133 - 82 + 122 + (0x2E ^ 0x12) - (0x3D ^ 0xD) + 3;
        i.llllllllI[232] = 102 + 54 - 41 + 22 + (0xEA ^ 0xC3) - (0xEF ^ 0xA6) + (108 + 99 - 147 + 67);
        i.llllllllI[233] = (0xE3 ^ 0xBD) + (0x24 ^ 0x4B) - (65 + 38 - -52 + 2) + (164 + 61 - 72 + 32);
        i.llllllllI[234] = 8 + 142 - 75 + 159;
        i.llllllllI[235] = 30 + 85 - 92 + 129 + (148 + 98 - 191 + 159) - (0xFFFFFF6B & 0x1DD) + (87 + 121 - 135 + 125);
        i.llllllllI[236] = 2 + 228 - 67 + 73;
        i.llllllllI[237] = 176 + 105 - 145 + 101;
        i.llllllllI[238] = 35 + 96 - 93 + 146 + (38 + 12 - -87 + 17) - (0x2B ^ 0x4D) + 2;
        i.llllllllI[239] = 72 + 187 - 147 + 127;
        i.llllllllI[240] = 67 + 68 - 27 + 132;
        i.llllllllI[241] = 150 + 94 - 91 + 3 + (0x79 ^ 7) - (0x3E ^ 0x45) + (0x2E ^ 0x7C);
        i.llllllllI[242] = 40 + 28 - 59 + 163 + (0x35 ^ 0x49) - (102 + 149 - 110 + 109) + (126 + 76 - 148 + 142);
        i.llllllllI[243] = 189 + 126 - 96 + 24;
        i.llllllllI[244] = 215 + 59 - 61 + 31;
        i.llllllllI[245] = (0xC ^ 0x14) + (15 + 56 - -92 + 16) - (0x8C ^ 0xB7) + (0xA4 ^ 0xC1);
        i.llllllllI[246] = (0xF ^ 0x1D) + (0x31 ^ 0x50) - (0x79 ^ 0x52) + (165 + 22 - 147 + 134);
        i.llllllllI[247] = 30 + 96 - 89 + 136 + (0x43 ^ 0x11) - (66 + 0 - 51 + 189) + (181 + 82 - 194 + 127);
        i.llllllllI[248] = 82 + 171 - 83 + 78;
        i.llllllllI[249] = 37 + 96 - 68 + 128 + (0x6F ^ 0x64) - (51 + 122 - 20 + 5) + (196 + 37 - 123 + 93);
        i.llllllllI[250] = (0x44 ^ 0x28) + (49 + 124 - 165 + 152) - (0x80 ^ 0xBC) + (0x66 ^ 0x4C);
        i.llllllllI[251] = 58 + 243 - 101 + 51;
        i.llllllllI[252] = 47 + 20 - 61 + 159 + (131 + 140 - 186 + 112) - (0xFFFFA953 & 0x57FC) + (92 + 74 - 7 + 67);
    }

    private static boolean llIllIIlIIII(int n2) {
        return n2 != 0;
    }

    public String ab() {
        return this.answer;
    }

    /*
     * WARNING - void declaration
     */
    static {
        block1: {
            void lIlIIlIIIIIlI;
            i.llIllIIIllIl();
            i.llIllIIIllII();
            LIZARD_1 = new i(llllllIIl[llllllllI[1]], llllllIIl[llllllllI[2]]);
            LIZARD_2 = new i(llllllIIl[llllllllI[4]], llllllIIl[llllllllI[5]]);
            LIZARD_3 = new i(llllllIIl[llllllllI[7]], llllllIIl[llllllllI[8]]);
            LIZARD_4 = new i(llllllIIl[llllllllI[10]], llllllIIl[llllllllI[11]]);
            LIZARD_5 = new i(llllllIIl[llllllllI[13]], llllllIIl[llllllllI[14]]);
            LIZARD_6 = new i(llllllIIl[llllllllI[16]], llllllIIl[llllllllI[17]]);
            TORTOISE_1 = new i(llllllIIl[llllllllI[19]], llllllIIl[llllllllI[20]]);
            TORTOISE_2 = new i(llllllIIl[llllllllI[22]], llllllIIl[llllllllI[23]]);
            TORTOISE_3 = new i(llllllIIl[llllllllI[25]], llllllIIl[llllllllI[26]]);
            TORTOISE_4 = new i(llllllIIl[llllllllI[28]], llllllIIl[llllllllI[29]]);
            TORTOISE_5 = new i(llllllIIl[llllllllI[31]], llllllIIl[llllllllI[32]]);
            TORTOISE_6 = new i(llllllIIl[llllllllI[34]], llllllIIl[llllllllI[35]]);
            DRAGON_1 = new i(llllllIIl[llllllllI[37]], llllllIIl[llllllllI[38]]);
            DRAGON_2 = new i(llllllIIl[llllllllI[40]], llllllIIl[llllllllI[41]]);
            DRAGON_3 = new i(llllllIIl[llllllllI[43]], llllllIIl[llllllllI[44]]);
            DRAGON_4 = new i(llllllIIl[llllllllI[46]], llllllIIl[llllllllI[47]]);
            DRAGON_5 = new i(llllllIIl[llllllllI[49]], llllllIIl[llllllllI[50]]);
            DRAGON_6 = new i(llllllIIl[llllllllI[52]], llllllIIl[llllllllI[53]]);
            WYVERN_1 = new i(llllllIIl[llllllllI[55]], llllllIIl[llllllllI[56]]);
            WYVERN_2 = new i(llllllIIl[llllllllI[58]], llllllIIl[llllllllI[59]]);
            WYVERN_3 = new i(llllllIIl[llllllllI[61]], llllllIIl[llllllllI[62]]);
            WYVERN_4 = new i(llllllIIl[llllllllI[64]], llllllIIl[llllllllI[65]]);
            WYVERN_5 = new i(llllllIIl[llllllllI[67]], llllllIIl[llllllllI[68]]);
            WYVERN_6 = new i(llllllIIl[llllllllI[70]], llllllIIl[llllllllI[71]]);
            SNAIL_1 = new i(llllllIIl[llllllllI[73]], llllllIIl[llllllllI[74]]);
            SNAIL_2 = new i(llllllIIl[llllllllI[76]], llllllIIl[llllllllI[77]]);
            SNAIL_3 = new i(llllllIIl[llllllllI[79]], llllllIIl[llllllllI[80]]);
            SNAIL_4 = new i(llllllIIl[llllllllI[82]], llllllIIl[llllllllI[83]]);
            SNAIL_5 = new i(llllllIIl[llllllllI[85]], llllllIIl[llllllllI[86]]);
            SNAIL_6 = new i(llllllIIl[llllllllI[88]], llllllIIl[llllllllI[89]]);
            SNAKE_1 = new i(llllllIIl[llllllllI[91]], llllllIIl[llllllllI[92]]);
            SNAKE_2 = new i(llllllIIl[llllllllI[94]], llllllIIl[llllllllI[95]]);
            SNAKE_3 = new i(llllllIIl[llllllllI[97]], llllllIIl[llllllllI[98]]);
            SNAKE_4 = new i(llllllIIl[llllllllI[100]], llllllIIl[llllllllI[101]]);
            SNAKE_5 = new i(llllllIIl[llllllllI[103]], llllllIIl[llllllllI[104]]);
            SNAKE_6 = new i(llllllIIl[llllllllI[106]], llllllIIl[llllllllI[107]]);
            SLUG_1 = new i(llllllIIl[llllllllI[109]], llllllIIl[llllllllI[110]]);
            SLUG_2 = new i(llllllIIl[llllllllI[112]], llllllIIl[llllllllI[113]]);
            SLUG_3 = new i(llllllIIl[llllllllI[115]], llllllIIl[llllllllI[116]]);
            SLUG_4 = new i(llllllIIl[llllllllI[118]], llllllIIl[llllllllI[119]]);
            SLUG_5 = new i(llllllIIl[llllllllI[121]], llllllIIl[llllllllI[122]]);
            SLUG_6 = new i(llllllIIl[llllllllI[124]], llllllIIl[llllllllI[125]]);
            MONKEY_1 = new i(llllllIIl[llllllllI[127]], llllllIIl[llllllllI[128]]);
            MONKEY_2 = new i(llllllIIl[llllllllI[130]], llllllIIl[llllllllI[131]]);
            MONKEY_3 = new i(llllllIIl[llllllllI[133]], llllllIIl[llllllllI[134]]);
            MONKEY_4 = new i(llllllIIl[llllllllI[136]], llllllIIl[llllllllI[137]]);
            MONKEY_5 = new i(llllllIIl[llllllllI[139]], llllllIIl[llllllllI[140]]);
            MONKEY_6 = new i(llllllIIl[llllllllI[142]], llllllIIl[llllllllI[143]]);
            KALPHITE_1 = new i(llllllIIl[llllllllI[145]], llllllIIl[llllllllI[146]]);
            KALPHITE_2 = new i(llllllIIl[llllllllI[148]], llllllIIl[llllllllI[149]]);
            KALPHITE_3 = new i(llllllIIl[llllllllI[151]], llllllIIl[llllllllI[152]]);
            KALPHITE_4 = new i(llllllIIl[llllllllI[154]], llllllIIl[llllllllI[155]]);
            KALPHITE_5 = new i(llllllIIl[llllllllI[157]], llllllIIl[llllllllI[158]]);
            KALPHITE_6 = new i(llllllIIl[llllllllI[160]], llllllIIl[llllllllI[161]]);
            TERRORBIRD_1 = new i(llllllIIl[llllllllI[163]], llllllIIl[llllllllI[164]]);
            TERRORBIRD_2 = new i(llllllIIl[llllllllI[166]], llllllIIl[llllllllI[167]]);
            TERRORBIRD_3 = new i(llllllIIl[llllllllI[169]], llllllIIl[llllllllI[170]]);
            TERRORBIRD_4 = new i(llllllIIl[llllllllI[172]], llllllIIl[llllllllI[173]]);
            TERRORBIRD_5 = new i(llllllIIl[llllllllI[175]], llllllIIl[llllllllI[176]]);
            TERRORBIRD_6 = new i(llllllIIl[llllllllI[178]], llllllIIl[llllllllI[179]]);
            PENGUIN_1 = new i(llllllIIl[llllllllI[181]], llllllIIl[llllllllI[182]]);
            PENGUIN_2 = new i(llllllIIl[llllllllI[184]], llllllIIl[llllllllI[185]]);
            PENGUIN_3 = new i(llllllIIl[llllllllI[187]], llllllIIl[llllllllI[188]]);
            PENGUIN_4 = new i(llllllIIl[llllllllI[190]], llllllIIl[llllllllI[191]]);
            PENGUIN_5 = new i(llllllIIl[llllllllI[193]], llllllIIl[llllllllI[194]]);
            PENGUIN_6 = new i(llllllIIl[llllllllI[196]], llllllIIl[llllllllI[197]]);
            MOLE_1 = new i(llllllIIl[llllllllI[199]], llllllIIl[llllllllI[200]]);
            MOLE_2 = new i(llllllIIl[llllllllI[202]], llllllIIl[llllllllI[203]]);
            MOLE_3 = new i(llllllIIl[llllllllI[205]], llllllIIl[llllllllI[206]]);
            MOLE_4 = new i(llllllIIl[llllllllI[208]], llllllIIl[llllllllI[209]]);
            MOLE_5 = new i(llllllIIl[llllllllI[211]], llllllIIl[llllllllI[212]]);
            MOLE_6 = new i(llllllIIl[llllllllI[214]], llllllIIl[llllllllI[215]]);
            CAMEL_1 = new i(llllllIIl[llllllllI[217]], llllllIIl[llllllllI[218]]);
            CAMEL_2 = new i(llllllIIl[llllllllI[220]], llllllIIl[llllllllI[221]]);
            CAMEL_3 = new i(llllllIIl[llllllllI[223]], llllllIIl[llllllllI[224]]);
            CAMEL_4 = new i(llllllIIl[llllllllI[226]], llllllIIl[llllllllI[227]]);
            CAMEL_5 = new i(llllllIIl[llllllllI[229]], llllllIIl[llllllllI[230]]);
            CAMEL_6 = new i(llllllIIl[llllllllI[232]], llllllIIl[llllllllI[233]]);
            LEECH_1 = new i(llllllIIl[llllllllI[235]], llllllIIl[llllllllI[236]]);
            LEECH_2 = new i(llllllIIl[llllllllI[238]], llllllIIl[llllllllI[239]]);
            LEECH_3 = new i(llllllIIl[llllllllI[241]], llllllIIl[llllllllI[242]]);
            LEECH_4 = new i(llllllIIl[llllllllI[244]], llllllIIl[llllllllI[245]]);
            LEECH_5 = new i(llllllIIl[llllllllI[247]], llllllIIl[llllllllI[248]]);
            LEECH_6 = new i(llllllIIl[llllllllI[250]], llllllIIl[llllllllI[251]]);
            i[] iArray = new i[llllllllI[84]];
            iArray[i.llllllllI[0]] = LIZARD_1;
            iArray[i.llllllllI[1]] = LIZARD_2;
            iArray[i.llllllllI[2]] = LIZARD_3;
            iArray[i.llllllllI[3]] = LIZARD_4;
            iArray[i.llllllllI[4]] = LIZARD_5;
            iArray[i.llllllllI[5]] = LIZARD_6;
            iArray[i.llllllllI[6]] = TORTOISE_1;
            iArray[i.llllllllI[7]] = TORTOISE_2;
            iArray[i.llllllllI[8]] = TORTOISE_3;
            iArray[i.llllllllI[9]] = TORTOISE_4;
            iArray[i.llllllllI[10]] = TORTOISE_5;
            iArray[i.llllllllI[11]] = TORTOISE_6;
            iArray[i.llllllllI[12]] = DRAGON_1;
            iArray[i.llllllllI[13]] = DRAGON_2;
            iArray[i.llllllllI[14]] = DRAGON_3;
            iArray[i.llllllllI[15]] = DRAGON_4;
            iArray[i.llllllllI[16]] = DRAGON_5;
            iArray[i.llllllllI[17]] = DRAGON_6;
            iArray[i.llllllllI[18]] = WYVERN_1;
            iArray[i.llllllllI[19]] = WYVERN_2;
            iArray[i.llllllllI[20]] = WYVERN_3;
            iArray[i.llllllllI[21]] = WYVERN_4;
            iArray[i.llllllllI[22]] = WYVERN_5;
            iArray[i.llllllllI[23]] = WYVERN_6;
            iArray[i.llllllllI[24]] = SNAIL_1;
            iArray[i.llllllllI[25]] = SNAIL_2;
            iArray[i.llllllllI[26]] = SNAIL_3;
            iArray[i.llllllllI[27]] = SNAIL_4;
            iArray[i.llllllllI[28]] = SNAIL_5;
            iArray[i.llllllllI[29]] = SNAIL_6;
            iArray[i.llllllllI[30]] = SNAKE_1;
            iArray[i.llllllllI[31]] = SNAKE_2;
            iArray[i.llllllllI[32]] = SNAKE_3;
            iArray[i.llllllllI[33]] = SNAKE_4;
            iArray[i.llllllllI[34]] = SNAKE_5;
            iArray[i.llllllllI[35]] = SNAKE_6;
            iArray[i.llllllllI[36]] = SLUG_1;
            iArray[i.llllllllI[37]] = SLUG_2;
            iArray[i.llllllllI[38]] = SLUG_3;
            iArray[i.llllllllI[39]] = SLUG_4;
            iArray[i.llllllllI[40]] = SLUG_5;
            iArray[i.llllllllI[41]] = SLUG_6;
            iArray[i.llllllllI[42]] = MONKEY_1;
            iArray[i.llllllllI[43]] = MONKEY_2;
            iArray[i.llllllllI[44]] = MONKEY_3;
            iArray[i.llllllllI[45]] = MONKEY_4;
            iArray[i.llllllllI[46]] = MONKEY_5;
            iArray[i.llllllllI[47]] = MONKEY_6;
            iArray[i.llllllllI[48]] = KALPHITE_1;
            iArray[i.llllllllI[49]] = KALPHITE_2;
            iArray[i.llllllllI[50]] = KALPHITE_3;
            iArray[i.llllllllI[51]] = KALPHITE_4;
            iArray[i.llllllllI[52]] = KALPHITE_5;
            iArray[i.llllllllI[53]] = KALPHITE_6;
            iArray[i.llllllllI[54]] = TERRORBIRD_1;
            iArray[i.llllllllI[55]] = TERRORBIRD_2;
            iArray[i.llllllllI[56]] = TERRORBIRD_3;
            iArray[i.llllllllI[57]] = TERRORBIRD_4;
            iArray[i.llllllllI[58]] = TERRORBIRD_5;
            iArray[i.llllllllI[59]] = TERRORBIRD_6;
            iArray[i.llllllllI[60]] = PENGUIN_1;
            iArray[i.llllllllI[61]] = PENGUIN_2;
            iArray[i.llllllllI[62]] = PENGUIN_3;
            iArray[i.llllllllI[63]] = PENGUIN_4;
            iArray[i.llllllllI[64]] = PENGUIN_5;
            iArray[i.llllllllI[65]] = PENGUIN_6;
            iArray[i.llllllllI[66]] = MOLE_1;
            iArray[i.llllllllI[67]] = MOLE_2;
            iArray[i.llllllllI[68]] = MOLE_3;
            iArray[i.llllllllI[69]] = MOLE_4;
            iArray[i.llllllllI[70]] = MOLE_5;
            iArray[i.llllllllI[71]] = MOLE_6;
            iArray[i.llllllllI[72]] = CAMEL_1;
            iArray[i.llllllllI[73]] = CAMEL_2;
            iArray[i.llllllllI[74]] = CAMEL_3;
            iArray[i.llllllllI[75]] = CAMEL_4;
            iArray[i.llllllllI[76]] = CAMEL_5;
            iArray[i.llllllllI[77]] = CAMEL_6;
            iArray[i.llllllllI[78]] = LEECH_1;
            iArray[i.llllllllI[79]] = LEECH_2;
            iArray[i.llllllllI[80]] = LEECH_3;
            iArray[i.llllllllI[81]] = LEECH_4;
            iArray[i.llllllllI[82]] = LEECH_5;
            iArray[i.llllllllI[83]] = LEECH_6;
            $VALUES = iArray;
            ImmutableMap.Builder builder = new ImmutableMap.Builder();
            i[] iArray2 = i.values();
            int n2 = iArray2.length;
            int lIlIIlIIIIIIl = llllllllI[0];
            while (i.llIllIIIlllI(lIlIIlIIIIIIl, (int)lIlIIlIIIIIlI)) {
                void lIlIIlIIIIlII;
                void lIlIIlIIIIIll;
                void lIlIIlIIIIIII = lIlIIlIIIIIll[lIlIIlIIIIIIl];
                lIlIIlIIIIlII.put((Object)lIlIIlIIIIIII.question, (Object)lIlIIlIIIIIII.answer);
                0;
                ++lIlIIlIIIIIIl;
                0;
                if (-1 <= 0) continue;
                break block1;
            }
            MATCHES = builder.build();
        }
    }

    private static String llIlIlllIlll(String lIlIIIlIlIIll, String lIlIIIlIlIIlI) {
        try {
            SecretKeySpec lIlIIIlIlIllI = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(lIlIIIlIlIIlI.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher lIlIIIlIlIlIl = Cipher.getInstance("Blowfish");
            lIlIIIlIlIlIl.init(llllllllI[2], lIlIIIlIlIllI);
            return new String(lIlIIIlIlIlIl.doFinal(Base64.getDecoder().decode(lIlIIIlIlIIll.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lIlIIIlIlIlII) {
            lIlIIIlIlIlII.printStackTrace();
            return null;
        }
    }

    private i(String string2, String string3) {
        this.question = string2;
        this.answer = string3;
    }

    private static String llIlIlllIlIl(String lIlIIIllIIIll, String lIlIIIllIIIlI) {
        lIlIIIllIIIll = new String(Base64.getDecoder().decode(lIlIIIllIIIll.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder lIlIIIllIIllI = new StringBuilder();
        char[] lIlIIIllIIlIl = lIlIIIllIIIlI.toCharArray();
        int lIlIIIllIIlII = llllllllI[0];
        char[] lIlIIIlIllllI = lIlIIIllIIIll.toCharArray();
        int lIlIIIlIlllIl = lIlIIIlIllllI.length;
        int lIlIIIlIlllII = llllllllI[0];
        while (i.llIllIIIlllI(lIlIIIlIlllII, lIlIIIlIlllIl)) {
            char lIlIIIllIlIIl = lIlIIIlIllllI[lIlIIIlIlllII];
            lIlIIIllIIllI.append((char)(lIlIIIllIlIIl ^ lIlIIIllIIlIl[lIlIIIllIIlII % lIlIIIllIIlIl.length]));
            0;
            ++lIlIIIllIIlII;
            ++lIlIIIlIlllII;
            0;
            if (((0x61 ^ 0x35) & ~(0x23 ^ 0x77)) != (0x6E ^ 0x6A)) continue;
            return null;
        }
        return String.valueOf(lIlIIIllIIllI);
    }

    public static i valueOf(String string) {
        return Enum.valueOf(i.class, string);
    }
}

