/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.7ff08cb7-2eac-4b0f-b288-ca118289a708.tasks;

public class FHelper {
    public static final  int[] aY;
    public static final  int[] bg;
    public static final  int aG;
    public static final  int aS;
    public static final  int az;
    public static final  int[] aZ;
    public static final  int[] aX;
    public static final  int aq;
    public static final  int[] bd;
    public static final  int aO;
    public static final  int[] bi;
    public static final  int aR;
    public static final  int ar;
    public static final  int[] bh;
    public static final  int[] bm;
    public static final  int au;
    public static final  int aM;
    public static final  int an;
    public static final  int ap;
    public static final  int at;
    public static final  int[] bn;
    public static final  int[] aT;
    public static final  int ak;
    public static final  int am;
    public static final  int[] bc;
    public static final  int aD;
    public static final  int aL;
    public static final  int aP;
    public static final  int aN;
    public static final  int[] bl;
    
    public static final  int al;
    public static final  int ao;
    public static final  int ay;
    public static final  int[] bk;
    public static final  int av;
    public static final  int aB;
    public static final  int as;
    public static final  int[] aW;
    public static final  int[] be;
    public static final  int aQ;
    public static final  int aC;
    public static final  int aj;
    public static final  int[] ba;
    public static final  int aF;
    public static final  int aJ;
    public static final  int aH;
    public static final  int[] aU;
    public static final  int aI;
    public static final  int aE;
    public static final  int[] bf;
    public static final  int ax;
    public static final  int aK;
    public static final  int aA;
    public static final  int[] bj;
    public static final  int[] aV;
    public static final  int[] bb;
    public static final  int[] bo;
    public static final  int aw;

    static {
        f.llIlIIllIIll();
        aF = lllllIIIl[0];
        aJ = lllllIIIl[1];
        aj = lllllIIIl[2];
        ap = lllllIIIl[3];
        aw = lllllIIIl[4];
        ar = lllllIIIl[5];
        aA = lllllIIIl[6];
        aE = lllllIIIl[7];
        aR = lllllIIIl[8];
        ak = lllllIIIl[9];
        az = lllllIIIl[10];
        ao = lllllIIIl[11];
        aD = lllllIIIl[12];
        aS = lllllIIIl[13];
        aP = lllllIIIl[14];
        am = lllllIIIl[15];
        ax = lllllIIIl[16];
        aI = lllllIIIl[17];
        aq = lllllIIIl[18];
        aG = lllllIIIl[19];
        aM = lllllIIIl[20];
        aN = lllllIIIl[21];
        aB = lllllIIIl[22];
        at = lllllIIIl[23];
        av = lllllIIIl[24];
        aC = lllllIIIl[25];
        as = lllllIIIl[26];
        aO = lllllIIIl[27];
        ay = lllllIIIl[28];
        al = lllllIIIl[29];
        an = lllllIIIl[30];
        aQ = lllllIIIl[31];
        aL = lllllIIIl[32];
        aH = lllllIIIl[33];
        au = lllllIIIl[34];
        aK = lllllIIIl[35];
        int[] nArray = new int[lllllIIIl[36]];
        nArray[f.lllllIIIl[12]] = lllllIIIl[11];
        nArray[f.lllllIIIl[37]] = lllllIIIl[3];
        nArray[f.lllllIIIl[38]] = lllllIIIl[8];
        aT = nArray;
        int[] nArray2 = new int[lllllIIIl[39]];
        nArray2[f.lllllIIIl[12]] = lllllIIIl[18];
        nArray2[f.lllllIIIl[37]] = lllllIIIl[40];
        nArray2[f.lllllIIIl[38]] = lllllIIIl[41];
        nArray2[f.lllllIIIl[36]] = lllllIIIl[42];
        nArray2[f.lllllIIIl[43]] = lllllIIIl[44];
        nArray2[f.lllllIIIl[45]] = lllllIIIl[46];
        nArray2[f.lllllIIIl[47]] = lllllIIIl[48];
        nArray2[f.lllllIIIl[49]] = lllllIIIl[50];
        aU = nArray2;
        int[] nArray3 = new int[lllllIIIl[51]];
        nArray3[f.lllllIIIl[12]] = lllllIIIl[52];
        nArray3[f.lllllIIIl[37]] = lllllIIIl[53];
        nArray3[f.lllllIIIl[38]] = lllllIIIl[54];
        nArray3[f.lllllIIIl[36]] = lllllIIIl[55];
        nArray3[f.lllllIIIl[43]] = lllllIIIl[56];
        nArray3[f.lllllIIIl[45]] = lllllIIIl[57];
        nArray3[f.lllllIIIl[47]] = lllllIIIl[58];
        nArray3[f.lllllIIIl[49]] = lllllIIIl[59];
        nArray3[f.lllllIIIl[39]] = lllllIIIl[59];
        aV = nArray3;
        int[] nArray4 = new int[lllllIIIl[43]];
        nArray4[f.lllllIIIl[12]] = lllllIIIl[60];
        nArray4[f.lllllIIIl[37]] = lllllIIIl[61];
        nArray4[f.lllllIIIl[38]] = lllllIIIl[62];
        nArray4[f.lllllIIIl[36]] = lllllIIIl[63];
        aW = nArray4;
        int[] nArray5 = new int[lllllIIIl[43]];
        nArray5[f.lllllIIIl[12]] = lllllIIIl[64];
        nArray5[f.lllllIIIl[37]] = lllllIIIl[65];
        nArray5[f.lllllIIIl[38]] = lllllIIIl[66];
        nArray5[f.lllllIIIl[36]] = lllllIIIl[67];
        aX = nArray5;
        int[] nArray6 = new int[lllllIIIl[47]];
        nArray6[f.lllllIIIl[12]] = lllllIIIl[68];
        nArray6[f.lllllIIIl[37]] = lllllIIIl[69];
        nArray6[f.lllllIIIl[38]] = lllllIIIl[70];
        nArray6[f.lllllIIIl[36]] = lllllIIIl[71];
        nArray6[f.lllllIIIl[43]] = lllllIIIl[31];
        nArray6[f.lllllIIIl[45]] = lllllIIIl[72];
        aY = nArray6;
        int[] nArray7 = new int[lllllIIIl[43]];
        nArray7[f.lllllIIIl[12]] = lllllIIIl[73];
        nArray7[f.lllllIIIl[37]] = lllllIIIl[74];
        nArray7[f.lllllIIIl[38]] = lllllIIIl[75];
        nArray7[f.lllllIIIl[36]] = lllllIIIl[76];
        aZ = nArray7;
        int[] nArray8 = new int[lllllIIIl[43]];
        nArray8[f.lllllIIIl[12]] = lllllIIIl[77];
        nArray8[f.lllllIIIl[37]] = lllllIIIl[78];
        nArray8[f.lllllIIIl[38]] = lllllIIIl[79];
        nArray8[f.lllllIIIl[36]] = lllllIIIl[80];
        ba = nArray8;
        int[] nArray9 = new int[lllllIIIl[36]];
        nArray9[f.lllllIIIl[12]] = lllllIIIl[77];
        nArray9[f.lllllIIIl[37]] = lllllIIIl[78];
        nArray9[f.lllllIIIl[38]] = lllllIIIl[79];
        bb = nArray9;
        int[] nArray10 = new int[lllllIIIl[43]];
        nArray10[f.lllllIIIl[12]] = lllllIIIl[81];
        nArray10[f.lllllIIIl[37]] = lllllIIIl[82];
        nArray10[f.lllllIIIl[38]] = lllllIIIl[83];
        nArray10[f.lllllIIIl[36]] = lllllIIIl[84];
        bc = nArray10;
        int[] nArray11 = new int[lllllIIIl[43]];
        nArray11[f.lllllIIIl[12]] = lllllIIIl[85];
        nArray11[f.lllllIIIl[37]] = lllllIIIl[86];
        nArray11[f.lllllIIIl[38]] = lllllIIIl[87];
        nArray11[f.lllllIIIl[36]] = lllllIIIl[88];
        bd = nArray11;
        int[] nArray12 = new int[lllllIIIl[43]];
        nArray12[f.lllllIIIl[12]] = lllllIIIl[89];
        nArray12[f.lllllIIIl[37]] = lllllIIIl[90];
        nArray12[f.lllllIIIl[38]] = lllllIIIl[91];
        nArray12[f.lllllIIIl[36]] = lllllIIIl[92];
        be = nArray12;
        int[] nArray13 = new int[lllllIIIl[43]];
        nArray13[f.lllllIIIl[12]] = lllllIIIl[93];
        nArray13[f.lllllIIIl[37]] = lllllIIIl[94];
        nArray13[f.lllllIIIl[38]] = lllllIIIl[95];
        nArray13[f.lllllIIIl[36]] = lllllIIIl[96];
        bf = nArray13;
        int[] nArray14 = new int[lllllIIIl[43]];
        nArray14[f.lllllIIIl[12]] = lllllIIIl[97];
        nArray14[f.lllllIIIl[37]] = lllllIIIl[98];
        nArray14[f.lllllIIIl[38]] = lllllIIIl[99];
        nArray14[f.lllllIIIl[36]] = lllllIIIl[100];
        bg = nArray14;
        int[] nArray15 = new int[lllllIIIl[45]];
        nArray15[f.lllllIIIl[12]] = lllllIIIl[101];
        nArray15[f.lllllIIIl[37]] = lllllIIIl[102];
        nArray15[f.lllllIIIl[38]] = lllllIIIl[103];
        nArray15[f.lllllIIIl[36]] = lllllIIIl[104];
        nArray15[f.lllllIIIl[43]] = lllllIIIl[105];
        bh = nArray15;
        int[] nArray16 = new int[lllllIIIl[43]];
        nArray16[f.lllllIIIl[12]] = lllllIIIl[106];
        nArray16[f.lllllIIIl[37]] = lllllIIIl[107];
        nArray16[f.lllllIIIl[38]] = lllllIIIl[108];
        nArray16[f.lllllIIIl[36]] = lllllIIIl[109];
        bi = nArray16;
        int[] nArray17 = new int[lllllIIIl[43]];
        nArray17[f.lllllIIIl[12]] = lllllIIIl[110];
        nArray17[f.lllllIIIl[37]] = lllllIIIl[111];
        nArray17[f.lllllIIIl[38]] = lllllIIIl[112];
        nArray17[f.lllllIIIl[36]] = lllllIIIl[113];
        bj = nArray17;
        int[] nArray18 = new int[lllllIIIl[43]];
        nArray18[f.lllllIIIl[12]] = lllllIIIl[114];
        nArray18[f.lllllIIIl[37]] = lllllIIIl[115];
        nArray18[f.lllllIIIl[38]] = lllllIIIl[116];
        nArray18[f.lllllIIIl[36]] = lllllIIIl[117];
        bk = nArray18;
        int[] nArray19 = new int[lllllIIIl[36]];
        nArray19[f.lllllIIIl[12]] = lllllIIIl[35];
        nArray19[f.lllllIIIl[37]] = lllllIIIl[1];
        nArray19[f.lllllIIIl[38]] = lllllIIIl[17];
        bl = nArray19;
        int[] nArray20 = new int[lllllIIIl[45]];
        nArray20[f.lllllIIIl[12]] = lllllIIIl[5];
        nArray20[f.lllllIIIl[37]] = lllllIIIl[118];
        nArray20[f.lllllIIIl[38]] = lllllIIIl[119];
        nArray20[f.lllllIIIl[36]] = lllllIIIl[120];
        nArray20[f.lllllIIIl[43]] = lllllIIIl[121];
        bm = nArray20;
        int[] nArray21 = new int[lllllIIIl[36]];
        nArray21[f.lllllIIIl[12]] = lllllIIIl[122];
        nArray21[f.lllllIIIl[37]] = lllllIIIl[123];
        nArray21[f.lllllIIIl[38]] = lllllIIIl[124];
        bn = nArray21;
        int[] nArray22 = new int[lllllIIIl[43]];
        nArray22[f.lllllIIIl[12]] = lllllIIIl[125];
        nArray22[f.lllllIIIl[37]] = lllllIIIl[126];
        nArray22[f.lllllIIIl[38]] = lllllIIIl[127];
        nArray22[f.lllllIIIl[36]] = lllllIIIl[128];
        bo = nArray22;
    }
}

