/*
 * Decompiled with CFR 0.152.
 */
package h.-.q.i.r.s.u.s.i.e.v.a.c.g.-.t.e.f;

import h.-.q.i.r.s.u.s.i.e.v.a.c.g.-.t.e.f.BEnum;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import java.util.stream.Stream;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

public final class EEnum
extends Enum<e> {
    public static final /* synthetic */ /* enum */ e WAVE21;
    public static final /* synthetic */ /* enum */ e WAVE23;
    public static final /* synthetic */ /* enum */ e WAVE42;
    public static final /* synthetic */ /* enum */ e WAVE61;
    private static final /* synthetic */ e[] $VALUES;
    public static final /* synthetic */ /* enum */ e WAVE57;
    final /* synthetic */ int waveNumber;
    public static final /* synthetic */ /* enum */ e WAVE9;
    public static final /* synthetic */ /* enum */ e WAVE51;
    public static final /* synthetic */ /* enum */ e WAVE46;
    public static final /* synthetic */ /* enum */ e WAVE40;
    public static final /* synthetic */ /* enum */ e WAVE15;
    public static final /* synthetic */ /* enum */ e WAVE8;
    public static final /* synthetic */ /* enum */ e WAVE44;
    public static final /* synthetic */ /* enum */ e WAVE41;
    public static final /* synthetic */ /* enum */ e WAVE36;
    public static final /* synthetic */ /* enum */ e WAVE13;
    public static final /* synthetic */ /* enum */ e WAVE62;
    public static final /* synthetic */ /* enum */ e WAVE47;
    public static final /* synthetic */ /* enum */ e WAVE48;
    public static final /* synthetic */ /* enum */ e WAVE24;
    private final /* synthetic */ b[] monstersInWave;
    private static /* synthetic */ String[] llIIlIIIllll;
    public static final /* synthetic */ /* enum */ e WAVE5;
    public static final /* synthetic */ /* enum */ e WAVE17;
    public static final /* synthetic */ /* enum */ e WAVE55;
    public static final /* synthetic */ /* enum */ e WAVE59;
    public static final /* synthetic */ /* enum */ e WAVE31;
    public static final /* synthetic */ /* enum */ e WAVE18;
    public static final /* synthetic */ /* enum */ e WAVE16;
    public static final /* synthetic */ /* enum */ e WAVE30;
    public static final /* synthetic */ /* enum */ e WAVE63;
    public static final /* synthetic */ /* enum */ e WAVE43;
    public static final /* synthetic */ /* enum */ e WAVE11;
    public static final /* synthetic */ /* enum */ e WAVE56;
    public static final /* synthetic */ /* enum */ e WAVE60;
    public static final /* synthetic */ /* enum */ e WAVE27;
    public static final /* synthetic */ /* enum */ e WAVE58;
    public static final /* synthetic */ /* enum */ e WAVE37;
    public static final /* synthetic */ /* enum */ e WAVE7;
    public static final /* synthetic */ /* enum */ e WAVE50;
    public static final /* synthetic */ /* enum */ e WAVE29;
    private static /* synthetic */ int[] llIIlIIlIIIl;
    public static final /* synthetic */ /* enum */ e WAVE34;
    public static final /* synthetic */ /* enum */ e WAVE3;
    public static final /* synthetic */ /* enum */ e WAVE35;
    public static final /* synthetic */ /* enum */ e WAVE52;
    public static final /* synthetic */ /* enum */ e WAVE49;
    public static final /* synthetic */ /* enum */ e WAVE4;
    public static final /* synthetic */ /* enum */ e WAVE22;
    public static final /* synthetic */ /* enum */ e WAVE20;
    public static final /* synthetic */ /* enum */ e WAVE26;
    public static final /* synthetic */ /* enum */ e WAVE19;
    public static final /* synthetic */ /* enum */ e WAVE38;
    public static final /* synthetic */ /* enum */ e WAVE32;
    public static final /* synthetic */ /* enum */ e WAVE33;
    public static final /* synthetic */ /* enum */ e NONE;
    public static final /* synthetic */ /* enum */ e WAVE28;
    public static final /* synthetic */ /* enum */ e WAVE2;
    public static final /* synthetic */ /* enum */ e WAVE6;
    public static final /* synthetic */ /* enum */ e WAVE45;
    public static final /* synthetic */ /* enum */ e WAVE1;
    public static final /* synthetic */ /* enum */ e WAVE12;
    public static final /* synthetic */ /* enum */ e WAVE14;
    public static final /* synthetic */ /* enum */ e WAVE25;
    public static final /* synthetic */ /* enum */ e WAVE10;
    public static final /* synthetic */ /* enum */ e WAVE39;
    public static final /* synthetic */ /* enum */ e WAVE53;
    public static final /* synthetic */ /* enum */ e WAVE54;

    public b[] h() {
        return this.monstersInWave;
    }

    private static String lllllIIIlllllI(String var14, String var1) {
        var14 = new String(Base64.getDecoder().decode(var14.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder var18 = new StringBuilder();
        char[] var6 = var1.toCharArray();
        int var16 = llIIlIIlIIIl[0];
        char[] var3 = var14.toCharArray();
        int var4 = var3.length;
        int var12 = llIIlIIlIIIl[0];
        while (e.lllllIIlIlIIll(var12, var4)) {
            char var13 = var3[var12];
            var18.append((char)(var13 ^ var6[var16 % var6.length]));
            0;
            ++var16;
            ++var12;
            0;
            if (-3 < 0) continue;
            return null;
        }
        return String.valueOf(var18);
    }

    private static String lllllIIIllllIl(String var15, String var17) {
        try {
            SecretKeySpec var2 = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(var17.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher var7 = Cipher.getInstance("Blowfish");
            var7.init(llIIlIIlIIIl[2], var2);
            return new String(var7.doFinal(Base64.getDecoder().decode(var15.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception var9) {
            var9.printStackTrace();
            return null;
        }
    }

    private e(b[] bArray, int n3) {
        this.monstersInWave = bArray;
        this.waveNumber = n3;
    }

    public static e valueOf(String string) {
        return Enum.valueOf(e.class, string);
    }

    private static String lllllIIlIIIIII(String var11, String var19) {
        try {
            SecretKeySpec var5 = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(var19.getBytes(StandardCharsets.UTF_8)), llIIlIIlIIIl[8]), "DES");
            Cipher var10 = Cipher.getInstance("DES");
            var10.init(llIIlIIlIIIl[2], var5);
            return new String(var10.doFinal(Base64.getDecoder().decode(var11.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception var8) {
            var8.printStackTrace();
            return null;
        }
    }

    static {
        e.lllllIIlIlIIlI();
        e.lllllIIlIlIIIl();
        NONE = new e(new b[llIIlIIlIIIl[0]], llIIlIIlIIIl[0]);
        b[] bArray = new b[llIIlIIlIIIl[1]];
        bArray[e.llIIlIIlIIIl[0]] = b.BAT;
        WAVE1 = new e(bArray, llIIlIIlIIIl[1]);
        b[] bArray2 = new b[llIIlIIlIIIl[2]];
        bArray2[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray2[e.llIIlIIlIIIl[1]] = b.BAT;
        WAVE2 = new e(bArray2, llIIlIIlIIIl[2]);
        b[] bArray3 = new b[llIIlIIlIIIl[1]];
        bArray3[e.llIIlIIlIIIl[0]] = b.BLOB;
        WAVE3 = new e(bArray3, llIIlIIlIIIl[3]);
        b[] bArray4 = new b[llIIlIIlIIIl[2]];
        bArray4[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray4[e.llIIlIIlIIIl[1]] = b.BLOB;
        WAVE4 = new e(bArray4, llIIlIIlIIIl[4]);
        b[] bArray5 = new b[llIIlIIlIIIl[3]];
        bArray5[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray5[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray5[e.llIIlIIlIIIl[2]] = b.BLOB;
        WAVE5 = new e(bArray5, llIIlIIlIIIl[5]);
        b[] bArray6 = new b[llIIlIIlIIIl[2]];
        bArray6[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray6[e.llIIlIIlIIIl[1]] = b.BLOB;
        WAVE6 = new e(bArray6, llIIlIIlIIIl[6]);
        b[] bArray7 = new b[llIIlIIlIIIl[1]];
        bArray7[e.llIIlIIlIIIl[0]] = b.RANGER;
        WAVE7 = new e(bArray7, llIIlIIlIIIl[7]);
        b[] bArray8 = new b[llIIlIIlIIIl[2]];
        bArray8[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray8[e.llIIlIIlIIIl[1]] = b.RANGER;
        WAVE8 = new e(bArray8, llIIlIIlIIIl[8]);
        b[] bArray9 = new b[llIIlIIlIIIl[3]];
        bArray9[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray9[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray9[e.llIIlIIlIIIl[2]] = b.RANGER;
        WAVE9 = new e(bArray9, llIIlIIlIIIl[9]);
        b[] bArray10 = new b[llIIlIIlIIIl[2]];
        bArray10[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray10[e.llIIlIIlIIIl[1]] = b.RANGER;
        WAVE10 = new e(bArray10, llIIlIIlIIIl[10]);
        b[] bArray11 = new b[llIIlIIlIIIl[3]];
        bArray11[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray11[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray11[e.llIIlIIlIIIl[2]] = b.RANGER;
        WAVE11 = new e(bArray11, llIIlIIlIIIl[11]);
        b[] bArray12 = new b[llIIlIIlIIIl[4]];
        bArray12[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray12[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray12[e.llIIlIIlIIIl[2]] = b.BLOB;
        bArray12[e.llIIlIIlIIIl[3]] = b.RANGER;
        WAVE12 = new e(bArray12, llIIlIIlIIIl[12]);
        b[] bArray13 = new b[llIIlIIlIIIl[3]];
        bArray13[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray13[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray13[e.llIIlIIlIIIl[2]] = b.RANGER;
        WAVE13 = new e(bArray13, llIIlIIlIIIl[13]);
        b[] bArray14 = new b[llIIlIIlIIIl[2]];
        bArray14[e.llIIlIIlIIIl[0]] = b.RANGER;
        bArray14[e.llIIlIIlIIIl[1]] = b.RANGER;
        WAVE14 = new e(bArray14, llIIlIIlIIIl[14]);
        b[] bArray15 = new b[llIIlIIlIIIl[1]];
        bArray15[e.llIIlIIlIIIl[0]] = b.MELEER;
        WAVE15 = new e(bArray15, llIIlIIlIIIl[15]);
        b[] bArray16 = new b[llIIlIIlIIIl[2]];
        bArray16[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray16[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE16 = new e(bArray16, llIIlIIlIIIl[16]);
        b[] bArray17 = new b[llIIlIIlIIIl[3]];
        bArray17[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray17[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray17[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE17 = new e(bArray17, llIIlIIlIIIl[17]);
        b[] bArray18 = new b[llIIlIIlIIIl[2]];
        bArray18[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray18[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE18 = new e(bArray18, llIIlIIlIIIl[18]);
        b[] bArray19 = new b[llIIlIIlIIIl[3]];
        bArray19[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray19[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray19[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE19 = new e(bArray19, llIIlIIlIIIl[19]);
        b[] bArray20 = new b[llIIlIIlIIIl[4]];
        bArray20[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray20[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray20[e.llIIlIIlIIIl[2]] = b.BLOB;
        bArray20[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE20 = new e(bArray20, llIIlIIlIIIl[20]);
        b[] bArray21 = new b[llIIlIIlIIIl[3]];
        bArray21[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray21[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray21[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE21 = new e(bArray21, llIIlIIlIIIl[21]);
        b[] bArray22 = new b[llIIlIIlIIIl[2]];
        bArray22[e.llIIlIIlIIIl[0]] = b.RANGER;
        bArray22[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE22 = new e(bArray22, llIIlIIlIIIl[22]);
        b[] bArray23 = new b[llIIlIIlIIIl[3]];
        bArray23[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray23[e.llIIlIIlIIIl[1]] = b.RANGER;
        bArray23[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE23 = new e(bArray23, llIIlIIlIIIl[23]);
        b[] bArray24 = new b[llIIlIIlIIIl[4]];
        bArray24[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray24[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray24[e.llIIlIIlIIIl[2]] = b.RANGER;
        bArray24[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE24 = new e(bArray24, llIIlIIlIIIl[24]);
        b[] bArray25 = new b[llIIlIIlIIIl[3]];
        bArray25[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray25[e.llIIlIIlIIIl[1]] = b.RANGER;
        bArray25[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE25 = new e(bArray25, llIIlIIlIIIl[25]);
        b[] bArray26 = new b[llIIlIIlIIIl[4]];
        bArray26[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray26[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray26[e.llIIlIIlIIIl[2]] = b.RANGER;
        bArray26[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE26 = new e(bArray26, llIIlIIlIIIl[26]);
        b[] bArray27 = new b[llIIlIIlIIIl[5]];
        bArray27[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray27[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray27[e.llIIlIIlIIIl[2]] = b.BLOB;
        bArray27[e.llIIlIIlIIIl[3]] = b.RANGER;
        bArray27[e.llIIlIIlIIIl[4]] = b.MELEER;
        WAVE27 = new e(bArray27, llIIlIIlIIIl[27]);
        b[] bArray28 = new b[llIIlIIlIIIl[4]];
        bArray28[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray28[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray28[e.llIIlIIlIIIl[2]] = b.RANGER;
        bArray28[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE28 = new e(bArray28, llIIlIIlIIIl[28]);
        b[] bArray29 = new b[llIIlIIlIIIl[3]];
        bArray29[e.llIIlIIlIIIl[0]] = b.RANGER;
        bArray29[e.llIIlIIlIIIl[1]] = b.RANGER;
        bArray29[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE29 = new e(bArray29, llIIlIIlIIIl[29]);
        b[] bArray30 = new b[llIIlIIlIIIl[2]];
        bArray30[e.llIIlIIlIIIl[0]] = b.MELEER;
        bArray30[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE30 = new e(bArray30, llIIlIIlIIIl[30]);
        b[] bArray31 = new b[llIIlIIlIIIl[1]];
        bArray31[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE31 = new e(bArray31, llIIlIIlIIIl[31]);
        b[] bArray32 = new b[llIIlIIlIIIl[1]];
        bArray32[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE32 = new e(bArray32, llIIlIIlIIIl[32]);
        b[] bArray33 = new b[llIIlIIlIIIl[1]];
        bArray33[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE33 = new e(bArray33, llIIlIIlIIIl[33]);
        b[] bArray34 = new b[llIIlIIlIIIl[1]];
        bArray34[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE34 = new e(bArray34, llIIlIIlIIIl[34]);
        b[] bArray35 = new b[llIIlIIlIIIl[1]];
        bArray35[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE35 = new e(bArray35, llIIlIIlIIIl[35]);
        b[] bArray36 = new b[llIIlIIlIIIl[1]];
        bArray36[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE36 = new e(bArray36, llIIlIIlIIIl[36]);
        b[] bArray37 = new b[llIIlIIlIIIl[1]];
        bArray37[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE37 = new e(bArray37, llIIlIIlIIIl[37]);
        b[] bArray38 = new b[llIIlIIlIIIl[1]];
        bArray38[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE38 = new e(bArray38, llIIlIIlIIIl[38]);
        b[] bArray39 = new b[llIIlIIlIIIl[1]];
        bArray39[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE39 = new e(bArray39, llIIlIIlIIIl[39]);
        b[] bArray40 = new b[llIIlIIlIIIl[1]];
        bArray40[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE40 = new e(bArray40, llIIlIIlIIIl[40]);
        b[] bArray41 = new b[llIIlIIlIIIl[1]];
        bArray41[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE41 = new e(bArray41, llIIlIIlIIIl[41]);
        b[] bArray42 = new b[llIIlIIlIIIl[1]];
        bArray42[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE42 = new e(bArray42, llIIlIIlIIIl[42]);
        b[] bArray43 = new b[llIIlIIlIIIl[1]];
        bArray43[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE43 = new e(bArray43, llIIlIIlIIIl[43]);
        b[] bArray44 = new b[llIIlIIlIIIl[1]];
        bArray44[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE44 = new e(bArray44, llIIlIIlIIIl[44]);
        b[] bArray45 = new b[llIIlIIlIIIl[1]];
        bArray45[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE45 = new e(bArray45, llIIlIIlIIIl[45]);
        b[] bArray46 = new b[llIIlIIlIIIl[1]];
        bArray46[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE46 = new e(bArray46, llIIlIIlIIIl[46]);
        b[] bArray47 = new b[llIIlIIlIIIl[1]];
        bArray47[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE47 = new e(bArray47, llIIlIIlIIIl[47]);
        b[] bArray48 = new b[llIIlIIlIIIl[1]];
        bArray48[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE48 = new e(bArray48, llIIlIIlIIIl[48]);
        b[] bArray49 = new b[llIIlIIlIIIl[1]];
        bArray49[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE49 = new e(bArray49, llIIlIIlIIIl[49]);
        b[] bArray50 = new b[llIIlIIlIIIl[1]];
        bArray50[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE50 = new e(bArray50, llIIlIIlIIIl[50]);
        b[] bArray51 = new b[llIIlIIlIIIl[1]];
        bArray51[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE51 = new e(bArray51, llIIlIIlIIIl[51]);
        b[] bArray52 = new b[llIIlIIlIIIl[1]];
        bArray52[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE52 = new e(bArray52, llIIlIIlIIIl[52]);
        b[] bArray53 = new b[llIIlIIlIIIl[1]];
        bArray53[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE53 = new e(bArray53, llIIlIIlIIIl[53]);
        b[] bArray54 = new b[llIIlIIlIIIl[1]];
        bArray54[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE54 = new e(bArray54, llIIlIIlIIIl[54]);
        b[] bArray55 = new b[llIIlIIlIIIl[1]];
        bArray55[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE55 = new e(bArray55, llIIlIIlIIIl[55]);
        b[] bArray56 = new b[llIIlIIlIIIl[1]];
        bArray56[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE56 = new e(bArray56, llIIlIIlIIIl[56]);
        b[] bArray57 = new b[llIIlIIlIIIl[1]];
        bArray57[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE57 = new e(bArray57, llIIlIIlIIIl[57]);
        b[] bArray58 = new b[llIIlIIlIIIl[1]];
        bArray58[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE58 = new e(bArray58, llIIlIIlIIIl[58]);
        b[] bArray59 = new b[llIIlIIlIIIl[1]];
        bArray59[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE59 = new e(bArray59, llIIlIIlIIIl[59]);
        b[] bArray60 = new b[llIIlIIlIIIl[1]];
        bArray60[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE60 = new e(bArray60, llIIlIIlIIIl[60]);
        b[] bArray61 = new b[llIIlIIlIIIl[1]];
        bArray61[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE61 = new e(bArray61, llIIlIIlIIIl[61]);
        b[] bArray62 = new b[llIIlIIlIIIl[1]];
        bArray62[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE62 = new e(bArray62, llIIlIIlIIIl[62]);
        b[] bArray63 = new b[llIIlIIlIIIl[1]];
        bArray63[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE63 = new e(bArray63, llIIlIIlIIIl[63]);
        e[] eArray = new e[llIIlIIlIIIl[64]];
        eArray[e.llIIlIIlIIIl[0]] = NONE;
        eArray[e.llIIlIIlIIIl[1]] = WAVE1;
        eArray[e.llIIlIIlIIIl[2]] = WAVE2;
        eArray[e.llIIlIIlIIIl[3]] = WAVE3;
        eArray[e.llIIlIIlIIIl[4]] = WAVE4;
        eArray[e.llIIlIIlIIIl[5]] = WAVE5;
        eArray[e.llIIlIIlIIIl[6]] = WAVE6;
        eArray[e.llIIlIIlIIIl[7]] = WAVE7;
        eArray[e.llIIlIIlIIIl[8]] = WAVE8;
        eArray[e.llIIlIIlIIIl[9]] = WAVE9;
        eArray[e.llIIlIIlIIIl[10]] = WAVE10;
        eArray[e.llIIlIIlIIIl[11]] = WAVE11;
        eArray[e.llIIlIIlIIIl[12]] = WAVE12;
        eArray[e.llIIlIIlIIIl[13]] = WAVE13;
        eArray[e.llIIlIIlIIIl[14]] = WAVE14;
        eArray[e.llIIlIIlIIIl[15]] = WAVE15;
        eArray[e.llIIlIIlIIIl[16]] = WAVE16;
        eArray[e.llIIlIIlIIIl[17]] = WAVE17;
        eArray[e.llIIlIIlIIIl[18]] = WAVE18;
        eArray[e.llIIlIIlIIIl[19]] = WAVE19;
        eArray[e.llIIlIIlIIIl[20]] = WAVE20;
        eArray[e.llIIlIIlIIIl[21]] = WAVE21;
        eArray[e.llIIlIIlIIIl[22]] = WAVE22;
        eArray[e.llIIlIIlIIIl[23]] = WAVE23;
        eArray[e.llIIlIIlIIIl[24]] = WAVE24;
        eArray[e.llIIlIIlIIIl[25]] = WAVE25;
        eArray[e.llIIlIIlIIIl[26]] = WAVE26;
        eArray[e.llIIlIIlIIIl[27]] = WAVE27;
        eArray[e.llIIlIIlIIIl[28]] = WAVE28;
        eArray[e.llIIlIIlIIIl[29]] = WAVE29;
        eArray[e.llIIlIIlIIIl[30]] = WAVE30;
        eArray[e.llIIlIIlIIIl[31]] = WAVE31;
        eArray[e.llIIlIIlIIIl[32]] = WAVE32;
        eArray[e.llIIlIIlIIIl[33]] = WAVE33;
        eArray[e.llIIlIIlIIIl[34]] = WAVE34;
        eArray[e.llIIlIIlIIIl[35]] = WAVE35;
        eArray[e.llIIlIIlIIIl[36]] = WAVE36;
        eArray[e.llIIlIIlIIIl[37]] = WAVE37;
        eArray[e.llIIlIIlIIIl[38]] = WAVE38;
        eArray[e.llIIlIIlIIIl[39]] = WAVE39;
        eArray[e.llIIlIIlIIIl[40]] = WAVE40;
        eArray[e.llIIlIIlIIIl[41]] = WAVE41;
        eArray[e.llIIlIIlIIIl[42]] = WAVE42;
        eArray[e.llIIlIIlIIIl[43]] = WAVE43;
        eArray[e.llIIlIIlIIIl[44]] = WAVE44;
        eArray[e.llIIlIIlIIIl[45]] = WAVE45;
        eArray[e.llIIlIIlIIIl[46]] = WAVE46;
        eArray[e.llIIlIIlIIIl[47]] = WAVE47;
        eArray[e.llIIlIIlIIIl[48]] = WAVE48;
        eArray[e.llIIlIIlIIIl[49]] = WAVE49;
        eArray[e.llIIlIIlIIIl[50]] = WAVE50;
        eArray[e.llIIlIIlIIIl[51]] = WAVE51;
        eArray[e.llIIlIIlIIIl[52]] = WAVE52;
        eArray[e.llIIlIIlIIIl[53]] = WAVE53;
        eArray[e.llIIlIIlIIIl[54]] = WAVE54;
        eArray[e.llIIlIIlIIIl[55]] = WAVE55;
        eArray[e.llIIlIIlIIIl[56]] = WAVE56;
        eArray[e.llIIlIIlIIIl[57]] = WAVE57;
        eArray[e.llIIlIIlIIIl[58]] = WAVE58;
        eArray[e.llIIlIIlIIIl[59]] = WAVE59;
        eArray[e.llIIlIIlIIIl[60]] = WAVE60;
        eArray[e.llIIlIIlIIIl[61]] = WAVE61;
        eArray[e.llIIlIIlIIIl[62]] = WAVE62;
        eArray[e.llIIlIIlIIIl[63]] = WAVE63;
        $VALUES = eArray;
    }

    public int i() {
        return this.waveNumber;
    }

    private static boolean lllllIIlIlIIll(int n2, int n3) {
        return n2 < n3;
    }

    private static void lllllIIlIlIIlI() {
        llIIlIIlIIIl = new int[65];
        e.llIIlIIlIIIl[0] = 2 & ~2;
        e.llIIlIIlIIIl[1] = 1;
        e.llIIlIIlIIIl[2] = 2;
        e.llIIlIIlIIIl[3] = 3;
        e.llIIlIIlIIIl[4] = 0x58 ^ 0x5C;
        e.llIIlIIlIIIl[5] = 0xD ^ 0x6A ^ (0xDE ^ 0xBC);
        e.llIIlIIlIIIl[6] = 0x20 ^ 0x26;
        e.llIIlIIlIIIl[7] = 0xA0 ^ 0xA7;
        e.llIIlIIlIIIl[8] = 0x62 ^ 0x6A;
        e.llIIlIIlIIIl[9] = 0x2F ^ 0x26;
        e.llIIlIIlIIIl[10] = 0x33 ^ 0x39;
        e.llIIlIIlIIIl[11] = 0xF9 ^ 0xA6 ^ (0x2C ^ 0x78);
        e.llIIlIIlIIIl[12] = 0xEA ^ 0xAF ^ (0xDC ^ 0x95);
        e.llIIlIIlIIIl[13] = 0xBB ^ 0xC7 ^ (0xB4 ^ 0xC5);
        e.llIIlIIlIIIl[14] = 0x11 ^ 0x1F;
        e.llIIlIIlIIIl[15] = 3 ^ (0xB6 ^ 0xBA);
        e.llIIlIIlIIIl[16] = 0x8A ^ 0x9A;
        e.llIIlIIlIIIl[17] = 0x23 ^ 0x1A ^ (0xA2 ^ 0x8A);
        e.llIIlIIlIIIl[18] = 0x86 ^ 0xB4 ^ (0xA0 ^ 0x80);
        e.llIIlIIlIIIl[19] = 0x57 ^ 0x40 ^ (0xA5 ^ 0xA1);
        e.llIIlIIlIIIl[20] = (0xAC ^ 0x9C) & ~(0x2A ^ 0x1A) ^ (0x43 ^ 0x57);
        e.llIIlIIlIIIl[21] = 0x34 ^ 0x3C ^ (0x1D ^ 0);
        e.llIIlIIlIIIl[22] = 0x82 ^ 0x94;
        e.llIIlIIlIIIl[23] = 0x84 ^ 0xAF ^ (0x2D ^ 0x11);
        e.llIIlIIlIIIl[24] = 0x1A ^ 0x1C ^ (0x71 ^ 0x6F);
        e.llIIlIIlIIIl[25] = 0x4C ^ 0x55;
        e.llIIlIIlIIIl[26] = 0x48 ^ 0x52;
        e.llIIlIIlIIIl[27] = 0xAB ^ 0xAC ^ (0x72 ^ 0x6E);
        e.llIIlIIlIIIl[28] = 0x1F ^ 3;
        e.llIIlIIlIIIl[29] = 0x9D ^ 0xB5 ^ (0x12 ^ 0x27);
        e.llIIlIIlIIIl[30] = 0xEA ^ 0xA9 ^ (0x76 ^ 0x2B);
        e.llIIlIIlIIIl[31] = 0xFE ^ 0xAD ^ (0xC4 ^ 0x88);
        e.llIIlIIlIIIl[32] = 0x20 ^ 0;
        e.llIIlIIlIIIl[33] = 0x38 ^ 0x19;
        e.llIIlIIlIIIl[34] = 0x6D ^ 0x4F;
        e.llIIlIIlIIIl[35] = 0x7F ^ 0x5C;
        e.llIIlIIlIIIl[36] = 0x24 ^ 0;
        e.llIIlIIlIIIl[37] = 110 + 93 - 172 + 129 ^ 87 + 129 - 190 + 107;
        e.llIIlIIlIIIl[38] = 0x43 ^ 0x47 ^ (0x50 ^ 0x72);
        e.llIIlIIlIIIl[39] = 0xE3 ^ 0x90 ^ (0xE0 ^ 0xB4);
        e.llIIlIIlIIIl[40] = 0x54 ^ 0x7C;
        e.llIIlIIlIIIl[41] = 0x7B ^ 2 ^ (0xF8 ^ 0xA8);
        e.llIIlIIlIIIl[42] = 0xAB ^ 0x81;
        e.llIIlIIlIIIl[43] = 0x64 ^ 0x4F;
        e.llIIlIIlIIIl[44] = 0xC7 ^ 0xC3 ^ (0x1E ^ 0x36);
        e.llIIlIIlIIIl[45] = 0x96 ^ 0xBB;
        e.llIIlIIlIIIl[46] = 0x5A ^ 0x74;
        e.llIIlIIlIIIl[47] = 3 + 201 - 87 + 115 ^ 101 + 18 - -13 + 67;
        e.llIIlIIlIIIl[48] = 0xA5 ^ 0xB1 ^ (0xBC ^ 0x98);
        e.llIIlIIlIIIl[49] = 0x69 ^ 0x7E ^ (0xE0 ^ 0xC6);
        e.llIIlIIlIIIl[50] = 0x4C ^ 0x7E;
        e.llIIlIIlIIIl[51] = 0x9F ^ 0xAC;
        e.llIIlIIlIIIl[52] = 0xBD ^ 0x89;
        e.llIIlIIlIIIl[53] = 0x79 ^ 0x4C;
        e.llIIlIIlIIIl[54] = 0x41 ^ 0x77;
        e.llIIlIIlIIIl[55] = 0x1F ^ 0x70 ^ (0x42 ^ 0x1A);
        e.llIIlIIlIIIl[56] = 79 + 25 - 84 + 123 ^ 73 + 145 - 42 + 7;
        e.llIIlIIlIIIl[57] = 26 + 16 - 30 + 116 ^ 54 + 6 - -9 + 116;
        e.llIIlIIlIIIl[58] = 7 ^ 0x3D;
        e.llIIlIIlIIIl[59] = 0x42 ^ 0x79;
        e.llIIlIIlIIIl[60] = 0x27 ^ 0x7C ^ (0x1A ^ 0x7D);
        e.llIIlIIlIIIl[61] = 0x66 ^ 0x5B;
        e.llIIlIIlIIIl[62] = 128 + 41 - 58 + 24 ^ 176 + 131 - 157 + 35;
        e.llIIlIIlIIIl[63] = 0x64 ^ 0x5B;
        e.llIIlIIlIIIl[64] = 0x28 ^ 0x6C ^ (0xAD ^ 0xA9);
    }

    public static e[] values() {
        return (e[])$VALUES.clone();
    }

    public static Stream<e> g() {
        return Stream.of(e.values());
    }

    private static void lllllIIlIlIIIl() {
        llIIlIIIllll = new String[llIIlIIlIIIl[64]];
        e.llIIlIIIllll[e.llIIlIIlIIIl[0]] = e."NONE";
        e.llIIlIIIllll[e.llIIlIIlIIIl[1]] = e."WAVE1";
        e.llIIlIIIllll[e.llIIlIIlIIIl[2]] = e."WAVE2";
        e.llIIlIIIllll[e.llIIlIIlIIIl[3]] = e."WAVE3";
        e.llIIlIIIllll[e.llIIlIIlIIIl[4]] = e."WAVE4";
        e.llIIlIIIllll[e.llIIlIIlIIIl[5]] = e."WAVE5";
        e.llIIlIIIllll[e.llIIlIIlIIIl[6]] = e."WAVE6";
        e.llIIlIIIllll[e.llIIlIIlIIIl[7]] = e."WAVE7";
        e.llIIlIIIllll[e.llIIlIIlIIIl[8]] = e."WAVE8";
        e.llIIlIIIllll[e.llIIlIIlIIIl[9]] = e."WAVE9";
        e.llIIlIIIllll[e.llIIlIIlIIIl[10]] = e."WAVE10";
        e.llIIlIIIllll[e.llIIlIIlIIIl[11]] = e."WAVE11";
        e.llIIlIIIllll[e.llIIlIIlIIIl[12]] = e."WAVE12";
        e.llIIlIIIllll[e.llIIlIIlIIIl[13]] = e."WAVE13";
        e.llIIlIIIllll[e.llIIlIIlIIIl[14]] = e."WAVE14";
        e.llIIlIIIllll[e.llIIlIIlIIIl[15]] = e."WAVE15";
        e.llIIlIIIllll[e.llIIlIIlIIIl[16]] = e."WAVE16";
        e.llIIlIIIllll[e.llIIlIIlIIIl[17]] = e."WAVE17";
        e.llIIlIIIllll[e.llIIlIIlIIIl[18]] = e."WAVE18";
        e.llIIlIIIllll[e.llIIlIIlIIIl[19]] = e."WAVE19";
        e.llIIlIIIllll[e.llIIlIIlIIIl[20]] = e."WAVE20";
        e.llIIlIIIllll[e.llIIlIIlIIIl[21]] = e."WAVE21";
        e.llIIlIIIllll[e.llIIlIIlIIIl[22]] = e."WAVE22";
        e.llIIlIIIllll[e.llIIlIIlIIIl[23]] = e."WAVE23";
        e.llIIlIIIllll[e.llIIlIIlIIIl[24]] = e."WAVE24";
        e.llIIlIIIllll[e.llIIlIIlIIIl[25]] = e."WAVE25";
        e.llIIlIIIllll[e.llIIlIIlIIIl[26]] = e."WAVE26";
        e.llIIlIIIllll[e.llIIlIIlIIIl[27]] = e."WAVE27";
        e.llIIlIIIllll[e.llIIlIIlIIIl[28]] = e."WAVE28";
        e.llIIlIIIllll[e.llIIlIIlIIIl[29]] = e."WAVE29";
        e.llIIlIIIllll[e.llIIlIIlIIIl[30]] = e."WAVE30";
        e.llIIlIIIllll[e.llIIlIIlIIIl[31]] = e."WAVE31";
        e.llIIlIIIllll[e.llIIlIIlIIIl[32]] = e."WAVE32";
        e.llIIlIIIllll[e.llIIlIIlIIIl[33]] = e."WAVE33";
        e.llIIlIIIllll[e.llIIlIIlIIIl[34]] = e."WAVE34";
        e.llIIlIIIllll[e.llIIlIIlIIIl[35]] = e."WAVE35";
        e.llIIlIIIllll[e.llIIlIIlIIIl[36]] = e."WAVE36";
        e.llIIlIIIllll[e.llIIlIIlIIIl[37]] = e."WAVE37";
        e.llIIlIIIllll[e.llIIlIIlIIIl[38]] = e."WAVE38";
        e.llIIlIIIllll[e.llIIlIIlIIIl[39]] = e."WAVE39";
        e.llIIlIIIllll[e.llIIlIIlIIIl[40]] = e."WAVE40";
        e.llIIlIIIllll[e.llIIlIIlIIIl[41]] = e."WAVE41";
        e.llIIlIIIllll[e.llIIlIIlIIIl[42]] = e."WAVE42";
        e.llIIlIIIllll[e.llIIlIIlIIIl[43]] = e."WAVE43";
        e.llIIlIIIllll[e.llIIlIIlIIIl[44]] = e."WAVE44";
        e.llIIlIIIllll[e.llIIlIIlIIIl[45]] = e."WAVE45";
        e.llIIlIIIllll[e.llIIlIIlIIIl[46]] = e."WAVE46";
        e.llIIlIIIllll[e.llIIlIIlIIIl[47]] = e."WAVE47";
        e.llIIlIIIllll[e.llIIlIIlIIIl[48]] = e."WAVE48";
        e.llIIlIIIllll[e.llIIlIIlIIIl[49]] = e."WAVE49";
        e.llIIlIIIllll[e.llIIlIIlIIIl[50]] = e."WAVE50";
        e.llIIlIIIllll[e.llIIlIIlIIIl[51]] = e."WAVE51";
        e.llIIlIIIllll[e.llIIlIIlIIIl[52]] = e."WAVE52";
        e.llIIlIIIllll[e.llIIlIIlIIIl[53]] = e."WAVE53";
        e.llIIlIIIllll[e.llIIlIIlIIIl[54]] = e."WAVE54";
        e.llIIlIIIllll[e.llIIlIIlIIIl[55]] = e."WAVE55";
        e.llIIlIIIllll[e.llIIlIIlIIIl[56]] = e."WAVE56";
        e.llIIlIIIllll[e.llIIlIIlIIIl[57]] = e."WAVE57";
        e.llIIlIIIllll[e.llIIlIIlIIIl[58]] = e."WAVE58";
        e.llIIlIIIllll[e.llIIlIIlIIIl[59]] = e."WAVE59";
        e.llIIlIIIllll[e.llIIlIIlIIIl[60]] = e."WAVE60";
        e.llIIlIIIllll[e.llIIlIIlIIIl[61]] = e."WAVE61";
        e.llIIlIIIllll[e.llIIlIIlIIIl[62]] = e."WAVE62";
        e.llIIlIIIllll[e.llIIlIIlIIIl[63]] = e."WAVE63";
    }
}

