package gg.squire.minigame.pestcontrol;

/**
 * Synthetic helper class for switch statements on PestControlDirection enum.
 * This is automatically generated by the Java compiler to support enum switch statements.
 * It maps enum ordinals to switch case values.
 */
class DirectionSwitchHelper {
    static final int[] directionOrdinalMapping;

    static {
        directionOrdinalMapping = new int[PestControlDirection.values().length];
        try {
            directionOrdinalMapping[PestControlDirection.EAST.ordinal()] = 1;
        } catch (NoSuchFieldError e) {
            // Ignore - enum value doesn't exist
        }
        try {
            directionOrdinalMapping[PestControlDirection.WEST.ordinal()] = 2;
        } catch (NoSuchFieldError e) {
            // Ignore - enum value doesn't exist
        }
        try {
            directionOrdinalMapping[PestControlDirection.SOUTH.ordinal()] = 3;
        } catch (NoSuchFieldError e) {
            // Ignore - enum value doesn't exist
        }
    }
}
