package s.r.s.o.l.t.t.l.r.a.p000.i.n.d.u.p001.q.i.i.e.a.u;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* renamed from: s.r.s.o.l.t.t.l.r.a.-.i.n.d.u.-.q.i.i.e.a.u.a  reason: invalid package and case insensitive filesystem */
/* loaded from: squire-tutorial-island-0.1.0.jar:s/r/s/o/l/t/t/l/r/a/-/i/n/d/u/-/q/i/i/e/a/u/a.class */
public final class EnumC0000a {
    public static final /* synthetic */ EnumC0000a QUEST_PIRATES_TREASURE;
    public static final /* synthetic */ EnumC0000a QUEST_DEATH_PLATEAU;
    public static final /* synthetic */ EnumC0000a QUEST_TRIBAL_TOTEM;
    public static final /* synthetic */ EnumC0000a QUEST_RUNE_MYSTERIES;
    public static final /* synthetic */ EnumC0000a QUEST_WITCHS_POTION;
    private final /* synthetic */ int id;
    public static final /* synthetic */ EnumC0000a QUEST_SHIELD_OF_ARRAV;
    public static final /* synthetic */ EnumC0000a QUEST_ERNEST_THE_CHICKEN;
    public static final /* synthetic */ EnumC0000a QUEST_THE_RESTLESS_GHOST;
    public static final /* synthetic */ EnumC0000a QUEST_MURDER_MYSTERY;
    public static final /* synthetic */ EnumC0000a QUEST_ROVING_ELVES;
    public static final /* synthetic */ EnumC0000a QUEST_TREE_GNOME_VILLAGE;
    public static final /* synthetic */ EnumC0000a QUEST_RAG_AND_BONE_MAN_II;
    public static final /* synthetic */ EnumC0000a QUEST_COOKS_ASSISTANT;
    public static final /* synthetic */ EnumC0000a QUEST_CABIN_FEVER;
    public static final /* synthetic */ EnumC0000a QUEST_MERLINS_CRYSTAL;
    public static final /* synthetic */ EnumC0000a QUEST_THE_GREAT_BRAIN_ROBBERY;
    public static final /* synthetic */ EnumC0000a QUEST_HOLY_GRAIL;
    public static final /* synthetic */ EnumC0000a QUEST_TROLL_ROMANCE;
    public static final /* synthetic */ EnumC0000a QUEST_DORICS_QUEST;
    public static final /* synthetic */ EnumC0000a QUEST_ENTER_THE_ABYSS;
    public static final /* synthetic */ EnumC0000a QUEST_RAG_AND_BONE_MAN_I;
    public static final /* synthetic */ EnumC0000a QUEST_THE_KNIGHTS_SWORD;
    public static final /* synthetic */ EnumC0000a QUEST_UNDERGROUND_PASS;
    public static final /* synthetic */ EnumC0000a QUEST_TAI_BWO_WANNAI_TRIO;
    public static final /* synthetic */ EnumC0000a QUEST_PLAGUE_CITY;
    public static final /* synthetic */ EnumC0000a QUEST_NATURE_SPIRIT;
    public static final /* synthetic */ EnumC0000a QUEST_BLACK_KNIGHTS_FORTRESS;
    private static /* synthetic */ int[] lIlIIIlllIIlI;
    public static final /* synthetic */ EnumC0000a QUEST_CLOCK_TOWER;
    public static final /* synthetic */ EnumC0000a QUEST_SHEEP_SHEARER;
    public static final /* synthetic */ EnumC0000a QUEST_UNDERGROUND_PASS_STATE_162;
    public static final /* synthetic */ EnumC0000a QUEST_THE_GRAND_TREE;
    public static final /* synthetic */ EnumC0000a QUEST_PRINCE_ALI_RESCUE;
    public static final /* synthetic */ EnumC0000a QUEST_DRUIDIC_RITUAL;
    public static final /* synthetic */ EnumC0000a QUEST_VAMPYRE_SLAYER;
    public static final /* synthetic */ EnumC0000a QUEST_EADGARS_RUSE;
    public static final /* synthetic */ EnumC0000a QUEST_DWARF_CANNON;
    public static final /* synthetic */ EnumC0000a QUEST_HAZEEL_CULT;
    public static final /* synthetic */ EnumC0000a QUEST_ONE_SMALL_FAVOUR;
    public static final /* synthetic */ EnumC0000a QUEST_GERTRUDES_CAT;
    public static final /* synthetic */ EnumC0000a QUEST_SHILO_VILLAGE;
    public static final /* synthetic */ EnumC0000a QUEST_HEROES_QUEST;
    public static final /* synthetic */ EnumC0000a QUEST_WATCHTOWER;
    public static final /* synthetic */ EnumC0000a QUEST_REGICIDE;
    public static final /* synthetic */ EnumC0000a QUEST_THE_TOURIST_TRAP;
    public static final /* synthetic */ EnumC0000a QUEST_WITCHS_HOUSE;
    public static final /* synthetic */ EnumC0000a QUEST_FIGHT_ARENA;
    public static final /* synthetic */ EnumC0000a QUEST_BIG_CHOMPY_BIRD_HUNTING;
    public static final /* synthetic */ EnumC0000a QUEST_THRONE_OF_MISCELLANIA;
    public static final /* synthetic */ EnumC0000a QUEST_THE_MAGE_ARENA;
    public static final /* synthetic */ EnumC0000a QUEST_ELEMENTAL_WORKSHOP_I;
    private static /* synthetic */ String[] lIlIIIllIIIII;
    public static final /* synthetic */ EnumC0000a QUEST_SEA_SLUG;
    public static final /* synthetic */ EnumC0000a QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
    public static final /* synthetic */ EnumC0000a QUEST_THE_DIG_SITE;
    public static final /* synthetic */ EnumC0000a QUEST_HAUNTED_MINE;
    public static final /* synthetic */ EnumC0000a QUEST_IMP_CATCHER;
    public static final /* synthetic */ EnumC0000a QUEST_MOURNINGS_END_PART_I;
    public static final /* synthetic */ EnumC0000a QUEST_JUNGLE_POTION;
    public static final /* synthetic */ EnumC0000a QUEST_RUM_DEAL;
    public static final /* synthetic */ EnumC0000a QUEST_LEGENDS_QUEST;
    public static final /* synthetic */ EnumC0000a QUEST_BIOHAZARD;
    public static final /* synthetic */ EnumC0000a QUEST_SHADES_OF_MORTTON;
    public static final /* synthetic */ EnumC0000a QUEST_TROLL_STRONGHOLD;
    public static final /* synthetic */ EnumC0000a QUEST_LOST_CITY;
    public static final /* synthetic */ EnumC0000a QUEST_FAMILY_CREST;
    public static final /* synthetic */ EnumC0000a QUEST_TEMPLE_OF_IKOV;
    public static final /* synthetic */ EnumC0000a QUEST_MONKEY_MADNESS_I;
    public static final /* synthetic */ EnumC0000a QUEST_THE_FREMENNIK_TRIALS;
    public static final /* synthetic */ EnumC0000a QUEST_FISHING_CONTEST;
    public static final /* synthetic */ EnumC0000a QUEST_OBSERVATORY_QUEST;
    public static final /* synthetic */ EnumC0000a QUEST_SHEEP_HERDER;
    public static final /* synthetic */ EnumC0000a QUEST_SHIELD_OF_ARRAV_STATE_146;
    public static final /* synthetic */ EnumC0000a QUEST_MONKS_FRIEND;
    public static final /* synthetic */ EnumC0000a QUEST_ROMEO_AND_JULIET;
    public static final /* synthetic */ EnumC0000a QUEST_DRAGON_SLAYER_I;
    private static final /* synthetic */ EnumC0000a[] $VALUES;
    public static final /* synthetic */ EnumC0000a QUEST_PRIEST_IN_PERIL;
    public static final /* synthetic */ EnumC0000a QUEST_ALFRED_GRIMHANDS_BARCRAWL;
    public static final /* synthetic */ EnumC0000a QUEST_CREATURE_OF_FENKENSTRAIN;
    public static final /* synthetic */ EnumC0000a QUEST_SCORPION_CATCHER;
    public static final /* synthetic */ EnumC0000a QUEST_IN_SEARCH_OF_THE_MYREQUE;
    public static final /* synthetic */ EnumC0000a QUEST_WATERFALL_QUEST;

    public static EnumC0000a[] values() {
        return (EnumC0000a[]) $VALUES.clone();
    }

    private static String lIlllIIIIIlIlII(String llllllllllllllIlllIIIIlllllIIlII, String llllllllllllllIlllIIIIlllllIIIll) {
        String str = new String(Base64.getDecoder().decode(llllllllllllllIlllIIIIlllllIIlII.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder sb = new StringBuilder();
        char[] charArray = llllllllllllllIlllIIIIlllllIIIll.toCharArray();
        int llllllllllllllIlllIIIIlllllIIIII = lIlIIIlllIIlI[0];
        char[] charArray2 = str.toCharArray();
        int length = charArray2.length;
        int i = lIlIIIlllIIlI[0];
        while (lIlllIIIlIIIllI(i, length)) {
            sb.append((char) (charArray2[i] ^ charArray[llllllllllllllIlllIIIIlllllIIIII % charArray.length]));
            "".length();
            llllllllllllllIlllIIIIlllllIIIII++;
            i++;
            "".length();
            if ((-"   ".length()) >= 0) {
                return null;
            }
        }
        return String.valueOf(sb);
    }

    private static void lIlllIIIlIIIlIl() {
        lIlIIIlllIIlI = new int[139];
        lIlIIIlllIIlI[0] = (40 ^ 126) & ((25 ^ 79) ^ (-1));
        lIlIIIlllIIlI[1] = (((117 ^ 76) + (95 ^ 4)) - (((54 + 102) - 126) + 109)) + (120 ^ 1);
        lIlIIIlllIIlI[2] = " ".length();
        lIlIIIlllIIlI[3] = 219 ^ 198;
        lIlIIIlllIIlI[4] = "  ".length();
        lIlIIIlllIIlI[5] = 3 ^ 28;
        lIlIIIlllIIlI[6] = "   ".length();
        lIlIIIlllIIlI[7] = ((97 + 89) - 137) + 127;
        lIlIIIlllIIlI[8] = (((107 + 110) - 204) + 146) ^ (((24 + 85) - 102) + 148);
        lIlIIIlllIIlI[9] = (46 ^ 75) ^ (66 ^ 7);
        lIlIIIlllIIlI[10] = 8 ^ 13;
        lIlIIIlllIIlI[11] = ((74 + 93) - 33) + 26;
        lIlIIIlllIIlI[12] = (97 ^ 29) ^ (51 ^ 73);
        lIlIIIlllIIlI[13] = (58 ^ 97) ^ (129 ^ 160);
        lIlIIIlllIIlI[14] = 94 ^ 89;
        lIlIIIlllIIlI[15] = 109 ^ 42;
        lIlIIIlllIIlI[16] = 70 ^ 78;
        lIlIIIlllIIlI[17] = (-((-16649) & 20397)) & (-16385) & 20405;
        lIlIIIlllIIlI[18] = 201 ^ 192;
        lIlIIIlllIIlI[19] = 46 ^ 69;
        lIlIIIlllIIlI[20] = 29 ^ 23;
        lIlIIIlllIIlI[21] = ((37 + 120) - 49) + 36;
        lIlIIIlllIIlI[22] = (109 ^ 85) ^ (30 ^ 45);
        lIlIIIlllIIlI[23] = 74 ^ 117;
        lIlIIIlllIIlI[24] = (139 ^ 194) ^ (58 ^ 127);
        lIlIIIlllIIlI[25] = ((92 + 37) - (-21)) + 29;
        lIlIIIlllIIlI[26] = (150 ^ 194) ^ (243 ^ 170);
        lIlIIIlllIIlI[27] = ((52 + 24) - 55) + 124;
        lIlIIIlllIIlI[28] = (((18 + 135) - 114) + 122) ^ (((49 + 121) - 85) + 90);
        lIlIIIlllIIlI[29] = ((3 + 55) - (-53)) + 35;
        lIlIIIlllIIlI[30] = 8 ^ 7;
        lIlIIIlllIIlI[31] = (((((96 + 130) - 68) + 7) + (53 ^ 99)) - (((117 + 38) - 37) + 27)) + (73 ^ 1);
        lIlIIIlllIIlI[32] = (255 ^ 185) ^ (211 ^ 133);
        lIlIIIlllIIlI[33] = 103 ^ 36;
        lIlIIIlllIIlI[34] = 176 ^ 161;
        lIlIIIlllIIlI[35] = (-((-1) & 7883)) & (-17) & 8191;
        lIlIIIlllIIlI[36] = 108 ^ 126;
        lIlIIIlllIIlI[37] = 26 ^ 94;
        lIlIIIlllIIlI[38] = (44 ^ 114) ^ (0 ^ 77);
        lIlIIIlllIIlI[39] = (-2113) & 2767;
        lIlIIIlllIIlI[40] = 175 ^ 187;
        lIlIIIlllIIlI[41] = 90 ^ 79;
        lIlIIIlllIIlI[42] = (-22577) & 22975;
        lIlIIIlllIIlI[43] = 2 ^ 20;
        lIlIIIlllIIlI[44] = (-2242) & 2555;
        lIlIIIlllIIlI[45] = (229 ^ 162) ^ (70 ^ 22);
        lIlIIIlllIIlI[46] = (((41 ^ 30) + (92 ^ 107)) - (160 ^ 177)) + (9 ^ 47);
        lIlIIIlllIIlI[47] = (46 ^ 102) ^ (32 ^ 112);
        lIlIIIlllIIlI[48] = 55 ^ 103;
        lIlIIIlllIIlI[49] = 93 ^ 68;
        lIlIIIlllIIlI[50] = (14 ^ 62) ^ (134 ^ 172);
        lIlIIIlllIIlI[51] = (-17) & 351;
        lIlIIIlllIIlI[52] = (79 ^ 30) ^ (91 ^ 17);
        lIlIIIlllIIlI[53] = (-((-27171) & 32439)) & (-27201) & 32767;
        lIlIIIlllIIlI[54] = 6 ^ 26;
        lIlIIIlllIIlI[55] = ((83 + 126) - 154) + 93;
        lIlIIIlllIIlI[56] = (20 ^ 28) ^ (187 ^ 173);
        lIlIIIlllIIlI[57] = (-22053) & 22399;
        lIlIIIlllIIlI[58] = (((58 + 127) - 17) + 36) ^ (((121 + 8) - 18) + 30);
        lIlIIIlllIIlI[59] = (73 ^ 122) ^ (92 ^ 78);
        lIlIIIlllIIlI[60] = ((28 + 146) - 7) + 13;
        lIlIIIlllIIlI[61] = 168 ^ 138;
        lIlIIIlllIIlI[62] = ((117 + 40) - 9) + 2;
        lIlIIIlllIIlI[63] = (12 ^ 43) ^ (123 ^ 127);
        lIlIIIlllIIlI[64] = (-642) & 1023;
        lIlIIIlllIIlI[65] = (15 ^ 41) ^ "  ".length();
        lIlIIIlllIIlI[66] = ((136 + 162) - 84) + 9;
        lIlIIIlllIIlI[67] = (112 ^ 121) ^ (30 ^ 50);
        lIlIIIlllIIlI[68] = (((((53 + 15) - (-65)) + 20) + (110 ^ 71)) - (((189 + 11) - 194) + 185)) + ((133 + 102) - 70) + 20;
        lIlIIIlllIIlI[69] = 175 ^ 137;
        lIlIIIlllIIlI[70] = 183 ^ 144;
        lIlIIIlllIIlI[71] = (-((-1293) & 32077)) & (-1) & 31171;
        lIlIIIlllIIlI[72] = 82 ^ 122;
        lIlIIIlllIIlI[73] = ((145 + 19) - 30) + 41;
        lIlIIIlllIIlI[74] = 115 ^ 90;
        lIlIIIlllIIlI[75] = ((16 + 40) - 49) + 132;
        lIlIIIlllIIlI[76] = 140 ^ 166;
        lIlIIIlllIIlI[77] = ((128 + 69) - 179) + 129;
        lIlIIIlllIIlI[78] = 137 ^ 162;
        lIlIIIlllIIlI[79] = 7 ^ 43;
        lIlIIIlllIIlI[80] = (-((-2109) & 15423)) & (-18433) & 32111;
        lIlIIIlllIIlI[81] = 85 ^ 120;
        lIlIIIlllIIlI[82] = (((170 + 155) - 277) + 130) ^ (((138 + 49) - 46) + 15);
        lIlIIIlllIIlI[83] = (-22659) & 23175;
        lIlIIIlllIIlI[84] = (37 ^ 46) ^ (59 ^ 31);
        lIlIIIlllIIlI[85] = ((51 + 79) - 83) + 145;
        lIlIIIlllIIlI[86] = (105 ^ 125) ^ (175 ^ 139);
        lIlIIIlllIIlI[87] = (-9413) & 9719;
        lIlIIIlllIIlI[88] = (128 ^ 147) ^ (188 ^ 158);
        lIlIIIlllIIlI[89] = (82 ^ 108) ^ (230 ^ 168);
        lIlIIIlllIIlI[90] = 5 ^ 55;
        lIlIIIlllIIlI[91] = (-29263) & 29678;
        lIlIIIlllIIlI[92] = (((7 + 108) - (-15)) + 6) ^ (((140 + 86) - 126) + 87);
        lIlIIIlllIIlI[93] = ((101 + 133) - 92) + 23;
        lIlIIIlllIIlI[94] = (135 ^ 161) ^ (23 ^ 5);
        lIlIIIlllIIlI[95] = (-6673) & 6974;
        lIlIIIlllIIlI[96] = 71 ^ 114;
        lIlIIIlllIIlI[97] = (-((-8815) & 29311)) & (-8230) & 29439;
        lIlIIIlllIIlI[98] = 151 ^ 161;
        lIlIIIlllIIlI[99] = (-((-266) & 10011)) & (-22659) & 32731;
        lIlIIIlllIIlI[100] = (134 ^ 181) ^ (95 ^ 91);
        lIlIIIlllIIlI[101] = (-8289) & 8690;
        lIlIIIlllIIlI[102] = (85 ^ 5) ^ (2 ^ 106);
        lIlIIIlllIIlI[103] = (-23970) & 24569;
        lIlIIIlllIIlI[104] = (214 ^ 184) ^ (35 ^ 116);
        lIlIIIlllIIlI[105] = 106 ^ 38;
        lIlIIIlllIIlI[106] = (231 ^ 165) ^ (5 ^ 125);
        lIlIIIlllIIlI[107] = ((68 + 20) - (-26)) + 45;
        lIlIIIlllIIlI[108] = (36 ^ 70) ^ (199 ^ 158);
        lIlIIIlllIIlI[109] = (-27277) & 27615;
        lIlIIIlllIIlI[110] = 149 ^ 169;
        lIlIIIlllIIlI[111] = 59 ^ 6;
        lIlIIIlllIIlI[112] = 26 ^ 110;
        lIlIIIlllIIlI[113] = 89 ^ 103;
        lIlIIIlllIIlI[114] = (-((-16389) & 19620)) & (-8737) & 12287;
        lIlIIIlllIIlI[115] = (((32 + 121) - 62) + 38) ^ (((77 + 11) - (-29)) + 76);
        lIlIIIlllIIlI[116] = (-((-16677) & 29621)) & (-18441) & 31743;
        lIlIIIlllIIlI[117] = ((128 + 173) - 122) + 18;
        lIlIIIlllIIlI[118] = 31 ^ 93;
        lIlIIIlllIIlI[119] = (((((124 + 38) - 138) + 160) + (((90 + 101) - 87) + 121)) - ((-8841) & 9195)) + ((36 + 56) - (-11)) + 69;
        lIlIIIlllIIlI[120] = 30 ^ 113;
        lIlIIIlllIIlI[121] = ((47 + 85) - 85) + 153;
        lIlIIIlllIIlI[122] = 34 ^ 103;
        lIlIIIlllIIlI[123] = (-13845) & 14229;
        lIlIIIlllIIlI[124] = 222 ^ 152;
        lIlIIIlllIIlI[125] = (-3651) & 3967;
        lIlIIIlllIIlI[126] = ((147 + 44) - 82) + 52;
        lIlIIIlllIIlI[127] = (36 ^ 55) ^ (98 ^ 57);
        lIlIIIlllIIlI[128] = ((18 + 70) - 21) + 95;
        lIlIIIlllIIlI[129] = 193 ^ 136;
        lIlIIIlllIIlI[130] = (((124 ^ 74) + (128 ^ 171)) - (-(108 ^ 5))) + (189 ^ 183);
        lIlIIIlllIIlI[131] = 96 ^ 42;
        lIlIIIlllIIlI[132] = (-17449) & 18428;
        lIlIIIlllIIlI[133] = 15 ^ 68;
        lIlIIIlllIIlI[134] = (-30209) & 30700;
        lIlIIIlllIIlI[135] = 227 ^ 174;
        lIlIIIlllIIlI[136] = (((12 + 53) - 28) + 186) ^ (((101 + 116) - 171) + 99);
        lIlIIIlllIIlI[137] = 196 ^ 139;
        lIlIIIlllIIlI[138] = (-((-5383) & 24423)) & (-9233) & 28539;
    }

    static {
        lIlllIIIlIIIlIl();
        lIlllIIIlIIIlII();
        QUEST_BLACK_KNIGHTS_FORTRESS = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[0]], lIlIIIlllIIlI[0], lIlIIIlllIIlI[1]);
        QUEST_COOKS_ASSISTANT = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[2]], lIlIIIlllIIlI[2], lIlIIIlllIIlI[3]);
        QUEST_DORICS_QUEST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[4]], lIlIIIlllIIlI[4], lIlIIIlllIIlI[5]);
        QUEST_DRAGON_SLAYER_I = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[6]], lIlIIIlllIIlI[6], lIlIIIlllIIlI[7]);
        QUEST_ERNEST_THE_CHICKEN = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[8]], lIlIIIlllIIlI[8], lIlIIIlllIIlI[9]);
        QUEST_IMP_CATCHER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[10]], lIlIIIlllIIlI[10], lIlIIIlllIIlI[11]);
        QUEST_THE_KNIGHTS_SWORD = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[12]], lIlIIIlllIIlI[12], lIlIIIlllIIlI[13]);
        QUEST_PIRATES_TREASURE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[14]], lIlIIIlllIIlI[14], lIlIIIlllIIlI[15]);
        QUEST_PRINCE_ALI_RESCUE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[16]], lIlIIIlllIIlI[16], lIlIIIlllIIlI[17]);
        QUEST_THE_RESTLESS_GHOST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[18]], lIlIIIlllIIlI[18], lIlIIIlllIIlI[19]);
        QUEST_ROMEO_AND_JULIET = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[20]], lIlIIIlllIIlI[20], lIlIIIlllIIlI[21]);
        QUEST_RUNE_MYSTERIES = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[22]], lIlIIIlllIIlI[22], lIlIIIlllIIlI[23]);
        QUEST_SHEEP_SHEARER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[24]], lIlIIIlllIIlI[24], lIlIIIlllIIlI[25]);
        QUEST_SHIELD_OF_ARRAV = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[26]], lIlIIIlllIIlI[26], lIlIIIlllIIlI[27]);
        QUEST_SHIELD_OF_ARRAV_STATE_146 = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[28]], lIlIIIlllIIlI[28], lIlIIIlllIIlI[29]);
        QUEST_VAMPYRE_SLAYER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[30]], lIlIIIlllIIlI[30], lIlIIIlllIIlI[31]);
        QUEST_WITCHS_POTION = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[32]], lIlIIIlllIIlI[32], lIlIIIlllIIlI[33]);
        QUEST_BIG_CHOMPY_BIRD_HUNTING = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[34]], lIlIIIlllIIlI[34], lIlIIIlllIIlI[35]);
        QUEST_BIOHAZARD = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[36]], lIlIIIlllIIlI[36], lIlIIIlllIIlI[37]);
        QUEST_CABIN_FEVER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[38]], lIlIIIlllIIlI[38], lIlIIIlllIIlI[39]);
        QUEST_CLOCK_TOWER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[40]], lIlIIIlllIIlI[40], lIlIIIlllIIlI[20]);
        QUEST_CREATURE_OF_FENKENSTRAIN = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[41]], lIlIIIlllIIlI[41], lIlIIIlllIIlI[42]);
        QUEST_DEATH_PLATEAU = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[43]], lIlIIIlllIIlI[43], lIlIIIlllIIlI[44]);
        QUEST_THE_DIG_SITE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[45]], lIlIIIlllIIlI[45], lIlIIIlllIIlI[46]);
        QUEST_DRUIDIC_RITUAL = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[47]], lIlIIIlllIIlI[47], lIlIIIlllIIlI[48]);
        QUEST_DWARF_CANNON = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[49]], lIlIIIlllIIlI[49], lIlIIIlllIIlI[0]);
        QUEST_EADGARS_RUSE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[50]], lIlIIIlllIIlI[50], lIlIIIlllIIlI[51]);
        QUEST_ELEMENTAL_WORKSHOP_I = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[52]], lIlIIIlllIIlI[52], lIlIIIlllIIlI[53]);
        QUEST_FAMILY_CREST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[54]], lIlIIIlllIIlI[54], lIlIIIlllIIlI[55]);
        QUEST_FIGHT_ARENA = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[3]], lIlIIIlllIIlI[3], lIlIIIlllIIlI[34]);
        QUEST_FISHING_CONTEST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[56]], lIlIIIlllIIlI[56], lIlIIIlllIIlI[22]);
        QUEST_THE_FREMENNIK_TRIALS = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[5]], lIlIIIlllIIlI[5], lIlIIIlllIIlI[57]);
        QUEST_WATERFALL_QUEST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[9]], lIlIIIlllIIlI[9], lIlIIIlllIIlI[58]);
        QUEST_GERTRUDES_CAT = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[59]], lIlIIIlllIIlI[59], lIlIIIlllIIlI[60]);
        QUEST_THE_GRAND_TREE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[61]], lIlIIIlllIIlI[61], lIlIIIlllIIlI[62]);
        QUEST_HAUNTED_MINE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[63]], lIlIIIlllIIlI[63], lIlIIIlllIIlI[64]);
        QUEST_HAZEEL_CULT = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[65]], lIlIIIlllIIlI[65], lIlIIIlllIIlI[66]);
        QUEST_HEROES_QUEST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[67]], lIlIIIlllIIlI[67], lIlIIIlllIIlI[68]);
        QUEST_HOLY_GRAIL = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[69]], lIlIIIlllIIlI[69], lIlIIIlllIIlI[10]);
        QUEST_IN_SEARCH_OF_THE_MYREQUE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[70]], lIlIIIlllIIlI[70], lIlIIIlllIIlI[71]);
        QUEST_JUNGLE_POTION = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[72]], lIlIIIlllIIlI[72], lIlIIIlllIIlI[73]);
        QUEST_LEGENDS_QUEST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[74]], lIlIIIlllIIlI[74], lIlIIIlllIIlI[75]);
        QUEST_LOST_CITY = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[76]], lIlIIIlllIIlI[76], lIlIIIlllIIlI[77]);
        QUEST_MERLINS_CRYSTAL = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[78]], lIlIIIlllIIlI[78], lIlIIIlllIIlI[28]);
        QUEST_MONKEY_MADNESS_I = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[79]], lIlIIIlllIIlI[79], lIlIIIlllIIlI[80]);
        QUEST_MONKS_FRIEND = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[81]], lIlIIIlllIIlI[81], lIlIIIlllIIlI[56]);
        QUEST_MOURNINGS_END_PART_I = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[82]], lIlIIIlllIIlI[82], lIlIIIlllIIlI[83]);
        QUEST_MURDER_MYSTERY = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[84]], lIlIIIlllIIlI[84], lIlIIIlllIIlI[85]);
        QUEST_NATURE_SPIRIT = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[86]], lIlIIIlllIIlI[86], lIlIIIlllIIlI[87]);
        QUEST_OBSERVATORY_QUEST = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[88]], lIlIIIlllIIlI[88], lIlIIIlllIIlI[89]);
        QUEST_ONE_SMALL_FAVOUR = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[90]], lIlIIIlllIIlI[90], lIlIIIlllIIlI[91]);
        QUEST_PLAGUE_CITY = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[92]], lIlIIIlllIIlI[92], lIlIIIlllIIlI[93]);
        QUEST_PRIEST_IN_PERIL = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[94]], lIlIIIlllIIlI[94], lIlIIIlllIIlI[95]);
        QUEST_RAG_AND_BONE_MAN_I = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[96]], lIlIIIlllIIlI[96], lIlIIIlllIIlI[97]);
        QUEST_REGICIDE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[98]], lIlIIIlllIIlI[98], lIlIIIlllIIlI[99]);
        QUEST_ROVING_ELVES = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[100]], lIlIIIlllIIlI[100], lIlIIIlllIIlI[101]);
        QUEST_RUM_DEAL = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[102]], lIlIIIlllIIlI[102], lIlIIIlllIIlI[103]);
        QUEST_SCORPION_CATCHER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[104]], lIlIIIlllIIlI[104], lIlIIIlllIIlI[105]);
        QUEST_SEA_SLUG = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[106]], lIlIIIlllIIlI[106], lIlIIIlllIIlI[107]);
        QUEST_SHADES_OF_MORTTON = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[108]], lIlIIIlllIIlI[108], lIlIIIlllIIlI[109]);
        QUEST_SHEEP_HERDER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[110]], lIlIIIlllIIlI[110], lIlIIIlllIIlI[110]);
        QUEST_SHILO_VILLAGE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[111]], lIlIIIlllIIlI[111], lIlIIIlllIIlI[112]);
        QUEST_TAI_BWO_WANNAI_TRIO = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[113]], lIlIIIlllIIlI[113], lIlIIIlllIIlI[114]);
        QUEST_TEMPLE_OF_IKOV = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[23]], lIlIIIlllIIlI[23], lIlIIIlllIIlI[50]);
        QUEST_THRONE_OF_MISCELLANIA = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[115]], lIlIIIlllIIlI[115], lIlIIIlllIIlI[116]);
        QUEST_THE_TOURIST_TRAP = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[58]], lIlIIIlllIIlI[58], lIlIIIlllIIlI[117]);
        QUEST_WITCHS_HOUSE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[118]], lIlIIIlllIIlI[118], lIlIIIlllIIlI[119]);
        QUEST_TREE_GNOME_VILLAGE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[33]], lIlIIIlllIIlI[33], lIlIIIlllIIlI[120]);
        QUEST_TRIBAL_TOTEM = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[37]], lIlIIIlllIIlI[37], lIlIIIlllIIlI[121]);
        QUEST_TROLL_ROMANCE = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[122]], lIlIIIlllIIlI[122], lIlIIIlllIIlI[123]);
        QUEST_TROLL_STRONGHOLD = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[124]], lIlIIIlllIIlI[124], lIlIIIlllIIlI[125]);
        QUEST_UNDERGROUND_PASS = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[15]], lIlIIIlllIIlI[15], lIlIIIlllIIlI[126]);
        QUEST_UNDERGROUND_PASS_STATE_162 = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[127]], lIlIIIlllIIlI[127], lIlIIIlllIIlI[128]);
        QUEST_WATCHTOWER = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[129]], lIlIIIlllIIlI[129], lIlIIIlllIIlI[130]);
        QUEST_THE_GREAT_BRAIN_ROBBERY = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[131]], lIlIIIlllIIlI[131], lIlIIIlllIIlI[132]);
        QUEST_RAG_AND_BONE_MAN_II = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[133]], lIlIIIlllIIlI[133], lIlIIIlllIIlI[97]);
        QUEST_ENTER_THE_ABYSS = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[105]], lIlIIIlllIIlI[105], lIlIIIlllIIlI[134]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[135]], lIlIIIlllIIlI[135], lIlIIIlllIIlI[135]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76 = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[136]], lIlIIIlllIIlI[136], lIlIIIlllIIlI[105]);
        QUEST_THE_MAGE_ARENA = new EnumC0000a(lIlIIIllIIIII[lIlIIIlllIIlI[137]], lIlIIIlllIIlI[137], lIlIIIlllIIlI[138]);
        EnumC0000a[] enumC0000aArr = new EnumC0000a[lIlIIIlllIIlI[48]];
        enumC0000aArr[lIlIIIlllIIlI[0]] = QUEST_BLACK_KNIGHTS_FORTRESS;
        enumC0000aArr[lIlIIIlllIIlI[2]] = QUEST_COOKS_ASSISTANT;
        enumC0000aArr[lIlIIIlllIIlI[4]] = QUEST_DORICS_QUEST;
        enumC0000aArr[lIlIIIlllIIlI[6]] = QUEST_DRAGON_SLAYER_I;
        enumC0000aArr[lIlIIIlllIIlI[8]] = QUEST_ERNEST_THE_CHICKEN;
        enumC0000aArr[lIlIIIlllIIlI[10]] = QUEST_IMP_CATCHER;
        enumC0000aArr[lIlIIIlllIIlI[12]] = QUEST_THE_KNIGHTS_SWORD;
        enumC0000aArr[lIlIIIlllIIlI[14]] = QUEST_PIRATES_TREASURE;
        enumC0000aArr[lIlIIIlllIIlI[16]] = QUEST_PRINCE_ALI_RESCUE;
        enumC0000aArr[lIlIIIlllIIlI[18]] = QUEST_THE_RESTLESS_GHOST;
        enumC0000aArr[lIlIIIlllIIlI[20]] = QUEST_ROMEO_AND_JULIET;
        enumC0000aArr[lIlIIIlllIIlI[22]] = QUEST_RUNE_MYSTERIES;
        enumC0000aArr[lIlIIIlllIIlI[24]] = QUEST_SHEEP_SHEARER;
        enumC0000aArr[lIlIIIlllIIlI[26]] = QUEST_SHIELD_OF_ARRAV;
        enumC0000aArr[lIlIIIlllIIlI[28]] = QUEST_SHIELD_OF_ARRAV_STATE_146;
        enumC0000aArr[lIlIIIlllIIlI[30]] = QUEST_VAMPYRE_SLAYER;
        enumC0000aArr[lIlIIIlllIIlI[32]] = QUEST_WITCHS_POTION;
        enumC0000aArr[lIlIIIlllIIlI[34]] = QUEST_BIG_CHOMPY_BIRD_HUNTING;
        enumC0000aArr[lIlIIIlllIIlI[36]] = QUEST_BIOHAZARD;
        enumC0000aArr[lIlIIIlllIIlI[38]] = QUEST_CABIN_FEVER;
        enumC0000aArr[lIlIIIlllIIlI[40]] = QUEST_CLOCK_TOWER;
        enumC0000aArr[lIlIIIlllIIlI[41]] = QUEST_CREATURE_OF_FENKENSTRAIN;
        enumC0000aArr[lIlIIIlllIIlI[43]] = QUEST_DEATH_PLATEAU;
        enumC0000aArr[lIlIIIlllIIlI[45]] = QUEST_THE_DIG_SITE;
        enumC0000aArr[lIlIIIlllIIlI[47]] = QUEST_DRUIDIC_RITUAL;
        enumC0000aArr[lIlIIIlllIIlI[49]] = QUEST_DWARF_CANNON;
        enumC0000aArr[lIlIIIlllIIlI[50]] = QUEST_EADGARS_RUSE;
        enumC0000aArr[lIlIIIlllIIlI[52]] = QUEST_ELEMENTAL_WORKSHOP_I;
        enumC0000aArr[lIlIIIlllIIlI[54]] = QUEST_FAMILY_CREST;
        enumC0000aArr[lIlIIIlllIIlI[3]] = QUEST_FIGHT_ARENA;
        enumC0000aArr[lIlIIIlllIIlI[56]] = QUEST_FISHING_CONTEST;
        enumC0000aArr[lIlIIIlllIIlI[5]] = QUEST_THE_FREMENNIK_TRIALS;
        enumC0000aArr[lIlIIIlllIIlI[9]] = QUEST_WATERFALL_QUEST;
        enumC0000aArr[lIlIIIlllIIlI[59]] = QUEST_GERTRUDES_CAT;
        enumC0000aArr[lIlIIIlllIIlI[61]] = QUEST_THE_GRAND_TREE;
        enumC0000aArr[lIlIIIlllIIlI[63]] = QUEST_HAUNTED_MINE;
        enumC0000aArr[lIlIIIlllIIlI[65]] = QUEST_HAZEEL_CULT;
        enumC0000aArr[lIlIIIlllIIlI[67]] = QUEST_HEROES_QUEST;
        enumC0000aArr[lIlIIIlllIIlI[69]] = QUEST_HOLY_GRAIL;
        enumC0000aArr[lIlIIIlllIIlI[70]] = QUEST_IN_SEARCH_OF_THE_MYREQUE;
        enumC0000aArr[lIlIIIlllIIlI[72]] = QUEST_JUNGLE_POTION;
        enumC0000aArr[lIlIIIlllIIlI[74]] = QUEST_LEGENDS_QUEST;
        enumC0000aArr[lIlIIIlllIIlI[76]] = QUEST_LOST_CITY;
        enumC0000aArr[lIlIIIlllIIlI[78]] = QUEST_MERLINS_CRYSTAL;
        enumC0000aArr[lIlIIIlllIIlI[79]] = QUEST_MONKEY_MADNESS_I;
        enumC0000aArr[lIlIIIlllIIlI[81]] = QUEST_MONKS_FRIEND;
        enumC0000aArr[lIlIIIlllIIlI[82]] = QUEST_MOURNINGS_END_PART_I;
        enumC0000aArr[lIlIIIlllIIlI[84]] = QUEST_MURDER_MYSTERY;
        enumC0000aArr[lIlIIIlllIIlI[86]] = QUEST_NATURE_SPIRIT;
        enumC0000aArr[lIlIIIlllIIlI[88]] = QUEST_OBSERVATORY_QUEST;
        enumC0000aArr[lIlIIIlllIIlI[90]] = QUEST_ONE_SMALL_FAVOUR;
        enumC0000aArr[lIlIIIlllIIlI[92]] = QUEST_PLAGUE_CITY;
        enumC0000aArr[lIlIIIlllIIlI[94]] = QUEST_PRIEST_IN_PERIL;
        enumC0000aArr[lIlIIIlllIIlI[96]] = QUEST_RAG_AND_BONE_MAN_I;
        enumC0000aArr[lIlIIIlllIIlI[98]] = QUEST_REGICIDE;
        enumC0000aArr[lIlIIIlllIIlI[100]] = QUEST_ROVING_ELVES;
        enumC0000aArr[lIlIIIlllIIlI[102]] = QUEST_RUM_DEAL;
        enumC0000aArr[lIlIIIlllIIlI[104]] = QUEST_SCORPION_CATCHER;
        enumC0000aArr[lIlIIIlllIIlI[106]] = QUEST_SEA_SLUG;
        enumC0000aArr[lIlIIIlllIIlI[108]] = QUEST_SHADES_OF_MORTTON;
        enumC0000aArr[lIlIIIlllIIlI[110]] = QUEST_SHEEP_HERDER;
        enumC0000aArr[lIlIIIlllIIlI[111]] = QUEST_SHILO_VILLAGE;
        enumC0000aArr[lIlIIIlllIIlI[113]] = QUEST_TAI_BWO_WANNAI_TRIO;
        enumC0000aArr[lIlIIIlllIIlI[23]] = QUEST_TEMPLE_OF_IKOV;
        enumC0000aArr[lIlIIIlllIIlI[115]] = QUEST_THRONE_OF_MISCELLANIA;
        enumC0000aArr[lIlIIIlllIIlI[58]] = QUEST_THE_TOURIST_TRAP;
        enumC0000aArr[lIlIIIlllIIlI[118]] = QUEST_WITCHS_HOUSE;
        enumC0000aArr[lIlIIIlllIIlI[33]] = QUEST_TREE_GNOME_VILLAGE;
        enumC0000aArr[lIlIIIlllIIlI[37]] = QUEST_TRIBAL_TOTEM;
        enumC0000aArr[lIlIIIlllIIlI[122]] = QUEST_TROLL_ROMANCE;
        enumC0000aArr[lIlIIIlllIIlI[124]] = QUEST_TROLL_STRONGHOLD;
        enumC0000aArr[lIlIIIlllIIlI[15]] = QUEST_UNDERGROUND_PASS;
        enumC0000aArr[lIlIIIlllIIlI[127]] = QUEST_UNDERGROUND_PASS_STATE_162;
        enumC0000aArr[lIlIIIlllIIlI[129]] = QUEST_WATCHTOWER;
        enumC0000aArr[lIlIIIlllIIlI[131]] = QUEST_THE_GREAT_BRAIN_ROBBERY;
        enumC0000aArr[lIlIIIlllIIlI[133]] = QUEST_RAG_AND_BONE_MAN_II;
        enumC0000aArr[lIlIIIlllIIlI[105]] = QUEST_ENTER_THE_ABYSS;
        enumC0000aArr[lIlIIIlllIIlI[135]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL;
        enumC0000aArr[lIlIIIlllIIlI[136]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
        enumC0000aArr[lIlIIIlllIIlI[137]] = QUEST_THE_MAGE_ARENA;
        $VALUES = enumC0000aArr;
    }

    private EnumC0000a(String str, int i, int i2) {
        this.id = i2;
    }

    public int d() {
        return this.id;
    }

    public static EnumC0000a valueOf(String str) {
        return (EnumC0000a) Enum.valueOf(EnumC0000a.class, str);
    }

    private static void lIlllIIIlIIIlII() {
        lIlIIIllIIIII = new String[lIlIIIlllIIlI[48]];
        lIlIIIllIIIII[lIlIIIlllIIlI[0]] = lIlllIIIIIlIlII("HSwnOjgTOy4oLwcmKSclCzE2OjMKNjA9PgkqMQ==", "Lybil");
        lIlIIIllIIIII[lIlIIIlllIIlI[2]] = lIlllIIIIIlIlIl("SXNoebbI9nL0eCfZFHXcYSPdUX16Djec", "CtNvt");
        lIlIIIllIIIII[lIlIIIlllIIlI[4]] = lIlllIIIIIlIlII("IBEQJAwuABolETIXCiYNNBcB", "qDUwX");
        lIlIIIllIIIII[lIlIIIlllIIlI[6]] = lIlllIIIIIlIlIl("XFa8+7cFxK7Iqy10P+3gPkpnT4GS7mrv", "ILHxB");
        lIlIIIllIIIII[lIlIIIlllIIlI[8]] = lIlllIIIIIlIlIl("tNT+kVMhCsUmMMq/7EgB7PnutXX9CGDjcReKg+2Qd1o=", "EVeIp");
        lIlIIIllIIIII[lIlIIIlllIIlI[10]] = lIlllIIIIIlIlII("GD0MGwAWIQQYCwopHQscDDo=", "IhIHT");
        lIlIIIllIIIII[lIlIIIlllIIlI[12]] = lIlllIIIIIlIllI("jo2Higy5IpVhEwrl7+l/sukaU9kal3X9", "UJDik");
        lIlIIIllIIIII[lIlIIIlllIIlI[14]] = lIlllIIIIIlIlII("KBw2ADcmGToBIi0MIAw3KwwyADYrDA==", "yIsSc");
        lIlIIIllIIIII[lIlIIIlllIIlI[16]] = lIlllIIIIIlIllI("xpms7u09Fug3RJYJ1YcgX7TcqUwVeP7M", "ENhUi");
        lIlIIIllIIIII[lIlIIIlllIIlI[18]] = lIlllIIIIIlIllI("H4bK2et2k2ZftEi7qiaHGDTLPdJkBkeZHlDac3e7Ehw=", "XLeXE");
        lIlIIIllIIIII[lIlIIIlllIIlI[20]] = lIlllIIIIIlIlII("Nhc/GCE4EDUGMCgdOwUxOAgvBzwiFg==", "gBzKu");
        lIlIIIllIIIII[lIlIIIlllIIlI[22]] = lIlllIIIIIlIlIl("7DqpLmAbbooIn3bzffRzgJID6Cpgy59U", "HBZZN");
        lIlIIIllIIIII[lIlIIIlllIIlI[24]] = lIlllIIIIIlIllI("sOpoRp86645oG8gaPamC8A5Gf5E/B1KE", "QGHbA");
        lIlIIIllIIIII[lIlIIIlllIIlI[26]] = lIlllIIIIIlIlIl("qBzp3/PP7c0HivwKmaGvTPnm4+o6eNDa", "kOKAp");
        lIlIIIllIIIII[lIlIIIlllIIlI[28]] = lIlllIIIIIlIllI("esYs/pIfDc+7BwYRhPedAX7YBRDZTA1R+ij5aR2cdDw=", "iTUQS");
        lIlIIIllIIIII[lIlIIIlllIIlI[30]] = lIlllIIIIIlIlIl("BaBPTSPEBKM43Wy6VfnXw0I7DM6jsCm8", "eWugh");
        lIlIIIllIIIII[lIlIIIlllIIlI[32]] = lIlllIIIIIlIllI("3sn+dHd8gFUkafuhUUxFEwvS/a7JZaXU", "oEeGJ");
        lIlIIIllIIIII[lIlIIIlllIIlI[34]] = lIlllIIIIIlIllI("s8bSOc2+Z5kRyNLusgIKU9jGBOaygALZNSnCI6/lz+I=", "DbTbH");
        lIlIIIllIIIII[lIlIIIlllIIlI[36]] = lIlllIIIIIlIlII("GBwAABAWCwwcDAgTBAEA", "IIESD");
        lIlIIIllIIIII[lIlIIIlllIIlI[38]] = lIlllIIIIIlIlIl("hgbAvGFs3mn/pg/1iAPz6bvxoijRKKvu", "EVphN");
        lIlIIIllIIIII[lIlIIIlllIIlI[40]] = lIlllIIIIIlIlIl("mycnnNH0167NbxPaNPorbiIppG14hYrk", "xtFjw");
        lIlIIIllIIIII[lIlIIIlllIIlI[41]] = lIlllIIIIIlIlIl("fliF2JrQ7use/0p1K1vHL0nTaaWfYKXFODqvnPtfiUQ=", "rEYNB");
        lIlIIIllIIIII[lIlIIIlllIIlI[43]] = lIlllIIIIIlIlIl("4ZDEJL1COV1Mb9vzN5FUbZ+MlTacnGeb", "RJxuj");
        lIlIIIllIIIII[lIlIIIlllIIlI[45]] = lIlllIIIIIlIllI("2cqJIQmiqn8IpxsEvPHR504hYPJ5Q8sn", "plahC");
        lIlIIIllIIIII[lIlIIIlllIIlI[47]] = lIlllIIIIIlIlIl("tBIUQWT2W5OWPDnjVmGoNLoNYng0oqu2", "mDWxl");
        lIlIIIllIIIII[lIlIIIlllIIlI[49]] = lIlllIIIIIlIlIl("0b778iQiBzcUS9i2BjZaAdTo1w/lL5qH", "cegrf");
        lIlIIIllIIIII[lIlIIIlllIIlI[50]] = lIlllIIIIIlIlIl("1T7kbTzLgoJlvkFawF5LjAH7IPuoj69y", "tAHTn");
        lIlIIIllIIIII[lIlIIIlllIIlI[52]] = lIlllIIIIIlIllI("kqjcSlmaaDYG6prwulkRLh7qMboJRRyg02ALxojT2DA=", "CEBkG");
        lIlIIIllIIIII[lIlIIIlllIIlI[54]] = lIlllIIIIIlIllI("+OvtKBZBOq33EonXZA0OPKWamQOC2eUn", "FcTKu");
        lIlIIIllIIIII[lIlIIIlllIIlI[3]] = lIlllIIIIIlIlII("PzQPCRoxJwMdBjo+CwgLICA=", "naJZN");
        lIlIIIllIIIII[lIlIIIlllIIlI[56]] = lIlllIIIIIlIllI("w8Op+9qswqE9hYFsVlKkxfByDVtdr4Fb", "BbPog");
        lIlIIIllIIIII[lIlIIIlllIIlI[5]] = lIlllIIIIIlIllI("CgLHmhDDRMYc+GpxrQ0s467AST+EKFlumrpq8xS8lCA=", "CCwTP");
        lIlIIIllIIIII[lIlIIIlllIIlI[9]] = lIlllIIIIIlIlIl("wOtPVp8jlMb8Xx8+xwdnAbkf/F8IBmqC", "EgNnq");
        lIlIIIllIIIII[lIlIIIlllIIlI[59]] = lIlllIIIIIlIlII("EC0kHAMePyQdAxMtJQoEHjsgGw==", "AxaOW");
        lIlIIIllIIIII[lIlIIIlllIIlI[61]] = lIlllIIIIIlIlIl("Yc5FQln+dJDRIhMkbA/T2Z+kcq7y1whj", "uVXqg");
        lIlIIIllIIIII[lIlIIIlllIIlI[63]] = lIlllIIIIIlIlII("ADoPBgQOJwsAHgUqDgodGCEP", "QoJUP");
        lIlIIIllIIIII[lIlIIIlllIIlI[65]] = lIlllIIIIIlIllI("5hE+pF7o98lhngaTx3NZjtSC7aPjozv5", "UNROl");
        lIlIIIllIIIII[lIlIIIlllIIlI[67]] = lIlllIIIIIlIlII("PCwcBCEyMRwFOigqBgYgKCoN", "myYWu");
        lIlIIIllIIIII[lIlIIIlllIIlI[69]] = lIlllIIIIIlIllI("14iZnZuM3RDq040wLljPx7dp8S/8vKeo", "ehwcG");
        lIlIIIllIIIII[lIlIIIlllIIlI[70]] = lIlllIIIIIlIlII("FxsAESwZBwsdKwMPFwEwGQEDHSwOCxoPIRQLFBc9", "FNEBx");
        lIlIIIllIIIII[lIlIIIlllIIlI[72]] = lIlllIIIIIlIlII("HxoXHRARBQcAAwIKDR4LGgYdAA==", "NORND");
        lIlIIIllIIIII[lIlIIIlllIIlI[74]] = lIlllIIIIIlIlIl("4kqFEUPz7AUnsTSDkYBAyiFrgoOT+aIV", "leLym");
        lIlIIIllIIIII[lIlIIIlllIIlI[76]] = lIlllIIIIIlIlIl("/DgNq28zaC8Hdr0HG7NSww==", "RSdRv");
        lIlIIIllIIIII[lIlIIIlllIIlI[78]] = lIlllIIIIIlIlIl("JoRPAoTlQizIqc2orKLRV1E4fCRes0NM", "jEiQC");
        lIlIIIllIIIII[lIlIIIlllIIlI[79]] = lIlllIIIIIlIlII("ATw3Ph4PJD0jARUwLSALFCc3PhkPIA==", "PirmJ");
        lIlIIIllIIIII[lIlIIIlllIIlI[81]] = lIlllIIIIIlIlII("OQQgIiE3HCo/PjsOIyM8LR8h", "hQequ");
        lIlIIIllIIIII[lIlIIIlllIIlI[82]] = lIlllIIIIIlIllI("aDIhaKT9KOd7qK2yNVsFiH1bYX4KodJDuQ+TyS1k5D0=", "tRWeW");
        lIlIIIllIIIII[lIlIIIlllIIlI[84]] = lIlllIIIIIlIlII("CwcoGyYFHzgaNh8AMgUrCQYoGis=", "ZRmHr");
        lIlIIIllIIIII[lIlIIIlllIIlI[86]] = lIlllIIIIIlIlIl("m0U6Qf2VE3TPiJLREOeVi7EraC47tlCh", "wZgrq");
        lIlIIIllIIIII[lIlIIIlllIIlI[88]] = lIlllIIIIIlIllI("OP53vSe5clfu78nSDu8ccVxRDtIy8wyw", "PSKlX");
        lIlIIIllIIIII[lIlIIIlllIIlI[90]] = lIlllIIIIIlIlII("KQYdITEnHBY3OiseGT4pJxUZJCotAQ==", "xSXre");
        lIlIIIllIIIII[lIlIIIlllIIlI[92]] = lIlllIIIIIlIlIl("6yEsjaeSmqVP0YsJjXkg/p6dQARFdSxi", "PONmb");
        lIlIIIllIIIII[lIlIIIlllIIlI[94]] = lIlllIIIIIlIlIl("o9fzZ+DrYgvJokeqAaGUTp4LSjXmhdgJ", "zYcsP");
        lIlIIIllIIIII[lIlIIIlllIIlI[96]] = lIlllIIIIIlIlIl("6FTt4dJUqM4SJZSzTZTT9p7wMZatuJn69HBqc04qNYI=", "hMhwA");
        lIlIIIllIIIII[lIlIIIlllIIlI[98]] = lIlllIIIIIlIllI("Cn8mFAlzYkLk7pEH/m+OiA==", "lFPvr");
        lIlIIIllIIIII[lIlIIIlllIIlI[100]] = lIlllIIIIIlIlIl("PIFLlwHwGXsGnT//md36kUrDKWC+0b1B", "FNFyb");
        lIlIIIllIIIII[lIlIIIlllIIlI[102]] = lIlllIIIIIlIlIl("l5GhWxtbI4B3F3w87OAepw==", "jXdSD");
        lIlIIIllIIIII[lIlIIIlllIIlI[104]] = lIlllIIIIIlIlIl("1AgvREYVTQRkZUSP5rwNVYQl/Pjn9RC7", "ZzTZo");
        lIlIIIllIIIII[lIlIIIlllIIlI[106]] = lIlllIIIIIlIlII("KRAvIRUnFi8zHisJPzU=", "xEjrA");
        lIlIIIllIIIII[lIlIIIlllIIlI[108]] = lIlllIIIIIlIllI("GJ/oC5+o5iVIhka21ys9rZl4Z0Me3GA7", "qgoOo");
        lIlIIIllIIIII[lIlIIIlllIIlI[110]] = lIlllIIIIIlIllI("52fwpE6TiNZAc8J8OX4b8uZ3DzcbYRA7", "LKAdt");
        lIlIIIllIIIII[lIlIIIlllIIlI[111]] = lIlllIIIIIlIlIl("V9ohmKjoROSgo+aCuY1UX9k53xxOgnk3", "sPzDA");
        lIlIIIllIIIII[lIlIIIlllIIlI[113]] = lIlllIIIIIlIllI("k7f2vLbDjNZQTgLrMSl2mywEjFPKs/WshUmzJ1MrsAE=", "GElpk");
        lIlIIIllIIIII[lIlIIIlllIIlI[23]] = lIlllIIIIIlIlIl("n6a5l69/UTQ63pWTJgS4VzPP8a3q1wdI", "bbeKJ");
        lIlIIIllIIIII[lIlIIIlllIIlI[115]] = lIlllIIIIIlIlIl("hSY2t05JLO6Vtbs8XxNL2ognhgeB6Hg2CWgE42UvpN4=", "PcACj");
        lIlIIIllIIIII[lIlIIIlllIIlI[58]] = lIlllIIIIIlIlII("CDksFRMGOCEDGA0jPBQOCjg2EhUYPA==", "YliFG");
        lIlIIIllIIIII[lIlIIIlllIIlI[118]] = lIlllIIIIIlIlII("OgAuJgw0AiIhGyMGND0XPgYu", "kUkuX");
        lIlIIIllIIIII[lIlIIIlllIIlI[33]] = lIlllIIIIIlIlII("Gi8IMQ0ULh8nHBQ9Ay0UDiUbKxUHOwon", "KzMbY");
        lIlIIIllIIIII[lIlIIIlllIIlI[37]] = lIlllIIIIIlIllI("TIRw/0jWkpJ7porJSrLtA18bRN+SKUMD", "KHPrN");
        lIlIIIllIIIII[lIlIIIlllIIlI[122]] = lIlllIIIIIlIlII("BCwJBB8KLR4YBxkmHhgGFDcPEg==", "UyLWK");
        lIlIIIllIIIII[lIlIIIlllIIlI[124]] = lIlllIIIIIlIlIl("CST8CoJX1lvf8DHWDnshReuvrjxtKjd5", "uZaaH");
        lIlIIIllIIIII[lIlIIIlllIIlI[15]] = lIlllIIIIIlIlIl("+37J4UXD+5ptRi5R9TvyWkZqlUaUtMdj", "LLzRm");
        lIlIIIllIIIII[lIlIIIlllIIlI[127]] = lIlllIIIIIlIlII("KRwUGTonHB8OKyoOAwU7Ng0OGi8rGg4ZOjkdFBVfTns=", "xIQJn");
        lIlIIIllIIIII[lIlIIIlllIIlI[129]] = lIlllIIIIIlIlII("IDAzGR4uMjceCTkxOR0PIw==", "qevJJ");
        lIlIIIllIIIII[lIlIIIlllIIlI[131]] = lIlllIIIIIlIlII("HR0LFhkTHAYAEgsaCwQZEwocBAQCFxwKDw4NHBw=", "LHNEM");
        lIlIIIllIIIII[lIlIIIlllIIlI[133]] = lIlllIIIIIlIlIl("4maFzM3Yvqauyaw6XTK1UqobpMxlMHoaCl5fDOS7d+w=", "xzxIe");
        lIlIIIllIIIII[lIlIIIlllIIlI[105]] = lIlllIIIIIlIlII("JDctBjcqJyYBJic9PB0mKiMqDDAm", "ubhUc");
        lIlIIIllIIIII[lIlIIIlllIIlI[135]] = lIlllIIIIIlIlIl("AaCvooMkk3RDim7tHmblNXXc4svgOMlltr4KMNK+66o=", "ObApS");
        lIlIIIllIIIII[lIlIIIlllIIlI[136]] = lIlllIIIIIlIllI("j5DrMdI8MCH2IOrF0e7YwLzLXt3OEvtc5LHwN87Nf2WbzzzQFi2tsE+BWlqV6LhW", "lRNEZ");
        lIlIIIllIIIII[lIlIIIlllIIlI[137]] = lIlllIIIIIlIlII("ICYONx8uJwMhFDwyDCEUMCEOKgo=", "qsKdK");
    }

    private static String lIlllIIIIIlIllI(String llllllllllllllIlllIIIIllllIIllll, String llllllllllllllIlllIIIIllllIIlllI) {
        try {
            SecretKeySpec secretKeySpec = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(llllllllllllllIlllIIIIllllIIlllI.getBytes(StandardCharsets.UTF_8)), lIlIIIlllIIlI[16]), "DES");
            Cipher llllllllllllllIlllIIIIllllIlIIIl = Cipher.getInstance("DES");
            llllllllllllllIlllIIIIllllIlIIIl.init(lIlIIIlllIIlI[4], secretKeySpec);
            return new String(llllllllllllllIlllIIIIllllIlIIIl.doFinal(Base64.getDecoder().decode(llllllllllllllIlllIIIIllllIIllll.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        } catch (Exception llllllllllllllIlllIIIIllllIlIIII) {
            llllllllllllllIlllIIIIllllIlIIII.printStackTrace();
            return null;
        }
    }

    private static String lIlllIIIIIlIlIl(String llllllllllllllIlllIIIIllllllIlII, String llllllllllllllIlllIIIIllllllIIll) {
        try {
            SecretKeySpec llllllllllllllIlllIIIIllllllIlll = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(llllllllllllllIlllIIIIllllllIIll.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher cipher = Cipher.getInstance("Blowfish");
            cipher.init(lIlIIIlllIIlI[4], llllllllllllllIlllIIIIllllllIlll);
            return new String(cipher.doFinal(Base64.getDecoder().decode(llllllllllllllIlllIIIIllllllIlII.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        } catch (Exception llllllllllllllIlllIIIIllllllIlIl) {
            llllllllllllllIlllIIIIllllllIlIl.printStackTrace();
            return null;
        }
    }

    private static boolean lIlllIIIlIIIllI(int i, int i2) {
        return i < i2;
    }
}
