/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.51c4371d-854c-4c1b-8841-207ed7d6bdc3.tasks;

public class FHelper {
    public static final  int aD;
    public static final  int aJ;
    public static final  int ai;
    public static final  int[] ba;
    public static final  int av;
    public static final  int[] bi;
    public static final  int ao;
    public static final  int[] bd;
    public static final  int[] bf;
    public static final  int aP;
    public static final  int aI;
    public static final  int aK;
    public static final  int az;
    public static final  int aQ;
    public static final  int aE;
    public static final  int[] bb;
    public static final  int[] aT;
    public static final  int an;
    public static final  int au;
    public static final  int[] bn;
    public static final  int[] bk;
    public static final  int[] aS;
    public static final  int al;
    public static final  int[] bj;
    public static final  int aA;
    public static final  int aN;
    public static final  int aF;
    public static final  int[] bc;
    public static final  int[] aX;
    public static final  int as;
    public static final  int[] aU;
    public static final  int[] bg;
    public static final  int am;
    public static final  int ak;
    public static final  int[] be;
    public static final  int ar;
    public static final  int ay;
    public static final  int[] aZ;
    public static final  int aw;
    public static final  int at;
    public static final  int[] aV;
    public static final  int ap;
    
    public static final  int aG;
    public static final  int aR;
    public static final  int[] aY;
    public static final  int aq;
    public static final  int[] bl;
    public static final  int aC;
    public static final  int[] bm;
    public static final  int aB;
    public static final  int aL;
    public static final  int ax;
    public static final  int aM;
    public static final  int aO;
    public static final  int[] bh;
    public static final  int aH;
    public static final  int aj;
    public static final  int[] aW;

    static {
        f.lIlIIlIllll();
        aG = llIIlIII[0];
        aj = llIIlIII[1];
        an = llIIlIII[2];
        ay = llIIlIII[3];
        aL = llIIlIII[4];
        aO = llIIlIII[5];
        at = llIIlIII[6];
        aQ = llIIlIII[7];
        aw = llIIlIII[8];
        aN = llIIlIII[9];
        aM = llIIlIII[10];
        ao = llIIlIII[11];
        ai = llIIlIII[12];
        aJ = llIIlIII[13];
        ak = llIIlIII[14];
        au = llIIlIII[15];
        aB = llIIlIII[16];
        aH = llIIlIII[17];
        aq = llIIlIII[18];
        ax = llIIlIII[19];
        aF = llIIlIII[20];
        aK = llIIlIII[21];
        aP = llIIlIII[22];
        aR = llIIlIII[23];
        aI = llIIlIII[24];
        aE = llIIlIII[25];
        al = llIIlIII[26];
        ap = llIIlIII[27];
        aD = llIIlIII[28];
        am = llIIlIII[29];
        az = llIIlIII[30];
        as = llIIlIII[31];
        ar = llIIlIII[32];
        aA = llIIlIII[33];
        av = llIIlIII[34];
        aC = llIIlIII[35];
        int[] nArray = new int[llIIlIII[36]];
        nArray[f.llIIlIII[35]] = llIIlIII[2];
        nArray[f.llIIlIII[37]] = llIIlIII[11];
        nArray[f.llIIlIII[38]] = llIIlIII[7];
        aS = nArray;
        int[] nArray2 = new int[llIIlIII[39]];
        nArray2[f.llIIlIII[35]] = llIIlIII[27];
        nArray2[f.llIIlIII[37]] = llIIlIII[40];
        nArray2[f.llIIlIII[38]] = llIIlIII[41];
        nArray2[f.llIIlIII[36]] = llIIlIII[42];
        nArray2[f.llIIlIII[43]] = llIIlIII[44];
        nArray2[f.llIIlIII[45]] = llIIlIII[46];
        nArray2[f.llIIlIII[47]] = llIIlIII[48];
        nArray2[f.llIIlIII[49]] = llIIlIII[50];
        aT = nArray2;
        int[] nArray3 = new int[llIIlIII[51]];
        nArray3[f.llIIlIII[35]] = llIIlIII[52];
        nArray3[f.llIIlIII[37]] = llIIlIII[53];
        nArray3[f.llIIlIII[38]] = llIIlIII[54];
        nArray3[f.llIIlIII[36]] = llIIlIII[55];
        nArray3[f.llIIlIII[43]] = llIIlIII[56];
        nArray3[f.llIIlIII[45]] = llIIlIII[57];
        nArray3[f.llIIlIII[47]] = llIIlIII[58];
        nArray3[f.llIIlIII[49]] = llIIlIII[59];
        nArray3[f.llIIlIII[39]] = llIIlIII[59];
        aU = nArray3;
        int[] nArray4 = new int[llIIlIII[43]];
        nArray4[f.llIIlIII[35]] = llIIlIII[60];
        nArray4[f.llIIlIII[37]] = llIIlIII[61];
        nArray4[f.llIIlIII[38]] = llIIlIII[62];
        nArray4[f.llIIlIII[36]] = llIIlIII[63];
        aV = nArray4;
        int[] nArray5 = new int[llIIlIII[43]];
        nArray5[f.llIIlIII[35]] = llIIlIII[64];
        nArray5[f.llIIlIII[37]] = llIIlIII[65];
        nArray5[f.llIIlIII[38]] = llIIlIII[66];
        nArray5[f.llIIlIII[36]] = llIIlIII[67];
        aW = nArray5;
        int[] nArray6 = new int[llIIlIII[47]];
        nArray6[f.llIIlIII[35]] = llIIlIII[68];
        nArray6[f.llIIlIII[37]] = llIIlIII[69];
        nArray6[f.llIIlIII[38]] = llIIlIII[70];
        nArray6[f.llIIlIII[36]] = llIIlIII[71];
        nArray6[f.llIIlIII[43]] = llIIlIII[22];
        nArray6[f.llIIlIII[45]] = llIIlIII[72];
        aX = nArray6;
        int[] nArray7 = new int[llIIlIII[43]];
        nArray7[f.llIIlIII[35]] = llIIlIII[73];
        nArray7[f.llIIlIII[37]] = llIIlIII[74];
        nArray7[f.llIIlIII[38]] = llIIlIII[75];
        nArray7[f.llIIlIII[36]] = llIIlIII[76];
        aY = nArray7;
        int[] nArray8 = new int[llIIlIII[43]];
        nArray8[f.llIIlIII[35]] = llIIlIII[77];
        nArray8[f.llIIlIII[37]] = llIIlIII[78];
        nArray8[f.llIIlIII[38]] = llIIlIII[79];
        nArray8[f.llIIlIII[36]] = llIIlIII[80];
        aZ = nArray8;
        int[] nArray9 = new int[llIIlIII[36]];
        nArray9[f.llIIlIII[35]] = llIIlIII[77];
        nArray9[f.llIIlIII[37]] = llIIlIII[78];
        nArray9[f.llIIlIII[38]] = llIIlIII[79];
        ba = nArray9;
        int[] nArray10 = new int[llIIlIII[43]];
        nArray10[f.llIIlIII[35]] = llIIlIII[81];
        nArray10[f.llIIlIII[37]] = llIIlIII[82];
        nArray10[f.llIIlIII[38]] = llIIlIII[83];
        nArray10[f.llIIlIII[36]] = llIIlIII[84];
        bb = nArray10;
        int[] nArray11 = new int[llIIlIII[43]];
        nArray11[f.llIIlIII[35]] = llIIlIII[85];
        nArray11[f.llIIlIII[37]] = llIIlIII[86];
        nArray11[f.llIIlIII[38]] = llIIlIII[87];
        nArray11[f.llIIlIII[36]] = llIIlIII[88];
        bc = nArray11;
        int[] nArray12 = new int[llIIlIII[43]];
        nArray12[f.llIIlIII[35]] = llIIlIII[89];
        nArray12[f.llIIlIII[37]] = llIIlIII[90];
        nArray12[f.llIIlIII[38]] = llIIlIII[91];
        nArray12[f.llIIlIII[36]] = llIIlIII[92];
        bd = nArray12;
        int[] nArray13 = new int[llIIlIII[43]];
        nArray13[f.llIIlIII[35]] = llIIlIII[93];
        nArray13[f.llIIlIII[37]] = llIIlIII[94];
        nArray13[f.llIIlIII[38]] = llIIlIII[95];
        nArray13[f.llIIlIII[36]] = llIIlIII[96];
        be = nArray13;
        int[] nArray14 = new int[llIIlIII[43]];
        nArray14[f.llIIlIII[35]] = llIIlIII[97];
        nArray14[f.llIIlIII[37]] = llIIlIII[98];
        nArray14[f.llIIlIII[38]] = llIIlIII[99];
        nArray14[f.llIIlIII[36]] = llIIlIII[100];
        bf = nArray14;
        int[] nArray15 = new int[llIIlIII[45]];
        nArray15[f.llIIlIII[35]] = llIIlIII[101];
        nArray15[f.llIIlIII[37]] = llIIlIII[102];
        nArray15[f.llIIlIII[38]] = llIIlIII[103];
        nArray15[f.llIIlIII[36]] = llIIlIII[104];
        nArray15[f.llIIlIII[43]] = llIIlIII[105];
        bg = nArray15;
        int[] nArray16 = new int[llIIlIII[43]];
        nArray16[f.llIIlIII[35]] = llIIlIII[106];
        nArray16[f.llIIlIII[37]] = llIIlIII[107];
        nArray16[f.llIIlIII[38]] = llIIlIII[108];
        nArray16[f.llIIlIII[36]] = llIIlIII[109];
        bh = nArray16;
        int[] nArray17 = new int[llIIlIII[43]];
        nArray17[f.llIIlIII[35]] = llIIlIII[110];
        nArray17[f.llIIlIII[37]] = llIIlIII[111];
        nArray17[f.llIIlIII[38]] = llIIlIII[112];
        nArray17[f.llIIlIII[36]] = llIIlIII[113];
        bi = nArray17;
        int[] nArray18 = new int[llIIlIII[43]];
        nArray18[f.llIIlIII[35]] = llIIlIII[114];
        nArray18[f.llIIlIII[37]] = llIIlIII[115];
        nArray18[f.llIIlIII[38]] = llIIlIII[116];
        nArray18[f.llIIlIII[36]] = llIIlIII[117];
        bj = nArray18;
        int[] nArray19 = new int[llIIlIII[36]];
        nArray19[f.llIIlIII[35]] = llIIlIII[13];
        nArray19[f.llIIlIII[37]] = llIIlIII[24];
        nArray19[f.llIIlIII[38]] = llIIlIII[17];
        bk = nArray19;
        int[] nArray20 = new int[llIIlIII[45]];
        nArray20[f.llIIlIII[35]] = llIIlIII[18];
        nArray20[f.llIIlIII[37]] = llIIlIII[118];
        nArray20[f.llIIlIII[38]] = llIIlIII[119];
        nArray20[f.llIIlIII[36]] = llIIlIII[120];
        nArray20[f.llIIlIII[43]] = llIIlIII[121];
        bl = nArray20;
        int[] nArray21 = new int[llIIlIII[36]];
        nArray21[f.llIIlIII[35]] = llIIlIII[122];
        nArray21[f.llIIlIII[37]] = llIIlIII[123];
        nArray21[f.llIIlIII[38]] = llIIlIII[124];
        bm = nArray21;
        int[] nArray22 = new int[llIIlIII[43]];
        nArray22[f.llIIlIII[35]] = llIIlIII[125];
        nArray22[f.llIIlIII[37]] = llIIlIII[126];
        nArray22[f.llIIlIII[38]] = llIIlIII[127];
        nArray22[f.llIIlIII[36]] = llIIlIII[128];
        bn = nArray22;
    }
}

