/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.d1f9e3af-c0a5-49dd-86b2-8e857984fef3.tasks;

public class FHelper {
    public static final  int ai;
    public static final  int[] aP;
    public static final  int[] bf;
    public static final  int aB;
    public static final  int aj;
    public static final  int aw;
    public static final  int ad;
    public static final  int[] aX;
    public static final  int ae;
    public static final  int[] bg;
    public static final  int ah;
    public static final  int ac;
    public static final  int ag;
    
    public static final  int af;
    public static final  int aH;
    public static final  int ap;
    public static final  int ay;
    public static final  int aG;
    public static final  int ao;
    public static final  int[] aV;
    public static final  int at;
    public static final  int[] aW;
    public static final  int au;
    public static final  int ax;
    public static final  int an;
    public static final  int[] ba;
    public static final  int aF;
    public static final  int[] bb;
    public static final  int[] aS;
    public static final  int aL;
    public static final  int aK;
    public static final  int ak;
    public static final  int[] bh;
    public static final  int az;
    public static final  int al;
    public static final  int aE;
    public static final  int aq;
    public static final  int[] aT;
    public static final  int[] aY;
    public static final  int[] aO;
    public static final  int aJ;
    public static final  int av;
    public static final  int[] aN;
    public static final  int aA;
    public static final  int ar;
    public static final  int aC;
    public static final  int as;
    public static final  int[] aU;
    public static final  int aI;
    public static final  int aD;
    public static final  int[] bd;
    public static final  int[] bc;
    public static final  int am;
    public static final  int[] aM;
    public static final  int[] aQ;
    public static final  int[] aR;
    public static final  int[] aZ;
    public static final  int[] be;

    static {
        f.lIIlIlIIllII();
        at = lIlIlllll[0];
        aq = lIlIlllll[1];
        aG = lIlIlllll[2];
        ay = lIlIlllll[3];
        aA = lIlIlllll[4];
        ai = lIlIlllll[5];
        aE = lIlIlllll[6];
        aF = lIlIlllll[7];
        an = lIlIlllll[8];
        ao = lIlIlllll[9];
        al = lIlIlllll[10];
        ax = lIlIlllll[11];
        af = lIlIlllll[12];
        aj = lIlIlllll[13];
        aH = lIlIlllll[14];
        ad = lIlIlllll[15];
        ae = lIlIlllll[16];
        aL = lIlIlllll[17];
        am = lIlIlllll[18];
        as = lIlIlllll[19];
        ap = lIlIlllll[20];
        aw = lIlIlllll[21];
        aK = lIlIlllll[22];
        az = lIlIlllll[23];
        aI = lIlIlllll[24];
        ah = lIlIlllll[25];
        ar = lIlIlllll[26];
        aD = lIlIlllll[27];
        aB = lIlIlllll[28];
        ag = lIlIlllll[29];
        ak = lIlIlllll[30];
        ac = lIlIlllll[31];
        av = lIlIlllll[32];
        aC = lIlIlllll[33];
        au = lIlIlllll[34];
        aJ = lIlIlllll[35];
        int[] nArray = new int[lIlIlllll[36]];
        nArray[f.lIlIlllll[21]] = lIlIlllll[25];
        nArray[f.lIlIlllll[37]] = lIlIlllll[5];
        nArray[f.lIlIlllll[38]] = lIlIlllll[22];
        aM = nArray;
        int[] nArray2 = new int[lIlIlllll[39]];
        nArray2[f.lIlIlllll[21]] = lIlIlllll[13];
        nArray2[f.lIlIlllll[37]] = lIlIlllll[40];
        nArray2[f.lIlIlllll[38]] = lIlIlllll[41];
        nArray2[f.lIlIlllll[36]] = lIlIlllll[42];
        nArray2[f.lIlIlllll[43]] = lIlIlllll[44];
        nArray2[f.lIlIlllll[45]] = lIlIlllll[46];
        nArray2[f.lIlIlllll[47]] = lIlIlllll[48];
        nArray2[f.lIlIlllll[49]] = lIlIlllll[50];
        aN = nArray2;
        int[] nArray3 = new int[lIlIlllll[51]];
        nArray3[f.lIlIlllll[21]] = lIlIlllll[52];
        nArray3[f.lIlIlllll[37]] = lIlIlllll[53];
        nArray3[f.lIlIlllll[38]] = lIlIlllll[54];
        nArray3[f.lIlIlllll[36]] = lIlIlllll[55];
        nArray3[f.lIlIlllll[43]] = lIlIlllll[56];
        nArray3[f.lIlIlllll[45]] = lIlIlllll[57];
        nArray3[f.lIlIlllll[47]] = lIlIlllll[58];
        nArray3[f.lIlIlllll[49]] = lIlIlllll[59];
        nArray3[f.lIlIlllll[39]] = lIlIlllll[59];
        aO = nArray3;
        int[] nArray4 = new int[lIlIlllll[43]];
        nArray4[f.lIlIlllll[21]] = lIlIlllll[60];
        nArray4[f.lIlIlllll[37]] = lIlIlllll[61];
        nArray4[f.lIlIlllll[38]] = lIlIlllll[62];
        nArray4[f.lIlIlllll[36]] = lIlIlllll[63];
        aP = nArray4;
        int[] nArray5 = new int[lIlIlllll[43]];
        nArray5[f.lIlIlllll[21]] = lIlIlllll[64];
        nArray5[f.lIlIlllll[37]] = lIlIlllll[65];
        nArray5[f.lIlIlllll[38]] = lIlIlllll[66];
        nArray5[f.lIlIlllll[36]] = lIlIlllll[67];
        aQ = nArray5;
        int[] nArray6 = new int[lIlIlllll[47]];
        nArray6[f.lIlIlllll[21]] = lIlIlllll[68];
        nArray6[f.lIlIlllll[37]] = lIlIlllll[69];
        nArray6[f.lIlIlllll[38]] = lIlIlllll[70];
        nArray6[f.lIlIlllll[36]] = lIlIlllll[71];
        nArray6[f.lIlIlllll[43]] = lIlIlllll[35];
        nArray6[f.lIlIlllll[45]] = lIlIlllll[72];
        aR = nArray6;
        int[] nArray7 = new int[lIlIlllll[43]];
        nArray7[f.lIlIlllll[21]] = lIlIlllll[73];
        nArray7[f.lIlIlllll[37]] = lIlIlllll[74];
        nArray7[f.lIlIlllll[38]] = lIlIlllll[75];
        nArray7[f.lIlIlllll[36]] = lIlIlllll[76];
        aS = nArray7;
        int[] nArray8 = new int[lIlIlllll[43]];
        nArray8[f.lIlIlllll[21]] = lIlIlllll[77];
        nArray8[f.lIlIlllll[37]] = lIlIlllll[78];
        nArray8[f.lIlIlllll[38]] = lIlIlllll[79];
        nArray8[f.lIlIlllll[36]] = lIlIlllll[80];
        aT = nArray8;
        int[] nArray9 = new int[lIlIlllll[36]];
        nArray9[f.lIlIlllll[21]] = lIlIlllll[77];
        nArray9[f.lIlIlllll[37]] = lIlIlllll[78];
        nArray9[f.lIlIlllll[38]] = lIlIlllll[79];
        aU = nArray9;
        int[] nArray10 = new int[lIlIlllll[43]];
        nArray10[f.lIlIlllll[21]] = lIlIlllll[81];
        nArray10[f.lIlIlllll[37]] = lIlIlllll[82];
        nArray10[f.lIlIlllll[38]] = lIlIlllll[83];
        nArray10[f.lIlIlllll[36]] = lIlIlllll[84];
        aV = nArray10;
        int[] nArray11 = new int[lIlIlllll[43]];
        nArray11[f.lIlIlllll[21]] = lIlIlllll[85];
        nArray11[f.lIlIlllll[37]] = lIlIlllll[86];
        nArray11[f.lIlIlllll[38]] = lIlIlllll[87];
        nArray11[f.lIlIlllll[36]] = lIlIlllll[88];
        aW = nArray11;
        int[] nArray12 = new int[lIlIlllll[43]];
        nArray12[f.lIlIlllll[21]] = lIlIlllll[89];
        nArray12[f.lIlIlllll[37]] = lIlIlllll[90];
        nArray12[f.lIlIlllll[38]] = lIlIlllll[91];
        nArray12[f.lIlIlllll[36]] = lIlIlllll[92];
        aX = nArray12;
        int[] nArray13 = new int[lIlIlllll[43]];
        nArray13[f.lIlIlllll[21]] = lIlIlllll[93];
        nArray13[f.lIlIlllll[37]] = lIlIlllll[94];
        nArray13[f.lIlIlllll[38]] = lIlIlllll[95];
        nArray13[f.lIlIlllll[36]] = lIlIlllll[96];
        aY = nArray13;
        int[] nArray14 = new int[lIlIlllll[43]];
        nArray14[f.lIlIlllll[21]] = lIlIlllll[97];
        nArray14[f.lIlIlllll[37]] = lIlIlllll[98];
        nArray14[f.lIlIlllll[38]] = lIlIlllll[99];
        nArray14[f.lIlIlllll[36]] = lIlIlllll[100];
        aZ = nArray14;
        int[] nArray15 = new int[lIlIlllll[45]];
        nArray15[f.lIlIlllll[21]] = lIlIlllll[101];
        nArray15[f.lIlIlllll[37]] = lIlIlllll[102];
        nArray15[f.lIlIlllll[38]] = lIlIlllll[103];
        nArray15[f.lIlIlllll[36]] = lIlIlllll[104];
        nArray15[f.lIlIlllll[43]] = lIlIlllll[105];
        ba = nArray15;
        int[] nArray16 = new int[lIlIlllll[43]];
        nArray16[f.lIlIlllll[21]] = lIlIlllll[106];
        nArray16[f.lIlIlllll[37]] = lIlIlllll[107];
        nArray16[f.lIlIlllll[38]] = lIlIlllll[108];
        nArray16[f.lIlIlllll[36]] = lIlIlllll[109];
        bb = nArray16;
        int[] nArray17 = new int[lIlIlllll[43]];
        nArray17[f.lIlIlllll[21]] = lIlIlllll[110];
        nArray17[f.lIlIlllll[37]] = lIlIlllll[111];
        nArray17[f.lIlIlllll[38]] = lIlIlllll[112];
        nArray17[f.lIlIlllll[36]] = lIlIlllll[113];
        bc = nArray17;
        int[] nArray18 = new int[lIlIlllll[43]];
        nArray18[f.lIlIlllll[21]] = lIlIlllll[114];
        nArray18[f.lIlIlllll[37]] = lIlIlllll[115];
        nArray18[f.lIlIlllll[38]] = lIlIlllll[116];
        nArray18[f.lIlIlllll[36]] = lIlIlllll[117];
        bd = nArray18;
        int[] nArray19 = new int[lIlIlllll[36]];
        nArray19[f.lIlIlllll[21]] = lIlIlllll[27];
        nArray19[f.lIlIlllll[37]] = lIlIlllll[33];
        nArray19[f.lIlIlllll[38]] = lIlIlllll[28];
        be = nArray19;
        int[] nArray20 = new int[lIlIlllll[45]];
        nArray20[f.lIlIlllll[21]] = lIlIlllll[30];
        nArray20[f.lIlIlllll[37]] = lIlIlllll[118];
        nArray20[f.lIlIlllll[38]] = lIlIlllll[119];
        nArray20[f.lIlIlllll[36]] = lIlIlllll[120];
        nArray20[f.lIlIlllll[43]] = lIlIlllll[121];
        bf = nArray20;
        int[] nArray21 = new int[lIlIlllll[36]];
        nArray21[f.lIlIlllll[21]] = lIlIlllll[122];
        nArray21[f.lIlIlllll[37]] = lIlIlllll[123];
        nArray21[f.lIlIlllll[38]] = lIlIlllll[124];
        bg = nArray21;
        int[] nArray22 = new int[lIlIlllll[43]];
        nArray22[f.lIlIlllll[21]] = lIlIlllll[125];
        nArray22[f.lIlIlllll[37]] = lIlIlllll[126];
        nArray22[f.lIlIlllll[38]] = lIlIlllll[127];
        nArray22[f.lIlIlllll[36]] = lIlIlllll[128];
        bh = nArray22;
    }

}

