/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.57051692-5fea-40a8-a012-903ac1ab23ac.tasks;

public class FHelper {
    public static final  int[] bf;
    public static final  int at;
    public static final  int[] aM;
    public static final  int az;
    public static final  int aA;
    public static final  int aD;
    public static final  int al;
    public static final  int ap;
    public static final  int[] be;
    public static final  int am;
    public static final  int aK;
    public static final  int aC;
    public static final  int[] aO;
    public static final  int ag;
    public static final  int aH;
    public static final  int[] bb;
    public static final  int ay;
    public static final  int[] aT;
    public static final  int ac;
    public static final  int ad;
    public static final  int[] aS;
    public static final  int aq;
    public static final  int[] aN;
    public static final  int aE;
    public static final  int aF;
    public static final  int[] bd;
    public static final  int[] aZ;
    public static final  int an;
    public static final  int[] aV;
    public static final  int ax;
    public static final  int[] aR;
    public static final  int ae;
    public static final  int aJ;
    public static final  int[] aX;
    public static final  int ah;
    public static final  int aI;
    public static final  int[] aU;
    public static final  int ak;
    public static final  int[] bg;
    public static final  int[] aP;
    public static final  int[] aQ;
    public static final  int ao;
    public static final  int[] aW;
    public static final  int[] bc;
    public static final  int ai;
    public static final  int ar;
    public static final  int av;
    public static final  int as;
    public static final  int af;
    public static final  int[] aL;
    
    public static final  int ab;
    public static final  int[] ba;
    public static final  int aB;
    public static final  int[] aY;
    public static final  int au;
    public static final  int aw;
    public static final  int aj;
    public static final  int aG;

    static {
        f.lIIllIIllIlll();
        aw = lIllIllIII[0];
        ax = lIllIllIII[1];
        at = lIllIllIII[2];
        ak = lIllIllIII[3];
        aD = lIllIllIII[4];
        am = lIllIllIII[5];
        aG = lIllIllIII[6];
        af = lIllIllIII[7];
        an = lIllIllIII[8];
        ah = lIllIllIII[9];
        aH = lIllIllIII[10];
        aB = lIllIllIII[11];
        aF = lIllIllIII[12];
        au = lIllIllIII[13];
        ap = lIllIllIII[14];
        ai = lIllIllIII[15];
        al = lIllIllIII[16];
        ao = lIllIllIII[17];
        aE = lIllIllIII[18];
        ar = lIllIllIII[19];
        ac = lIllIllIII[20];
        ad = lIllIllIII[21];
        aA = lIllIllIII[22];
        av = lIllIllIII[23];
        ab = lIllIllIII[24];
        aI = lIllIllIII[25];
        as = lIllIllIII[26];
        ag = lIllIllIII[27];
        ae = lIllIllIII[28];
        aK = lIllIllIII[29];
        aC = lIllIllIII[30];
        aJ = lIllIllIII[31];
        aj = lIllIllIII[32];
        aq = lIllIllIII[33];
        az = lIllIllIII[34];
        ay = lIllIllIII[35];
        int[] nArray = new int[lIllIllIII[36]];
        nArray[f.lIllIllIII[23]] = lIllIllIII[27];
        nArray[f.lIllIllIII[37]] = lIllIllIII[9];
        nArray[f.lIllIllIII[38]] = lIllIllIII[31];
        aL = nArray;
        int[] nArray2 = new int[lIllIllIII[39]];
        nArray2[f.lIllIllIII[23]] = lIllIllIII[15];
        nArray2[f.lIllIllIII[37]] = lIllIllIII[40];
        nArray2[f.lIllIllIII[38]] = lIllIllIII[41];
        nArray2[f.lIllIllIII[36]] = lIllIllIII[42];
        nArray2[f.lIllIllIII[43]] = lIllIllIII[44];
        nArray2[f.lIllIllIII[45]] = lIllIllIII[46];
        nArray2[f.lIllIllIII[47]] = lIllIllIII[48];
        nArray2[f.lIllIllIII[49]] = lIllIllIII[50];
        aM = nArray2;
        int[] nArray3 = new int[lIllIllIII[51]];
        nArray3[f.lIllIllIII[23]] = lIllIllIII[52];
        nArray3[f.lIllIllIII[37]] = lIllIllIII[53];
        nArray3[f.lIllIllIII[38]] = lIllIllIII[54];
        nArray3[f.lIllIllIII[36]] = lIllIllIII[55];
        nArray3[f.lIllIllIII[43]] = lIllIllIII[56];
        nArray3[f.lIllIllIII[45]] = lIllIllIII[57];
        nArray3[f.lIllIllIII[47]] = lIllIllIII[58];
        nArray3[f.lIllIllIII[49]] = lIllIllIII[59];
        nArray3[f.lIllIllIII[39]] = lIllIllIII[59];
        aN = nArray3;
        int[] nArray4 = new int[lIllIllIII[43]];
        nArray4[f.lIllIllIII[23]] = lIllIllIII[60];
        nArray4[f.lIllIllIII[37]] = lIllIllIII[61];
        nArray4[f.lIllIllIII[38]] = lIllIllIII[62];
        nArray4[f.lIllIllIII[36]] = lIllIllIII[63];
        aO = nArray4;
        int[] nArray5 = new int[lIllIllIII[43]];
        nArray5[f.lIllIllIII[23]] = lIllIllIII[64];
        nArray5[f.lIllIllIII[37]] = lIllIllIII[65];
        nArray5[f.lIllIllIII[38]] = lIllIllIII[66];
        nArray5[f.lIllIllIII[36]] = lIllIllIII[67];
        aP = nArray5;
        int[] nArray6 = new int[lIllIllIII[47]];
        nArray6[f.lIllIllIII[23]] = lIllIllIII[68];
        nArray6[f.lIllIllIII[37]] = lIllIllIII[69];
        nArray6[f.lIllIllIII[38]] = lIllIllIII[70];
        nArray6[f.lIllIllIII[36]] = lIllIllIII[71];
        nArray6[f.lIllIllIII[43]] = lIllIllIII[25];
        nArray6[f.lIllIllIII[45]] = lIllIllIII[72];
        aQ = nArray6;
        int[] nArray7 = new int[lIllIllIII[43]];
        nArray7[f.lIllIllIII[23]] = lIllIllIII[73];
        nArray7[f.lIllIllIII[37]] = lIllIllIII[74];
        nArray7[f.lIllIllIII[38]] = lIllIllIII[75];
        nArray7[f.lIllIllIII[36]] = lIllIllIII[76];
        aR = nArray7;
        int[] nArray8 = new int[lIllIllIII[43]];
        nArray8[f.lIllIllIII[23]] = lIllIllIII[77];
        nArray8[f.lIllIllIII[37]] = lIllIllIII[78];
        nArray8[f.lIllIllIII[38]] = lIllIllIII[79];
        nArray8[f.lIllIllIII[36]] = lIllIllIII[80];
        aS = nArray8;
        int[] nArray9 = new int[lIllIllIII[36]];
        nArray9[f.lIllIllIII[23]] = lIllIllIII[77];
        nArray9[f.lIllIllIII[37]] = lIllIllIII[78];
        nArray9[f.lIllIllIII[38]] = lIllIllIII[79];
        aT = nArray9;
        int[] nArray10 = new int[lIllIllIII[43]];
        nArray10[f.lIllIllIII[23]] = lIllIllIII[81];
        nArray10[f.lIllIllIII[37]] = lIllIllIII[82];
        nArray10[f.lIllIllIII[38]] = lIllIllIII[83];
        nArray10[f.lIllIllIII[36]] = lIllIllIII[84];
        aU = nArray10;
        int[] nArray11 = new int[lIllIllIII[43]];
        nArray11[f.lIllIllIII[23]] = lIllIllIII[85];
        nArray11[f.lIllIllIII[37]] = lIllIllIII[86];
        nArray11[f.lIllIllIII[38]] = lIllIllIII[87];
        nArray11[f.lIllIllIII[36]] = lIllIllIII[88];
        aV = nArray11;
        int[] nArray12 = new int[lIllIllIII[43]];
        nArray12[f.lIllIllIII[23]] = lIllIllIII[89];
        nArray12[f.lIllIllIII[37]] = lIllIllIII[90];
        nArray12[f.lIllIllIII[38]] = lIllIllIII[91];
        nArray12[f.lIllIllIII[36]] = lIllIllIII[92];
        aW = nArray12;
        int[] nArray13 = new int[lIllIllIII[43]];
        nArray13[f.lIllIllIII[23]] = lIllIllIII[93];
        nArray13[f.lIllIllIII[37]] = lIllIllIII[94];
        nArray13[f.lIllIllIII[38]] = lIllIllIII[95];
        nArray13[f.lIllIllIII[36]] = lIllIllIII[96];
        aX = nArray13;
        int[] nArray14 = new int[lIllIllIII[43]];
        nArray14[f.lIllIllIII[23]] = lIllIllIII[97];
        nArray14[f.lIllIllIII[37]] = lIllIllIII[98];
        nArray14[f.lIllIllIII[38]] = lIllIllIII[99];
        nArray14[f.lIllIllIII[36]] = lIllIllIII[100];
        aY = nArray14;
        int[] nArray15 = new int[lIllIllIII[45]];
        nArray15[f.lIllIllIII[23]] = lIllIllIII[101];
        nArray15[f.lIllIllIII[37]] = lIllIllIII[102];
        nArray15[f.lIllIllIII[38]] = lIllIllIII[103];
        nArray15[f.lIllIllIII[36]] = lIllIllIII[104];
        nArray15[f.lIllIllIII[43]] = lIllIllIII[105];
        aZ = nArray15;
        int[] nArray16 = new int[lIllIllIII[43]];
        nArray16[f.lIllIllIII[23]] = lIllIllIII[106];
        nArray16[f.lIllIllIII[37]] = lIllIllIII[107];
        nArray16[f.lIllIllIII[38]] = lIllIllIII[108];
        nArray16[f.lIllIllIII[36]] = lIllIllIII[109];
        ba = nArray16;
        int[] nArray17 = new int[lIllIllIII[43]];
        nArray17[f.lIllIllIII[23]] = lIllIllIII[110];
        nArray17[f.lIllIllIII[37]] = lIllIllIII[111];
        nArray17[f.lIllIllIII[38]] = lIllIllIII[112];
        nArray17[f.lIllIllIII[36]] = lIllIllIII[113];
        bb = nArray17;
        int[] nArray18 = new int[lIllIllIII[43]];
        nArray18[f.lIllIllIII[23]] = lIllIllIII[114];
        nArray18[f.lIllIllIII[37]] = lIllIllIII[115];
        nArray18[f.lIllIllIII[38]] = lIllIllIII[116];
        nArray18[f.lIllIllIII[36]] = lIllIllIII[117];
        bc = nArray18;
        int[] nArray19 = new int[lIllIllIII[36]];
        nArray19[f.lIllIllIII[23]] = lIllIllIII[30];
        nArray19[f.lIllIllIII[37]] = lIllIllIII[11];
        nArray19[f.lIllIllIII[38]] = lIllIllIII[22];
        bd = nArray19;
        int[] nArray20 = new int[lIllIllIII[45]];
        nArray20[f.lIllIllIII[23]] = lIllIllIII[32];
        nArray20[f.lIllIllIII[37]] = lIllIllIII[118];
        nArray20[f.lIllIllIII[38]] = lIllIllIII[119];
        nArray20[f.lIllIllIII[36]] = lIllIllIII[120];
        nArray20[f.lIllIllIII[43]] = lIllIllIII[121];
        be = nArray20;
        int[] nArray21 = new int[lIllIllIII[36]];
        nArray21[f.lIllIllIII[23]] = lIllIllIII[122];
        nArray21[f.lIllIllIII[37]] = lIllIllIII[123];
        nArray21[f.lIllIllIII[38]] = lIllIllIII[124];
        bf = nArray21;
        int[] nArray22 = new int[lIllIllIII[43]];
        nArray22[f.lIllIllIII[23]] = lIllIllIII[125];
        nArray22[f.lIllIllIII[37]] = lIllIllIII[126];
        nArray22[f.lIllIllIII[38]] = lIllIllIII[127];
        nArray22[f.lIllIllIII[36]] = lIllIllIII[128];
        bg = nArray22;
    }
}

