/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.3047f210-3107-4c67-939d-3c9e588029ae.tasks;

public class FHelper {
    public static final  int[] aL;
    public static final  int aj;
    public static final  int[] aO;
    public static final  int ak;
    public static final  int[] ba;
    public static final  int[] bc;
    public static final  int[] aP;
    public static final  int ac;
    public static final  int am;
    public static final  int as;
    public static final  int ag;
    public static final  int ax;
    public static final  int[] aT;
    public static final  int aJ;
    public static final  int ae;
    public static final  int al;
    public static final  int[] aZ;
    
    public static final  int[] aN;
    public static final  int ab;
    public static final  int av;
    public static final  int[] aV;
    public static final  int aq;
    public static final  int aB;
    public static final  int[] bf;
    public static final  int ai;
    public static final  int[] aW;
    public static final  int aK;
    public static final  int ao;
    public static final  int ap;
    public static final  int[] be;
    public static final  int at;
    public static final  int aF;
    public static final  int aC;
    public static final  int au;
    public static final  int ah;
    public static final  int aD;
    public static final  int[] aY;
    public static final  int aA;
    public static final  int[] aM;
    public static final  int aG;
    public static final  int ay;
    public static final  int[] aR;
    public static final  int an;
    public static final  int[] bd;
    public static final  int af;
    public static final  int[] bb;
    public static final  int[] bg;
    public static final  int[] aS;
    public static final  int[] aU;
    public static final  int[] aQ;
    public static final  int aE;
    public static final  int aw;
    public static final  int az;
    public static final  int ad;
    public static final  int aH;
    public static final  int aI;
    public static final  int[] aX;
    public static final  int ar;

    static {
        f.llIlllIllllIl();
        ac = lIIIIIlIlIl[0];
        aw = lIIIIIlIlIl[1];
        ar = lIIIIIlIlIl[2];
        af = lIIIIIlIlIl[3];
        ao = lIIIIIlIlIl[4];
        ag = lIIIIIlIlIl[5];
        ap = lIIIIIlIlIl[6];
        aj = lIIIIIlIlIl[7];
        al = lIIIIIlIlIl[8];
        am = lIIIIIlIlIl[9];
        aA = lIIIIIlIlIl[10];
        ab = lIIIIIlIlIl[11];
        an = lIIIIIlIlIl[12];
        ax = lIIIIIlIlIl[13];
        aB = lIIIIIlIlIl[14];
        aq = lIIIIIlIlIl[15];
        ai = lIIIIIlIlIl[16];
        av = lIIIIIlIlIl[17];
        ak = lIIIIIlIlIl[18];
        ay = lIIIIIlIlIl[19];
        aE = lIIIIIlIlIl[20];
        ah = lIIIIIlIlIl[21];
        az = lIIIIIlIlIl[22];
        aC = lIIIIIlIlIl[23];
        aJ = lIIIIIlIlIl[24];
        aI = lIIIIIlIlIl[25];
        as = lIIIIIlIlIl[26];
        aF = lIIIIIlIlIl[27];
        ad = lIIIIIlIlIl[28];
        aG = lIIIIIlIlIl[29];
        at = lIIIIIlIlIl[30];
        aH = lIIIIIlIlIl[31];
        aK = lIIIIIlIlIl[32];
        ae = lIIIIIlIlIl[33];
        au = lIIIIIlIlIl[34];
        aD = lIIIIIlIlIl[35];
        int[] nArray = new int[lIIIIIlIlIl[36]];
        nArray[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[5];
        nArray[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[21];
        nArray[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[24];
        aL = nArray;
        int[] nArray2 = new int[lIIIIIlIlIl[39]];
        nArray2[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[16];
        nArray2[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[40];
        nArray2[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[41];
        nArray2[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[42];
        nArray2[f.lIIIIIlIlIl[43]] = lIIIIIlIlIl[44];
        nArray2[f.lIIIIIlIlIl[45]] = lIIIIIlIlIl[46];
        nArray2[f.lIIIIIlIlIl[47]] = lIIIIIlIlIl[48];
        nArray2[f.lIIIIIlIlIl[49]] = lIIIIIlIlIl[50];
        aM = nArray2;
        int[] nArray3 = new int[lIIIIIlIlIl[51]];
        nArray3[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[52];
        nArray3[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[53];
        nArray3[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[54];
        nArray3[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[55];
        nArray3[f.lIIIIIlIlIl[43]] = lIIIIIlIlIl[56];
        nArray3[f.lIIIIIlIlIl[45]] = lIIIIIlIlIl[57];
        nArray3[f.lIIIIIlIlIl[47]] = lIIIIIlIlIl[58];
        nArray3[f.lIIIIIlIlIl[49]] = lIIIIIlIlIl[59];
        nArray3[f.lIIIIIlIlIl[39]] = lIIIIIlIlIl[59];
        aN = nArray3;
        int[] nArray4 = new int[lIIIIIlIlIl[43]];
        nArray4[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[60];
        nArray4[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[61];
        nArray4[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[62];
        nArray4[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[63];
        aO = nArray4;
        int[] nArray5 = new int[lIIIIIlIlIl[43]];
        nArray5[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[64];
        nArray5[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[65];
        nArray5[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[66];
        nArray5[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[67];
        aP = nArray5;
        int[] nArray6 = new int[lIIIIIlIlIl[47]];
        nArray6[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[68];
        nArray6[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[69];
        nArray6[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[70];
        nArray6[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[71];
        nArray6[f.lIIIIIlIlIl[43]] = lIIIIIlIlIl[25];
        nArray6[f.lIIIIIlIlIl[45]] = lIIIIIlIlIl[72];
        aQ = nArray6;
        int[] nArray7 = new int[lIIIIIlIlIl[43]];
        nArray7[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[73];
        nArray7[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[74];
        nArray7[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[75];
        nArray7[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[76];
        aR = nArray7;
        int[] nArray8 = new int[lIIIIIlIlIl[43]];
        nArray8[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[77];
        nArray8[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[78];
        nArray8[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[79];
        nArray8[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[80];
        aS = nArray8;
        int[] nArray9 = new int[lIIIIIlIlIl[36]];
        nArray9[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[77];
        nArray9[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[78];
        nArray9[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[79];
        aT = nArray9;
        int[] nArray10 = new int[lIIIIIlIlIl[43]];
        nArray10[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[81];
        nArray10[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[82];
        nArray10[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[83];
        nArray10[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[84];
        aU = nArray10;
        int[] nArray11 = new int[lIIIIIlIlIl[43]];
        nArray11[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[85];
        nArray11[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[86];
        nArray11[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[87];
        nArray11[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[88];
        aV = nArray11;
        int[] nArray12 = new int[lIIIIIlIlIl[43]];
        nArray12[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[89];
        nArray12[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[90];
        nArray12[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[91];
        nArray12[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[92];
        aW = nArray12;
        int[] nArray13 = new int[lIIIIIlIlIl[43]];
        nArray13[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[93];
        nArray13[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[94];
        nArray13[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[95];
        nArray13[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[96];
        aX = nArray13;
        int[] nArray14 = new int[lIIIIIlIlIl[43]];
        nArray14[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[97];
        nArray14[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[98];
        nArray14[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[99];
        nArray14[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[100];
        aY = nArray14;
        int[] nArray15 = new int[lIIIIIlIlIl[45]];
        nArray15[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[101];
        nArray15[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[102];
        nArray15[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[103];
        nArray15[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[104];
        nArray15[f.lIIIIIlIlIl[43]] = lIIIIIlIlIl[105];
        aZ = nArray15;
        int[] nArray16 = new int[lIIIIIlIlIl[43]];
        nArray16[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[106];
        nArray16[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[107];
        nArray16[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[108];
        nArray16[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[109];
        ba = nArray16;
        int[] nArray17 = new int[lIIIIIlIlIl[43]];
        nArray17[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[110];
        nArray17[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[111];
        nArray17[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[112];
        nArray17[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[113];
        bb = nArray17;
        int[] nArray18 = new int[lIIIIIlIlIl[43]];
        nArray18[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[114];
        nArray18[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[115];
        nArray18[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[116];
        nArray18[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[117];
        bc = nArray18;
        int[] nArray19 = new int[lIIIIIlIlIl[36]];
        nArray19[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[23];
        nArray19[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[14];
        nArray19[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[10];
        bd = nArray19;
        int[] nArray20 = new int[lIIIIIlIlIl[45]];
        nArray20[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[7];
        nArray20[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[118];
        nArray20[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[119];
        nArray20[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[120];
        nArray20[f.lIIIIIlIlIl[43]] = lIIIIIlIlIl[121];
        be = nArray20;
        int[] nArray21 = new int[lIIIIIlIlIl[36]];
        nArray21[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[122];
        nArray21[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[123];
        nArray21[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[124];
        bf = nArray21;
        int[] nArray22 = new int[lIIIIIlIlIl[43]];
        nArray22[f.lIIIIIlIlIl[17]] = lIIIIIlIlIl[125];
        nArray22[f.lIIIIIlIlIl[37]] = lIIIIIlIlIl[126];
        nArray22[f.lIIIIIlIlIl[38]] = lIIIIIlIlIl[127];
        nArray22[f.lIIIIIlIlIl[36]] = lIIIIIlIlIl[128];
        bg = nArray22;
    }
}

