/*
 * Decompiled with CFR 0.152.
 */
package s.r.s.o.l.t.t.l.r.a.-.i.n.d.u.-.q.i.i.e.a.u;

public class c {
    public static final /* synthetic */ int q;
    public static final /* synthetic */ int[] A;
    public static final /* synthetic */ int[] u;
    private static /* synthetic */ int[] lIlIIIllIllIl;
    public static final /* synthetic */ int[] w;
    public static final /* synthetic */ int s;
    public static final /* synthetic */ int t;
    public static final /* synthetic */ int[] y;
    public static final /* synthetic */ int o;
    public static final /* synthetic */ int[] x;
    public static final /* synthetic */ int[] B;
    public static final /* synthetic */ int[] v;
    public static final /* synthetic */ int l;
    public static final /* synthetic */ int i;
    public static final /* synthetic */ int[] z;
    public static final /* synthetic */ int k;
    public static final /* synthetic */ int[] C;
    public static final /* synthetic */ int m;
    public static final /* synthetic */ int[] F;
    public static final /* synthetic */ int p;
    public static final /* synthetic */ int r;
    public static final /* synthetic */ int[] E;
    public static final /* synthetic */ int n;
    public static final /* synthetic */ int j;
    public static final /* synthetic */ int[][] G;
    public static final /* synthetic */ int h;
    public static final /* synthetic */ int[] D;

    static {
        c.lIlllIIIIllIllI();
        l = lIlIIIllIllIl[0];
        n = lIlIIIllIllIl[1];
        j = lIlIIIllIllIl[2];
        q = lIlIIIllIllIl[3];
        s = lIlIIIllIllIl[0];
        o = lIlIIIllIllIl[4];
        p = lIlIIIllIllIl[5];
        m = lIlIIIllIllIl[6];
        h = lIlIIIllIllIl[7];
        i = lIlIIIllIllIl[8];
        k = lIlIIIllIllIl[9];
        t = lIlIIIllIllIl[10];
        r = lIlIIIllIllIl[11];
        int[] nArray = new int[lIlIIIllIllIl[12]];
        nArray[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[6];
        nArray[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[8];
        u = nArray;
        int[] nArray2 = new int[lIlIIIllIllIl[12]];
        nArray2[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[15];
        nArray2[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[16];
        v = nArray2;
        int[] nArray3 = new int[lIlIIIllIllIl[12]];
        nArray3[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[17];
        nArray3[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[18];
        w = nArray3;
        int[] nArray4 = new int[lIlIIIllIllIl[12]];
        nArray4[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[19];
        nArray4[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[20];
        x = nArray4;
        int[] nArray5 = new int[lIlIIIllIllIl[12]];
        nArray5[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[21];
        nArray5[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[22];
        y = nArray5;
        int[] nArray6 = new int[lIlIIIllIllIl[12]];
        nArray6[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[23];
        nArray6[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[24];
        z = nArray6;
        int[] nArray7 = new int[lIlIIIllIllIl[12]];
        nArray7[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[25];
        nArray7[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[26];
        A = nArray7;
        int[] nArray8 = new int[lIlIIIllIllIl[12]];
        nArray8[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[27];
        nArray8[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[28];
        B = nArray8;
        int[] nArray9 = new int[lIlIIIllIllIl[12]];
        nArray9[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[29];
        nArray9[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[30];
        C = nArray9;
        int[] nArray10 = new int[lIlIIIllIllIl[12]];
        nArray10[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[31];
        nArray10[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[32];
        D = nArray10;
        int[] nArray11 = new int[lIlIIIllIllIl[12]];
        nArray11[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[33];
        nArray11[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[34];
        E = nArray11;
        int[] nArray12 = new int[lIlIIIllIllIl[12]];
        nArray12[c.lIlIIIllIllIl[13]] = lIlIIIllIllIl[35];
        nArray12[c.lIlIIIllIllIl[14]] = lIlIIIllIllIl[36];
        F = nArray12;
        int[][] nArrayArray = new int[lIlIIIllIllIl[6]][];
        nArrayArray[c.lIlIIIllIllIl[13]] = u;
        nArrayArray[c.lIlIIIllIllIl[14]] = v;
        nArrayArray[c.lIlIIIllIllIl[12]] = w;
        nArrayArray[c.lIlIIIllIllIl[37]] = x;
        nArrayArray[c.lIlIIIllIllIl[38]] = y;
        nArrayArray[c.lIlIIIllIllIl[39]] = z;
        nArrayArray[c.lIlIIIllIllIl[40]] = A;
        nArrayArray[c.lIlIIIllIllIl[1]] = B;
        nArrayArray[c.lIlIIIllIllIl[41]] = C;
        nArrayArray[c.lIlIIIllIllIl[0]] = D;
        nArrayArray[c.lIlIIIllIllIl[42]] = E;
        nArrayArray[c.lIlIIIllIllIl[43]] = F;
        G = nArrayArray;
    }

    private static void lIlllIIIIllIllI() {
        lIlIIIllIllIl = new int[44];
        c.lIlIIIllIllIl[0] = 17 + 62 - -54 + 11 ^ 63 + 35 - 30 + 85;
        c.lIlIIIllIllIl[1] = 0x6C ^ 0x6B;
        c.lIlIIIllIllIl[2] = 124 + 155 - 127 + 29 ^ 87 + 54 - 32 + 58;
        c.lIlIIIllIllIl[3] = 0x18 ^ 0x4B ^ (0x33 ^ 0x21);
        c.lIlIIIllIllIl[4] = 0xFFFFF2B7 & 0xFEF;
        c.lIlIIIllIllIl[5] = 0xF6 ^ 0x95;
        c.lIlIIIllIllIl[6] = 0x59 ^ 0x55;
        c.lIlIIIllIllIl[7] = -(0xFFFFCF17 & 0x71E9) & (0xFFFFE73E & 0x5BEF);
        c.lIlIIIllIllIl[8] = 0xC ^ 1;
        c.lIlIIIllIllIl[9] = 0xAB ^ 0xB8;
        c.lIlIIIllIllIl[10] = 0xC5 ^ 0x8C ^ (0x3D ^ 0x30);
        c.lIlIIIllIllIl[11] = 118 + 198 - 162 + 80 ^ 13 + 6 - -111 + 38;
        c.lIlIIIllIllIl[12] = "  ".length();
        c.lIlIIIllIllIl[13] = (0x22 ^ 0x31) & ~(0x85 ^ 0x96);
        c.lIlIIIllIllIl[14] = " ".length();
        c.lIlIIIllIllIl[15] = 78 + 127 - 134 + 84 ^ 86 + 79 - 150 + 124;
        c.lIlIIIllIllIl[16] = 0x46 ^ 0x1D ^ (0xC3 ^ 0x89);
        c.lIlIIIllIllIl[17] = 0x15 ^ 1;
        c.lIlIIIllIllIl[18] = 0x24 ^ 0x31;
        c.lIlIIIllIllIl[19] = 0x18 ^ 0;
        c.lIlIIIllIllIl[20] = 0x13 ^ 0xA;
        c.lIlIIIllIllIl[21] = 0x6F ^ 0x5B ^ (0xA5 ^ 0x8D);
        c.lIlIIIllIllIl[22] = 0x91 ^ 0x8C;
        c.lIlIIIllIllIl[23] = 0x53 ^ 0x2A ^ (0x70 ^ 0x29);
        c.lIlIIIllIllIl[24] = 0x9C ^ 0xBD;
        c.lIlIIIllIllIl[25] = 0x88 ^ 0xBB ^ (0x21 ^ 0x36);
        c.lIlIIIllIllIl[26] = 0x95 ^ 0xB0;
        c.lIlIIIllIllIl[27] = 0x29 ^ 2;
        c.lIlIIIllIllIl[28] = 87 + 86 - 155 + 165 ^ 79 + 144 - 76 + 8;
        c.lIlIIIllIllIl[29] = 0x21 ^ 0xE;
        c.lIlIIIllIllIl[30] = 0x8D ^ 0xBD;
        c.lIlIIIllIllIl[31] = 0x17 ^ 0x47 ^ (0xEC ^ 0x8F);
        c.lIlIIIllIllIl[32] = 0x69 ^ 0x5D;
        c.lIlIIIllIllIl[33] = 0x72 ^ 0x45;
        c.lIlIIIllIllIl[34] = 0x8A ^ 0xAC ^ (0xB ^ 0x15);
        c.lIlIIIllIllIl[35] = 130 + 74 - 60 + 0 ^ 23 + 147 - 13 + 14;
        c.lIlIIIllIllIl[36] = 0x2D ^ 0x11;
        c.lIlIIIllIllIl[37] = "   ".length();
        c.lIlIIIllIllIl[38] = 48 + 188 - 155 + 115 ^ 180 + 13 - 90 + 89;
        c.lIlIIIllIllIl[39] = 0x43 ^ 0x63 ^ (0x7D ^ 0x58);
        c.lIlIIIllIllIl[40] = 0x3B ^ 0x2D ^ (0x5F ^ 0x4F);
        c.lIlIIIllIllIl[41] = 0x2F ^ 0x27;
        c.lIlIIIllIllIl[42] = 0x14 ^ 0x1E;
        c.lIlIIIllIllIl[43] = 0x26 ^ 0x2D;
    }
}

