/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap$Builder
 *  net.runelite.api.widgets.Widget
 *  net.runelite.api.widgets.WidgetInfo
 *  net.unethicalite.api.widgets.Widgets
 */
package l.i.r.i.y.c.c.-.s.e.n.-.e.l.b.e.l.k.d.-.c.o.a.u.e.u.-;

import com.google.common.collect.ImmutableMap;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import java.util.Map;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import net.runelite.api.widgets.Widget;
import net.runelite.api.widgets.WidgetInfo;
import net.unethicalite.api.widgets.Widgets;

public final class HerbType
extends Enum<h> {
    public static final /* synthetic */ /* enum */ h TERRORBIRD_4;
    public static final /* synthetic */ /* enum */ h PENGUIN_5;
    public static final /* synthetic */ /* enum */ h KALPHITE_2;
    private final /* synthetic */ String question;
    public static final /* synthetic */ /* enum */ h SLUG_3;
    public static final /* synthetic */ /* enum */ h SNAIL_3;
    public static final /* synthetic */ /* enum */ h PENGUIN_6;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_6;
    public static final /* synthetic */ /* enum */ h WYVERN_3;
    public static final /* synthetic */ /* enum */ h SNAIL_4;
    public static final /* synthetic */ /* enum */ h SLUG_1;
    public static final /* synthetic */ /* enum */ h TORTOISE_1;
    public static final /* synthetic */ /* enum */ h WYVERN_1;
    public static final /* synthetic */ /* enum */ h SNAIL_5;
    public static final /* synthetic */ /* enum */ h PENGUIN_4;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_1;
    public static final /* synthetic */ /* enum */ h MOLE_4;
    public static final /* synthetic */ /* enum */ h TORTOISE_4;
    public static final /* synthetic */ /* enum */ h LEECH_4;
    public static final /* synthetic */ /* enum */ h MOLE_5;
    public static final /* synthetic */ /* enum */ h MOLE_6;
    public static final /* synthetic */ /* enum */ h SNAKE_4;
    public static final /* synthetic */ /* enum */ h SLUG_4;
    private final /* synthetic */ String answer;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_3;
    public static final /* synthetic */ /* enum */ h DRAGON_2;
    public static final /* synthetic */ /* enum */ h TORTOISE_2;
    public static final /* synthetic */ /* enum */ h SNAKE_6;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_5;
    public static final /* synthetic */ /* enum */ h LIZARD_5;
    public static final /* synthetic */ /* enum */ h SNAKE_3;
    public static final /* synthetic */ /* enum */ h KALPHITE_3;
    public static final /* synthetic */ /* enum */ h LEECH_6;
    public static final /* synthetic */ /* enum */ h PENGUIN_3;
    public static final /* synthetic */ /* enum */ h MONKEY_6;
    public static final /* synthetic */ /* enum */ h LIZARD_6;
    public static final /* synthetic */ /* enum */ h DRAGON_4;
    public static final /* synthetic */ /* enum */ h WYVERN_2;
    public static final /* synthetic */ /* enum */ h DRAGON_1;
    public static final /* synthetic */ /* enum */ h WYVERN_6;
    public static final /* synthetic */ /* enum */ h MONKEY_1;
    public static final /* synthetic */ /* enum */ h PENGUIN_1;
    public static final /* synthetic */ /* enum */ h WYVERN_5;
    public static final /* synthetic */ /* enum */ h SNAIL_1;
    public static final /* synthetic */ /* enum */ h CAMEL_4;
    private static final /* synthetic */ Map<String, String> MATCHES;
    public static final /* synthetic */ /* enum */ h SNAIL_2;
    public static final /* synthetic */ /* enum */ h MOLE_1;
    public static final /* synthetic */ /* enum */ h WYVERN_4;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_2;
    public static final /* synthetic */ /* enum */ h SLUG_6;
    public static final /* synthetic */ /* enum */ h SNAKE_2;
    public static final /* synthetic */ /* enum */ h KALPHITE_1;
    public static final /* synthetic */ /* enum */ h SNAIL_6;
    public static final /* synthetic */ /* enum */ h CAMEL_5;
    public static final /* synthetic */ /* enum */ h SNAKE_1;
    public static final /* synthetic */ /* enum */ h PENGUIN_2;
    public static final /* synthetic */ /* enum */ h DRAGON_5;
    private static /* synthetic */ String[] lIIIlIllI;
    public static final /* synthetic */ /* enum */ h LEECH_5;
    public static final /* synthetic */ /* enum */ h DRAGON_3;
    public static final /* synthetic */ /* enum */ h CAMEL_2;
    public static final /* synthetic */ /* enum */ h LEECH_1;
    private static final /* synthetic */ h[] $VALUES;
    public static final /* synthetic */ /* enum */ h KALPHITE_6;
    public static final /* synthetic */ /* enum */ h MONKEY_3;
    public static final /* synthetic */ /* enum */ h LIZARD_3;
    public static final /* synthetic */ /* enum */ h TORTOISE_3;
    public static final /* synthetic */ /* enum */ h LIZARD_2;
    public static final /* synthetic */ /* enum */ h CAMEL_3;
    public static final /* synthetic */ /* enum */ h SNAKE_5;
    public static final /* synthetic */ /* enum */ h SLUG_2;
    public static final /* synthetic */ /* enum */ h KALPHITE_4;
    public static final /* synthetic */ /* enum */ h DRAGON_6;
    public static final /* synthetic */ /* enum */ h MONKEY_2;
    public static final /* synthetic */ /* enum */ h LEECH_2;
    public static final /* synthetic */ /* enum */ h CAMEL_6;
    public static final /* synthetic */ /* enum */ h LIZARD_4;
    public static final /* synthetic */ /* enum */ h LIZARD_1;
    public static final /* synthetic */ /* enum */ h MONKEY_4;
    public static final /* synthetic */ /* enum */ h MOLE_2;
    public static final /* synthetic */ /* enum */ h CAMEL_1;
    public static final /* synthetic */ /* enum */ h TORTOISE_6;
    public static final /* synthetic */ /* enum */ h KALPHITE_5;
    private static /* synthetic */ int[] lIIIllIlI;
    public static final /* synthetic */ /* enum */ h TORTOISE_5;
    public static final /* synthetic */ /* enum */ h MONKEY_5;
    public static final /* synthetic */ /* enum */ h MOLE_3;
    public static final /* synthetic */ /* enum */ h SLUG_5;
    public static final /* synthetic */ /* enum */ h LEECH_3;

    private h(String string2, String string3) {
        this.question = string2;
        this.answer = string3;
    }

    public static h valueOf(String string) {
        return Enum.valueOf(h.class, string);
    }

    private static String lllIIllIIIl(String lIIIllIlIlIlIII, String lIIIllIlIlIIlll) {
        try {
            SecretKeySpec lIIIllIlIlIlIll = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(lIIIllIlIlIIlll.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher lIIIllIlIlIlIlI = Cipher.getInstance("Blowfish");
            lIIIllIlIlIlIlI.init(lIIIllIlI[2], lIIIllIlIlIlIll);
            return new String(lIIIllIlIlIlIlI.doFinal(Base64.getDecoder().decode(lIIIllIlIlIlIII.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lIIIllIlIlIlIIl) {
            lIIIllIlIlIlIIl.printStackTrace();
            return null;
        }
    }

    private static String lllIIllIIlI(String lIIIllIlIIIIIIl, String lIIIllIlIIIIIII) {
        try {
            SecretKeySpec lIIIllIlIIIIllI = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(lIIIllIlIIIIIII.getBytes(StandardCharsets.UTF_8)), lIIIllIlI[8]), "DES");
            Cipher lIIIllIlIIIIlIl = Cipher.getInstance("DES");
            lIIIllIlIIIIlIl.init(lIIIllIlI[2], lIIIllIlIIIIllI);
            return new String(lIIIllIlIIIIlIl.doFinal(Base64.getDecoder().decode(lIIIllIlIIIIIIl.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lIIIllIlIIIIlII) {
            lIIIllIlIIIIlII.printStackTrace();
            return null;
        }
    }

    private static String lllIIllIIll(String lIIIllIlIIllIII, String lIIIllIlIIlIIlI) {
        lIIIllIlIIllIII = new String(Base64.getDecoder().decode(lIIIllIlIIllIII.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder lIIIllIlIIlIllI = new StringBuilder();
        char[] lIIIllIlIIlIlIl = lIIIllIlIIlIIlI.toCharArray();
        int lIIIllIlIIlIlII = lIIIllIlI[0];
        char[] lIIIllIlIIIlllI = lIIIllIlIIllIII.toCharArray();
        int lIIIllIlIIIllIl = lIIIllIlIIIlllI.length;
        int lIIIllIlIIIllII = lIIIllIlI[0];
        while (h.lllIlIlIlIl(lIIIllIlIIIllII, lIIIllIlIIIllIl)) {
            char lIIIllIlIIllIIl = lIIIllIlIIIlllI[lIIIllIlIIIllII];
            lIIIllIlIIlIllI.append((char)(lIIIllIlIIllIIl ^ lIIIllIlIIlIlIl[lIIIllIlIIlIlII % lIIIllIlIIlIlIl.length]));
            0;
            ++lIIIllIlIIlIlII;
            ++lIIIllIlIIIllII;
            0;
            if (((0x24 ^ 0xB ^ (0xD4 ^ 0xAD)) & (2 ^ (0x5D ^ 9) ^ -1)) == 0) continue;
            return null;
        }
        return String.valueOf(lIIIllIlIIlIllI);
    }

    private static void lllIlIlIlII() {
        lIIIllIlI = new int[253];
        h.lIIIllIlI[0] = (18 + 132 - 122 + 114 ^ 131 + 172 - 213 + 94) & (58 + 90 - 142 + 167 ^ 89 + 111 - 50 + 5 ^ -1);
        h.lIIIllIlI[1] = 1;
        h.lIIIllIlI[2] = 2;
        h.lIIIllIlI[3] = 3;
        h.lIIIllIlI[4] = 0x6A ^ 0x6E;
        h.lIIIllIlI[5] = 0x99 ^ 0x9C;
        h.lIIIllIlI[6] = 0xC2 ^ 0xC4;
        h.lIIIllIlI[7] = 0x8D ^ 0x8A;
        h.lIIIllIlI[8] = 0x31 ^ 0x39;
        h.lIIIllIlI[9] = 0x7D ^ 0x74;
        h.lIIIllIlI[10] = 0 ^ 0xA;
        h.lIIIllIlI[11] = 0x6D ^ 0x66;
        h.lIIIllIlI[12] = 0x63 ^ 0x6F;
        h.lIIIllIlI[13] = 0x68 ^ 0x65;
        h.lIIIllIlI[14] = 0x28 ^ 0x26;
        h.lIIIllIlI[15] = 0x96 ^ 0x92 ^ (0x2F ^ 0x24);
        h.lIIIllIlI[16] = 0x34 ^ 0x24;
        h.lIIIllIlI[17] = 103 + 52 - 11 + 33 ^ 102 + 99 - 47 + 6;
        h.lIIIllIlI[18] = 0x9F ^ 0x8D;
        h.lIIIllIlI[19] = 0x34 ^ 0x63 ^ (0xCA ^ 0x8E);
        h.lIIIllIlI[20] = 0xB1 ^ 0xC2 ^ (0x36 ^ 0x51);
        h.lIIIllIlI[21] = 0x1C ^ 9;
        h.lIIIllIlI[22] = 12 + 59 - 36 + 136 ^ 46 + 133 - 143 + 153;
        h.lIIIllIlI[23] = 0x17 ^ 0x31 ^ (0x6D ^ 0x5C);
        h.lIIIllIlI[24] = 0xB8 ^ 0x8F ^ (0x11 ^ 0x3E);
        h.lIIIllIlI[25] = 0xE ^ 0x38 ^ (0x93 ^ 0xBC);
        h.lIIIllIlI[26] = 0x87 ^ 0x9D;
        h.lIIIllIlI[27] = 0x99 ^ 0x82;
        h.lIIIllIlI[28] = 0x69 ^ 0x5D ^ (0x91 ^ 0xB9);
        h.lIIIllIlI[29] = 0xA9 ^ 0xB4;
        h.lIIIllIlI[30] = 9 ^ 0x17;
        h.lIIIllIlI[31] = 9 ^ 0x16;
        h.lIIIllIlI[32] = 2 ^ 7 ^ (0x1E ^ 0x3B);
        h.lIIIllIlI[33] = 0xAC ^ 0x8D;
        h.lIIIllIlI[34] = 136 + 131 - 226 + 118 ^ 127 + 166 - 120 + 16;
        h.lIIIllIlI[35] = 0x2F ^ 0xC;
        h.lIIIllIlI[36] = 0x9C ^ 0xB8;
        h.lIIIllIlI[37] = 0x26 ^ 0x1B ^ (0x1A ^ 2);
        h.lIIIllIlI[38] = 0xA2 ^ 0x84;
        h.lIIIllIlI[39] = (0x30 ^ 0x67) & ~(0x90 ^ 0xC7) ^ (0x24 ^ 3);
        h.lIIIllIlI[40] = 0xED ^ 0xC5;
        h.lIIIllIlI[41] = 0x3C ^ 0x29 ^ (0x6B ^ 0x57);
        h.lIIIllIlI[42] = 0xC ^ 0x5E ^ (0xDD ^ 0xA5);
        h.lIIIllIlI[43] = 6 ^ 1 ^ (0x8E ^ 0xA2);
        h.lIIIllIlI[44] = 0x6F ^ 0x43;
        h.lIIIllIlI[45] = 0x47 ^ 0x6A;
        h.lIIIllIlI[46] = 0x31 ^ 0x1F;
        h.lIIIllIlI[47] = 145 + 7 - 58 + 78 ^ 95 + 37 - 117 + 116;
        h.lIIIllIlI[48] = 0x54 ^ 0xA ^ (0x6F ^ 1);
        h.lIIIllIlI[49] = 0x17 ^ 0x26;
        h.lIIIllIlI[50] = 0x9A ^ 0xA0 ^ (4 ^ 0xC);
        h.lIIIllIlI[51] = 0xF ^ 0x5F ^ (0xE7 ^ 0x84);
        h.lIIIllIlI[52] = 0x7D ^ 0x1C ^ (0x32 ^ 0x67);
        h.lIIIllIlI[53] = 0x7B ^ 0x4E;
        h.lIIIllIlI[54] = 2 ^ 0x34;
        h.lIIIllIlI[55] = 0x28 ^ 0x33 ^ (0x2C ^ 0);
        h.lIIIllIlI[56] = 0x9F ^ 0xB2 ^ (0x12 ^ 7);
        h.lIIIllIlI[57] = 0xAF ^ 0x96;
        h.lIIIllIlI[58] = 0x9F ^ 0xA5;
        h.lIIIllIlI[59] = 5 ^ 0x3E;
        h.lIIIllIlI[60] = 0x5A ^ 0x66;
        h.lIIIllIlI[61] = 50 + 60 - 92 + 143 ^ 61 + 112 - 28 + 11;
        h.lIIIllIlI[62] = 0x82 ^ 0xBC;
        h.lIIIllIlI[63] = 0x6A ^ 0x55;
        h.lIIIllIlI[64] = 0x15 ^ 0x7C ^ (0xB6 ^ 0x9F);
        h.lIIIllIlI[65] = 0x66 ^ 0x1B ^ (0x20 ^ 0x1C);
        h.lIIIllIlI[66] = 0x17 ^ 0x45 ^ (0x56 ^ 0x46);
        h.lIIIllIlI[67] = 0x2B ^ 0x67 ^ (0x97 ^ 0x98);
        h.lIIIllIlI[68] = 0x4C ^ 0xC ^ (0x5C ^ 0x58);
        h.lIIIllIlI[69] = 0x60 ^ 0x25;
        h.lIIIllIlI[70] = 86 + 28 - 110 + 123 ^ (0x40 ^ 0x79);
        h.lIIIllIlI[71] = 3 ^ (0x3C ^ 0x78);
        h.lIIIllIlI[72] = 0x46 ^ 0xE;
        h.lIIIllIlI[73] = 0x31 ^ 0x56 ^ (0xBF ^ 0x91);
        h.lIIIllIlI[74] = 16 + 248 - 77 + 66 ^ 135 + 123 - 113 + 38;
        h.lIIIllIlI[75] = 211 + 10 - 22 + 53 ^ 73 + 58 - 9 + 61;
        h.lIIIllIlI[76] = 0x4C ^ 0;
        h.lIIIllIlI[77] = 0xA1 ^ 0x87 ^ (0xD0 ^ 0xBB);
        h.lIIIllIlI[78] = 0xFE ^ 0xB0;
        h.lIIIllIlI[79] = 0xE7 ^ 0xA8;
        h.lIIIllIlI[80] = 0x3E ^ 0x6E;
        h.lIIIllIlI[81] = 0x5D ^ 5 ^ (0x45 ^ 0x4C);
        h.lIIIllIlI[82] = 0x24 ^ 0x76;
        h.lIIIllIlI[83] = 0xC2 ^ 0x91;
        h.lIIIllIlI[84] = 0x5B ^ 0x76 ^ (0x79 ^ 0);
        h.lIIIllIlI[85] = 0x24 ^ 0x71;
        h.lIIIllIlI[86] = 32 + 212 - 232 + 218 ^ 47 + 157 - 128 + 100;
        h.lIIIllIlI[87] = 0x37 ^ 0x6E ^ (0x23 ^ 0x2D);
        h.lIIIllIlI[88] = 202 + 30 - 117 + 92 ^ 96 + 15 - 89 + 129;
        h.lIIIllIlI[89] = 0xEC ^ 0xC5 ^ (0x11 ^ 0x61);
        h.lIIIllIlI[90] = 0x4D ^ 0x20 ^ (0x3D ^ 0xA);
        h.lIIIllIlI[91] = 0x27 ^ 0x7C;
        h.lIIIllIlI[92] = 0x3E ^ 0x62;
        h.lIIIllIlI[93] = 0x72 ^ 0x2F;
        h.lIIIllIlI[94] = 77 + 150 - 93 + 104 ^ 112 + 48 - 95 + 111;
        h.lIIIllIlI[95] = 0xD9 ^ 0x86;
        h.lIIIllIlI[96] = 0x96 ^ 0x87 ^ (0xB2 ^ 0xC3);
        h.lIIIllIlI[97] = 74 + 235 - 134 + 63 ^ 16 + 125 - 76 + 78;
        h.lIIIllIlI[98] = 0x4C ^ 0x2E;
        h.lIIIllIlI[99] = 0xEE ^ 0x8D;
        h.lIIIllIlI[100] = 107 + 3 - 108 + 200 ^ 163 + 86 - 162 + 87;
        h.lIIIllIlI[101] = 0x3A ^ 0x67 ^ (0x18 ^ 0x20);
        h.lIIIllIlI[102] = 0x41 ^ 0x53 ^ (0x38 ^ 0x4C);
        h.lIIIllIlI[103] = 0x3C ^ 0x5B;
        h.lIIIllIlI[104] = 0x75 ^ 0x1D;
        h.lIIIllIlI[105] = 54 + 117 - 120 + 171 ^ 12 + 111 - -20 + 40;
        h.lIIIllIlI[106] = 0xE0 ^ 0x8A;
        h.lIIIllIlI[107] = 0x6D ^ 6;
        h.lIIIllIlI[108] = 0x7F ^ 0x52 ^ (0xCE ^ 0x8F);
        h.lIIIllIlI[109] = 0x8C ^ 0xB9 ^ (0x75 ^ 0x2D);
        h.lIIIllIlI[110] = 0x3C ^ 0x52;
        h.lIIIllIlI[111] = 0xF1 ^ 0xA9 ^ (0x77 ^ 0x40);
        h.lIIIllIlI[112] = 0xD9 ^ 0xA9;
        h.lIIIllIlI[113] = 0x73 ^ 0x42 ^ (0x77 ^ 0x37);
        h.lIIIllIlI[114] = 0x21 ^ 0x1D ^ (0x66 ^ 0x28);
        h.lIIIllIlI[115] = 0x6E ^ 0x1D;
        h.lIIIllIlI[116] = 0x7A ^ 0xE;
        h.lIIIllIlI[117] = 0xFB ^ 0x8E;
        h.lIIIllIlI[118] = 0xF7 ^ 0x81;
        h.lIIIllIlI[119] = 0x4B ^ 0x7D ^ (0xCA ^ 0x8B);
        h.lIIIllIlI[120] = 0x58 ^ 0x51 ^ (0xCF ^ 0xBE);
        h.lIIIllIlI[121] = 0xB ^ 0x72;
        h.lIIIllIlI[122] = 0x10 ^ 0x6A;
        h.lIIIllIlI[123] = 0x51 ^ 0x24 ^ (0x8D ^ 0x83);
        h.lIIIllIlI[124] = 0 ^ 0x50 ^ (0x22 ^ 0xE);
        h.lIIIllIlI[125] = 0x3F ^ 0x42;
        h.lIIIllIlI[126] = 0xC9 ^ 0x8B ^ (0x35 ^ 9);
        h.lIIIllIlI[127] = (0x56 ^ 0x26) + (0x95 ^ 0xBA) - (24 + 95 - 89 + 119) + (0x13 ^ 0x66);
        h.lIIIllIlI[128] = (0x6B ^ 0x4B) + (0x22 ^ 0x5C) - (0x2B ^ 0x7E) + (0x63 ^ 0x54);
        h.lIIIllIlI[129] = (0x2B ^ 0x6D) + (0x33 ^ 0x24) - (0x4E ^ 4) + (0x18 ^ 0x76);
        h.lIIIllIlI[130] = (0xE2 ^ 0xA1) + (0xA2 ^ 0x92) - (0x4F ^ 0x75) + (0xC2 ^ 0x8B);
        h.lIIIllIlI[131] = 64 + 70 - 125 + 122;
        h.lIIIllIlI[132] = 57 + 105 - 161 + 131;
        h.lIIIllIlI[133] = 44 + 65 - 69 + 93;
        h.lIIIllIlI[134] = 99 + 114 - 126 + 47;
        h.lIIIllIlI[135] = 107 + 97 - 168 + 99;
        h.lIIIllIlI[136] = 99 + 58 - 47 + 26;
        h.lIIIllIlI[137] = 107 + 38 - 85 + 77;
        h.lIIIllIlI[138] = (0x26 ^ 0x52) + (0x3F ^ 0x28) - (0x1D ^ 0x70) + (0xC2 ^ 0xAE);
        h.lIIIllIlI[139] = 90 + 58 - 78 + 69;
        h.lIIIllIlI[140] = 128 + 120 - 176 + 68;
        h.lIIIllIlI[141] = 127 + 59 - 147 + 102;
        h.lIIIllIlI[142] = (2 ^ 0x73) + (0x1E ^ 0x3D) - (0x81 ^ 0xBD) + (0xF1 ^ 0xC7);
        h.lIIIllIlI[143] = 126 + 33 - 147 + 130 + (0x44 ^ 0x3E) - (57 + 47 - 27 + 70) + (0x38 ^ 0x22);
        h.lIIIllIlI[144] = 143 + 117 - 210 + 94;
        h.lIIIllIlI[145] = (0x32 ^ 0x6B) + (0xA4 ^ 0xC1) - (98 + 137 - 93 + 1) + (8 ^ 0x6A);
        h.lIIIllIlI[146] = 79 + 33 - -11 + 23;
        h.lIIIllIlI[147] = (0x22 ^ 0x63) + (0x81 ^ 0xAF) - (0xA1 ^ 0xC5) + (39 + 13 - 26 + 110);
        h.lIIIllIlI[148] = 59 + 142 - 144 + 91;
        h.lIIIllIlI[149] = 87 + 2 - 8 + 68;
        h.lIIIllIlI[150] = 50 + 72 - 6 + 34;
        h.lIIIllIlI[151] = 92 + 81 - 164 + 142;
        h.lIIIllIlI[152] = (0xCC ^ 0xBE) + (0x13 ^ 3) - (0xC1 ^ 0x84) + (0x79 ^ 0x22);
        h.lIIIllIlI[153] = 119 + 65 - 86 + 55;
        h.lIIIllIlI[154] = 7 + 135 - -2 + 10;
        h.lIIIllIlI[155] = (0x1D ^ 0x61) + (21 + 92 - 8 + 30) - (0xE7 ^ 0x92) + (0x7B ^ 0x76);
        h.lIIIllIlI[156] = 13 + 138 - 113 + 118;
        h.lIIIllIlI[157] = 118 + 117 - 131 + 53;
        h.lIIIllIlI[158] = (1 ^ 0x70) + (1 ^ 0x50) - (0x68 ^ 0x29) + (0x13 ^ 0xE);
        h.lIIIllIlI[159] = 44 + 111 - 66 + 55 + (0x8C ^ 0xBA) - (0x4B ^ 9) + (0xA4 ^ 0xBF);
        h.lIIIllIlI[160] = 22 + 31 - 37 + 144;
        h.lIIIllIlI[161] = 66 + 126 - 155 + 124;
        h.lIIIllIlI[162] = (0xF0 ^ 0xB5) + (63 + 42 - 44 + 76) - (128 + 43 - 101 + 125) + (94 + 46 - -8 + 3);
        h.lIIIllIlI[163] = 85 + 96 - 148 + 130;
        h.lIIIllIlI[164] = (0x7F ^ 0x28) + (0xEF ^ 0x9B) - (0xFE ^ 0xC2) + (0x5C ^ 0x49);
        h.lIIIllIlI[165] = 40 + 82 - 20 + 63;
        h.lIIIllIlI[166] = (0x48 ^ 0x63) + (0x82 ^ 0xAE) - -(0x49 ^ 1) + (0x7C ^ 0x7B);
        h.lIIIllIlI[167] = 127 + 72 - 33 + 1;
        h.lIIIllIlI[168] = (0x45 ^ 0x67) + (33 + 1 - -29 + 90) - (10 + 21 - -28 + 78) + (0x72 ^ 4);
        h.lIIIllIlI[169] = 88 + 142 - 107 + 46;
        h.lIIIllIlI[170] = 114 + 163 - 273 + 166;
        h.lIIIllIlI[171] = (0x51 ^ 0x1A) + (0xCE ^ 0xA4) - (0xBB ^ 0xAA) + (0x70 ^ 0x77);
        h.lIIIllIlI[172] = (0x5C ^ 0x26) + (0x50 ^ 0x46) - (0x2D ^ 0x5E) + (105 + 9 - 55 + 84);
        h.lIIIllIlI[173] = (7 ^ 0x3E) + (0x13 ^ 0x44) - (0x62 ^ 0x26) + (0x36 ^ 0x57);
        h.lIIIllIlI[174] = 53 + 16 - -43 + 62;
        h.lIIIllIlI[175] = (0x47 ^ 0x4B) + (0xBA ^ 0x85) - -(0x76 ^ 0x65) + (0x97 ^ 0xC6);
        h.lIIIllIlI[176] = 173 + 22 - 99 + 80;
        h.lIIIllIlI[177] = 94 + 0 - 88 + 171;
        h.lIIIllIlI[178] = 17 + 64 - -50 + 47;
        h.lIIIllIlI[179] = (0x19 ^ 0x5B) + (79 + 74 - 70 + 62) - (0x52 ^ 0x21) + (0x13 ^ 0x40);
        h.lIIIllIlI[180] = (0x6B ^ 0x51) + (0x3A ^ 0x73) - (0x3C ^ 0xA) + (0x35 ^ 0x52);
        h.lIIIllIlI[181] = 86 + 150 - 186 + 131;
        h.lIIIllIlI[182] = 8 + 12 - -87 + 75;
        h.lIIIllIlI[183] = 3 + 42 - -61 + 77;
        h.lIIIllIlI[184] = 150 + 49 - 15 + 0;
        h.lIIIllIlI[185] = (0x44 ^ 0x19) + (0xC9 ^ 0x9C) - (0x5E ^ 0x2E) + (0x50 ^ 0x27);
        h.lIIIllIlI[186] = 98 + 176 - 262 + 174;
        h.lIIIllIlI[187] = 22 + 86 - -22 + 57;
        h.lIIIllIlI[188] = 11 + 0 - -103 + 46 + (64 + 3 - -24 + 61) - (92 + 56 - 106 + 95) + (0x92 ^ 0x9F);
        h.lIIIllIlI[189] = 22 + 134 - 99 + 132;
        h.lIIIllIlI[190] = (0x31 ^ 0x1C) + (96 + 78 - 140 + 134) - (126 + 69 - 173 + 171) + (141 + 77 - 79 + 31);
        h.lIIIllIlI[191] = 156 + 83 - 187 + 139;
        h.lIIIllIlI[192] = 171 + 89 - 246 + 164 + (0xB0 ^ 0x9C) - (11 + 20 - -78 + 32) + (0x72 ^ 0x1D);
        h.lIIIllIlI[193] = 33 + 8 - 30 + 182;
        h.lIIIllIlI[194] = 17 + 112 - 93 + 158;
        h.lIIIllIlI[195] = 139 + 115 - 119 + 60;
        h.lIIIllIlI[196] = 141 + 165 - 293 + 183;
        h.lIIIllIlI[197] = (0x1C ^ 0x25) + (50 + 37 - 77 + 159) - (188 + 17 - 144 + 130) + (68 + 34 - 71 + 131);
        h.lIIIllIlI[198] = (2 ^ 0x66) + (0xAC ^ 0xA4) - (0x36 ^ 0x3C) + (0xF7 ^ 0x93);
        h.lIIIllIlI[199] = (0x42 ^ 0x2D) + (0xEF ^ 0xB8) - (87 + 20 - 101 + 158) + (28 + 2 - -69 + 66);
        h.lIIIllIlI[200] = ((0x3B ^ 0x2F) & ~(0xB8 ^ 0xAC)) + (0x25 ^ 0x61) - -(0xDD ^ 0xAB) + (0xCA ^ 0xC4);
        h.lIIIllIlI[201] = 48 + 100 - 37 + 90;
        h.lIIIllIlI[202] = 110 + 102 - 89 + 72 + (0x92 ^ 0xC2) - (0xFFFFE9F7 & 0x170E) + (25 + 165 - 46 + 45);
        h.lIIIllIlI[203] = (0x1D ^ 0x24) + (0x5B ^ 0x23) - (0xB5 ^ 0xBE) + (0x16 ^ 0x33);
        h.lIIIllIlI[204] = (0x28 ^ 4) + (0xB9 ^ 0xA8) - (0x60 ^ 0x55) + (117 + 91 - 136 + 124);
        h.lIIIllIlI[205] = 114 + 7 - 73 + 139 + (0xBC ^ 0xB8) - (0x9F ^ 0xC4) + (0xE1 ^ 0x88);
        h.lIIIllIlI[206] = 10 + 80 - 51 + 167;
        h.lIIIllIlI[207] = 129 + 155 - 114 + 37;
        h.lIIIllIlI[208] = 62 + 118 - 153 + 181;
        h.lIIIllIlI[209] = 194 + 41 - 139 + 113;
        h.lIIIllIlI[210] = (0x9A ^ 0xBE) + (2 ^ 0x51) - (0x91 ^ 0xAC) + (34 + 124 - 103 + 97);
        h.lIIIllIlI[211] = 65 + 164 - 90 + 49 + (117 + 23 - 64 + 81) - (0xFFFFE3F9 & 0x1D5E) + (56 + 209 - 59 + 4);
        h.lIIIllIlI[212] = (0xFA ^ 0x86) + (7 + 17 - 4 + 119) - (154 + 157 - 270 + 171) + (10 + 40 - -94 + 17);
        h.lIIIllIlI[213] = (0x80 ^ 0x87) + (81 + 86 - 111 + 87) - -(0x35 ^ 0x38) + (0xA ^ 0x38);
        h.lIIIllIlI[214] = 212 + 187 - 208 + 23;
        h.lIIIllIlI[215] = 176 + 208 - 293 + 124;
        h.lIIIllIlI[216] = 12 + 70 - 10 + 106 + (78 + 32 - 72 + 94) - (153 + 149 - 132 + 72) + (112 + 114 - 164 + 86);
        h.lIIIllIlI[217] = 45 + 97 - 13 + 88;
        h.lIIIllIlI[218] = (0x16 ^ 0xD) + (0x36 ^ 0x3D) - -(0x1E ^ 4) + (56 + 73 - 25 + 50);
        h.lIIIllIlI[219] = 125 + 157 - 133 + 70;
        h.lIIIllIlI[220] = 146 + 65 - 184 + 193;
        h.lIIIllIlI[221] = (0x6A ^ 0x21) + (83 + 57 - 77 + 64) - (0x2D ^ 0x6B) + (0x7D ^ 0x24);
        h.lIIIllIlI[222] = 174 + 43 - 208 + 213;
        h.lIIIllIlI[223] = (0x62 ^ 0x15) + (111 + 126 - 78 + 15) - (19 + 131 - 31 + 37) + (0xED ^ 0xBB);
        h.lIIIllIlI[224] = 148 + 118 - 264 + 222;
        h.lIIIllIlI[225] = 99 + 49 - 112 + 135 + (0xF8 ^ 0x89) - (6 ^ 0x42) + (0x6A ^ 0x63);
        h.lIIIllIlI[226] = 169 + 28 - -13 + 16;
        h.lIIIllIlI[227] = 192 + 150 - 298 + 183;
        h.lIIIllIlI[228] = 137 + 156 - 256 + 191;
        h.lIIIllIlI[229] = 55 + 80 - 63 + 157;
        h.lIIIllIlI[230] = 144 + 96 - 164 + 154;
        h.lIIIllIlI[231] = (0xB4 ^ 0x8D) + (42 + 59 - -94 + 1) - (0x92 ^ 0xAE) + (0xA ^ 0x2C);
        h.lIIIllIlI[232] = (0x46 ^ 0x5F) + (0xA3 ^ 0x90) - -(0x3C ^ 0x56) + (0xBB ^ 0x89);
        h.lIIIllIlI[233] = (0x6C ^ 0x2F) + (114 + 76 - 77 + 76) - (39 + 94 - -16 + 3) + (61 + 107 - 89 + 50);
        h.lIIIllIlI[234] = 106 + 146 - 139 + 59 + (188 + 225 - 300 + 119) - (0xFFFF915B & 0x6FFF) + (95 + 82 - 129 + 129);
        h.lIIIllIlI[235] = 54 + 108 - 88 + 161;
        h.lIIIllIlI[236] = 10 + 122 - -20 + 36 + (0x6B ^ 0x4B) - (0xD0 ^ 0xA2) + (34 + 31 - 32 + 97);
        h.lIIIllIlI[237] = 9 + 12 - -164 + 12 + (69 + 41 - 64 + 120) - (0xFFFF8DFF & 0x731A) + (53 + 69 - 80 + 114);
        h.lIIIllIlI[238] = 72 + 11 - -125 + 30;
        h.lIIIllIlI[239] = (0x7D ^ 0x6F) + (109 + 110 - 97 + 71) - (0xE7 ^ 0xB8) + (0x5E ^ 0x25);
        h.lIIIllIlI[240] = (0x4E ^ 0x2F) + (150 + 27 - 86 + 91) - (0xE5 ^ 0xBC) + (0x16 ^ 0x24);
        h.lIIIllIlI[241] = 216 + 212 - 227 + 32 + (182 + 70 - 172 + 115) - (95 + 74 - 45 + 66) + 3;
        h.lIIIllIlI[242] = 180 + 35 - 208 + 210 + (46 + 106 - 27 + 12) - (0x25 ^ 0x55) + ((0x53 ^ 0x32) & ~(0x44 ^ 0x25));
        h.lIIIllIlI[243] = 57 + 175 - 21 + 32;
        h.lIIIllIlI[244] = 144 + 201 - 119 + 18;
        h.lIIIllIlI[245] = 4 + 102 - 69 + 90 + (52 + 19 - -43 + 24) - (1 ^ 0x7A) + (0xC8 ^ 0xAF);
        h.lIIIllIlI[246] = (0x51 ^ 0x35) + (3 + 56 - -96 + 12) - (0x16 ^ 8) + (0x73 ^ 0x7A);
        h.lIIIllIlI[247] = 188 + 95 - 103 + 67;
        h.lIIIllIlI[248] = (0x36 ^ 0x7A) + (0x68 ^ 0x39) - -(0x2B ^ 7) + (0xA4 ^ 0x8B);
        h.lIIIllIlI[249] = 129 + 165 - 207 + 162;
        h.lIIIllIlI[250] = 121 + 79 - -14 + 3 + (127 + 23 - 49 + 52) - (0xFFFFB17D & 0x4FD7) + (96 + 14 - -49 + 62);
        h.lIIIllIlI[251] = 32 + 63 - 60 + 139 + (0xED ^ 0x88) - (19 + 90 - 75 + 109) + (0xFA ^ 0x8D);
        h.lIIIllIlI[252] = 44 + 76 - -42 + 90;
    }

    public String P() {
        return this.answer;
    }

    private static boolean lllIlIlIlIl(int n2, int n3) {
        return n2 < n3;
    }

    public String O() {
        return this.question;
    }

    /*
     * WARNING - void declaration
     */
    public static Widget a(String string, WidgetInfo ... widgetInfoArray) {
        void lIIIllIlIllllIl;
        String string2 = MATCHES.get(string);
        WidgetInfo[] widgetInfoArray2 = widgetInfoArray;
        int n2 = widgetInfoArray.length;
        int lIIIllIlIllllII = lIIIllIlI[0];
        while (h.lllIlIlIlIl(lIIIllIlIllllII, (int)lIIIllIlIllllIl)) {
            void lIIIllIlIllllll;
            void lIIIllIlIlllllI;
            void lIIIllIlIlllIll = lIIIllIlIlllllI[lIIIllIlIllllII];
            Widget lIIIllIlIlllIlI = Widgets.get((WidgetInfo)lIIIllIlIlllIll);
            if (h.lllIlIlIllI(lIIIllIlIlllIlI) && h.lllIlIlIlll(lIIIllIlIlllIlI.getText().equals(lIIIllIlIllllll) ? 1 : 0)) {
                return lIIIllIlIlllIlI;
            }
            ++lIIIllIlIllllII;
            0;
            if ((0x70 ^ 0x74) > -1) continue;
            return null;
        }
        return null;
    }

    /*
     * WARNING - void declaration
     */
    static {
        block1: {
            void lIIIllIlIllIIlI;
            h.lllIlIlIlII();
            h.lllIlIlIIll();
            LIZARD_1 = new h(lIIIlIllI[lIIIllIlI[1]], lIIIlIllI[lIIIllIlI[2]]);
            LIZARD_2 = new h(lIIIlIllI[lIIIllIlI[4]], lIIIlIllI[lIIIllIlI[5]]);
            LIZARD_3 = new h(lIIIlIllI[lIIIllIlI[7]], lIIIlIllI[lIIIllIlI[8]]);
            LIZARD_4 = new h(lIIIlIllI[lIIIllIlI[10]], lIIIlIllI[lIIIllIlI[11]]);
            LIZARD_5 = new h(lIIIlIllI[lIIIllIlI[13]], lIIIlIllI[lIIIllIlI[14]]);
            LIZARD_6 = new h(lIIIlIllI[lIIIllIlI[16]], lIIIlIllI[lIIIllIlI[17]]);
            TORTOISE_1 = new h(lIIIlIllI[lIIIllIlI[19]], lIIIlIllI[lIIIllIlI[20]]);
            TORTOISE_2 = new h(lIIIlIllI[lIIIllIlI[22]], lIIIlIllI[lIIIllIlI[23]]);
            TORTOISE_3 = new h(lIIIlIllI[lIIIllIlI[25]], lIIIlIllI[lIIIllIlI[26]]);
            TORTOISE_4 = new h(lIIIlIllI[lIIIllIlI[28]], lIIIlIllI[lIIIllIlI[29]]);
            TORTOISE_5 = new h(lIIIlIllI[lIIIllIlI[31]], lIIIlIllI[lIIIllIlI[32]]);
            TORTOISE_6 = new h(lIIIlIllI[lIIIllIlI[34]], lIIIlIllI[lIIIllIlI[35]]);
            DRAGON_1 = new h(lIIIlIllI[lIIIllIlI[37]], lIIIlIllI[lIIIllIlI[38]]);
            DRAGON_2 = new h(lIIIlIllI[lIIIllIlI[40]], lIIIlIllI[lIIIllIlI[41]]);
            DRAGON_3 = new h(lIIIlIllI[lIIIllIlI[43]], lIIIlIllI[lIIIllIlI[44]]);
            DRAGON_4 = new h(lIIIlIllI[lIIIllIlI[46]], lIIIlIllI[lIIIllIlI[47]]);
            DRAGON_5 = new h(lIIIlIllI[lIIIllIlI[49]], lIIIlIllI[lIIIllIlI[50]]);
            DRAGON_6 = new h(lIIIlIllI[lIIIllIlI[52]], lIIIlIllI[lIIIllIlI[53]]);
            WYVERN_1 = new h(lIIIlIllI[lIIIllIlI[55]], lIIIlIllI[lIIIllIlI[56]]);
            WYVERN_2 = new h(lIIIlIllI[lIIIllIlI[58]], lIIIlIllI[lIIIllIlI[59]]);
            WYVERN_3 = new h(lIIIlIllI[lIIIllIlI[61]], lIIIlIllI[lIIIllIlI[62]]);
            WYVERN_4 = new h(lIIIlIllI[lIIIllIlI[64]], lIIIlIllI[lIIIllIlI[65]]);
            WYVERN_5 = new h(lIIIlIllI[lIIIllIlI[67]], lIIIlIllI[lIIIllIlI[68]]);
            WYVERN_6 = new h(lIIIlIllI[lIIIllIlI[70]], lIIIlIllI[lIIIllIlI[71]]);
            SNAIL_1 = new h(lIIIlIllI[lIIIllIlI[73]], lIIIlIllI[lIIIllIlI[74]]);
            SNAIL_2 = new h(lIIIlIllI[lIIIllIlI[76]], lIIIlIllI[lIIIllIlI[77]]);
            SNAIL_3 = new h(lIIIlIllI[lIIIllIlI[79]], lIIIlIllI[lIIIllIlI[80]]);
            SNAIL_4 = new h(lIIIlIllI[lIIIllIlI[82]], lIIIlIllI[lIIIllIlI[83]]);
            SNAIL_5 = new h(lIIIlIllI[lIIIllIlI[85]], lIIIlIllI[lIIIllIlI[86]]);
            SNAIL_6 = new h(lIIIlIllI[lIIIllIlI[88]], lIIIlIllI[lIIIllIlI[89]]);
            SNAKE_1 = new h(lIIIlIllI[lIIIllIlI[91]], lIIIlIllI[lIIIllIlI[92]]);
            SNAKE_2 = new h(lIIIlIllI[lIIIllIlI[94]], lIIIlIllI[lIIIllIlI[95]]);
            SNAKE_3 = new h(lIIIlIllI[lIIIllIlI[97]], lIIIlIllI[lIIIllIlI[98]]);
            SNAKE_4 = new h(lIIIlIllI[lIIIllIlI[100]], lIIIlIllI[lIIIllIlI[101]]);
            SNAKE_5 = new h(lIIIlIllI[lIIIllIlI[103]], lIIIlIllI[lIIIllIlI[104]]);
            SNAKE_6 = new h(lIIIlIllI[lIIIllIlI[106]], lIIIlIllI[lIIIllIlI[107]]);
            SLUG_1 = new h(lIIIlIllI[lIIIllIlI[109]], lIIIlIllI[lIIIllIlI[110]]);
            SLUG_2 = new h(lIIIlIllI[lIIIllIlI[112]], lIIIlIllI[lIIIllIlI[113]]);
            SLUG_3 = new h(lIIIlIllI[lIIIllIlI[115]], lIIIlIllI[lIIIllIlI[116]]);
            SLUG_4 = new h(lIIIlIllI[lIIIllIlI[118]], lIIIlIllI[lIIIllIlI[119]]);
            SLUG_5 = new h(lIIIlIllI[lIIIllIlI[121]], lIIIlIllI[lIIIllIlI[122]]);
            SLUG_6 = new h(lIIIlIllI[lIIIllIlI[124]], lIIIlIllI[lIIIllIlI[125]]);
            MONKEY_1 = new h(lIIIlIllI[lIIIllIlI[127]], lIIIlIllI[lIIIllIlI[128]]);
            MONKEY_2 = new h(lIIIlIllI[lIIIllIlI[130]], lIIIlIllI[lIIIllIlI[131]]);
            MONKEY_3 = new h(lIIIlIllI[lIIIllIlI[133]], lIIIlIllI[lIIIllIlI[134]]);
            MONKEY_4 = new h(lIIIlIllI[lIIIllIlI[136]], lIIIlIllI[lIIIllIlI[137]]);
            MONKEY_5 = new h(lIIIlIllI[lIIIllIlI[139]], lIIIlIllI[lIIIllIlI[140]]);
            MONKEY_6 = new h(lIIIlIllI[lIIIllIlI[142]], lIIIlIllI[lIIIllIlI[143]]);
            KALPHITE_1 = new h(lIIIlIllI[lIIIllIlI[145]], lIIIlIllI[lIIIllIlI[146]]);
            KALPHITE_2 = new h(lIIIlIllI[lIIIllIlI[148]], lIIIlIllI[lIIIllIlI[149]]);
            KALPHITE_3 = new h(lIIIlIllI[lIIIllIlI[151]], lIIIlIllI[lIIIllIlI[152]]);
            KALPHITE_4 = new h(lIIIlIllI[lIIIllIlI[154]], lIIIlIllI[lIIIllIlI[155]]);
            KALPHITE_5 = new h(lIIIlIllI[lIIIllIlI[157]], lIIIlIllI[lIIIllIlI[158]]);
            KALPHITE_6 = new h(lIIIlIllI[lIIIllIlI[160]], lIIIlIllI[lIIIllIlI[161]]);
            TERRORBIRD_1 = new h(lIIIlIllI[lIIIllIlI[163]], lIIIlIllI[lIIIllIlI[164]]);
            TERRORBIRD_2 = new h(lIIIlIllI[lIIIllIlI[166]], lIIIlIllI[lIIIllIlI[167]]);
            TERRORBIRD_3 = new h(lIIIlIllI[lIIIllIlI[169]], lIIIlIllI[lIIIllIlI[170]]);
            TERRORBIRD_4 = new h(lIIIlIllI[lIIIllIlI[172]], lIIIlIllI[lIIIllIlI[173]]);
            TERRORBIRD_5 = new h(lIIIlIllI[lIIIllIlI[175]], lIIIlIllI[lIIIllIlI[176]]);
            TERRORBIRD_6 = new h(lIIIlIllI[lIIIllIlI[178]], lIIIlIllI[lIIIllIlI[179]]);
            PENGUIN_1 = new h(lIIIlIllI[lIIIllIlI[181]], lIIIlIllI[lIIIllIlI[182]]);
            PENGUIN_2 = new h(lIIIlIllI[lIIIllIlI[184]], lIIIlIllI[lIIIllIlI[185]]);
            PENGUIN_3 = new h(lIIIlIllI[lIIIllIlI[187]], lIIIlIllI[lIIIllIlI[188]]);
            PENGUIN_4 = new h(lIIIlIllI[lIIIllIlI[190]], lIIIlIllI[lIIIllIlI[191]]);
            PENGUIN_5 = new h(lIIIlIllI[lIIIllIlI[193]], lIIIlIllI[lIIIllIlI[194]]);
            PENGUIN_6 = new h(lIIIlIllI[lIIIllIlI[196]], lIIIlIllI[lIIIllIlI[197]]);
            MOLE_1 = new h(lIIIlIllI[lIIIllIlI[199]], lIIIlIllI[lIIIllIlI[200]]);
            MOLE_2 = new h(lIIIlIllI[lIIIllIlI[202]], lIIIlIllI[lIIIllIlI[203]]);
            MOLE_3 = new h(lIIIlIllI[lIIIllIlI[205]], lIIIlIllI[lIIIllIlI[206]]);
            MOLE_4 = new h(lIIIlIllI[lIIIllIlI[208]], lIIIlIllI[lIIIllIlI[209]]);
            MOLE_5 = new h(lIIIlIllI[lIIIllIlI[211]], lIIIlIllI[lIIIllIlI[212]]);
            MOLE_6 = new h(lIIIlIllI[lIIIllIlI[214]], lIIIlIllI[lIIIllIlI[215]]);
            CAMEL_1 = new h(lIIIlIllI[lIIIllIlI[217]], lIIIlIllI[lIIIllIlI[218]]);
            CAMEL_2 = new h(lIIIlIllI[lIIIllIlI[220]], lIIIlIllI[lIIIllIlI[221]]);
            CAMEL_3 = new h(lIIIlIllI[lIIIllIlI[223]], lIIIlIllI[lIIIllIlI[224]]);
            CAMEL_4 = new h(lIIIlIllI[lIIIllIlI[226]], lIIIlIllI[lIIIllIlI[227]]);
            CAMEL_5 = new h(lIIIlIllI[lIIIllIlI[229]], lIIIlIllI[lIIIllIlI[230]]);
            CAMEL_6 = new h(lIIIlIllI[lIIIllIlI[232]], lIIIlIllI[lIIIllIlI[233]]);
            LEECH_1 = new h(lIIIlIllI[lIIIllIlI[235]], lIIIlIllI[lIIIllIlI[236]]);
            LEECH_2 = new h(lIIIlIllI[lIIIllIlI[238]], lIIIlIllI[lIIIllIlI[239]]);
            LEECH_3 = new h(lIIIlIllI[lIIIllIlI[241]], lIIIlIllI[lIIIllIlI[242]]);
            LEECH_4 = new h(lIIIlIllI[lIIIllIlI[244]], lIIIlIllI[lIIIllIlI[245]]);
            LEECH_5 = new h(lIIIlIllI[lIIIllIlI[247]], lIIIlIllI[lIIIllIlI[248]]);
            LEECH_6 = new h(lIIIlIllI[lIIIllIlI[250]], lIIIlIllI[lIIIllIlI[251]]);
            h[] hArray = new h[lIIIllIlI[84]];
            hArray[h.lIIIllIlI[0]] = LIZARD_1;
            hArray[h.lIIIllIlI[1]] = LIZARD_2;
            hArray[h.lIIIllIlI[2]] = LIZARD_3;
            hArray[h.lIIIllIlI[3]] = LIZARD_4;
            hArray[h.lIIIllIlI[4]] = LIZARD_5;
            hArray[h.lIIIllIlI[5]] = LIZARD_6;
            hArray[h.lIIIllIlI[6]] = TORTOISE_1;
            hArray[h.lIIIllIlI[7]] = TORTOISE_2;
            hArray[h.lIIIllIlI[8]] = TORTOISE_3;
            hArray[h.lIIIllIlI[9]] = TORTOISE_4;
            hArray[h.lIIIllIlI[10]] = TORTOISE_5;
            hArray[h.lIIIllIlI[11]] = TORTOISE_6;
            hArray[h.lIIIllIlI[12]] = DRAGON_1;
            hArray[h.lIIIllIlI[13]] = DRAGON_2;
            hArray[h.lIIIllIlI[14]] = DRAGON_3;
            hArray[h.lIIIllIlI[15]] = DRAGON_4;
            hArray[h.lIIIllIlI[16]] = DRAGON_5;
            hArray[h.lIIIllIlI[17]] = DRAGON_6;
            hArray[h.lIIIllIlI[18]] = WYVERN_1;
            hArray[h.lIIIllIlI[19]] = WYVERN_2;
            hArray[h.lIIIllIlI[20]] = WYVERN_3;
            hArray[h.lIIIllIlI[21]] = WYVERN_4;
            hArray[h.lIIIllIlI[22]] = WYVERN_5;
            hArray[h.lIIIllIlI[23]] = WYVERN_6;
            hArray[h.lIIIllIlI[24]] = SNAIL_1;
            hArray[h.lIIIllIlI[25]] = SNAIL_2;
            hArray[h.lIIIllIlI[26]] = SNAIL_3;
            hArray[h.lIIIllIlI[27]] = SNAIL_4;
            hArray[h.lIIIllIlI[28]] = SNAIL_5;
            hArray[h.lIIIllIlI[29]] = SNAIL_6;
            hArray[h.lIIIllIlI[30]] = SNAKE_1;
            hArray[h.lIIIllIlI[31]] = SNAKE_2;
            hArray[h.lIIIllIlI[32]] = SNAKE_3;
            hArray[h.lIIIllIlI[33]] = SNAKE_4;
            hArray[h.lIIIllIlI[34]] = SNAKE_5;
            hArray[h.lIIIllIlI[35]] = SNAKE_6;
            hArray[h.lIIIllIlI[36]] = SLUG_1;
            hArray[h.lIIIllIlI[37]] = SLUG_2;
            hArray[h.lIIIllIlI[38]] = SLUG_3;
            hArray[h.lIIIllIlI[39]] = SLUG_4;
            hArray[h.lIIIllIlI[40]] = SLUG_5;
            hArray[h.lIIIllIlI[41]] = SLUG_6;
            hArray[h.lIIIllIlI[42]] = MONKEY_1;
            hArray[h.lIIIllIlI[43]] = MONKEY_2;
            hArray[h.lIIIllIlI[44]] = MONKEY_3;
            hArray[h.lIIIllIlI[45]] = MONKEY_4;
            hArray[h.lIIIllIlI[46]] = MONKEY_5;
            hArray[h.lIIIllIlI[47]] = MONKEY_6;
            hArray[h.lIIIllIlI[48]] = KALPHITE_1;
            hArray[h.lIIIllIlI[49]] = KALPHITE_2;
            hArray[h.lIIIllIlI[50]] = KALPHITE_3;
            hArray[h.lIIIllIlI[51]] = KALPHITE_4;
            hArray[h.lIIIllIlI[52]] = KALPHITE_5;
            hArray[h.lIIIllIlI[53]] = KALPHITE_6;
            hArray[h.lIIIllIlI[54]] = TERRORBIRD_1;
            hArray[h.lIIIllIlI[55]] = TERRORBIRD_2;
            hArray[h.lIIIllIlI[56]] = TERRORBIRD_3;
            hArray[h.lIIIllIlI[57]] = TERRORBIRD_4;
            hArray[h.lIIIllIlI[58]] = TERRORBIRD_5;
            hArray[h.lIIIllIlI[59]] = TERRORBIRD_6;
            hArray[h.lIIIllIlI[60]] = PENGUIN_1;
            hArray[h.lIIIllIlI[61]] = PENGUIN_2;
            hArray[h.lIIIllIlI[62]] = PENGUIN_3;
            hArray[h.lIIIllIlI[63]] = PENGUIN_4;
            hArray[h.lIIIllIlI[64]] = PENGUIN_5;
            hArray[h.lIIIllIlI[65]] = PENGUIN_6;
            hArray[h.lIIIllIlI[66]] = MOLE_1;
            hArray[h.lIIIllIlI[67]] = MOLE_2;
            hArray[h.lIIIllIlI[68]] = MOLE_3;
            hArray[h.lIIIllIlI[69]] = MOLE_4;
            hArray[h.lIIIllIlI[70]] = MOLE_5;
            hArray[h.lIIIllIlI[71]] = MOLE_6;
            hArray[h.lIIIllIlI[72]] = CAMEL_1;
            hArray[h.lIIIllIlI[73]] = CAMEL_2;
            hArray[h.lIIIllIlI[74]] = CAMEL_3;
            hArray[h.lIIIllIlI[75]] = CAMEL_4;
            hArray[h.lIIIllIlI[76]] = CAMEL_5;
            hArray[h.lIIIllIlI[77]] = CAMEL_6;
            hArray[h.lIIIllIlI[78]] = LEECH_1;
            hArray[h.lIIIllIlI[79]] = LEECH_2;
            hArray[h.lIIIllIlI[80]] = LEECH_3;
            hArray[h.lIIIllIlI[81]] = LEECH_4;
            hArray[h.lIIIllIlI[82]] = LEECH_5;
            hArray[h.lIIIllIlI[83]] = LEECH_6;
            $VALUES = hArray;
            ImmutableMap.Builder builder = new ImmutableMap.Builder();
            h[] hArray2 = h.values();
            int n2 = hArray2.length;
            int lIIIllIlIllIIIl = lIIIllIlI[0];
            while (h.lllIlIlIlIl(lIIIllIlIllIIIl, (int)lIIIllIlIllIIlI)) {
                void lIIIllIlIllIlII;
                void lIIIllIlIllIIll;
                void lIIIllIlIllIIII = lIIIllIlIllIIll[lIIIllIlIllIIIl];
                lIIIllIlIllIlII.put((Object)lIIIllIlIllIIII.question, (Object)lIIIllIlIllIIII.answer);
                0;
                ++lIIIllIlIllIIIl;
                0;
                if ((0x3A ^ 0x3E) == (0xC5 ^ 0xC1)) continue;
                break block1;
            }
            MATCHES = builder.build();
        }
    }

    private static boolean lllIlIlIllI(Object object) {
        return object != null;
    }

    private static boolean lllIlIlIlll(int n2) {
        return n2 != 0;
    }

    private static void lllIlIlIIll() {
        lIIIlIllI = new String[lIIIllIlI[252]];
        h.lIIIlIllI[h.lIIIllIlI[0]] = h."LIZARD_1";
        h.lIIIlIllI[h.lIIIllIlI[1]] = h."How does a lizard regulate body heat?";
        h.lIIIlIllI[h.lIIIllIlI[2]] = h."Sunlight.";
        h.lIIIlIllI[h.lIIIllIlI[3]] = h."LIZARD_2";
        h.lIIIlIllI[h.lIIIllIlI[4]] = h."Who discovered how to kill lizards?";
        h.lIIIlIllI[h.lIIIllIlI[5]] = h."The Slayer Masters.";
        h.lIIIlIllI[h.lIIIllIlI[6]] = h."LIZARD_3";
        h.lIIIlIllI[h.lIIIllIlI[7]] = h."How many eyes does a lizard have?";
        h.lIIIlIllI[h.lIIIllIlI[8]] = h."Three.";
        h.lIIIlIllI[h.lIIIllIlI[9]] = h."LIZARD_4";
        h.lIIIlIllI[h.lIIIllIlI[10]] = h."What order do lizards belong to?";
        h.lIIIlIllI[h.lIIIllIlI[11]] = h."Squamata.";
        h.lIIIlIllI[h.lIIIllIlI[12]] = h."LIZARD_5";
        h.lIIIlIllI[h.lIIIllIlI[13]] = h."What happens when a lizard becomes cold?";
        h.lIIIlIllI[h.lIIIllIlI[14]] = h."It becomes sleepy.";
        h.lIIIlIllI[h.lIIIllIlI[15]] = h."LIZARD_6";
        h.lIIIlIllI[h.lIIIllIlI[16]] = h."Lizard skin is made of the same substance as?";
        h.lIIIlIllI[h.lIIIllIlI[17]] = h."Hair.";
        h.lIIIlIllI[h.lIIIllIlI[18]] = h."TORTOISE_1";
        h.lIIIlIllI[h.lIIIllIlI[19]] = h."What is the name of the oldest tortoise ever recorded?";
        h.lIIIlIllI[h.lIIIllIlI[20]] = h."Mibbiwocket.";
        h.lIIIlIllI[h.lIIIllIlI[21]] = h."TORTOISE_2";
        h.lIIIlIllI[h.lIIIllIlI[22]] = h."What is a tortoise's favourite food?";
        h.lIIIlIllI[h.lIIIllIlI[23]] = h."Vegetables.";
        h.lIIIlIllI[h.lIIIllIlI[24]] = h."TORTOISE_3";
        h.lIIIlIllI[h.lIIIllIlI[25]] = h."Name the explorer who discovered the world's oldest tortoise.";
        h.lIIIlIllI[h.lIIIllIlI[26]] = h."Admiral Bake.";
        h.lIIIlIllI[h.lIIIllIlI[27]] = h."TORTOISE_4";
        h.lIIIlIllI[h.lIIIllIlI[28]] = h."How does the tortoise protect itself?";
        h.lIIIlIllI[h.lIIIllIlI[29]] = h."Hard shell.";
        h.lIIIlIllI[h.lIIIllIlI[30]] = h."TORTOISE_5";
        h.lIIIlIllI[h.lIIIllIlI[31]] = h."If a tortoise had twenty rings on its shell, how old would it be?";
        h.lIIIlIllI[h.lIIIllIlI[32]] = h."Twenty years.";
        h.lIIIlIllI[h.lIIIllIlI[33]] = h."TORTOISE_6";
        h.lIIIlIllI[h.lIIIllIlI[34]] = h."Which race breeds tortoises for battle?";
        h.lIIIlIllI[h.lIIIllIlI[35]] = h."Gnomes.";
        h.lIIIlIllI[h.lIIIllIlI[36]] = h."DRAGON_1";
        h.lIIIlIllI[h.lIIIllIlI[37]] = h."What is considered a delicacy by dragons?";
        h.lIIIlIllI[h.lIIIllIlI[38]] = h."Runite.";
        h.lIIIlIllI[h.lIIIllIlI[39]] = h."DRAGON_2";
        h.lIIIlIllI[h.lIIIllIlI[40]] = h."What is the best defence against a dragon's attack?";
        h.lIIIlIllI[h.lIIIllIlI[41]] = h."Anti dragon-breath shield.";
        h.lIIIlIllI[h.lIIIllIlI[42]] = h."DRAGON_3";
        h.lIIIlIllI[h.lIIIllIlI[43]] = h."How long do dragons live?";
        h.lIIIlIllI[h.lIIIllIlI[44]] = h."Unknown.";
        h.lIIIlIllI[h.lIIIllIlI[45]] = h."DRAGON_4";
        h.lIIIlIllI[h.lIIIllIlI[46]] = h."Which of these is not a type of dragon?";
        h.lIIIlIllI[h.lIIIllIlI[47]] = h."Elemental.";
        h.lIIIlIllI[h.lIIIllIlI[48]] = h."DRAGON_5";
        h.lIIIlIllI[h.lIIIllIlI[49]] = h."What is the favoured territory of a dragon?";
        h.lIIIlIllI[h.lIIIllIlI[50]] = h."Old battle sites.";
        h.lIIIlIllI[h.lIIIllIlI[51]] = h."DRAGON_6";
        h.lIIIlIllI[h.lIIIllIlI[52]] = h."Approximately how many feet tall do dragons stand?";
        h.lIIIlIllI[h.lIIIllIlI[53]] = h."Twelve.";
        h.lIIIlIllI[h.lIIIllIlI[54]] = h."WYVERN_1";
        h.lIIIlIllI[h.lIIIllIlI[55]] = h."How did the wyverns die out?";
        h.lIIIlIllI[h.lIIIllIlI[56]] = h."Climate change.";
        h.lIIIlIllI[h.lIIIllIlI[57]] = h."WYVERN_2";
        h.lIIIlIllI[h.lIIIllIlI[58]] = h."How many legs does a wyvern have?";
        h.lIIIlIllI[h.lIIIllIlI[59]] = h."Two.";
        h.lIIIlIllI[h.lIIIllIlI[60]] = h."WYVERN_3";
        h.lIIIlIllI[h.lIIIllIlI[61]] = h."Where have wyvern bones been found?";
        h.lIIIlIllI[h.lIIIllIlI[62]] = h."Asgarnia.";
        h.lIIIlIllI[h.lIIIllIlI[63]] = h."WYVERN_4";
        h.lIIIlIllI[h.lIIIllIlI[64]] = h."Which genus does the wyvern theoretically belong to?";
        h.lIIIlIllI[h.lIIIllIlI[65]] = h."Reptiles.";
        h.lIIIlIllI[h.lIIIllIlI[66]] = h."WYVERN_5";
        h.lIIIlIllI[h.lIIIllIlI[67]] = h."What are the wyverns' closest relations?";
        h.lIIIlIllI[h.lIIIllIlI[68]] = h."Dragons.";
        h.lIIIlIllI[h.lIIIllIlI[69]] = h."WYVERN_6";
        h.lIIIlIllI[h.lIIIllIlI[70]] = h."What is the ambient temperature of wyvern bones?";
        h.lIIIlIllI[h.lIIIllIlI[71]] = h."Below room temperature.";
        h.lIIIlIllI[h.lIIIllIlI[72]] = h."SNAIL_1";
        h.lIIIlIllI[h.lIIIllIlI[73]] = h."What is special about the shell of the giant Morytanian snail?";
        h.lIIIlIllI[h.lIIIllIlI[74]] = h."It is resistant to acid.";
        h.lIIIlIllI[h.lIIIllIlI[75]] = h."SNAIL_2";
        h.lIIIlIllI[h.lIIIllIlI[76]] = h."How do Morytanian snails capture their prey?";
        h.lIIIlIllI[h.lIIIllIlI[77]] = h."Spitting acid.";
        h.lIIIlIllI[h.lIIIllIlI[78]] = h."SNAIL_3";
        h.lIIIlIllI[h.lIIIllIlI[79]] = h."Which of these is a snail byproduct?";
        h.lIIIlIllI[h.lIIIllIlI[80]] = h."Fireproof oil.";
        h.lIIIlIllI[h.lIIIllIlI[81]] = h."SNAIL_4";
        h.lIIIlIllI[h.lIIIllIlI[82]] = h."What does 'Achatina Acidia' mean?";
        h.lIIIlIllI[h.lIIIllIlI[83]] = h."Acid-spitting snail.";
        h.lIIIlIllI[h.lIIIllIlI[84]] = h."SNAIL_5";
        h.lIIIlIllI[h.lIIIllIlI[85]] = h."How do snails move?";
        h.lIIIlIllI[h.lIIIllIlI[86]] = h."Contracting and stretching.";
        h.lIIIlIllI[h.lIIIllIlI[87]] = h."SNAIL_6";
        h.lIIIlIllI[h.lIIIllIlI[88]] = h."What is the 'trapdoor', which snails use to cover the entrance to their shells called?";
        h.lIIIlIllI[h.lIIIllIlI[89]] = h."An operculum.";
        h.lIIIlIllI[h.lIIIllIlI[90]] = h."SNAKE_1";
        h.lIIIlIllI[h.lIIIllIlI[91]] = h."What is snake venom adapted from?";
        h.lIIIlIllI[h.lIIIllIlI[92]] = h."Stomach acid.";
        h.lIIIlIllI[h.lIIIllIlI[93]] = h."SNAKE_2";
        h.lIIIlIllI[h.lIIIllIlI[94]] = h."Aside from their noses, what do snakes use to smell?";
        h.lIIIlIllI[h.lIIIllIlI[95]] = h."Tongue.";
        h.lIIIlIllI[h.lIIIllIlI[96]] = h."SNAKE_3";
        h.lIIIlIllI[h.lIIIllIlI[97]] = h."If a snake sticks its tongue out at you, what is it doing?";
        h.lIIIlIllI[h.lIIIllIlI[98]] = h."Seeing how you smell.";
        h.lIIIlIllI[h.lIIIllIlI[99]] = h."SNAKE_4";
        h.lIIIlIllI[h.lIIIllIlI[100]] = h."If some snakes use venom to kill their prey, what do other snakes use?";
        h.lIIIlIllI[h.lIIIllIlI[101]] = h."Constriction.";
        h.lIIIlIllI[h.lIIIllIlI[102]] = h."SNAKE_5";
        h.lIIIlIllI[h.lIIIllIlI[103]] = h."Lizards and snakes belong to the same order - what is it?";
        h.lIIIlIllI[h.lIIIllIlI[104]] = h."Squamata.";
        h.lIIIlIllI[h.lIIIllIlI[105]] = h."SNAKE_6";
        h.lIIIlIllI[h.lIIIllIlI[106]] = h."Which habitat do snakes prefer?";
        h.lIIIlIllI[h.lIIIllIlI[107]] = h."Anywhere.";
        h.lIIIlIllI[h.lIIIllIlI[108]] = h."SLUG_1";
        h.lIIIlIllI[h.lIIIllIlI[109]] = h."We assume that sea slugs have a stinging organ on their soft skin - what is it called?";
        h.lIIIlIllI[h.lIIIllIlI[110]] = h."Nematocysts.";
        h.lIIIlIllI[h.lIIIllIlI[111]] = h."SLUG_2";
        h.lIIIlIllI[h.lIIIllIlI[112]] = h."Why has the museum never examined a live sea slug?";
        h.lIIIlIllI[h.lIIIllIlI[113]] = h."The researchers keep vanishing.";
        h.lIIIlIllI[h.lIIIllIlI[114]] = h."SLUG_3";
        h.lIIIlIllI[h.lIIIllIlI[115]] = h."What do we think the sea slug feeds upon?";
        h.lIIIlIllI[h.lIIIllIlI[116]] = h."Seaweed.";
        h.lIIIlIllI[h.lIIIllIlI[117]] = h."SLUG_4";
        h.lIIIlIllI[h.lIIIllIlI[118]] = h."What are the two fangs presumed to be used for?";
        h.lIIIlIllI[h.lIIIllIlI[119]] = h."Defense or display.";
        h.lIIIlIllI[h.lIIIllIlI[120]] = h."SLUG_5";
        h.lIIIlIllI[h.lIIIllIlI[121]] = h."Off of which coastline would you find sea slugs?";
        h.lIIIlIllI[h.lIIIllIlI[122]] = h."Ardougne.";
        h.lIIIlIllI[h.lIIIllIlI[123]] = h."SLUG_6";
        h.lIIIlIllI[h.lIIIllIlI[124]] = h."In what way are sea slugs similar to snails?";
        h.lIIIlIllI[h.lIIIllIlI[125]] = h."They have a hard shell.";
        h.lIIIlIllI[h.lIIIllIlI[126]] = h."MONKEY_1";
        h.lIIIlIllI[h.lIIIllIlI[127]] = h."Which type of primates do monkeys belong to?";
        h.lIIIlIllI[h.lIIIllIlI[128]] = h."Simian.";
        h.lIIIlIllI[h.lIIIllIlI[129]] = h."MONKEY_2";
        h.lIIIlIllI[h.lIIIllIlI[130]] = h."Which have the lighter colour: Karamjan or Harmless monkeys?";
        h.lIIIlIllI[h.lIIIllIlI[131]] = h."Harmless.";
        h.lIIIlIllI[h.lIIIllIlI[132]] = h."MONKEY_3";
        h.lIIIlIllI[h.lIIIllIlI[133]] = h."Monkeys love bananas. What else do they like to eat?";
        h.lIIIlIllI[h.lIIIllIlI[134]] = h."Bitternuts.";
        h.lIIIlIllI[h.lIIIllIlI[135]] = h."MONKEY_4";
        h.lIIIlIllI[h.lIIIllIlI[136]] = h."There are two known families of monkeys. One is Karamjan, the other is...?";
        h.lIIIlIllI[h.lIIIllIlI[137]] = h."Harmless.";
        h.lIIIlIllI[h.lIIIllIlI[138]] = h."MONKEY_5";
        h.lIIIlIllI[h.lIIIllIlI[139]] = h."What colour mohawk do Karamjan monkeys have?";
        h.lIIIlIllI[h.lIIIllIlI[140]] = h."Red.";
        h.lIIIlIllI[h.lIIIllIlI[141]] = h."MONKEY_6";
        h.lIIIlIllI[h.lIIIllIlI[142]] = h."What have Karamjan monkeys taken a deep dislike to?";
        h.lIIIlIllI[h.lIIIllIlI[143]] = h."Seaweed.";
        h.lIIIlIllI[h.lIIIllIlI[144]] = h."KALPHITE_1";
        h.lIIIlIllI[h.lIIIllIlI[145]] = h."Kalphites are ruled by a...?";
        h.lIIIlIllI[h.lIIIllIlI[146]] = h."Pasha.";
        h.lIIIlIllI[h.lIIIllIlI[147]] = h."KALPHITE_2";
        h.lIIIlIllI[h.lIIIllIlI[148]] = h."What is the lowest caste in kalphite society?";
        h.lIIIlIllI[h.lIIIllIlI[149]] = h."Worker.";
        h.lIIIlIllI[h.lIIIllIlI[150]] = h."KALPHITE_3";
        h.lIIIlIllI[h.lIIIllIlI[151]] = h."What are the armoured plates on a kalphite called?";
        h.lIIIlIllI[h.lIIIllIlI[152]] = h."Lamellae.";
        h.lIIIlIllI[h.lIIIllIlI[153]] = h."KALPHITE_4";
        h.lIIIlIllI[h.lIIIllIlI[154]] = h."Are kalphites carnivores, herbivores or omnivores?";
        h.lIIIlIllI[h.lIIIllIlI[155]] = h."Carnivores.";
        h.lIIIlIllI[h.lIIIllIlI[156]] = h."KALPHITE_5";
        h.lIIIlIllI[h.lIIIllIlI[157]] = h."What are kalphites assumed to have evolved from?";
        h.lIIIlIllI[h.lIIIllIlI[158]] = h."Scarab beetles.";
        h.lIIIlIllI[h.lIIIllIlI[159]] = h."KALPHITE_6";
        h.lIIIlIllI[h.lIIIllIlI[160]] = h."Name the prominent figure in kalphite mythology?";
        h.lIIIlIllI[h.lIIIllIlI[161]] = h."Scabaras.";
        h.lIIIlIllI[h.lIIIllIlI[162]] = h."TERRORBIRD_1";
        h.lIIIlIllI[h.lIIIllIlI[163]] = h."What is a terrorbird's preferred food?";
        h.lIIIlIllI[h.lIIIllIlI[164]] = h."Anything.";
        h.lIIIlIllI[h.lIIIllIlI[165]] = h."TERRORBIRD_2";
        h.lIIIlIllI[h.lIIIllIlI[166]] = h."Who use terrorbirds as mounts?";
        h.lIIIlIllI[h.lIIIllIlI[167]] = h."Gnomes.";
        h.lIIIlIllI[h.lIIIllIlI[168]] = h."TERRORBIRD_3";
        h.lIIIlIllI[h.lIIIllIlI[169]] = h."Where do terrorbirds get most of their water?";
        h.lIIIlIllI[h.lIIIllIlI[170]] = h."Eating plants.";
        h.lIIIlIllI[h.lIIIllIlI[171]] = h."TERRORBIRD_4";
        h.lIIIlIllI[h.lIIIllIlI[172]] = h."How many claws do terrorbirds have?";
        h.lIIIlIllI[h.lIIIllIlI[173]] = h."Four.";
        h.lIIIlIllI[h.lIIIllIlI[174]] = h."TERRORBIRD_5";
        h.lIIIlIllI[h.lIIIllIlI[175]] = h."What do terrorbirds eat to aid digestion?";
        h.lIIIlIllI[h.lIIIllIlI[176]] = h."Stones.";
        h.lIIIlIllI[h.lIIIllIlI[177]] = h."TERRORBIRD_6";
        h.lIIIlIllI[h.lIIIllIlI[178]] = h."How many teeth do terrorbirds have?";
        h.lIIIlIllI[h.lIIIllIlI[179]] = h."0.";
        h.lIIIlIllI[h.lIIIllIlI[180]] = h."PENGUIN_1";
        h.lIIIlIllI[h.lIIIllIlI[181]] = h."Which sense do penguins rely on when hunting?";
        h.lIIIlIllI[h.lIIIllIlI[182]] = h."Sight.";
        h.lIIIlIllI[h.lIIIllIlI[183]] = h."PENGUIN_2";
        h.lIIIlIllI[h.lIIIllIlI[184]] = h."Which skill seems unusual for the penguins to possess?";
        h.lIIIlIllI[h.lIIIllIlI[185]] = h."Planning.";
        h.lIIIlIllI[h.lIIIllIlI[186]] = h."PENGUIN_3";
        h.lIIIlIllI[h.lIIIllIlI[187]] = h."How do penguins keep warm?";
        h.lIIIlIllI[h.lIIIllIlI[188]] = h."A layer of fat.";
        h.lIIIlIllI[h.lIIIllIlI[189]] = h."PENGUIN_4";
        h.lIIIlIllI[h.lIIIllIlI[190]] = h."What is the preferred climate for penguins?";
        h.lIIIlIllI[h.lIIIllIlI[191]] = h."Cold.";
        h.lIIIlIllI[h.lIIIllIlI[192]] = h."PENGUIN_5";
        h.lIIIlIllI[h.lIIIllIlI[193]] = h."Describe the behaviour of penguins?";
        h.lIIIlIllI[h.lIIIllIlI[194]] = h."Social.";
        h.lIIIlIllI[h.lIIIllIlI[195]] = h."PENGUIN_6";
        h.lIIIlIllI[h.lIIIllIlI[196]] = h."When do penguins fast?";
        h.lIIIlIllI[h.lIIIllIlI[197]] = h."During breeding.";
        h.lIIIlIllI[h.lIIIllIlI[198]] = h."MOLE_1";
        h.lIIIlIllI[h.lIIIllIlI[199]] = h."What habitat do moles prefer?";
        h.lIIIlIllI[h.lIIIllIlI[200]] = h."Subterranean.";
        h.lIIIlIllI[h.lIIIllIlI[201]] = h."MOLE_2";
        h.lIIIlIllI[h.lIIIllIlI[202]] = h."Why are moles considered to be an agricultural pest?";
        h.lIIIlIllI[h.lIIIllIlI[203]] = h."They dig holes.";
        h.lIIIlIllI[h.lIIIllIlI[204]] = h."MOLE_3";
        h.lIIIlIllI[h.lIIIllIlI[205]] = h."Who discovered giant moles?";
        h.lIIIlIllI[h.lIIIllIlI[206]] = h."Wyson the Gardener.";
        h.lIIIlIllI[h.lIIIllIlI[207]] = h."MOLE_4";
        h.lIIIlIllI[h.lIIIllIlI[208]] = h."What would you call a group of young moles?";
        h.lIIIlIllI[h.lIIIllIlI[209]] = h."A labour.";
        h.lIIIlIllI[h.lIIIllIlI[210]] = h."MOLE_5";
        h.lIIIlIllI[h.lIIIllIlI[211]] = h."What is a mole's favourite food?";
        h.lIIIlIllI[h.lIIIllIlI[212]] = h."Insects and other invertebrates.";
        h.lIIIlIllI[h.lIIIllIlI[213]] = h."MOLE_6";
        h.lIIIlIllI[h.lIIIllIlI[214]] = h."Which family do moles belong to?";
        h.lIIIlIllI[h.lIIIllIlI[215]] = h."The Talpidae family.";
        h.lIIIlIllI[h.lIIIllIlI[216]] = h."CAMEL_1";
        h.lIIIlIllI[h.lIIIllIlI[217]] = h."What is produced by feeding chilli to a camel?";
        h.lIIIlIllI[h.lIIIllIlI[218]] = h."Toxic dung.";
        h.lIIIlIllI[h.lIIIllIlI[219]] = h."CAMEL_2";
        h.lIIIlIllI[h.lIIIllIlI[220]] = h."If an ugthanki has one, how many does a bactrian have?";
        h.lIIIlIllI[h.lIIIllIlI[221]] = h."Two.";
        h.lIIIlIllI[h.lIIIllIlI[222]] = h."CAMEL_3";
        h.lIIIlIllI[h.lIIIllIlI[223]] = h."Camels: herbivore, carnivore or omnivore?";
        h.lIIIlIllI[h.lIIIllIlI[224]] = h."Omnivore.";
        h.lIIIlIllI[h.lIIIllIlI[225]] = h."CAMEL_4";
        h.lIIIlIllI[h.lIIIllIlI[226]] = h."What is the usual mood for a camel?";
        h.lIIIlIllI[h.lIIIllIlI[227]] = h."Annoyed.";
        h.lIIIlIllI[h.lIIIllIlI[228]] = h."CAMEL_5";
        h.lIIIlIllI[h.lIIIllIlI[229]] = h."Where would you find an ugthanki?";
        h.lIIIlIllI[h.lIIIllIlI[230]] = h."Al Kharid.";
        h.lIIIlIllI[h.lIIIllIlI[231]] = h."CAMEL_6";
        h.lIIIlIllI[h.lIIIllIlI[232]] = h."Which camel byproduct is known to be very nutritious?";
        h.lIIIlIllI[h.lIIIllIlI[233]] = h."Milk.";
        h.lIIIlIllI[h.lIIIllIlI[234]] = h."LEECH_1";
        h.lIIIlIllI[h.lIIIllIlI[235]] = h."What is the favoured habitat of leeches?";
        h.lIIIlIllI[h.lIIIllIlI[236]] = h."Water.";
        h.lIIIlIllI[h.lIIIllIlI[237]] = h."LEECH_2";
        h.lIIIlIllI[h.lIIIllIlI[238]] = h."What shape is the inside of a leech's mouth?";
        h.lIIIlIllI[h.lIIIllIlI[239]] = h."'Y'-shaped.";
        h.lIIIlIllI[h.lIIIllIlI[240]] = h."LEECH_3";
        h.lIIIlIllI[h.lIIIllIlI[241]] = h."Which of these is not eaten by leeches?";
        h.lIIIlIllI[h.lIIIllIlI[242]] = h."Apples.";
        h.lIIIlIllI[h.lIIIllIlI[243]] = h."LEECH_4";
        h.lIIIlIllI[h.lIIIllIlI[244]] = h."What contributed to the giant growth of Morytanian leeches?";
        h.lIIIlIllI[h.lIIIllIlI[245]] = h."Environment.";
        h.lIIIlIllI[h.lIIIllIlI[246]] = h."LEECH_5";
        h.lIIIlIllI[h.lIIIllIlI[247]] = h."What is special about Morytanian leeches?";
        h.lIIIlIllI[h.lIIIllIlI[248]] = h."They attack by jumping.";
        h.lIIIlIllI[h.lIIIllIlI[249]] = h."LEECH_6";
        h.lIIIlIllI[h.lIIIllIlI[250]] = h."How does a leech change when it feeds?";
        h.lIIIlIllI[h.lIIIllIlI[251]] = h."It doubles in size.";
    }

    public static h[] values() {
        return (h[])$VALUES.clone();
    }
}

