/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.base.Preconditions
 *  com.google.common.collect.ImmutableList
 *  javax.annotation.Nullable
 */
package gg.squire.construction.tasks;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;
import java.util.function.IntPredicate;
import javax.annotation.Nullable;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

public final class GameEnum115
extends Enum<T> {
    public static final  /* enum */ T BLUE_DRAGONS;
    public static final  /* enum */ T DARK_WARRIORS;
    public static final  /* enum */ T CHAOS_DRUIDS;
    public static final  /* enum */ T MUTATED_ZYGOMITES;
    public static final  /* enum */ T WALL_BEASTS;
    public static final  /* enum */ T FIRE_GIANTS;
    public static final  /* enum */ T CRAZY_ARCHAEOLOGIST;
    public static final  /* enum */ T RED_DRAGONS;
    public static final  /* enum */ T KURASK;
    public static final  /* enum */ T MITHRIL_DRAGONS;
    public static final  /* enum */ T THERMONUCLEAR_SMOKE_DEVIL;
    public static final  /* enum */ T ZOMBIES;
    private final  int itemSpriteId;
    public static final  /* enum */ T SARACHNIS;
    private static final  T[] $VALUES;
    public static final  /* enum */ T CRAWLING_HANDS;
    static final  List<String> LOCATIONS;
    public static final  /* enum */ T CHAOS_FANATIC;
    public static final  /* enum */ T TROLLS;
    public static final  /* enum */ T WOLVES;
    public static final  /* enum */ T CATABLEPON;
    public static final  /* enum */ T HYDRAS;
    public static final  /* enum */ T WATERFIENDS;
    public static final  /* enum */ T SULPHUR_LIZARDS;
    public static final  /* enum */ T ICE_WARRIORS;
    public static final  /* enum */ T CAVE_SLIMES;
    public static final  /* enum */ T RATS;
    public static final  /* enum */ T CAVE_HORRORS;
    public static final  /* enum */ T FEVER_SPIDERS;
    public static final  /* enum */ T SCORPIONS;
    public static final  /* enum */ T TUROTH;
    public static final  /* enum */ T CAVE_BUGS;
    public static final  /* enum */ T ICE_GIANTS;
    public static final  /* enum */ T LESSER_DEMONS;
    public static final  /* enum */ T BLACK_KNIGHTS;
    public static final  /* enum */ T ANKOU;
    public static final  /* enum */ T MONKEYS;
    public static final  /* enum */ T EARTH_WARRIORS;
    public static final  /* enum */ T CAVE_KRAKEN;
    public static final  /* enum */ T KALPHITE_QUEEN;
    public static final  /* enum */ T MINIONS_OF_SCABARAS;
    public static final  /* enum */ T ZUK;
    public static final  /* enum */ T VAMPYRES;
    public static final  /* enum */ T FLESH_CRAWLERS;
    public static final  /* enum */ T KILLERWATTS;
    public static final  /* enum */ T TZHAAR;
    public static final  /* enum */ T GENERAL_GRAARDOR;
    public static final  /* enum */ T IRON_DRAGONS;
    public static final  /* enum */ T DAGANNOTH;
    public static final  /* enum */ T DERANGED_ARCHAEOLOGIST;
    public static final  /* enum */ T MINOTAURS;
    public static final  /* enum */ T SMOKE_DEVILS;
    public static final  /* enum */ T SKELETONS;
    public static final  /* enum */ T ALCHEMICAL_HYDRA;
    public static final  /* enum */ T SPIDERS;
    public static final  /* enum */ T STEEL_DRAGONS;
    public static final  /* enum */ T SKELETAL_WYVERNS;
    @Nullable
    private final  IntPredicate xpMatcher;
    public static final  /* enum */ T CALLISTO;
    public static final  /* enum */ T BASILISKS;
    public static final  /* enum */ T LAVA_DRAGONS;
    public static final  /* enum */ T KRIL_TSUTSAROTH;
    public static final  /* enum */ T MOSS_GIANTS;
    public static final  /* enum */ T BANDITS;
    public static final  /* enum */ T LIZARDS;
    public static final  /* enum */ T JAD;
    public static final  /* enum */ T KREEARRA;
    public static final  /* enum */ T INFERNAL_MAGES;
    public static final  /* enum */ T CERBERUS;
    public static final  /* enum */ T HOBGOBLINS;
    public static final  /* enum */ T VORKATH;
    private final  String[] targetNames;
    public static final  /* enum */ T KRAKEN;
    public static final  /* enum */ T TEMPLE_SPIDERS;
    public static final  /* enum */ T BATS;
    public static final  /* enum */ T GOBLINS;
    public static final  /* enum */ T MOLANISKS;
    public static final  /* enum */ T ABYSSAL_DEMONS;
    public static final  /* enum */ T DAGANNOTH_KINGS;
    public static final  /* enum */ T DRAKES;
    public static final  /* enum */ T BANSHEES;
    public static final  /* enum */ T MOGRES;
    public static final  /* enum */ T SCORPIA;
    public static final  /* enum */ T ZILYANA;
    public static final  /* enum */ T ENTS;
    public static final  /* enum */ T ELVES;
    public static final  /* enum */ T ABYSSAL_SIRE;
    public static final  /* enum */ T SOURHOGS;
    public static final  /* enum */ T AVIANSIES;
    public static final  /* enum */ T PYREFIENDS;
    public static final  /* enum */ T LIZARDMEN;
    public static final  /* enum */ T MAGIC_AXES;
    public static final  /* enum */ T BLACK_DEMONS;
    public static final  /* enum */ T GHOSTS;
    public static final  /* enum */ T VENENATIS;
    public static final  /* enum */ T FOSSIL_ISLAND_WYVERNS;
    public static final  /* enum */ T ICEFIENDS;
    public static final  /* enum */ T ADAMANT_DRAGONS;
    public static final  /* enum */ T JELLIES;
    public static final  /* enum */ T JUNGLE_HORROR;
    public static final  /* enum */ T CAVE_CRAWLERS;
    public static final  /* enum */ T GHOULS;
    public static final  /* enum */ T DOGS;
    public static final  /* enum */ T ROCKSLUGS;
    public static final  /* enum */ T SPIRITUAL_CREATURES;
    public static final  /* enum */ T GROTESQUE_GUARDIANS;
    public static final  /* enum */ T COCKATRICE;
    public static final  /* enum */ T ZULRAH;
    public static final  /* enum */ T COWS;
    public static final  /* enum */ T REVENANTS;
    public static final  /* enum */ T HELLHOUNDS;
    public static final  /* enum */ T SUQAHS;
    public static final  /* enum */ T DARK_BEASTS;
    public static final  /* enum */ T OTHERWORLDLY_BEING;
    private final  int weaknessThreshold;
    public static final  /* enum */ T HARPIE_BUG_SWARMS;
    
    public static final  /* enum */ T GREATER_DEMONS;
    public static final  /* enum */ T RUNE_DRAGONS;
    public static final  /* enum */ T BLACK_DRAGONS;
    
    public static final  /* enum */ T BLOODVELD;
    public static final  /* enum */ T VETION;
    public static final  /* enum */ T CROCODILES;
    private final  String name;
    public static final  /* enum */ T GARGOYLES;
    public static final  /* enum */ T PIRATES;
    private final  int weaknessItem;
    public static final  /* enum */ T BARROWS_BROTHERS;
    public static final  /* enum */ T DWARVES;
    public static final  /* enum */ T GIANT_MOLE;
    public static final  /* enum */ T MAMMOTHS;
    public static final  /* enum */ T WYRMS;
    public static final  /* enum */ T BEARS;
    public static final  /* enum */ T KING_BLACK_DRAGON;
    public static final  /* enum */ T DUST_DEVILS;
    public static final  /* enum */ T BRONZE_DRAGONS;
    public static final  /* enum */ T BRINE_RATS;
    public static final  /* enum */ T OGRES;
    public static final  /* enum */ T GREEN_DRAGONS;
    public static final  /* enum */ T HILL_GIANTS;
    public static final  /* enum */ T CHAOS_ELEMENTAL;
    public static final  /* enum */ T WEREWOLVES;
    public static final  /* enum */ T SHADES;
    public static final  /* enum */ T BIRDS;
    public static final  /* enum */ T SHADOW_WARRIORS;
    public static final  /* enum */ T UNDEAD_DRUIDS;
    public static final  /* enum */ T KALPHITE;
    public static final  /* enum */ T ABERRANT_SPECTRES;
    public static final  /* enum */ T SEA_SNAKES;
    public static final  /* enum */ T TERROR_DOGS;
    public static final  /* enum */ T NECHRYAEL;
    public static final  /* enum */ T ROGUES;

    private GameEnum115(String string2, int n3, IntPredicate intPredicate) {
        boolean bl2;
        if (T.llIlIIlllII(n3)) {
            bl2 = lllIlIIll[0];

            if (3 > 3) {
                throw null;
            }
        } else {
            bl2 = lllIlIIll[1];
        }
        Preconditions.checkArgument((boolean)bl2);
        this.name = string2;
        this.itemSpriteId = n3;
        this.weaknessThreshold = lllIlIIll[2];
        this.weaknessItem = lllIlIIll[2];
        this.targetNames = new String[lllIlIIll[1]];
        this.xpMatcher = intPredicate;
    }

    private GameEnum115(String string2, int n3, String ... stringArray) {
        boolean bl2;
        if (T.llIlIIlllII(n3)) {
            bl2 = lllIlIIll[0];

        } else {
            bl2 = lllIlIIll[1];
        }
        Preconditions.checkArgument((boolean)bl2);
        this.name = string2;
        this.itemSpriteId = n3;
        this.weaknessThreshold = lllIlIIll[2];
        this.weaknessItem = lllIlIIll[2];
        this.targetNames = stringArray;
        this.xpMatcher = null;
    }

    private static boolean llIlIIlllIl(int n2, int n3) {
        return n2 == n3;
    }

    public int aO() {
        return this.itemSpriteId;
    }

    static {
        T.llIlIIllIll();
        T.llIIlIIIlII();
        String[] stringArray = new String[lllIlIIll[0]];
        stringArray[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[7]];
        ABERRANT_SPECTRES = new GameEnum115(llIlIIIlI[lllIlIIll[0]], lllIlIIll[6], stringArray);
        ABYSSAL_DEMONS = new GameEnum115(llIlIIIlI[lllIlIIll[9]], lllIlIIll[10], n2 -> {
            boolean bl2;
            if (T.llIlIIllllI(n2, lllIlIIll[5])) {
                bl2 = lllIlIIll[0];

                if (2 == 0) {
                    return false;
                }
            } else {
                bl2 = lllIlIIll[1];
            }
            return bl2;
        });
        ABYSSAL_SIRE = new GameEnum115(llIlIIIlI[lllIlIIll[12]], lllIlIIll[13], n2 -> {
            boolean bl2;
            if (T.llIlIIllllI(n2, lllIlIIll[5])) {
                bl2 = lllIlIIll[0];

                }
            } else {
                bl2 = lllIlIIll[1];
            }
            return bl2;
        });
        ADAMANT_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[15]], lllIlIIll[16], new String[lllIlIIll[1]]);
        ALCHEMICAL_HYDRA = new GameEnum115(llIlIIIlI[lllIlIIll[18]], lllIlIIll[19], new String[lllIlIIll[1]]);
        ANKOU = new GameEnum115(llIlIIIlI[lllIlIIll[21]], lllIlIIll[22], new String[lllIlIIll[1]]);
        AVIANSIES = new GameEnum115(llIlIIIlI[lllIlIIll[24]], lllIlIIll[25], new String[lllIlIIll[1]]);
        String[] stringArray2 = new String[lllIlIIll[9]];
        stringArray2[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[29]];
        stringArray2[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[30]];
        stringArray2[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[31]];
        stringArray2[T.lllIlIIll[8]] = llIlIIIlI[lllIlIIll[32]];
        BANDITS = new GameEnum115(llIlIIIlI[lllIlIIll[27]], lllIlIIll[28], stringArray2);
        BANSHEES = new GameEnum115(llIlIIIlI[lllIlIIll[34]], lllIlIIll[35], new String[lllIlIIll[1]]);
        BARROWS_BROTHERS = new GameEnum115(llIlIIIlI[lllIlIIll[37]], lllIlIIll[38], new String[lllIlIIll[1]]);
        BASILISKS = new GameEnum115(llIlIIIlI[lllIlIIll[40]], lllIlIIll[41], new String[lllIlIIll[1]]);
        String[] stringArray3 = new String[lllIlIIll[0]];
        stringArray3[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[45]];
        BATS = new GameEnum115(llIlIIIlI[lllIlIIll[43]], lllIlIIll[44], stringArray3);
        BEARS = new GameEnum115(llIlIIIlI[lllIlIIll[47]], lllIlIIll[48], new String[lllIlIIll[1]]);
        String[] stringArray4 = new String[lllIlIIll[14]];
        stringArray4[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[52]];
        stringArray4[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[53]];
        stringArray4[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[54]];
        stringArray4[T.lllIlIIll[8]] = llIlIIIlI[lllIlIIll[55]];
        stringArray4[T.lllIlIIll[9]] = llIlIIIlI[lllIlIIll[56]];
        stringArray4[T.lllIlIIll[11]] = llIlIIIlI[lllIlIIll[57]];
        stringArray4[T.lllIlIIll[12]] = llIlIIIlI[lllIlIIll[58]];
        BIRDS = new GameEnum115(llIlIIIlI[lllIlIIll[50]], lllIlIIll[51], stringArray4);
        BLACK_DEMONS = new GameEnum115(llIlIIIlI[lllIlIIll[60]], lllIlIIll[61], new String[lllIlIIll[1]]);
        String[] stringArray5 = new String[lllIlIIll[0]];
        stringArray5[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[65]];
        BLACK_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[63]], lllIlIIll[64], stringArray5);
        String[] stringArray6 = new String[lllIlIIll[0]];
        stringArray6[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[69]];
        BLACK_KNIGHTS = new GameEnum115(llIlIIIlI[lllIlIIll[67]], lllIlIIll[68], stringArray6);
        BLOODVELD = new GameEnum115(llIlIIIlI[lllIlIIll[5]], lllIlIIll[71], new String[lllIlIIll[1]]);
        String[] stringArray7 = new String[lllIlIIll[0]];
        stringArray7[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[75]];
        BLUE_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[73]], lllIlIIll[74], stringArray7);
        BRINE_RATS = new GameEnum115(llIlIIIlI[lllIlIIll[77]], lllIlIIll[78], new String[lllIlIIll[1]]);
        BRONZE_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[80]], lllIlIIll[81], new String[lllIlIIll[1]]);
        CALLISTO = new GameEnum115(llIlIIIlI[lllIlIIll[83]], lllIlIIll[84], new String[lllIlIIll[1]]);
        CATABLEPON = new GameEnum115(llIlIIIlI[lllIlIIll[86]], lllIlIIll[87], new String[lllIlIIll[1]]);
        CAVE_BUGS = new GameEnum115(llIlIIIlI[lllIlIIll[89]], lllIlIIll[90], new String[lllIlIIll[1]]);
        String[] stringArray8 = new String[lllIlIIll[0]];
        stringArray8[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[94]];
        CAVE_CRAWLERS = new GameEnum115(llIlIIIlI[lllIlIIll[92]], lllIlIIll[93], stringArray8);
        String[] stringArray9 = new String[lllIlIIll[0]];
        stringArray9[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[98]];
        CAVE_HORRORS = new GameEnum115(llIlIIIlI[lllIlIIll[96]], lllIlIIll[97], stringArray9);
        CAVE_KRAKEN = new GameEnum115(llIlIIIlI[lllIlIIll[100]], lllIlIIll[101], new String[lllIlIIll[1]]);
        CAVE_SLIMES = new GameEnum115(llIlIIIlI[lllIlIIll[103]], lllIlIIll[104], new String[lllIlIIll[1]]);
        CERBERUS = new GameEnum115(llIlIIIlI[lllIlIIll[106]], lllIlIIll[107], new String[lllIlIIll[1]]);
        String[] stringArray10 = new String[lllIlIIll[7]];
        stringArray10[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[111]];
        stringArray10[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[112]];
        CHAOS_DRUIDS = new GameEnum115(llIlIIIlI[lllIlIIll[109]], lllIlIIll[110], stringArray10);
        CHAOS_ELEMENTAL = new GameEnum115(llIlIIIlI[lllIlIIll[114]], lllIlIIll[115], new String[lllIlIIll[1]]);
        CHAOS_FANATIC = new GameEnum115(llIlIIIlI[lllIlIIll[117]], lllIlIIll[118], new String[lllIlIIll[1]]);
        String[] stringArray11 = new String[lllIlIIll[0]];
        stringArray11[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[122]];
        COCKATRICE = new GameEnum115(llIlIIIlI[lllIlIIll[120]], lllIlIIll[121], stringArray11);
        COWS = new GameEnum115(llIlIIIlI[lllIlIIll[124]], lllIlIIll[125], new String[lllIlIIll[1]]);
        String[] stringArray12 = new String[lllIlIIll[0]];
        stringArray12[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[129]];
        CRAWLING_HANDS = new GameEnum115(llIlIIIlI[lllIlIIll[127]], lllIlIIll[128], stringArray12);
        String[] stringArray13 = new String[lllIlIIll[0]];
        stringArray13[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[133]];
        CRAZY_ARCHAEOLOGIST = new GameEnum115(llIlIIIlI[lllIlIIll[131]], lllIlIIll[132], stringArray13);
        CROCODILES = new GameEnum115(llIlIIIlI[lllIlIIll[135]], lllIlIIll[136], new String[lllIlIIll[1]]);
        DAGANNOTH = new GameEnum115(llIlIIIlI[lllIlIIll[138]], lllIlIIll[139], new String[lllIlIIll[1]]);
        DAGANNOTH_KINGS = new GameEnum115(llIlIIIlI[lllIlIIll[141]], lllIlIIll[142], new String[lllIlIIll[1]]);
        String[] stringArray14 = new String[lllIlIIll[0]];
        stringArray14[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[146]];
        DARK_BEASTS = new GameEnum115(llIlIIIlI[lllIlIIll[144]], lllIlIIll[145], stringArray14);
        String[] stringArray15 = new String[lllIlIIll[0]];
        stringArray15[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[150]];
        DARK_WARRIORS = new GameEnum115(llIlIIIlI[lllIlIIll[148]], lllIlIIll[149], stringArray15);
        DERANGED_ARCHAEOLOGIST = new GameEnum115(llIlIIIlI[lllIlIIll[152]], lllIlIIll[153], new String[lllIlIIll[1]]);
        String[] stringArray16 = new String[lllIlIIll[0]];
        stringArray16[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[157]];
        DOGS = new GameEnum115(llIlIIIlI[lllIlIIll[155]], lllIlIIll[156], stringArray16);
        DRAKES = new GameEnum115(llIlIIIlI[lllIlIIll[159]], lllIlIIll[160], new String[lllIlIIll[1]]);
        String[] stringArray17 = new String[lllIlIIll[0]];
        stringArray17[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[164]];
        DUST_DEVILS = new GameEnum115(llIlIIIlI[lllIlIIll[162]], lllIlIIll[163], stringArray17);
        String[] stringArray18 = new String[lllIlIIll[7]];
        stringArray18[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[168]];
        stringArray18[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[169]];
        DWARVES = new GameEnum115(llIlIIIlI[lllIlIIll[166]], lllIlIIll[167], stringArray18);
        EARTH_WARRIORS = new GameEnum115(llIlIIIlI[lllIlIIll[171]], lllIlIIll[172], new String[lllIlIIll[1]]);
        String[] stringArray19 = new String[lllIlIIll[8]];
        stringArray19[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[176]];
        stringArray19[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[177]];
        stringArray19[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[178]];
        ELVES = new GameEnum115(llIlIIIlI[lllIlIIll[174]], lllIlIIll[175], stringArray19);
        String[] stringArray20 = new String[lllIlIIll[0]];
        stringArray20[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[182]];
        ENTS = new GameEnum115(llIlIIIlI[lllIlIIll[180]], lllIlIIll[181], stringArray20);
        FEVER_SPIDERS = new GameEnum115(llIlIIIlI[lllIlIIll[184]], lllIlIIll[185], new String[lllIlIIll[1]]);
        FIRE_GIANTS = new GameEnum115(llIlIIIlI[lllIlIIll[187]], lllIlIIll[188], new String[lllIlIIll[1]]);
        String[] stringArray21 = new String[lllIlIIll[0]];
        stringArray21[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[192]];
        FLESH_CRAWLERS = new GameEnum115(llIlIIIlI[lllIlIIll[190]], lllIlIIll[191], stringArray21);
        String[] stringArray22 = new String[lllIlIIll[9]];
        stringArray22[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[196]];
        stringArray22[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[197]];
        stringArray22[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[198]];
        stringArray22[T.lllIlIIll[8]] = llIlIIIlI[lllIlIIll[199]];
        FOSSIL_ISLAND_WYVERNS = new GameEnum115(llIlIIIlI[lllIlIIll[194]], lllIlIIll[195], stringArray22);
        GARGOYLES = new GameEnum115(llIlIIIlI[lllIlIIll[201]], lllIlIIll[202], lllIlIIll[17], lllIlIIll[203], new String[lllIlIIll[1]]);
        GENERAL_GRAARDOR = new GameEnum115(llIlIIIlI[lllIlIIll[205]], lllIlIIll[206], new String[lllIlIIll[1]]);
        String[] stringArray23 = new String[lllIlIIll[7]];
        stringArray23[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[210]];
        stringArray23[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[211]];
        GHOSTS = new GameEnum115(llIlIIIlI[lllIlIIll[208]], lllIlIIll[209], stringArray23);
        GHOULS = new GameEnum115(llIlIIIlI[lllIlIIll[213]], lllIlIIll[214], new String[lllIlIIll[1]]);
        GIANT_MOLE = new GameEnum115(llIlIIIlI[lllIlIIll[216]], lllIlIIll[217], new String[lllIlIIll[1]]);
        GOBLINS = new GameEnum115(llIlIIIlI[lllIlIIll[219]], lllIlIIll[220], new String[lllIlIIll[1]]);
        GREATER_DEMONS = new GameEnum115(llIlIIIlI[lllIlIIll[222]], lllIlIIll[223], new String[lllIlIIll[1]]);
        String[] stringArray24 = new String[lllIlIIll[7]];
        stringArray24[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[227]];
        stringArray24[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[228]];
        GREEN_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[225]], lllIlIIll[226], stringArray24);
        String[] stringArray25 = new String[lllIlIIll[7]];
        stringArray25[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[232]];
        stringArray25[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[233]];
        GROTESQUE_GUARDIANS = new GameEnum115(llIlIIIlI[lllIlIIll[230]], lllIlIIll[231], lllIlIIll[1], lllIlIIll[203], stringArray25);
        HARPIE_BUG_SWARMS = new GameEnum115(llIlIIIlI[lllIlIIll[235]], lllIlIIll[236], new String[lllIlIIll[1]]);
        HELLHOUNDS = new GameEnum115(llIlIIIlI[lllIlIIll[238]], lllIlIIll[239], new String[lllIlIIll[1]]);
        String[] stringArray26 = new String[lllIlIIll[0]];
        stringArray26[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[243]];
        HILL_GIANTS = new GameEnum115(llIlIIIlI[lllIlIIll[241]], lllIlIIll[242], stringArray26);
        HOBGOBLINS = new GameEnum115(llIlIIIlI[lllIlIIll[245]], lllIlIIll[246], new String[lllIlIIll[1]]);
        HYDRAS = new GameEnum115(llIlIIIlI[lllIlIIll[248]], lllIlIIll[249], new String[lllIlIIll[1]]);
        ICEFIENDS = new GameEnum115(llIlIIIlI[lllIlIIll[251]], lllIlIIll[252], new String[lllIlIIll[1]]);
        ICE_GIANTS = new GameEnum115(llIlIIIlI[lllIlIIll[254]], lllIlIIll[252], new String[lllIlIIll[1]]);
        String[] stringArray27 = new String[lllIlIIll[0]];
        stringArray27[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[258]];
        ICE_WARRIORS = new GameEnum115(llIlIIIlI[lllIlIIll[256]], lllIlIIll[257], stringArray27);
        String[] stringArray28 = new String[lllIlIIll[0]];
        stringArray28[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[262]];
        INFERNAL_MAGES = new GameEnum115(llIlIIIlI[lllIlIIll[260]], lllIlIIll[261], stringArray28);
        IRON_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[264]], lllIlIIll[265], new String[lllIlIIll[1]]);
        JAD = new GameEnum115(llIlIIIlI[lllIlIIll[267]], lllIlIIll[268], n2 -> {
            boolean bl2;
            if (T.llIlIIlllIl(n2, lllIlIIll[4])) {
                bl2 = lllIlIIll[0];

            } else {
                bl2 = lllIlIIll[1];
            }
            return bl2;
        });
        String[] stringArray29 = new String[lllIlIIll[0]];
        stringArray29[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[272]];
        JELLIES = new GameEnum115(llIlIIIlI[lllIlIIll[270]], lllIlIIll[271], stringArray29);
        JUNGLE_HORROR = new GameEnum115(llIlIIIlI[lllIlIIll[274]], lllIlIIll[275], new String[lllIlIIll[1]]);
        KALPHITE = new GameEnum115(llIlIIIlI[lllIlIIll[277]], lllIlIIll[278], new String[lllIlIIll[1]]);
        KALPHITE_QUEEN = new GameEnum115(llIlIIIlI[lllIlIIll[280]], lllIlIIll[281], new String[lllIlIIll[1]]);
        KILLERWATTS = new GameEnum115(llIlIIIlI[lllIlIIll[283]], lllIlIIll[284], new String[lllIlIIll[1]]);
        KING_BLACK_DRAGON = new GameEnum115(llIlIIIlI[lllIlIIll[286]], lllIlIIll[287], new String[lllIlIIll[1]]);
        String[] stringArray30 = new String[lllIlIIll[0]];
        stringArray30[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[291]];
        KRAKEN = new GameEnum115(llIlIIIlI[lllIlIIll[289]], lllIlIIll[290], stringArray30);
        KREEARRA = new GameEnum115(llIlIIIlI[lllIlIIll[293]], lllIlIIll[294], new String[lllIlIIll[1]]);
        KRIL_TSUTSAROTH = new GameEnum115(llIlIIIlI[lllIlIIll[296]], lllIlIIll[297], new String[lllIlIIll[1]]);
        KURASK = new GameEnum115(llIlIIIlI[lllIlIIll[299]], lllIlIIll[300], new String[lllIlIIll[1]]);
        String[] stringArray31 = new String[lllIlIIll[0]];
        stringArray31[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[304]];
        LAVA_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[302]], lllIlIIll[303], stringArray31);
        LESSER_DEMONS = new GameEnum115(llIlIIIlI[lllIlIIll[306]], lllIlIIll[307], new String[lllIlIIll[1]]);
        String[] stringArray32 = new String[lllIlIIll[0]];
        stringArray32[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[311]];
        LIZARDMEN = new GameEnum115(llIlIIIlI[lllIlIIll[309]], lllIlIIll[310], stringArray32);
        String[] stringArray33 = new String[lllIlIIll[9]];
        stringArray33[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[315]];
        stringArray33[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[316]];
        stringArray33[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[317]];
        stringArray33[T.lllIlIIll[8]] = llIlIIIlI[lllIlIIll[318]];
        LIZARDS = new GameEnum115(llIlIIIlI[lllIlIIll[313]], lllIlIIll[314], stringArray33);
        String[] stringArray34 = new String[lllIlIIll[0]];
        stringArray34[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[322]];
        MAGIC_AXES = new GameEnum115(llIlIIIlI[lllIlIIll[320]], lllIlIIll[321], stringArray34);
        String[] stringArray35 = new String[lllIlIIll[0]];
        stringArray35[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[326]];
        MAMMOTHS = new GameEnum115(llIlIIIlI[lllIlIIll[324]], lllIlIIll[325], stringArray35);
        String[] stringArray36 = new String[lllIlIIll[8]];
        stringArray36[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[330]];
        stringArray36[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[331]];
        stringArray36[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[332]];
        MINIONS_OF_SCABARAS = new GameEnum115(llIlIIIlI[lllIlIIll[328]], lllIlIIll[329], stringArray36);
        MINOTAURS = new GameEnum115(llIlIIIlI[lllIlIIll[334]], lllIlIIll[335], new String[lllIlIIll[1]]);
        MITHRIL_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[337]], lllIlIIll[338], new String[lllIlIIll[1]]);
        MOGRES = new GameEnum115(llIlIIIlI[lllIlIIll[340]], lllIlIIll[341], new String[lllIlIIll[1]]);
        MOLANISKS = new GameEnum115(llIlIIIlI[lllIlIIll[343]], lllIlIIll[344], new String[lllIlIIll[1]]);
        String[] stringArray37 = new String[lllIlIIll[0]];
        stringArray37[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[348]];
        MONKEYS = new GameEnum115(llIlIIIlI[lllIlIIll[346]], lllIlIIll[347], stringArray37);
        MOSS_GIANTS = new GameEnum115(llIlIIIlI[lllIlIIll[350]], lllIlIIll[351], new String[lllIlIIll[1]]);
        String[] stringArray38 = new String[lllIlIIll[7]];
        stringArray38[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[356]];
        stringArray38[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[357]];
        MUTATED_ZYGOMITES = new GameEnum115(llIlIIIlI[lllIlIIll[353]], lllIlIIll[354], lllIlIIll[14], lllIlIIll[355], stringArray38);
        String[] stringArray39 = new String[lllIlIIll[0]];
        stringArray39[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[361]];
        NECHRYAEL = new GameEnum115(llIlIIIlI[lllIlIIll[359]], lllIlIIll[360], stringArray39);
        OGRES = new GameEnum115(llIlIIIlI[lllIlIIll[363]], lllIlIIll[364], new String[lllIlIIll[1]]);
        OTHERWORLDLY_BEING = new GameEnum115(llIlIIIlI[lllIlIIll[366]], lllIlIIll[367], new String[lllIlIIll[1]]);
        String[] stringArray40 = new String[lllIlIIll[0]];
        stringArray40[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[371]];
        PIRATES = new GameEnum115(llIlIIIlI[lllIlIIll[369]], lllIlIIll[370], stringArray40);
        String[] stringArray41 = new String[lllIlIIll[0]];
        stringArray41[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[375]];
        PYREFIENDS = new GameEnum115(llIlIIIlI[lllIlIIll[373]], lllIlIIll[374], stringArray41);
        RATS = new GameEnum115(llIlIIIlI[lllIlIIll[377]], lllIlIIll[378], new String[lllIlIIll[1]]);
        String[] stringArray42 = new String[lllIlIIll[0]];
        stringArray42[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[382]];
        RED_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[380]], lllIlIIll[381], stringArray42);
        String[] stringArray43 = new String[lllIlIIll[20]];
        stringArray43[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[386]];
        stringArray43[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[387]];
        stringArray43[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[388]];
        stringArray43[T.lllIlIIll[8]] = llIlIIIlI[lllIlIIll[389]];
        stringArray43[T.lllIlIIll[9]] = llIlIIIlI[lllIlIIll[390]];
        stringArray43[T.lllIlIIll[11]] = llIlIIIlI[lllIlIIll[391]];
        stringArray43[T.lllIlIIll[12]] = llIlIIIlI[lllIlIIll[392]];
        stringArray43[T.lllIlIIll[14]] = llIlIIIlI[lllIlIIll[393]];
        stringArray43[T.lllIlIIll[15]] = llIlIIIlI[lllIlIIll[394]];
        stringArray43[T.lllIlIIll[17]] = llIlIIIlI[lllIlIIll[395]];
        stringArray43[T.lllIlIIll[18]] = llIlIIIlI[lllIlIIll[396]];
        REVENANTS = new GameEnum115(llIlIIIlI[lllIlIIll[384]], lllIlIIll[385], stringArray43);
        ROCKSLUGS = new GameEnum115(llIlIIIlI[lllIlIIll[398]], lllIlIIll[399], lllIlIIll[9], lllIlIIll[400], new String[lllIlIIll[1]]);
        String[] stringArray44 = new String[lllIlIIll[0]];
        stringArray44[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[404]];
        ROGUES = new GameEnum115(llIlIIIlI[lllIlIIll[402]], lllIlIIll[403], stringArray44);
        RUNE_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[406]], lllIlIIll[407], new String[lllIlIIll[1]]);
        SARACHNIS = new GameEnum115(llIlIIIlI[lllIlIIll[409]], lllIlIIll[410], new String[lllIlIIll[1]]);
        SCORPIA = new GameEnum115(llIlIIIlI[lllIlIIll[412]], lllIlIIll[413], new String[lllIlIIll[1]]);
        SCORPIONS = new GameEnum115(llIlIIIlI[lllIlIIll[378]], lllIlIIll[191], new String[lllIlIIll[1]]);
        SEA_SNAKES = new GameEnum115(llIlIIIlI[lllIlIIll[416]], lllIlIIll[417], new String[lllIlIIll[1]]);
        String[] stringArray45 = new String[lllIlIIll[18]];
        stringArray45[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[421]];
        stringArray45[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[422]];
        stringArray45[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[423]];
        stringArray45[T.lllIlIIll[8]] = llIlIIIlI[lllIlIIll[424]];
        stringArray45[T.lllIlIIll[9]] = llIlIIIlI[lllIlIIll[425]];
        stringArray45[T.lllIlIIll[11]] = llIlIIIlI[lllIlIIll[426]];
        stringArray45[T.lllIlIIll[12]] = llIlIIIlI[lllIlIIll[427]];
        stringArray45[T.lllIlIIll[14]] = llIlIIIlI[lllIlIIll[428]];
        stringArray45[T.lllIlIIll[15]] = llIlIIIlI[lllIlIIll[429]];
        stringArray45[T.lllIlIIll[17]] = llIlIIIlI[lllIlIIll[51]];
        SHADES = new GameEnum115(llIlIIIlI[lllIlIIll[419]], lllIlIIll[420], stringArray45);
        SHADOW_WARRIORS = new GameEnum115(llIlIIIlI[lllIlIIll[431]], lllIlIIll[68], new String[lllIlIIll[1]]);
        SKELETAL_WYVERNS = new GameEnum115(llIlIIIlI[lllIlIIll[433]], lllIlIIll[434], new String[lllIlIIll[1]]);
        SKELETONS = new GameEnum115(llIlIIIlI[lllIlIIll[436]], lllIlIIll[437], new String[lllIlIIll[1]]);
        SMOKE_DEVILS = new GameEnum115(llIlIIIlI[lllIlIIll[439]], lllIlIIll[440], new String[lllIlIIll[1]]);
        SOURHOGS = new GameEnum115(llIlIIIlI[lllIlIIll[442]], lllIlIIll[443], new String[lllIlIIll[1]]);
        SPIDERS = new GameEnum115(llIlIIIlI[lllIlIIll[445]], lllIlIIll[446], new String[lllIlIIll[1]]);
        String[] stringArray46 = new String[lllIlIIll[8]];
        stringArray46[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[450]];
        stringArray46[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[451]];
        stringArray46[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[452]];
        SPIRITUAL_CREATURES = new GameEnum115(llIlIIIlI[lllIlIIll[448]], lllIlIIll[449], stringArray46);
        STEEL_DRAGONS = new GameEnum115(llIlIIIlI[lllIlIIll[454]], lllIlIIll[455], new String[lllIlIIll[1]]);
        SULPHUR_LIZARDS = new GameEnum115(llIlIIIlI[lllIlIIll[457]], lllIlIIll[458], new String[lllIlIIll[1]]);
        SUQAHS = new GameEnum115(llIlIIIlI[lllIlIIll[460]], lllIlIIll[461], new String[lllIlIIll[1]]);
        TEMPLE_SPIDERS = new GameEnum115(llIlIIIlI[lllIlIIll[463]], lllIlIIll[312], new String[lllIlIIll[1]]);
        TERROR_DOGS = new GameEnum115(llIlIIIlI[lllIlIIll[465]], lllIlIIll[466], new String[lllIlIIll[1]]);
        THERMONUCLEAR_SMOKE_DEVIL = new GameEnum115(llIlIIIlI[lllIlIIll[468]], lllIlIIll[469], new String[lllIlIIll[1]]);
        String[] stringArray47 = new String[lllIlIIll[7]];
        stringArray47[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[473]];
        stringArray47[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[474]];
        TROLLS = new GameEnum115(llIlIIIlI[lllIlIIll[471]], lllIlIIll[472], stringArray47);
        TUROTH = new GameEnum115(llIlIIIlI[lllIlIIll[476]], lllIlIIll[477], new String[lllIlIIll[1]]);
        TZHAAR = new GameEnum115(llIlIIIlI[lllIlIIll[479]], lllIlIIll[480], new String[lllIlIIll[1]]);
        UNDEAD_DRUIDS = new GameEnum115(llIlIIIlI[lllIlIIll[482]], lllIlIIll[483], new String[lllIlIIll[1]]);
        String[] stringArray48 = new String[lllIlIIll[7]];
        stringArray48[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[487]];
        stringArray48[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[488]];
        VAMPYRES = new GameEnum115(llIlIIIlI[lllIlIIll[485]], lllIlIIll[486], stringArray48);
        VENENATIS = new GameEnum115(llIlIIIlI[lllIlIIll[490]], lllIlIIll[491], new String[lllIlIIll[1]]);
        VETION = new GameEnum115(llIlIIIlI[lllIlIIll[493]], lllIlIIll[494], new String[lllIlIIll[1]]);
        VORKATH = new GameEnum115(llIlIIIlI[lllIlIIll[496]], lllIlIIll[497], new String[lllIlIIll[1]]);
        WALL_BEASTS = new GameEnum115(llIlIIIlI[lllIlIIll[499]], lllIlIIll[500], new String[lllIlIIll[1]]);
        WATERFIENDS = new GameEnum115(llIlIIIlI[lllIlIIll[502]], lllIlIIll[503], new String[lllIlIIll[1]]);
        String[] stringArray49 = new String[lllIlIIll[0]];
        stringArray49[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[507]];
        WEREWOLVES = new GameEnum115(llIlIIIlI[lllIlIIll[505]], lllIlIIll[506], stringArray49);
        String[] stringArray50 = new String[lllIlIIll[0]];
        stringArray50[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[511]];
        WOLVES = new GameEnum115(llIlIIIlI[lllIlIIll[509]], lllIlIIll[510], stringArray50);
        WYRMS = new GameEnum115(llIlIIIlI[lllIlIIll[513]], lllIlIIll[514], new String[lllIlIIll[1]]);
        ZILYANA = new GameEnum115(llIlIIIlI[lllIlIIll[516]], lllIlIIll[517], new String[lllIlIIll[1]]);
        String[] stringArray51 = new String[lllIlIIll[0]];
        stringArray51[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[520]];
        ZOMBIES = new GameEnum115(llIlIIIlI[lllIlIIll[519]], lllIlIIll[214], stringArray51);
        ZUK = new GameEnum115(llIlIIIlI[lllIlIIll[522]], lllIlIIll[523], n2 -> {
            boolean bl2;
            if (T.llIlIIlllIl(n2, lllIlIIll[3])) {
                bl2 = lllIlIIll[0];

            } else {
                bl2 = lllIlIIll[1];
            }
            return bl2;
        });
        ZULRAH = new GameEnum115(llIlIIIlI[lllIlIIll[525]], lllIlIIll[526], new String[lllIlIIll[1]]);
        T[] tArray = new T[lllIlIIll[199]];
        tArray[T.lllIlIIll[1]] = ABERRANT_SPECTRES;
        tArray[T.lllIlIIll[0]] = ABYSSAL_DEMONS;
        tArray[T.lllIlIIll[7]] = ABYSSAL_SIRE;
        tArray[T.lllIlIIll[8]] = ADAMANT_DRAGONS;
        tArray[T.lllIlIIll[9]] = ALCHEMICAL_HYDRA;
        tArray[T.lllIlIIll[11]] = ANKOU;
        tArray[T.lllIlIIll[12]] = AVIANSIES;
        tArray[T.lllIlIIll[14]] = BANDITS;
        tArray[T.lllIlIIll[15]] = BANSHEES;
        tArray[T.lllIlIIll[17]] = BARROWS_BROTHERS;
        tArray[T.lllIlIIll[18]] = BASILISKS;
        tArray[T.lllIlIIll[20]] = BATS;
        tArray[T.lllIlIIll[21]] = BEARS;
        tArray[T.lllIlIIll[23]] = BIRDS;
        tArray[T.lllIlIIll[24]] = BLACK_DEMONS;
        tArray[T.lllIlIIll[26]] = BLACK_DRAGONS;
        tArray[T.lllIlIIll[27]] = BLACK_KNIGHTS;
        tArray[T.lllIlIIll[29]] = BLOODVELD;
        tArray[T.lllIlIIll[30]] = BLUE_DRAGONS;
        tArray[T.lllIlIIll[31]] = BRINE_RATS;
        tArray[T.lllIlIIll[32]] = BRONZE_DRAGONS;
        tArray[T.lllIlIIll[33]] = CALLISTO;
        tArray[T.lllIlIIll[34]] = CATABLEPON;
        tArray[T.lllIlIIll[36]] = CAVE_BUGS;
        tArray[T.lllIlIIll[37]] = CAVE_CRAWLERS;
        tArray[T.lllIlIIll[39]] = CAVE_HORRORS;
        tArray[T.lllIlIIll[40]] = CAVE_KRAKEN;
        tArray[T.lllIlIIll[42]] = CAVE_SLIMES;
        tArray[T.lllIlIIll[43]] = CERBERUS;
        tArray[T.lllIlIIll[45]] = CHAOS_DRUIDS;
        tArray[T.lllIlIIll[46]] = CHAOS_ELEMENTAL;
        tArray[T.lllIlIIll[47]] = CHAOS_FANATIC;
        tArray[T.lllIlIIll[49]] = COCKATRICE;
        tArray[T.lllIlIIll[50]] = COWS;
        tArray[T.lllIlIIll[52]] = CRAWLING_HANDS;
        tArray[T.lllIlIIll[53]] = CRAZY_ARCHAEOLOGIST;
        tArray[T.lllIlIIll[54]] = CROCODILES;
        tArray[T.lllIlIIll[55]] = DAGANNOTH;
        tArray[T.lllIlIIll[56]] = DAGANNOTH_KINGS;
        tArray[T.lllIlIIll[57]] = DARK_BEASTS;
        tArray[T.lllIlIIll[58]] = DARK_WARRIORS;
        tArray[T.lllIlIIll[59]] = DERANGED_ARCHAEOLOGIST;
        tArray[T.lllIlIIll[60]] = DOGS;
        tArray[T.lllIlIIll[62]] = DRAKES;
        tArray[T.lllIlIIll[63]] = DUST_DEVILS;
        tArray[T.lllIlIIll[65]] = DWARVES;
        tArray[T.lllIlIIll[66]] = EARTH_WARRIORS;
        tArray[T.lllIlIIll[67]] = ELVES;
        tArray[T.lllIlIIll[69]] = ENTS;
        tArray[T.lllIlIIll[70]] = FEVER_SPIDERS;
        tArray[T.lllIlIIll[5]] = FIRE_GIANTS;
        tArray[T.lllIlIIll[72]] = FLESH_CRAWLERS;
        tArray[T.lllIlIIll[73]] = FOSSIL_ISLAND_WYVERNS;
        tArray[T.lllIlIIll[75]] = GARGOYLES;
        tArray[T.lllIlIIll[76]] = GENERAL_GRAARDOR;
        tArray[T.lllIlIIll[77]] = GHOSTS;
        tArray[T.lllIlIIll[79]] = GHOULS;
        tArray[T.lllIlIIll[80]] = GIANT_MOLE;
        tArray[T.lllIlIIll[82]] = GOBLINS;
        tArray[T.lllIlIIll[83]] = GREATER_DEMONS;
        tArray[T.lllIlIIll[85]] = GREEN_DRAGONS;
        tArray[T.lllIlIIll[86]] = GROTESQUE_GUARDIANS;
        tArray[T.lllIlIIll[88]] = HARPIE_BUG_SWARMS;
        tArray[T.lllIlIIll[89]] = HELLHOUNDS;
        tArray[T.lllIlIIll[91]] = HILL_GIANTS;
        tArray[T.lllIlIIll[92]] = HOBGOBLINS;
        tArray[T.lllIlIIll[94]] = HYDRAS;
        tArray[T.lllIlIIll[95]] = ICEFIENDS;
        tArray[T.lllIlIIll[96]] = ICE_GIANTS;
        tArray[T.lllIlIIll[98]] = ICE_WARRIORS;
        tArray[T.lllIlIIll[99]] = INFERNAL_MAGES;
        tArray[T.lllIlIIll[100]] = IRON_DRAGONS;
        tArray[T.lllIlIIll[102]] = JAD;
        tArray[T.lllIlIIll[103]] = JELLIES;
        tArray[T.lllIlIIll[105]] = JUNGLE_HORROR;
        tArray[T.lllIlIIll[106]] = KALPHITE;
        tArray[T.lllIlIIll[108]] = KALPHITE_QUEEN;
        tArray[T.lllIlIIll[109]] = KILLERWATTS;
        tArray[T.lllIlIIll[111]] = KING_BLACK_DRAGON;
        tArray[T.lllIlIIll[112]] = KRAKEN;
        tArray[T.lllIlIIll[113]] = KREEARRA;
        tArray[T.lllIlIIll[114]] = KRIL_TSUTSAROTH;
        tArray[T.lllIlIIll[116]] = KURASK;
        tArray[T.lllIlIIll[117]] = LAVA_DRAGONS;
        tArray[T.lllIlIIll[119]] = LESSER_DEMONS;
        tArray[T.lllIlIIll[120]] = LIZARDMEN;
        tArray[T.lllIlIIll[122]] = LIZARDS;
        tArray[T.lllIlIIll[123]] = MAGIC_AXES;
        tArray[T.lllIlIIll[124]] = MAMMOTHS;
        tArray[T.lllIlIIll[126]] = MINIONS_OF_SCABARAS;
        tArray[T.lllIlIIll[127]] = MINOTAURS;
        tArray[T.lllIlIIll[129]] = MITHRIL_DRAGONS;
        tArray[T.lllIlIIll[130]] = MOGRES;
        tArray[T.lllIlIIll[131]] = MOLANISKS;
        tArray[T.lllIlIIll[133]] = MONKEYS;
        tArray[T.lllIlIIll[134]] = MOSS_GIANTS;
        tArray[T.lllIlIIll[135]] = MUTATED_ZYGOMITES;
        tArray[T.lllIlIIll[137]] = NECHRYAEL;
        tArray[T.lllIlIIll[138]] = OGRES;
        tArray[T.lllIlIIll[140]] = OTHERWORLDLY_BEING;
        tArray[T.lllIlIIll[141]] = PIRATES;
        tArray[T.lllIlIIll[143]] = PYREFIENDS;
        tArray[T.lllIlIIll[144]] = RATS;
        tArray[T.lllIlIIll[146]] = RED_DRAGONS;
        tArray[T.lllIlIIll[147]] = REVENANTS;
        tArray[T.lllIlIIll[148]] = ROCKSLUGS;
        tArray[T.lllIlIIll[150]] = ROGUES;
        tArray[T.lllIlIIll[151]] = RUNE_DRAGONS;
        tArray[T.lllIlIIll[152]] = SARACHNIS;
        tArray[T.lllIlIIll[154]] = SCORPIA;
        tArray[T.lllIlIIll[155]] = SCORPIONS;
        tArray[T.lllIlIIll[157]] = SEA_SNAKES;
        tArray[T.lllIlIIll[158]] = SHADES;
        tArray[T.lllIlIIll[159]] = SHADOW_WARRIORS;
        tArray[T.lllIlIIll[161]] = SKELETAL_WYVERNS;
        tArray[T.lllIlIIll[162]] = SKELETONS;
        tArray[T.lllIlIIll[164]] = SMOKE_DEVILS;
        tArray[T.lllIlIIll[165]] = SOURHOGS;
        tArray[T.lllIlIIll[166]] = SPIDERS;
        tArray[T.lllIlIIll[168]] = SPIRITUAL_CREATURES;
        tArray[T.lllIlIIll[169]] = STEEL_DRAGONS;
        tArray[T.lllIlIIll[170]] = SULPHUR_LIZARDS;
        tArray[T.lllIlIIll[171]] = SUQAHS;
        tArray[T.lllIlIIll[173]] = TEMPLE_SPIDERS;
        tArray[T.lllIlIIll[174]] = TERROR_DOGS;
        tArray[T.lllIlIIll[176]] = THERMONUCLEAR_SMOKE_DEVIL;
        tArray[T.lllIlIIll[177]] = TROLLS;
        tArray[T.lllIlIIll[178]] = TUROTH;
        tArray[T.lllIlIIll[179]] = TZHAAR;
        tArray[T.lllIlIIll[180]] = UNDEAD_DRUIDS;
        tArray[T.lllIlIIll[182]] = VAMPYRES;
        tArray[T.lllIlIIll[183]] = VENENATIS;
        tArray[T.lllIlIIll[184]] = VETION;
        tArray[T.lllIlIIll[186]] = VORKATH;
        tArray[T.lllIlIIll[187]] = WALL_BEASTS;
        tArray[T.lllIlIIll[189]] = WATERFIENDS;
        tArray[T.lllIlIIll[190]] = WEREWOLVES;
        tArray[T.lllIlIIll[192]] = WOLVES;
        tArray[T.lllIlIIll[193]] = WYRMS;
        tArray[T.lllIlIIll[194]] = ZILYANA;
        tArray[T.lllIlIIll[196]] = ZOMBIES;
        tArray[T.lllIlIIll[197]] = ZUK;
        tArray[T.lllIlIIll[198]] = ZULRAH;
        $VALUES = tArray;
        Object[] objectArray = new String[lllIlIIll[52]];
        objectArray[T.lllIlIIll[1]] = llIlIIIlI[lllIlIIll[539]];
        objectArray[T.lllIlIIll[0]] = llIlIIIlI[lllIlIIll[540]];
        objectArray[T.lllIlIIll[7]] = llIlIIIlI[lllIlIIll[541]];
        objectArray[T.lllIlIIll[8]] = llIlIIIlI[lllIlIIll[542]];
        objectArray[T.lllIlIIll[9]] = llIlIIIlI[lllIlIIll[543]];
        objectArray[T.lllIlIIll[11]] = llIlIIIlI[lllIlIIll[544]];
        objectArray[T.lllIlIIll[12]] = llIlIIIlI[lllIlIIll[545]];
        objectArray[T.lllIlIIll[14]] = llIlIIIlI[lllIlIIll[546]];
        objectArray[T.lllIlIIll[15]] = llIlIIIlI[lllIlIIll[547]];
        objectArray[T.lllIlIIll[17]] = llIlIIIlI[lllIlIIll[548]];
        objectArray[T.lllIlIIll[18]] = llIlIIIlI[lllIlIIll[549]];
        objectArray[T.lllIlIIll[20]] = llIlIIIlI[lllIlIIll[550]];
        objectArray[T.lllIlIIll[21]] = llIlIIIlI[lllIlIIll[551]];
        objectArray[T.lllIlIIll[23]] = llIlIIIlI[lllIlIIll[552]];
        objectArray[T.lllIlIIll[24]] = llIlIIIlI[lllIlIIll[553]];
        objectArray[T.lllIlIIll[26]] = llIlIIIlI[lllIlIIll[554]];
        objectArray[T.lllIlIIll[27]] = llIlIIIlI[lllIlIIll[555]];
        objectArray[T.lllIlIIll[29]] = llIlIIIlI[lllIlIIll[556]];
        objectArray[T.lllIlIIll[30]] = llIlIIIlI[lllIlIIll[557]];
        objectArray[T.lllIlIIll[31]] = llIlIIIlI[lllIlIIll[558]];
        objectArray[T.lllIlIIll[32]] = llIlIIIlI[lllIlIIll[559]];
        objectArray[T.lllIlIIll[33]] = llIlIIIlI[lllIlIIll[560]];
        objectArray[T.lllIlIIll[34]] = llIlIIIlI[lllIlIIll[561]];
        objectArray[T.lllIlIIll[36]] = llIlIIIlI[lllIlIIll[562]];
        objectArray[T.lllIlIIll[37]] = llIlIIIlI[lllIlIIll[563]];
        objectArray[T.lllIlIIll[39]] = llIlIIIlI[lllIlIIll[564]];
        objectArray[T.lllIlIIll[40]] = llIlIIIlI[lllIlIIll[565]];
        objectArray[T.lllIlIIll[42]] = llIlIIIlI[lllIlIIll[566]];
        objectArray[T.lllIlIIll[43]] = llIlIIIlI[lllIlIIll[567]];
        objectArray[T.lllIlIIll[45]] = llIlIIIlI[lllIlIIll[568]];
        objectArray[T.lllIlIIll[46]] = llIlIIIlI[lllIlIIll[569]];
        objectArray[T.lllIlIIll[47]] = llIlIIIlI[lllIlIIll[570]];
        objectArray[T.lllIlIIll[49]] = llIlIIIlI[lllIlIIll[571]];
        objectArray[T.lllIlIIll[50]] = llIlIIIlI[lllIlIIll[572]];
        LOCATIONS = ImmutableList.of((Object)llIlIIIlI[lllIlIIll[527]], (Object)llIlIIIlI[lllIlIIll[528]], (Object)llIlIIIlI[lllIlIIll[529]], (Object)llIlIIIlI[lllIlIIll[530]], (Object)llIlIIIlI[lllIlIIll[531]], (Object)llIlIIIlI[lllIlIIll[532]], (Object)llIlIIIlI[lllIlIIll[533]], (Object)llIlIIIlI[lllIlIIll[534]], (Object)llIlIIIlI[lllIlIIll[535]], (Object)llIlIIIlI[lllIlIIll[536]], (Object)llIlIIIlI[lllIlIIll[537]], (Object)llIlIIIlI[lllIlIIll[538]], (Object[])objectArray);
    }

    private static boolean llIlIIllllI(int n2, int n3) {
        return n2 != n3;
    }

    public int aR() {
        return this.weaknessItem;
    }

    private static boolean llIlIIlllll(int n2, int n3) {
        return n2 < n3;
    }

        return String.valueOf(lIlIIlIlIlIIlIl);
    }

    private static boolean llIlIIlllII(int n2) {
        return n2 >= 0;
    }

    @Nullable
    public IntPredicate aS() {
        return this.xpMatcher;
    }

    private static void llIIlIIIlII() {
        llIlIIIlI = new String[lllIlIIll[573]];
        T.llIlIIIlI[T.lllIlIIll[1]] = "ABERRANT_SPECTRES";
        T.llIlIIIlI[T.lllIlIIll[0]] = "Aberrant spectres";
        T.llIlIIIlI[T.lllIlIIll[7]] = "Spectre";
        T.llIlIIIlI[T.lllIlIIll[8]] = "ABYSSAL_DEMONS";
        T.llIlIIIlI[T.lllIlIIll[9]] = "Abyssal demons";
        T.llIlIIIlI[T.lllIlIIll[11]] = "ABYSSAL_SIRE";
        T.llIlIIIlI[T.lllIlIIll[12]] = "Abyssal Sire";
        T.llIlIIIlI[T.lllIlIIll[14]] = "ADAMANT_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[15]] = "Adamant dragons";
        T.llIlIIIlI[T.lllIlIIll[17]] = "ALCHEMICAL_HYDRA";
        T.llIlIIIlI[T.lllIlIIll[18]] = "Alchemical Hydra";
        T.llIlIIIlI[T.lllIlIIll[20]] = "ANKOU";
        T.llIlIIIlI[T.lllIlIIll[21]] = "Ankou";
        T.llIlIIIlI[T.lllIlIIll[23]] = "AVIANSIES";
        T.llIlIIIlI[T.lllIlIIll[24]] = "Aviansies";
        T.llIlIIIlI[T.lllIlIIll[26]] = "BANDITS";
        T.llIlIIIlI[T.lllIlIIll[27]] = "Bandits";
        T.llIlIIIlI[T.lllIlIIll[29]] = "Bandit";
        T.llIlIIIlI[T.lllIlIIll[30]] = "Black Heather";
        T.llIlIIIlI[T.lllIlIIll[31]] = "Donny the Lad";
        T.llIlIIIlI[T.lllIlIIll[32]] = "Speedy Keith";
        T.llIlIIIlI[T.lllIlIIll[33]] = "BANSHEES";
        T.llIlIIIlI[T.lllIlIIll[34]] = "Banshees";
        T.llIlIIIlI[T.lllIlIIll[36]] = "BARROWS_BROTHERS";
        T.llIlIIIlI[T.lllIlIIll[37]] = "Barrows Brothers";
        T.llIlIIIlI[T.lllIlIIll[39]] = "BASILISKS";
        T.llIlIIIlI[T.lllIlIIll[40]] = "Basilisks";
        T.llIlIIIlI[T.lllIlIIll[42]] = "BATS";
        T.llIlIIIlI[T.lllIlIIll[43]] = "Bats";
        T.llIlIIIlI[T.lllIlIIll[45]] = "Death wing";
        T.llIlIIIlI[T.lllIlIIll[46]] = "BEARS";
        T.llIlIIIlI[T.lllIlIIll[47]] = "Bears";
        T.llIlIIIlI[T.lllIlIIll[49]] = "BIRDS";
        T.llIlIIIlI[T.lllIlIIll[50]] = "Birds";
        T.llIlIIIlI[T.lllIlIIll[52]] = "Chicken";
        T.llIlIIIlI[T.lllIlIIll[53]] = "Rooster";
        T.llIlIIIlI[T.lllIlIIll[54]] = "Terrorbird";
        T.llIlIIIlI[T.lllIlIIll[55]] = "Seagull";
        T.llIlIIIlI[T.lllIlIIll[56]] = "Vulture";
        T.llIlIIIlI[T.lllIlIIll[57]] = "Duck";
        T.llIlIIIlI[T.lllIlIIll[58]] = "Penguin";
        T.llIlIIIlI[T.lllIlIIll[59]] = "BLACK_DEMONS";
        T.llIlIIIlI[T.lllIlIIll[60]] = "Black demons";
        T.llIlIIIlI[T.lllIlIIll[62]] = "BLACK_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[63]] = "Black dragons";
        T.llIlIIIlI[T.lllIlIIll[65]] = "Baby black dragon";
        T.llIlIIIlI[T.lllIlIIll[66]] = "BLACK_KNIGHTS";
        T.llIlIIIlI[T.lllIlIIll[67]] = "Black Knights";
        T.llIlIIIlI[T.lllIlIIll[69]] = "Black Knight";
        T.llIlIIIlI[T.lllIlIIll[70]] = "BLOODVELD";
        T.llIlIIIlI[T.lllIlIIll[5]] = "Bloodveld";
        T.llIlIIIlI[T.lllIlIIll[72]] = "BLUE_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[73]] = "Blue dragons";
        T.llIlIIIlI[T.lllIlIIll[75]] = "Baby blue dragon";
        T.llIlIIIlI[T.lllIlIIll[76]] = "BRINE_RATS";
        T.llIlIIIlI[T.lllIlIIll[77]] = "Brine rats";
        T.llIlIIIlI[T.lllIlIIll[79]] = "BRONZE_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[80]] = "Bronze dragons";
        T.llIlIIIlI[T.lllIlIIll[82]] = "CALLISTO";
        T.llIlIIIlI[T.lllIlIIll[83]] = "Callisto";
        T.llIlIIIlI[T.lllIlIIll[85]] = "CATABLEPON";
        T.llIlIIIlI[T.lllIlIIll[86]] = "Catablepon";
        T.llIlIIIlI[T.lllIlIIll[88]] = "CAVE_BUGS";
        T.llIlIIIlI[T.lllIlIIll[89]] = "Cave bugs";
        T.llIlIIIlI[T.lllIlIIll[91]] = "CAVE_CRAWLERS";
        T.llIlIIIlI[T.lllIlIIll[92]] = "Cave crawlers";
        T.llIlIIIlI[T.lllIlIIll[94]] = "Chasm crawler";
        T.llIlIIIlI[T.lllIlIIll[95]] = "CAVE_HORRORS";
        T.llIlIIIlI[T.lllIlIIll[96]] = "Cave horrors";
        T.llIlIIIlI[T.lllIlIIll[98]] = "Cave abomination";
        T.llIlIIIlI[T.lllIlIIll[99]] = "CAVE_KRAKEN";
        T.llIlIIIlI[T.lllIlIIll[100]] = "Cave kraken";
        T.llIlIIIlI[T.lllIlIIll[102]] = "CAVE_SLIMES";
        T.llIlIIIlI[T.lllIlIIll[103]] = "Cave slimes";
        T.llIlIIIlI[T.lllIlIIll[105]] = "CERBERUS";
        T.llIlIIIlI[T.lllIlIIll[106]] = "Cerberus";
        T.llIlIIIlI[T.lllIlIIll[108]] = "CHAOS_DRUIDS";
        T.llIlIIIlI[T.lllIlIIll[109]] = "Chaos druids";
        T.llIlIIIlI[T.lllIlIIll[111]] = "Elder Chaos druid";
        T.llIlIIIlI[T.lllIlIIll[112]] = "Chaos druid";
        T.llIlIIIlI[T.lllIlIIll[113]] = "CHAOS_ELEMENTAL";
        T.llIlIIIlI[T.lllIlIIll[114]] = "Chaos Elemental";
        T.llIlIIIlI[T.lllIlIIll[116]] = "CHAOS_FANATIC";
        T.llIlIIIlI[T.lllIlIIll[117]] = "Chaos Fanatic";
        T.llIlIIIlI[T.lllIlIIll[119]] = "COCKATRICE";
        T.llIlIIIlI[T.lllIlIIll[120]] = "Cockatrice";
        T.llIlIIIlI[T.lllIlIIll[122]] = "Cockathrice";
        T.llIlIIIlI[T.lllIlIIll[123]] = "COWS";
        T.llIlIIIlI[T.lllIlIIll[124]] = "Cows";
        T.llIlIIIlI[T.lllIlIIll[126]] = "CRAWLING_HANDS";
        T.llIlIIIlI[T.lllIlIIll[127]] = "Crawling hands";
        T.llIlIIIlI[T.lllIlIIll[129]] = "Crushing hand";
        T.llIlIIIlI[T.lllIlIIll[130]] = "CRAZY_ARCHAEOLOGIST";
        T.llIlIIIlI[T.lllIlIIll[131]] = "Crazy Archaeologists";
        T.llIlIIIlI[T.lllIlIIll[133]] = "Crazy Archaeologist";
        T.llIlIIIlI[T.lllIlIIll[134]] = "CROCODILES";
        T.llIlIIIlI[T.lllIlIIll[135]] = "Crocodiles";
        T.llIlIIIlI[T.lllIlIIll[137]] = "DAGANNOTH";
        T.llIlIIIlI[T.lllIlIIll[138]] = "Dagannoth";
        T.llIlIIIlI[T.lllIlIIll[140]] = "DAGANNOTH_KINGS";
        T.llIlIIIlI[T.lllIlIIll[141]] = "Dagannoth Kings";
        T.llIlIIIlI[T.lllIlIIll[143]] = "DARK_BEASTS";
        T.llIlIIIlI[T.lllIlIIll[144]] = "Dark beasts";
        T.llIlIIIlI[T.lllIlIIll[146]] = "Night beast";
        T.llIlIIIlI[T.lllIlIIll[147]] = "DARK_WARRIORS";
        T.llIlIIIlI[T.lllIlIIll[148]] = "Dark warriors";
        T.llIlIIIlI[T.lllIlIIll[150]] = "Dark warrior";
        T.llIlIIIlI[T.lllIlIIll[151]] = "DERANGED_ARCHAEOLOGIST";
        T.llIlIIIlI[T.lllIlIIll[152]] = "Deranged Archaeologist";
        T.llIlIIIlI[T.lllIlIIll[154]] = "DOGS";
        T.llIlIIIlI[T.lllIlIIll[155]] = "Dogs";
        T.llIlIIIlI[T.lllIlIIll[157]] = "Jackal";
        T.llIlIIIlI[T.lllIlIIll[158]] = "DRAKES";
        T.llIlIIIlI[T.lllIlIIll[159]] = "Drakes";
        T.llIlIIIlI[T.lllIlIIll[161]] = "DUST_DEVILS";
        T.llIlIIIlI[T.lllIlIIll[162]] = "Dust devils";
        T.llIlIIIlI[T.lllIlIIll[164]] = "Choke devil";
        T.llIlIIIlI[T.lllIlIIll[165]] = "DWARVES";
        T.llIlIIIlI[T.lllIlIIll[166]] = "Dwarves";
        T.llIlIIIlI[T.lllIlIIll[168]] = "Dwarf";
        T.llIlIIIlI[T.lllIlIIll[169]] = "Black Guard";
        T.llIlIIIlI[T.lllIlIIll[170]] = "EARTH_WARRIORS";
        T.llIlIIIlI[T.lllIlIIll[171]] = "Earth warriors";
        T.llIlIIIlI[T.lllIlIIll[173]] = "ELVES";
        T.llIlIIIlI[T.lllIlIIll[174]] = "Elves";
        T.llIlIIIlI[T.lllIlIIll[176]] = "Elf";
        T.llIlIIIlI[T.lllIlIIll[177]] = "Iorwerth Warrior";
        T.llIlIIIlI[T.lllIlIIll[178]] = "Iorwerth Archer";
        T.llIlIIIlI[T.lllIlIIll[179]] = "ENTS";
        T.llIlIIIlI[T.lllIlIIll[180]] = "Ents";
        T.llIlIIIlI[T.lllIlIIll[182]] = "Ent";
        T.llIlIIIlI[T.lllIlIIll[183]] = "FEVER_SPIDERS";
        T.llIlIIIlI[T.lllIlIIll[184]] = "Fever spiders";
        T.llIlIIIlI[T.lllIlIIll[186]] = "FIRE_GIANTS";
        T.llIlIIIlI[T.lllIlIIll[187]] = "Fire giants";
        T.llIlIIIlI[T.lllIlIIll[189]] = "FLESH_CRAWLERS";
        T.llIlIIIlI[T.lllIlIIll[190]] = "Fleshcrawlers";
        T.llIlIIIlI[T.lllIlIIll[192]] = "Flesh crawler";
        T.llIlIIIlI[T.lllIlIIll[193]] = "FOSSIL_ISLAND_WYVERNS";
        T.llIlIIIlI[T.lllIlIIll[194]] = "Fossil island wyverns";
        T.llIlIIIlI[T.lllIlIIll[196]] = "Ancient wyvern";
        T.llIlIIIlI[T.lllIlIIll[197]] = "Long-tailed wyvern";
        T.llIlIIIlI[T.lllIlIIll[198]] = "Spitting wyvern";
        T.llIlIIIlI[T.lllIlIIll[199]] = "Taloned wyvern";
        T.llIlIIIlI[T.lllIlIIll[200]] = "GARGOYLES";
        T.llIlIIIlI[T.lllIlIIll[201]] = "Gargoyles";
        T.llIlIIIlI[T.lllIlIIll[204]] = "GENERAL_GRAARDOR";
        T.llIlIIIlI[T.lllIlIIll[205]] = "General Graardor";
        T.llIlIIIlI[T.lllIlIIll[207]] = "GHOSTS";
        T.llIlIIIlI[T.lllIlIIll[208]] = "Ghosts";
        T.llIlIIIlI[T.lllIlIIll[210]] = "Death wing";
        T.llIlIIIlI[T.lllIlIIll[211]] = "Tortured soul";
        T.llIlIIIlI[T.lllIlIIll[212]] = "GHOULS";
        T.llIlIIIlI[T.lllIlIIll[213]] = "Ghouls";
        T.llIlIIIlI[T.lllIlIIll[215]] = "GIANT_MOLE";
        T.llIlIIIlI[T.lllIlIIll[216]] = "Giant Mole";
        T.llIlIIIlI[T.lllIlIIll[218]] = "GOBLINS";
        T.llIlIIIlI[T.lllIlIIll[219]] = "Goblins";
        T.llIlIIIlI[T.lllIlIIll[221]] = "GREATER_DEMONS";
        T.llIlIIIlI[T.lllIlIIll[222]] = "Greater demons";
        T.llIlIIIlI[T.lllIlIIll[224]] = "GREEN_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[225]] = "Green dragons";
        T.llIlIIIlI[T.lllIlIIll[227]] = "Baby green dragon";
        T.llIlIIIlI[T.lllIlIIll[228]] = "Elvarg";
        T.llIlIIIlI[T.lllIlIIll[229]] = "GROTESQUE_GUARDIANS";
        T.llIlIIIlI[T.lllIlIIll[230]] = "Grotesque Guardians";
        T.llIlIIIlI[T.lllIlIIll[232]] = "Dusk";
        T.llIlIIIlI[T.lllIlIIll[233]] = "Dawn";
        T.llIlIIIlI[T.lllIlIIll[234]] = "HARPIE_BUG_SWARMS";
        T.llIlIIIlI[T.lllIlIIll[235]] = "Harpie bug swarms";
        T.llIlIIIlI[T.lllIlIIll[237]] = "HELLHOUNDS";
        T.llIlIIIlI[T.lllIlIIll[238]] = "Hellhounds";
        T.llIlIIIlI[T.lllIlIIll[240]] = "HILL_GIANTS";
        T.llIlIIIlI[T.lllIlIIll[241]] = "Hill giants";
        T.llIlIIIlI[T.lllIlIIll[243]] = "Cyclops";
        T.llIlIIIlI[T.lllIlIIll[244]] = "HOBGOBLINS";
        T.llIlIIIlI[T.lllIlIIll[245]] = "Hobgoblins";
        T.llIlIIIlI[T.lllIlIIll[247]] = "HYDRAS";
        T.llIlIIIlI[T.lllIlIIll[248]] = "Hydras";
        T.llIlIIIlI[T.lllIlIIll[250]] = "ICEFIENDS";
        T.llIlIIIlI[T.lllIlIIll[251]] = "Icefiends";
        T.llIlIIIlI[T.lllIlIIll[253]] = "ICE_GIANTS";
        T.llIlIIIlI[T.lllIlIIll[254]] = "Ice giants";
        T.llIlIIIlI[T.lllIlIIll[255]] = "ICE_WARRIORS";
        T.llIlIIIlI[T.lllIlIIll[256]] = "Ice warriors";
        T.llIlIIIlI[T.lllIlIIll[258]] = "Icelord";
        T.llIlIIIlI[T.lllIlIIll[259]] = "INFERNAL_MAGES";
        T.llIlIIIlI[T.lllIlIIll[260]] = "Infernal mages";
        T.llIlIIIlI[T.lllIlIIll[262]] = "Malevolent mage";
        T.llIlIIIlI[T.lllIlIIll[263]] = "IRON_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[264]] = "Iron dragons";
        T.llIlIIIlI[T.lllIlIIll[266]] = "JAD";
        T.llIlIIIlI[T.lllIlIIll[267]] = "TzTok-Jad";
        T.llIlIIIlI[T.lllIlIIll[269]] = "JELLIES";
        T.llIlIIIlI[T.lllIlIIll[270]] = "Jellies";
        T.llIlIIIlI[T.lllIlIIll[272]] = "Jelly";
        T.llIlIIIlI[T.lllIlIIll[273]] = "JUNGLE_HORROR";
        T.llIlIIIlI[T.lllIlIIll[274]] = "Jungle horrors";
        T.llIlIIIlI[T.lllIlIIll[276]] = "KALPHITE";
        T.llIlIIIlI[T.lllIlIIll[277]] = "Kalphite";
        T.llIlIIIlI[T.lllIlIIll[279]] = "KALPHITE_QUEEN";
        T.llIlIIIlI[T.lllIlIIll[280]] = "Kalphite Queen";
        T.llIlIIIlI[T.lllIlIIll[282]] = "KILLERWATTS";
        T.llIlIIIlI[T.lllIlIIll[283]] = "Killerwatts";
        T.llIlIIIlI[T.lllIlIIll[285]] = "KING_BLACK_DRAGON";
        T.llIlIIIlI[T.lllIlIIll[286]] = "King Black Dragon";
        T.llIlIIIlI[T.lllIlIIll[288]] = "KRAKEN";
        T.llIlIIIlI[T.lllIlIIll[289]] = "Cave Kraken Boss";
        T.llIlIIIlI[T.lllIlIIll[291]] = "Kraken";
        T.llIlIIIlI[T.lllIlIIll[292]] = "KREEARRA";
        T.llIlIIIlI[T.lllIlIIll[293]] = "Kree'arra";
        T.llIlIIIlI[T.lllIlIIll[295]] = "KRIL_TSUTSAROTH";
        T.llIlIIIlI[T.lllIlIIll[296]] = "K'ril Tsutsaroth";
        T.llIlIIIlI[T.lllIlIIll[298]] = "KURASK";
        T.llIlIIIlI[T.lllIlIIll[299]] = "Kurask";
        T.llIlIIIlI[T.lllIlIIll[301]] = "LAVA_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[302]] = "Lava Dragons";
        T.llIlIIIlI[T.lllIlIIll[304]] = "Lava dragon";
        T.llIlIIIlI[T.lllIlIIll[305]] = "LESSER_DEMONS";
        T.llIlIIIlI[T.lllIlIIll[306]] = "Lesser demons";
        T.llIlIIIlI[T.lllIlIIll[308]] = "LIZARDMEN";
        T.llIlIIIlI[T.lllIlIIll[309]] = "Lizardmen";
        T.llIlIIIlI[T.lllIlIIll[311]] = "Lizardman";
        T.llIlIIIlI[T.lllIlIIll[312]] = "LIZARDS";
        T.llIlIIIlI[T.lllIlIIll[313]] = "Lizards";
        T.llIlIIIlI[T.lllIlIIll[315]] = "Desert lizard";
        T.llIlIIIlI[T.lllIlIIll[316]] = "Sulphur lizard";
        T.llIlIIIlI[T.lllIlIIll[317]] = "Small lizard";
        T.llIlIIIlI[T.lllIlIIll[318]] = "Lizard";
        T.llIlIIIlI[T.lllIlIIll[319]] = "MAGIC_AXES";
        T.llIlIIIlI[T.lllIlIIll[320]] = "Magic axes";
        T.llIlIIIlI[T.lllIlIIll[322]] = "Magic axe";
        T.llIlIIIlI[T.lllIlIIll[323]] = "MAMMOTHS";
        T.llIlIIIlI[T.lllIlIIll[324]] = "Mammoths";
        T.llIlIIIlI[T.lllIlIIll[326]] = "Mammoth";
        T.llIlIIIlI[T.lllIlIIll[327]] = "MINIONS_OF_SCABARAS";
        T.llIlIIIlI[T.lllIlIIll[328]] = "Minions of scabaras";
        T.llIlIIIlI[T.lllIlIIll[330]] = "Scarab swarm";
        T.llIlIIIlI[T.lllIlIIll[331]] = "Locust rider";
        T.llIlIIIlI[T.lllIlIIll[332]] = "Scarab mage";
        T.llIlIIIlI[T.lllIlIIll[333]] = "MINOTAURS";
        T.llIlIIIlI[T.lllIlIIll[334]] = "Minotaurs";
        T.llIlIIIlI[T.lllIlIIll[336]] = "MITHRIL_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[337]] = "Mithril dragons";
        T.llIlIIIlI[T.lllIlIIll[339]] = "MOGRES";
        T.llIlIIIlI[T.lllIlIIll[340]] = "Mogres";
        T.llIlIIIlI[T.lllIlIIll[342]] = "MOLANISKS";
        T.llIlIIIlI[T.lllIlIIll[343]] = "Molanisks";
        T.llIlIIIlI[T.lllIlIIll[345]] = "MONKEYS";
        T.llIlIIIlI[T.lllIlIIll[346]] = "Monkeys";
        T.llIlIIIlI[T.lllIlIIll[348]] = "Tortured gorilla";
        T.llIlIIIlI[T.lllIlIIll[349]] = "MOSS_GIANTS";
        T.llIlIIIlI[T.lllIlIIll[350]] = "Moss giants";
        T.llIlIIIlI[T.lllIlIIll[352]] = "MUTATED_ZYGOMITES";
        T.llIlIIIlI[T.lllIlIIll[353]] = "Mutated zygomites";
        T.llIlIIIlI[T.lllIlIIll[356]] = "Zygomite";
        T.llIlIIIlI[T.lllIlIIll[357]] = "Fungi";
        T.llIlIIIlI[T.lllIlIIll[358]] = "NECHRYAEL";
        T.llIlIIIlI[T.lllIlIIll[359]] = "Nechryael";
        T.llIlIIIlI[T.lllIlIIll[361]] = "Nechryarch";
        T.llIlIIIlI[T.lllIlIIll[362]] = "OGRES";
        T.llIlIIIlI[T.lllIlIIll[363]] = "Ogres";
        T.llIlIIIlI[T.lllIlIIll[365]] = "OTHERWORLDLY_BEING";
        T.llIlIIIlI[T.lllIlIIll[366]] = "Otherworldly beings";
        T.llIlIIIlI[T.lllIlIIll[368]] = "PIRATES";
        T.llIlIIIlI[T.lllIlIIll[369]] = "Pirates";
        T.llIlIIIlI[T.lllIlIIll[371]] = "Pirate";
        T.llIlIIIlI[T.lllIlIIll[372]] = "PYREFIENDS";
        T.llIlIIIlI[T.lllIlIIll[373]] = "Pyrefiends";
        T.llIlIIIlI[T.lllIlIIll[375]] = "Flaming pyrelord";
        T.llIlIIIlI[T.lllIlIIll[376]] = "RATS";
        T.llIlIIIlI[T.lllIlIIll[377]] = "Rats";
        T.llIlIIIlI[T.lllIlIIll[379]] = "RED_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[380]] = "Red dragons";
        T.llIlIIIlI[T.lllIlIIll[382]] = "Baby red dragon";
        T.llIlIIIlI[T.lllIlIIll[383]] = "REVENANTS";
        T.llIlIIIlI[T.lllIlIIll[384]] = "Revenants";
        T.llIlIIIlI[T.lllIlIIll[386]] = "Revenant imp";
        T.llIlIIIlI[T.lllIlIIll[387]] = "Revenant goblin";
        T.llIlIIIlI[T.lllIlIIll[388]] = "Revenant pyrefiend";
        T.llIlIIIlI[T.lllIlIIll[389]] = "Revenant hobgoblin";
        T.llIlIIIlI[T.lllIlIIll[390]] = "Revenant cyclops";
        T.llIlIIIlI[T.lllIlIIll[391]] = "Revenant hellhound";
        T.llIlIIIlI[T.lllIlIIll[392]] = "Revenant demon";
        T.llIlIIIlI[T.lllIlIIll[393]] = "Revenant ork";
        T.llIlIIIlI[T.lllIlIIll[394]] = "Revenant dark beast";
        T.llIlIIIlI[T.lllIlIIll[395]] = "Revenant knight";
        T.llIlIIIlI[T.lllIlIIll[396]] = "Revenant dragon";
        T.llIlIIIlI[T.lllIlIIll[397]] = "ROCKSLUGS";
        T.llIlIIIlI[T.lllIlIIll[398]] = "Rockslugs";
        T.llIlIIIlI[T.lllIlIIll[401]] = "ROGUES";
        T.llIlIIIlI[T.lllIlIIll[402]] = "Rogues";
        T.llIlIIIlI[T.lllIlIIll[404]] = "Rogue";
        T.llIlIIIlI[T.lllIlIIll[405]] = "RUNE_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[406]] = "Rune dragons";
        T.llIlIIIlI[T.lllIlIIll[408]] = "SARACHNIS";
        T.llIlIIIlI[T.lllIlIIll[409]] = "Sarachnis";
        T.llIlIIIlI[T.lllIlIIll[411]] = "SCORPIA";
        T.llIlIIIlI[T.lllIlIIll[412]] = "Scorpia";
        T.llIlIIIlI[T.lllIlIIll[414]] = "SCORPIONS";
        T.llIlIIIlI[T.lllIlIIll[378]] = "Scorpions";
        T.llIlIIIlI[T.lllIlIIll[415]] = "SEA_SNAKES";
        T.llIlIIIlI[T.lllIlIIll[416]] = "Sea snakes";
        T.llIlIIIlI[T.lllIlIIll[418]] = "SHADES";
        T.llIlIIIlI[T.lllIlIIll[419]] = "Shades";
        T.llIlIIIlI[T.lllIlIIll[421]] = "Loar Shadow";
        T.llIlIIIlI[T.lllIlIIll[422]] = "Loar Shade";
        T.llIlIIIlI[T.lllIlIIll[423]] = "Phrin Shadow";
        T.llIlIIIlI[T.lllIlIIll[424]] = "Phrin Shade";
        T.llIlIIIlI[T.lllIlIIll[425]] = "Riyl Shadow";
        T.llIlIIIlI[T.lllIlIIll[426]] = "Riyl Shade";
        T.llIlIIIlI[T.lllIlIIll[427]] = "Asyn Shadow";
        T.llIlIIIlI[T.lllIlIIll[428]] = "Asyn Shade";
        T.llIlIIIlI[T.lllIlIIll[429]] = "Fiyr Shadow";
        T.llIlIIIlI[T.lllIlIIll[51]] = "Fiyr Shade";
        T.llIlIIIlI[T.lllIlIIll[430]] = "SHADOW_WARRIORS";
        T.llIlIIIlI[T.lllIlIIll[431]] = "Shadow warriors";
        T.llIlIIIlI[T.lllIlIIll[432]] = "SKELETAL_WYVERNS";
        T.llIlIIIlI[T.lllIlIIll[433]] = "Skeletal wyverns";
        T.llIlIIIlI[T.lllIlIIll[435]] = "SKELETONS";
        T.llIlIIIlI[T.lllIlIIll[436]] = "Skeletons";
        T.llIlIIIlI[T.lllIlIIll[438]] = "SMOKE_DEVILS";
        T.llIlIIIlI[T.lllIlIIll[439]] = "Smoke devils";
        T.llIlIIIlI[T.lllIlIIll[441]] = "SOURHOGS";
        T.llIlIIIlI[T.lllIlIIll[442]] = "Sourhogs";
        T.llIlIIIlI[T.lllIlIIll[444]] = "SPIDERS";
        T.llIlIIIlI[T.lllIlIIll[445]] = "Spiders";
        T.llIlIIIlI[T.lllIlIIll[447]] = "SPIRITUAL_CREATURES";
        T.llIlIIIlI[T.lllIlIIll[448]] = "Spiritual creatures";
        T.llIlIIIlI[T.lllIlIIll[450]] = "Spiritual ranger";
        T.llIlIIIlI[T.lllIlIIll[451]] = "Spiritual mage";
        T.llIlIIIlI[T.lllIlIIll[452]] = "Spiritual warrior";
        T.llIlIIIlI[T.lllIlIIll[453]] = "STEEL_DRAGONS";
        T.llIlIIIlI[T.lllIlIIll[454]] = "Steel dragons";
        T.llIlIIIlI[T.lllIlIIll[456]] = "SULPHUR_LIZARDS";
        T.llIlIIIlI[T.lllIlIIll[457]] = "Sulphur Lizards";
        T.llIlIIIlI[T.lllIlIIll[459]] = "SUQAHS";
        T.llIlIIIlI[T.lllIlIIll[460]] = "Suqahs";
        T.llIlIIIlI[T.lllIlIIll[462]] = "TEMPLE_SPIDERS";
        T.llIlIIIlI[T.lllIlIIll[463]] = "Temple Spiders";
        T.llIlIIIlI[T.lllIlIIll[464]] = "TERROR_DOGS";
        T.llIlIIIlI[T.lllIlIIll[465]] = "Terror dogs";
        T.llIlIIIlI[T.lllIlIIll[467]] = "THERMONUCLEAR_SMOKE_DEVIL";
        T.llIlIIIlI[T.lllIlIIll[468]] = "Thermonuclear Smoke Devil";
        T.llIlIIIlI[T.lllIlIIll[470]] = "TROLLS";
        T.llIlIIIlI[T.lllIlIIll[471]] = "Trolls";
        T.llIlIIIlI[T.lllIlIIll[473]] = "Dad";
        T.llIlIIIlI[T.lllIlIIll[474]] = "Arrg";
        T.llIlIIIlI[T.lllIlIIll[475]] = "TUROTH";
        T.llIlIIIlI[T.lllIlIIll[476]] = "Turoth";
        T.llIlIIIlI[T.lllIlIIll[478]] = "TZHAAR";
        T.llIlIIIlI[T.lllIlIIll[479]] = "Tzhaar";
        T.llIlIIIlI[T.lllIlIIll[481]] = "UNDEAD_DRUIDS";
        T.llIlIIIlI[T.lllIlIIll[482]] = "Undead Druids";
        T.llIlIIIlI[T.lllIlIIll[484]] = "VAMPYRES";
        T.llIlIIIlI[T.lllIlIIll[485]] = "Vampyres";
        T.llIlIIIlI[T.lllIlIIll[487]] = "Vyrewatch";
        T.llIlIIIlI[T.lllIlIIll[488]] = "Vampire";
        T.llIlIIIlI[T.lllIlIIll[489]] = "VENENATIS";
        T.llIlIIIlI[T.lllIlIIll[490]] = "Venenatis";
        T.llIlIIIlI[T.lllIlIIll[492]] = "VETION";
        T.llIlIIIlI[T.lllIlIIll[493]] = "Vet'ion";
        T.llIlIIIlI[T.lllIlIIll[495]] = "VORKATH";
        T.llIlIIIlI[T.lllIlIIll[496]] = "Vorkath";
        T.llIlIIIlI[T.lllIlIIll[498]] = "WALL_BEASTS";
        T.llIlIIIlI[T.lllIlIIll[499]] = "Wall beasts";
        T.llIlIIIlI[T.lllIlIIll[501]] = "WATERFIENDS";
        T.llIlIIIlI[T.lllIlIIll[502]] = "Waterfiends";
        T.llIlIIIlI[T.lllIlIIll[504]] = "WEREWOLVES";
        T.llIlIIIlI[T.lllIlIIll[505]] = "Werewolves";
        T.llIlIIIlI[T.lllIlIIll[507]] = "Werewolf";
        T.llIlIIIlI[T.lllIlIIll[508]] = "WOLVES";
        T.llIlIIIlI[T.lllIlIIll[509]] = "Wolves";
        T.llIlIIIlI[T.lllIlIIll[511]] = "Wolf";
        T.llIlIIIlI[T.lllIlIIll[512]] = "WYRMS";
        T.llIlIIIlI[T.lllIlIIll[513]] = "Wyrms";
        T.llIlIIIlI[T.lllIlIIll[515]] = "ZILYANA";
        T.llIlIIIlI[T.lllIlIIll[516]] = "Commander Zilyana";
        T.llIlIIIlI[T.lllIlIIll[518]] = "ZOMBIES";
        T.llIlIIIlI[T.lllIlIIll[519]] = "Zombies";
        T.llIlIIIlI[T.lllIlIIll[520]] = "Undead";
        T.llIlIIIlI[T.lllIlIIll[521]] = "ZUK";
        T.llIlIIIlI[T.lllIlIIll[522]] = "TzKal-Zuk";
        T.llIlIIIlI[T.lllIlIIll[524]] = "ZULRAH";
        T.llIlIIIlI[T.lllIlIIll[525]] = "Zulrah";
        T.llIlIIIlI[T.lllIlIIll[527]] = T.lIllIllIIll("", "FaCqE");
        T.llIlIIIlI[T.lllIlIIll[528]] = "Abyss";
        T.llIlIIIlI[T.lllIlIIll[529]] = "Ancient Cavern";
        T.llIlIIIlI[T.lllIlIIll[530]] = "Asgarnian Ice Dungeon";
        T.llIlIIIlI[T.lllIlIIll[531]] = "Battlefront";
        T.llIlIIIlI[T.lllIlIIll[532]] = "Brimhaven Dungeon";
        T.llIlIIIlI[T.lllIlIIll[533]] = "Brine Rat Cavern";
        T.llIlIIIlI[T.lllIlIIll[534]] = "Catacombs of Kourend";
        T.llIlIIIlI[T.lllIlIIll[535]] = "Chasm of Fire";
        T.llIlIIIlI[T.lllIlIIll[536]] = "Clan Wars";
        T.llIlIIIlI[T.lllIlIIll[537]] = "Death Plateau";
        T.llIlIIIlI[T.lllIlIIll[538]] = "Evil Chicken's Lair";
        T.llIlIIIlI[T.lllIlIIll[539]] = "Fossil Island";
        T.llIlIIIlI[T.lllIlIIll[540]] = "Forthos Dungeon";
        T.llIlIIIlI[T.lllIlIIll[541]] = "Fremennik Slayer Dungeon";
        T.llIlIIIlI[T.lllIlIIll[542]] = "God Wars Dungeon";
        T.llIlIIIlI[T.lllIlIIll[543]] = "Iorwerth Dungeon";
        T.llIlIIIlI[T.lllIlIIll[544]] = "Isle of Souls";
        T.llIlIIIlI[T.lllIlIIll[545]] = "Jormungand's Prison";
        T.llIlIIIlI[T.lllIlIIll[546]] = "Kalphite Lair";
        T.llIlIIIlI[T.lllIlIIll[547]] = "Karuulm Slayer Dungeon";
        T.llIlIIIlI[T.lllIlIIll[548]] = "Keldagrim";
        T.llIlIIIlI[T.lllIlIIll[549]] = "Kraken Cove";
        T.llIlIIIlI[T.lllIlIIll[550]] = "Lighthouse";
        T.llIlIIIlI[T.lllIlIIll[551]] = "Lithkren Vault";
        T.llIlIIIlI[T.lllIlIIll[552]] = "Lizardman Canyon";
        T.llIlIIIlI[T.lllIlIIll[553]] = "Lizardman Settlement";
        T.llIlIIIlI[T.lllIlIIll[554]] = "Meiyerditch Laboratories";
        T.llIlIIIlI[T.lllIlIIll[555]] = "Molch";
        T.llIlIIIlI[T.lllIlIIll[556]] = "Mount Quidamortem";
        T.llIlIIIlI[T.lllIlIIll[557]] = "Mourner Tunnels";
        T.llIlIIIlI[T.lllIlIIll[558]] = "Myths' Guild Dungeon";
        T.llIlIIIlI[T.lllIlIIll[559]] = "Ogre Enclave";
        T.llIlIIIlI[T.lllIlIIll[560]] = "Slayer Tower";
        T.llIlIIIlI[T.lllIlIIll[561]] = "Smoke Devil Dungeon";
        T.llIlIIIlI[T.lllIlIIll[562]] = "Smoke Dungeon";
        T.llIlIIIlI[T.lllIlIIll[563]] = "Stronghold of Security";
        T.llIlIIIlI[T.lllIlIIll[564]] = "Stronghold Slayer Dungeon";
        T.llIlIIIlI[T.lllIlIIll[565]] = "task-only Kalphite Cave";
        T.llIlIIIlI[T.lllIlIIll[566]] = "Taverley Dungeon";
        T.llIlIIIlI[T.lllIlIIll[567]] = "Troll Stronghold";
        T.llIlIIIlI[T.lllIlIIll[568]] = "Waterbirth Island";
        T.llIlIIIlI[T.lllIlIIll[569]] = "Waterfall Dungeon";
        T.llIlIIIlI[T.lllIlIIll[570]] = "Wilderness";
        T.llIlIIIlI[T.lllIlIIll[571]] = "Witchaven Dungeon";
        T.llIlIIIlI[T.lllIlIIll[572]] = "Zanaris";
    }

    public static T[] values() {
        return (T[])$VALUES.clone();
    }

    public static T valueOf(String string) {
        return Enum.valueOf(GameEnum115.class, string);
    }

    public int aQ() {
        return this.weaknessThreshold;
    }

    public String ax() {
        return this.name;
    }

    public String[] aP() {
        return this.targetNames;
    }

    private GameEnum115(String string2, int n3, int n4, int n5, String ... stringArray) {
        boolean bl2;
        if (T.llIlIIlllII(n3)) {
            bl2 = lllIlIIll[0];

            if (((0x58 ^ 0x74) & ~(0x4C ^ 0x60)) != ((0x2E ^ 0x60) & ~(0xF9 ^ 0xB7))) {
                throw null;
            }
        } else {
            bl2 = lllIlIIll[1];
        }
        Preconditions.checkArgument((boolean)bl2);
        this.name = string2;
        this.itemSpriteId = n3;
        this.weaknessThreshold = n4;
        this.weaknessItem = n5;
        this.targetNames = stringArray;
        this.xpMatcher = null;
    }
}

