/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.minigames.tasks;

import gg.squire.minigames.tasks.GameEnum;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import java.util.stream.Stream;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

public final class GameEnum11
extends Enum<e> {
    public static final  /* enum */ e WAVE21;
    public static final  /* enum */ e WAVE23;
    public static final  /* enum */ e WAVE42;
    public static final  /* enum */ e WAVE61;
    private static final  e[] $VALUES;
    public static final  /* enum */ e WAVE57;
    final  int waveNumber;
    public static final  /* enum */ e WAVE9;
    public static final  /* enum */ e WAVE51;
    public static final  /* enum */ e WAVE46;
    public static final  /* enum */ e WAVE40;
    public static final  /* enum */ e WAVE15;
    public static final  /* enum */ e WAVE8;
    public static final  /* enum */ e WAVE44;
    public static final  /* enum */ e WAVE41;
    public static final  /* enum */ e WAVE36;
    public static final  /* enum */ e WAVE13;
    public static final  /* enum */ e WAVE62;
    public static final  /* enum */ e WAVE47;
    public static final  /* enum */ e WAVE48;
    public static final  /* enum */ e WAVE24;
    private final  b[] monstersInWave;
    
    public static final  /* enum */ e WAVE5;
    public static final  /* enum */ e WAVE17;
    public static final  /* enum */ e WAVE55;
    public static final  /* enum */ e WAVE59;
    public static final  /* enum */ e WAVE31;
    public static final  /* enum */ e WAVE18;
    public static final  /* enum */ e WAVE16;
    public static final  /* enum */ e WAVE30;
    public static final  /* enum */ e WAVE63;
    public static final  /* enum */ e WAVE43;
    public static final  /* enum */ e WAVE11;
    public static final  /* enum */ e WAVE56;
    public static final  /* enum */ e WAVE60;
    public static final  /* enum */ e WAVE27;
    public static final  /* enum */ e WAVE58;
    public static final  /* enum */ e WAVE37;
    public static final  /* enum */ e WAVE7;
    public static final  /* enum */ e WAVE50;
    public static final  /* enum */ e WAVE29;
    
    public static final  /* enum */ e WAVE34;
    public static final  /* enum */ e WAVE3;
    public static final  /* enum */ e WAVE35;
    public static final  /* enum */ e WAVE52;
    public static final  /* enum */ e WAVE49;
    public static final  /* enum */ e WAVE4;
    public static final  /* enum */ e WAVE22;
    public static final  /* enum */ e WAVE20;
    public static final  /* enum */ e WAVE26;
    public static final  /* enum */ e WAVE19;
    public static final  /* enum */ e WAVE38;
    public static final  /* enum */ e WAVE32;
    public static final  /* enum */ e WAVE33;
    public static final  /* enum */ e NONE;
    public static final  /* enum */ e WAVE28;
    public static final  /* enum */ e WAVE2;
    public static final  /* enum */ e WAVE6;
    public static final  /* enum */ e WAVE45;
    public static final  /* enum */ e WAVE1;
    public static final  /* enum */ e WAVE12;
    public static final  /* enum */ e WAVE14;
    public static final  /* enum */ e WAVE25;
    public static final  /* enum */ e WAVE10;
    public static final  /* enum */ e WAVE39;
    public static final  /* enum */ e WAVE53;
    public static final  /* enum */ e WAVE54;

    public b[] h() {
        return this.monstersInWave;
    }

        return String.valueOf(var1);
    }

    private GameEnum11(b[] bArray, int n3) {
        this.monstersInWave = bArray;
        this.waveNumber = n3;
    }

    public static e valueOf(String string) {
        return Enum.valueOf(GameEnum11.class, string);
    }

    static {
        e.lllllIIlIlIIlI();
        e.lllllIIlIlIIIl();
        NONE = new GameEnum11(new b[llIIlIIlIIIl[0]], llIIlIIlIIIl[0]);
        b[] bArray = new b[llIIlIIlIIIl[1]];
        bArray[e.llIIlIIlIIIl[0]] = b.BAT;
        WAVE1 = new GameEnum11(bArray, llIIlIIlIIIl[1]);
        b[] bArray2 = new b[llIIlIIlIIIl[2]];
        bArray2[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray2[e.llIIlIIlIIIl[1]] = b.BAT;
        WAVE2 = new GameEnum11(bArray2, llIIlIIlIIIl[2]);
        b[] bArray3 = new b[llIIlIIlIIIl[1]];
        bArray3[e.llIIlIIlIIIl[0]] = b.BLOB;
        WAVE3 = new GameEnum11(bArray3, llIIlIIlIIIl[3]);
        b[] bArray4 = new b[llIIlIIlIIIl[2]];
        bArray4[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray4[e.llIIlIIlIIIl[1]] = b.BLOB;
        WAVE4 = new GameEnum11(bArray4, llIIlIIlIIIl[4]);
        b[] bArray5 = new b[llIIlIIlIIIl[3]];
        bArray5[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray5[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray5[e.llIIlIIlIIIl[2]] = b.BLOB;
        WAVE5 = new GameEnum11(bArray5, llIIlIIlIIIl[5]);
        b[] bArray6 = new b[llIIlIIlIIIl[2]];
        bArray6[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray6[e.llIIlIIlIIIl[1]] = b.BLOB;
        WAVE6 = new GameEnum11(bArray6, llIIlIIlIIIl[6]);
        b[] bArray7 = new b[llIIlIIlIIIl[1]];
        bArray7[e.llIIlIIlIIIl[0]] = b.RANGER;
        WAVE7 = new GameEnum11(bArray7, llIIlIIlIIIl[7]);
        b[] bArray8 = new b[llIIlIIlIIIl[2]];
        bArray8[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray8[e.llIIlIIlIIIl[1]] = b.RANGER;
        WAVE8 = new GameEnum11(bArray8, llIIlIIlIIIl[8]);
        b[] bArray9 = new b[llIIlIIlIIIl[3]];
        bArray9[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray9[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray9[e.llIIlIIlIIIl[2]] = b.RANGER;
        WAVE9 = new GameEnum11(bArray9, llIIlIIlIIIl[9]);
        b[] bArray10 = new b[llIIlIIlIIIl[2]];
        bArray10[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray10[e.llIIlIIlIIIl[1]] = b.RANGER;
        WAVE10 = new GameEnum11(bArray10, llIIlIIlIIIl[10]);
        b[] bArray11 = new b[llIIlIIlIIIl[3]];
        bArray11[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray11[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray11[e.llIIlIIlIIIl[2]] = b.RANGER;
        WAVE11 = new GameEnum11(bArray11, llIIlIIlIIIl[11]);
        b[] bArray12 = new b[llIIlIIlIIIl[4]];
        bArray12[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray12[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray12[e.llIIlIIlIIIl[2]] = b.BLOB;
        bArray12[e.llIIlIIlIIIl[3]] = b.RANGER;
        WAVE12 = new GameEnum11(bArray12, llIIlIIlIIIl[12]);
        b[] bArray13 = new b[llIIlIIlIIIl[3]];
        bArray13[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray13[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray13[e.llIIlIIlIIIl[2]] = b.RANGER;
        WAVE13 = new GameEnum11(bArray13, llIIlIIlIIIl[13]);
        b[] bArray14 = new b[llIIlIIlIIIl[2]];
        bArray14[e.llIIlIIlIIIl[0]] = b.RANGER;
        bArray14[e.llIIlIIlIIIl[1]] = b.RANGER;
        WAVE14 = new GameEnum11(bArray14, llIIlIIlIIIl[14]);
        b[] bArray15 = new b[llIIlIIlIIIl[1]];
        bArray15[e.llIIlIIlIIIl[0]] = b.MELEER;
        WAVE15 = new GameEnum11(bArray15, llIIlIIlIIIl[15]);
        b[] bArray16 = new b[llIIlIIlIIIl[2]];
        bArray16[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray16[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE16 = new GameEnum11(bArray16, llIIlIIlIIIl[16]);
        b[] bArray17 = new b[llIIlIIlIIIl[3]];
        bArray17[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray17[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray17[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE17 = new GameEnum11(bArray17, llIIlIIlIIIl[17]);
        b[] bArray18 = new b[llIIlIIlIIIl[2]];
        bArray18[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray18[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE18 = new GameEnum11(bArray18, llIIlIIlIIIl[18]);
        b[] bArray19 = new b[llIIlIIlIIIl[3]];
        bArray19[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray19[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray19[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE19 = new GameEnum11(bArray19, llIIlIIlIIIl[19]);
        b[] bArray20 = new b[llIIlIIlIIIl[4]];
        bArray20[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray20[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray20[e.llIIlIIlIIIl[2]] = b.BLOB;
        bArray20[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE20 = new GameEnum11(bArray20, llIIlIIlIIIl[20]);
        b[] bArray21 = new b[llIIlIIlIIIl[3]];
        bArray21[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray21[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray21[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE21 = new GameEnum11(bArray21, llIIlIIlIIIl[21]);
        b[] bArray22 = new b[llIIlIIlIIIl[2]];
        bArray22[e.llIIlIIlIIIl[0]] = b.RANGER;
        bArray22[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE22 = new GameEnum11(bArray22, llIIlIIlIIIl[22]);
        b[] bArray23 = new b[llIIlIIlIIIl[3]];
        bArray23[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray23[e.llIIlIIlIIIl[1]] = b.RANGER;
        bArray23[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE23 = new GameEnum11(bArray23, llIIlIIlIIIl[23]);
        b[] bArray24 = new b[llIIlIIlIIIl[4]];
        bArray24[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray24[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray24[e.llIIlIIlIIIl[2]] = b.RANGER;
        bArray24[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE24 = new GameEnum11(bArray24, llIIlIIlIIIl[24]);
        b[] bArray25 = new b[llIIlIIlIIIl[3]];
        bArray25[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray25[e.llIIlIIlIIIl[1]] = b.RANGER;
        bArray25[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE25 = new GameEnum11(bArray25, llIIlIIlIIIl[25]);
        b[] bArray26 = new b[llIIlIIlIIIl[4]];
        bArray26[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray26[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray26[e.llIIlIIlIIIl[2]] = b.RANGER;
        bArray26[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE26 = new GameEnum11(bArray26, llIIlIIlIIIl[26]);
        b[] bArray27 = new b[llIIlIIlIIIl[5]];
        bArray27[e.llIIlIIlIIIl[0]] = b.BAT;
        bArray27[e.llIIlIIlIIIl[1]] = b.BAT;
        bArray27[e.llIIlIIlIIIl[2]] = b.BLOB;
        bArray27[e.llIIlIIlIIIl[3]] = b.RANGER;
        bArray27[e.llIIlIIlIIIl[4]] = b.MELEER;
        WAVE27 = new GameEnum11(bArray27, llIIlIIlIIIl[27]);
        b[] bArray28 = new b[llIIlIIlIIIl[4]];
        bArray28[e.llIIlIIlIIIl[0]] = b.BLOB;
        bArray28[e.llIIlIIlIIIl[1]] = b.BLOB;
        bArray28[e.llIIlIIlIIIl[2]] = b.RANGER;
        bArray28[e.llIIlIIlIIIl[3]] = b.MELEER;
        WAVE28 = new GameEnum11(bArray28, llIIlIIlIIIl[28]);
        b[] bArray29 = new b[llIIlIIlIIIl[3]];
        bArray29[e.llIIlIIlIIIl[0]] = b.RANGER;
        bArray29[e.llIIlIIlIIIl[1]] = b.RANGER;
        bArray29[e.llIIlIIlIIIl[2]] = b.MELEER;
        WAVE29 = new GameEnum11(bArray29, llIIlIIlIIIl[29]);
        b[] bArray30 = new b[llIIlIIlIIIl[2]];
        bArray30[e.llIIlIIlIIIl[0]] = b.MELEER;
        bArray30[e.llIIlIIlIIIl[1]] = b.MELEER;
        WAVE30 = new GameEnum11(bArray30, llIIlIIlIIIl[30]);
        b[] bArray31 = new b[llIIlIIlIIIl[1]];
        bArray31[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE31 = new GameEnum11(bArray31, llIIlIIlIIIl[31]);
        b[] bArray32 = new b[llIIlIIlIIIl[1]];
        bArray32[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE32 = new GameEnum11(bArray32, llIIlIIlIIIl[32]);
        b[] bArray33 = new b[llIIlIIlIIIl[1]];
        bArray33[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE33 = new GameEnum11(bArray33, llIIlIIlIIIl[33]);
        b[] bArray34 = new b[llIIlIIlIIIl[1]];
        bArray34[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE34 = new GameEnum11(bArray34, llIIlIIlIIIl[34]);
        b[] bArray35 = new b[llIIlIIlIIIl[1]];
        bArray35[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE35 = new GameEnum11(bArray35, llIIlIIlIIIl[35]);
        b[] bArray36 = new b[llIIlIIlIIIl[1]];
        bArray36[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE36 = new GameEnum11(bArray36, llIIlIIlIIIl[36]);
        b[] bArray37 = new b[llIIlIIlIIIl[1]];
        bArray37[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE37 = new GameEnum11(bArray37, llIIlIIlIIIl[37]);
        b[] bArray38 = new b[llIIlIIlIIIl[1]];
        bArray38[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE38 = new GameEnum11(bArray38, llIIlIIlIIIl[38]);
        b[] bArray39 = new b[llIIlIIlIIIl[1]];
        bArray39[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE39 = new GameEnum11(bArray39, llIIlIIlIIIl[39]);
        b[] bArray40 = new b[llIIlIIlIIIl[1]];
        bArray40[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE40 = new GameEnum11(bArray40, llIIlIIlIIIl[40]);
        b[] bArray41 = new b[llIIlIIlIIIl[1]];
        bArray41[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE41 = new GameEnum11(bArray41, llIIlIIlIIIl[41]);
        b[] bArray42 = new b[llIIlIIlIIIl[1]];
        bArray42[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE42 = new GameEnum11(bArray42, llIIlIIlIIIl[42]);
        b[] bArray43 = new b[llIIlIIlIIIl[1]];
        bArray43[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE43 = new GameEnum11(bArray43, llIIlIIlIIIl[43]);
        b[] bArray44 = new b[llIIlIIlIIIl[1]];
        bArray44[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE44 = new GameEnum11(bArray44, llIIlIIlIIIl[44]);
        b[] bArray45 = new b[llIIlIIlIIIl[1]];
        bArray45[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE45 = new GameEnum11(bArray45, llIIlIIlIIIl[45]);
        b[] bArray46 = new b[llIIlIIlIIIl[1]];
        bArray46[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE46 = new GameEnum11(bArray46, llIIlIIlIIIl[46]);
        b[] bArray47 = new b[llIIlIIlIIIl[1]];
        bArray47[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE47 = new GameEnum11(bArray47, llIIlIIlIIIl[47]);
        b[] bArray48 = new b[llIIlIIlIIIl[1]];
        bArray48[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE48 = new GameEnum11(bArray48, llIIlIIlIIIl[48]);
        b[] bArray49 = new b[llIIlIIlIIIl[1]];
        bArray49[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE49 = new GameEnum11(bArray49, llIIlIIlIIIl[49]);
        b[] bArray50 = new b[llIIlIIlIIIl[1]];
        bArray50[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE50 = new GameEnum11(bArray50, llIIlIIlIIIl[50]);
        b[] bArray51 = new b[llIIlIIlIIIl[1]];
        bArray51[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE51 = new GameEnum11(bArray51, llIIlIIlIIIl[51]);
        b[] bArray52 = new b[llIIlIIlIIIl[1]];
        bArray52[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE52 = new GameEnum11(bArray52, llIIlIIlIIIl[52]);
        b[] bArray53 = new b[llIIlIIlIIIl[1]];
        bArray53[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE53 = new GameEnum11(bArray53, llIIlIIlIIIl[53]);
        b[] bArray54 = new b[llIIlIIlIIIl[1]];
        bArray54[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE54 = new GameEnum11(bArray54, llIIlIIlIIIl[54]);
        b[] bArray55 = new b[llIIlIIlIIIl[1]];
        bArray55[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE55 = new GameEnum11(bArray55, llIIlIIlIIIl[55]);
        b[] bArray56 = new b[llIIlIIlIIIl[1]];
        bArray56[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE56 = new GameEnum11(bArray56, llIIlIIlIIIl[56]);
        b[] bArray57 = new b[llIIlIIlIIIl[1]];
        bArray57[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE57 = new GameEnum11(bArray57, llIIlIIlIIIl[57]);
        b[] bArray58 = new b[llIIlIIlIIIl[1]];
        bArray58[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE58 = new GameEnum11(bArray58, llIIlIIlIIIl[58]);
        b[] bArray59 = new b[llIIlIIlIIIl[1]];
        bArray59[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE59 = new GameEnum11(bArray59, llIIlIIlIIIl[59]);
        b[] bArray60 = new b[llIIlIIlIIIl[1]];
        bArray60[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE60 = new GameEnum11(bArray60, llIIlIIlIIIl[60]);
        b[] bArray61 = new b[llIIlIIlIIIl[1]];
        bArray61[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE61 = new GameEnum11(bArray61, llIIlIIlIIIl[61]);
        b[] bArray62 = new b[llIIlIIlIIIl[1]];
        bArray62[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE62 = new GameEnum11(bArray62, llIIlIIlIIIl[62]);
        b[] bArray63 = new b[llIIlIIlIIIl[1]];
        bArray63[e.llIIlIIlIIIl[0]] = b.MAGER;
        WAVE63 = new GameEnum11(bArray63, llIIlIIlIIIl[63]);
        e[] eArray = new e[llIIlIIlIIIl[64]];
        eArray[e.llIIlIIlIIIl[0]] = NONE;
        eArray[e.llIIlIIlIIIl[1]] = WAVE1;
        eArray[e.llIIlIIlIIIl[2]] = WAVE2;
        eArray[e.llIIlIIlIIIl[3]] = WAVE3;
        eArray[e.llIIlIIlIIIl[4]] = WAVE4;
        eArray[e.llIIlIIlIIIl[5]] = WAVE5;
        eArray[e.llIIlIIlIIIl[6]] = WAVE6;
        eArray[e.llIIlIIlIIIl[7]] = WAVE7;
        eArray[e.llIIlIIlIIIl[8]] = WAVE8;
        eArray[e.llIIlIIlIIIl[9]] = WAVE9;
        eArray[e.llIIlIIlIIIl[10]] = WAVE10;
        eArray[e.llIIlIIlIIIl[11]] = WAVE11;
        eArray[e.llIIlIIlIIIl[12]] = WAVE12;
        eArray[e.llIIlIIlIIIl[13]] = WAVE13;
        eArray[e.llIIlIIlIIIl[14]] = WAVE14;
        eArray[e.llIIlIIlIIIl[15]] = WAVE15;
        eArray[e.llIIlIIlIIIl[16]] = WAVE16;
        eArray[e.llIIlIIlIIIl[17]] = WAVE17;
        eArray[e.llIIlIIlIIIl[18]] = WAVE18;
        eArray[e.llIIlIIlIIIl[19]] = WAVE19;
        eArray[e.llIIlIIlIIIl[20]] = WAVE20;
        eArray[e.llIIlIIlIIIl[21]] = WAVE21;
        eArray[e.llIIlIIlIIIl[22]] = WAVE22;
        eArray[e.llIIlIIlIIIl[23]] = WAVE23;
        eArray[e.llIIlIIlIIIl[24]] = WAVE24;
        eArray[e.llIIlIIlIIIl[25]] = WAVE25;
        eArray[e.llIIlIIlIIIl[26]] = WAVE26;
        eArray[e.llIIlIIlIIIl[27]] = WAVE27;
        eArray[e.llIIlIIlIIIl[28]] = WAVE28;
        eArray[e.llIIlIIlIIIl[29]] = WAVE29;
        eArray[e.llIIlIIlIIIl[30]] = WAVE30;
        eArray[e.llIIlIIlIIIl[31]] = WAVE31;
        eArray[e.llIIlIIlIIIl[32]] = WAVE32;
        eArray[e.llIIlIIlIIIl[33]] = WAVE33;
        eArray[e.llIIlIIlIIIl[34]] = WAVE34;
        eArray[e.llIIlIIlIIIl[35]] = WAVE35;
        eArray[e.llIIlIIlIIIl[36]] = WAVE36;
        eArray[e.llIIlIIlIIIl[37]] = WAVE37;
        eArray[e.llIIlIIlIIIl[38]] = WAVE38;
        eArray[e.llIIlIIlIIIl[39]] = WAVE39;
        eArray[e.llIIlIIlIIIl[40]] = WAVE40;
        eArray[e.llIIlIIlIIIl[41]] = WAVE41;
        eArray[e.llIIlIIlIIIl[42]] = WAVE42;
        eArray[e.llIIlIIlIIIl[43]] = WAVE43;
        eArray[e.llIIlIIlIIIl[44]] = WAVE44;
        eArray[e.llIIlIIlIIIl[45]] = WAVE45;
        eArray[e.llIIlIIlIIIl[46]] = WAVE46;
        eArray[e.llIIlIIlIIIl[47]] = WAVE47;
        eArray[e.llIIlIIlIIIl[48]] = WAVE48;
        eArray[e.llIIlIIlIIIl[49]] = WAVE49;
        eArray[e.llIIlIIlIIIl[50]] = WAVE50;
        eArray[e.llIIlIIlIIIl[51]] = WAVE51;
        eArray[e.llIIlIIlIIIl[52]] = WAVE52;
        eArray[e.llIIlIIlIIIl[53]] = WAVE53;
        eArray[e.llIIlIIlIIIl[54]] = WAVE54;
        eArray[e.llIIlIIlIIIl[55]] = WAVE55;
        eArray[e.llIIlIIlIIIl[56]] = WAVE56;
        eArray[e.llIIlIIlIIIl[57]] = WAVE57;
        eArray[e.llIIlIIlIIIl[58]] = WAVE58;
        eArray[e.llIIlIIlIIIl[59]] = WAVE59;
        eArray[e.llIIlIIlIIIl[60]] = WAVE60;
        eArray[e.llIIlIIlIIIl[61]] = WAVE61;
        eArray[e.llIIlIIlIIIl[62]] = WAVE62;
        eArray[e.llIIlIIlIIIl[63]] = WAVE63;
        $VALUES = eArray;
    }

    public int i() {
        return this.waveNumber;
    }

    private static boolean lllllIIlIlIIll(int n2, int n3) {
        return n2 < n3;
    }

    public static e[] values() {
        return (e[])$VALUES.clone();
    }

    public static Stream<e> g() {
        return Stream.of(e.values());
    }

    private static void lllllIIlIlIIIl() {
        llIIlIIIllll = new String[llIIlIIlIIIl[64]];
        e.llIIlIIIllll[e.llIIlIIlIIIl[0]] = "NONE";
        e.llIIlIIIllll[e.llIIlIIlIIIl[1]] = "WAVE1";
        e.llIIlIIIllll[e.llIIlIIlIIIl[2]] = "WAVE2";
        e.llIIlIIIllll[e.llIIlIIlIIIl[3]] = "WAVE3";
        e.llIIlIIIllll[e.llIIlIIlIIIl[4]] = "WAVE4";
        e.llIIlIIIllll[e.llIIlIIlIIIl[5]] = "WAVE5";
        e.llIIlIIIllll[e.llIIlIIlIIIl[6]] = "WAVE6";
        e.llIIlIIIllll[e.llIIlIIlIIIl[7]] = "WAVE7";
        e.llIIlIIIllll[e.llIIlIIlIIIl[8]] = "WAVE8";
        e.llIIlIIIllll[e.llIIlIIlIIIl[9]] = "WAVE9";
        e.llIIlIIIllll[e.llIIlIIlIIIl[10]] = "WAVE10";
        e.llIIlIIIllll[e.llIIlIIlIIIl[11]] = "WAVE11";
        e.llIIlIIIllll[e.llIIlIIlIIIl[12]] = "WAVE12";
        e.llIIlIIIllll[e.llIIlIIlIIIl[13]] = "WAVE13";
        e.llIIlIIIllll[e.llIIlIIlIIIl[14]] = "WAVE14";
        e.llIIlIIIllll[e.llIIlIIlIIIl[15]] = "WAVE15";
        e.llIIlIIIllll[e.llIIlIIlIIIl[16]] = "WAVE16";
        e.llIIlIIIllll[e.llIIlIIlIIIl[17]] = "WAVE17";
        e.llIIlIIIllll[e.llIIlIIlIIIl[18]] = "WAVE18";
        e.llIIlIIIllll[e.llIIlIIlIIIl[19]] = "WAVE19";
        e.llIIlIIIllll[e.llIIlIIlIIIl[20]] = "WAVE20";
        e.llIIlIIIllll[e.llIIlIIlIIIl[21]] = "WAVE21";
        e.llIIlIIIllll[e.llIIlIIlIIIl[22]] = "WAVE22";
        e.llIIlIIIllll[e.llIIlIIlIIIl[23]] = "WAVE23";
        e.llIIlIIIllll[e.llIIlIIlIIIl[24]] = "WAVE24";
        e.llIIlIIIllll[e.llIIlIIlIIIl[25]] = "WAVE25";
        e.llIIlIIIllll[e.llIIlIIlIIIl[26]] = "WAVE26";
        e.llIIlIIIllll[e.llIIlIIlIIIl[27]] = "WAVE27";
        e.llIIlIIIllll[e.llIIlIIlIIIl[28]] = "WAVE28";
        e.llIIlIIIllll[e.llIIlIIlIIIl[29]] = "WAVE29";
        e.llIIlIIIllll[e.llIIlIIlIIIl[30]] = "WAVE30";
        e.llIIlIIIllll[e.llIIlIIlIIIl[31]] = "WAVE31";
        e.llIIlIIIllll[e.llIIlIIlIIIl[32]] = "WAVE32";
        e.llIIlIIIllll[e.llIIlIIlIIIl[33]] = "WAVE33";
        e.llIIlIIIllll[e.llIIlIIlIIIl[34]] = "WAVE34";
        e.llIIlIIIllll[e.llIIlIIlIIIl[35]] = "WAVE35";
        e.llIIlIIIllll[e.llIIlIIlIIIl[36]] = "WAVE36";
        e.llIIlIIIllll[e.llIIlIIlIIIl[37]] = "WAVE37";
        e.llIIlIIIllll[e.llIIlIIlIIIl[38]] = "WAVE38";
        e.llIIlIIIllll[e.llIIlIIlIIIl[39]] = "WAVE39";
        e.llIIlIIIllll[e.llIIlIIlIIIl[40]] = "WAVE40";
        e.llIIlIIIllll[e.llIIlIIlIIIl[41]] = "WAVE41";
        e.llIIlIIIllll[e.llIIlIIlIIIl[42]] = "WAVE42";
        e.llIIlIIIllll[e.llIIlIIlIIIl[43]] = "WAVE43";
        e.llIIlIIIllll[e.llIIlIIlIIIl[44]] = "WAVE44";
        e.llIIlIIIllll[e.llIIlIIlIIIl[45]] = "WAVE45";
        e.llIIlIIIllll[e.llIIlIIlIIIl[46]] = "WAVE46";
        e.llIIlIIIllll[e.llIIlIIlIIIl[47]] = "WAVE47";
        e.llIIlIIIllll[e.llIIlIIlIIIl[48]] = "WAVE48";
        e.llIIlIIIllll[e.llIIlIIlIIIl[49]] = "WAVE49";
        e.llIIlIIIllll[e.llIIlIIlIIIl[50]] = "WAVE50";
        e.llIIlIIIllll[e.llIIlIIlIIIl[51]] = "WAVE51";
        e.llIIlIIIllll[e.llIIlIIlIIIl[52]] = "WAVE52";
        e.llIIlIIIllll[e.llIIlIIlIIIl[53]] = "WAVE53";
        e.llIIlIIIllll[e.llIIlIIlIIIl[54]] = "WAVE54";
        e.llIIlIIIllll[e.llIIlIIlIIIl[55]] = "WAVE55";
        e.llIIlIIIllll[e.llIIlIIlIIIl[56]] = "WAVE56";
        e.llIIlIIIllll[e.llIIlIIlIIIl[57]] = "WAVE57";
        e.llIIlIIIllll[e.llIIlIIlIIIl[58]] = "WAVE58";
        e.llIIlIIIllll[e.llIIlIIlIIIl[59]] = "WAVE59";
        e.llIIlIIIllll[e.llIIlIIlIIIl[60]] = "WAVE60";
        e.llIIlIIIllll[e.llIIlIIlIIIl[61]] = "WAVE61";
        e.llIIlIIIllll[e.llIIlIIlIIIl[62]] = "WAVE62";
        e.llIIlIIIllll[e.llIIlIIlIIIl[63]] = "WAVE63";
    }
}

