/*
 * Decompiled with CFR 0.152.
 */
package gg.squire.7bb63fa7-229b-499f-b77f-e1768cbbcc1e.tasks;

public class MHelper {
    public static final  int aT;
    public static final  int bx;
    public static final  int bt;
    public static final  int[] bL;
    public static final  int aV;
    public static final  int aZ;
    public static final  int bo;
    public static final  int bb;
    public static final  int bA;
    public static final  int[] bU;
    public static final  int[] bP;
    public static final  int[] bG;
    public static final  int[] bR;
    public static final  int bv;
    public static final  int bh;
    public static final  int[] bW;
    public static final  int bd;
    public static final  int bl;
    public static final  int[] bF;
    public static final  int bk;
    public static final  int by;
    public static final  int bw;
    public static final  int bB;
    public static final  int aY;
    public static final  int bg;
    public static final  int bq;
    public static final  int bi;
    public static final  int[] bX;
    public static final  int[] bQ;
    public static final  int[] bT;
    public static final  int[] bK;
    public static final  int[] bS;
    public static final  int bc;
    public static final  int bu;
    public static final  int[] bY;
    public static final  int bp;
    public static final  int bm;
    public static final  int[] bH;
    public static final  int bC;
    public static final  int ba;
    
    public static final  int[] bI;
    public static final  int be;
    public static final  int[] bV;
    public static final  int aX;
    public static final  int[] bJ;
    public static final  int bn;
    public static final  int bf;
    public static final  int[] bD;
    public static final  int aU;
    public static final  int bj;
    public static final  int[] bM;
    public static final  int aW;
    public static final  int bs;
    public static final  int[] bN;
    public static final  int bz;
    public static final  int[] bE;
    public static final  int br;
    public static final  int[] bO;

    static {
        m.lIIIlIll();
        bA = llllI[0];
        bc = llllI[1];
        aX = llllI[2];
        bg = llllI[3];
        by = llllI[4];
        bC = llllI[5];
        bB = llllI[6];
        bh = llllI[7];
        bk = llllI[8];
        aU = llllI[9];
        bi = llllI[10];
        aW = llllI[11];
        bt = llllI[12];
        bm = llllI[13];
        bd = llllI[14];
        bn = llllI[15];
        aT = llllI[16];
        bw = llllI[17];
        bx = llllI[18];
        br = llllI[19];
        bz = llllI[20];
        bs = llllI[21];
        bj = llllI[22];
        bu = llllI[23];
        be = llllI[24];
        aZ = llllI[25];
        bl = llllI[26];
        aV = llllI[27];
        bo = llllI[28];
        ba = llllI[29];
        bf = llllI[30];
        bq = llllI[31];
        aY = llllI[32];
        bb = llllI[33];
        bv = llllI[34];
        bp = llllI[35];
        int[] nArray = new int[llllI[36]];
        nArray[m.llllI[15]] = llllI[32];
        nArray[m.llllI[37]] = llllI[25];
        nArray[m.llllI[38]] = llllI[6];
        bD = nArray;
        int[] nArray2 = new int[llllI[39]];
        nArray2[m.llllI[15]] = llllI[29];
        nArray2[m.llllI[37]] = llllI[40];
        nArray2[m.llllI[38]] = llllI[41];
        nArray2[m.llllI[36]] = llllI[42];
        nArray2[m.llllI[43]] = llllI[44];
        nArray2[m.llllI[45]] = llllI[46];
        nArray2[m.llllI[47]] = llllI[48];
        nArray2[m.llllI[49]] = llllI[50];
        bE = nArray2;
        int[] nArray3 = new int[llllI[51]];
        nArray3[m.llllI[15]] = llllI[52];
        nArray3[m.llllI[37]] = llllI[53];
        nArray3[m.llllI[38]] = llllI[54];
        nArray3[m.llllI[36]] = llllI[55];
        nArray3[m.llllI[43]] = llllI[56];
        nArray3[m.llllI[45]] = llllI[57];
        nArray3[m.llllI[47]] = llllI[58];
        nArray3[m.llllI[49]] = llllI[59];
        nArray3[m.llllI[39]] = llllI[59];
        bF = nArray3;
        int[] nArray4 = new int[llllI[43]];
        nArray4[m.llllI[15]] = llllI[60];
        nArray4[m.llllI[37]] = llllI[61];
        nArray4[m.llllI[38]] = llllI[62];
        nArray4[m.llllI[36]] = llllI[63];
        bG = nArray4;
        int[] nArray5 = new int[llllI[43]];
        nArray5[m.llllI[15]] = llllI[64];
        nArray5[m.llllI[37]] = llllI[65];
        nArray5[m.llllI[38]] = llllI[66];
        nArray5[m.llllI[36]] = llllI[67];
        bH = nArray5;
        int[] nArray6 = new int[llllI[47]];
        nArray6[m.llllI[15]] = llllI[68];
        nArray6[m.llllI[37]] = llllI[69];
        nArray6[m.llllI[38]] = llllI[70];
        nArray6[m.llllI[36]] = llllI[71];
        nArray6[m.llllI[43]] = llllI[0];
        nArray6[m.llllI[45]] = llllI[72];
        bI = nArray6;
        int[] nArray7 = new int[llllI[43]];
        nArray7[m.llllI[15]] = llllI[73];
        nArray7[m.llllI[37]] = llllI[74];
        nArray7[m.llllI[38]] = llllI[75];
        nArray7[m.llllI[36]] = llllI[76];
        bJ = nArray7;
        int[] nArray8 = new int[llllI[43]];
        nArray8[m.llllI[15]] = llllI[77];
        nArray8[m.llllI[37]] = llllI[78];
        nArray8[m.llllI[38]] = llllI[79];
        nArray8[m.llllI[36]] = llllI[80];
        bK = nArray8;
        int[] nArray9 = new int[llllI[36]];
        nArray9[m.llllI[15]] = llllI[77];
        nArray9[m.llllI[37]] = llllI[78];
        nArray9[m.llllI[38]] = llllI[79];
        bL = nArray9;
        int[] nArray10 = new int[llllI[43]];
        nArray10[m.llllI[15]] = llllI[81];
        nArray10[m.llllI[37]] = llllI[82];
        nArray10[m.llllI[38]] = llllI[83];
        nArray10[m.llllI[36]] = llllI[84];
        bM = nArray10;
        int[] nArray11 = new int[llllI[43]];
        nArray11[m.llllI[15]] = llllI[85];
        nArray11[m.llllI[37]] = llllI[86];
        nArray11[m.llllI[38]] = llllI[87];
        nArray11[m.llllI[36]] = llllI[88];
        bN = nArray11;
        int[] nArray12 = new int[llllI[43]];
        nArray12[m.llllI[15]] = llllI[89];
        nArray12[m.llllI[37]] = llllI[90];
        nArray12[m.llllI[38]] = llllI[91];
        nArray12[m.llllI[36]] = llllI[92];
        bO = nArray12;
        int[] nArray13 = new int[llllI[43]];
        nArray13[m.llllI[15]] = llllI[93];
        nArray13[m.llllI[37]] = llllI[94];
        nArray13[m.llllI[38]] = llllI[95];
        nArray13[m.llllI[36]] = llllI[96];
        bP = nArray13;
        int[] nArray14 = new int[llllI[43]];
        nArray14[m.llllI[15]] = llllI[97];
        nArray14[m.llllI[37]] = llllI[98];
        nArray14[m.llllI[38]] = llllI[99];
        nArray14[m.llllI[36]] = llllI[100];
        bQ = nArray14;
        int[] nArray15 = new int[llllI[45]];
        nArray15[m.llllI[15]] = llllI[101];
        nArray15[m.llllI[37]] = llllI[102];
        nArray15[m.llllI[38]] = llllI[103];
        nArray15[m.llllI[36]] = llllI[104];
        nArray15[m.llllI[43]] = llllI[105];
        bR = nArray15;
        int[] nArray16 = new int[llllI[43]];
        nArray16[m.llllI[15]] = llllI[106];
        nArray16[m.llllI[37]] = llllI[107];
        nArray16[m.llllI[38]] = llllI[108];
        nArray16[m.llllI[36]] = llllI[109];
        bS = nArray16;
        int[] nArray17 = new int[llllI[43]];
        nArray17[m.llllI[15]] = llllI[110];
        nArray17[m.llllI[37]] = llllI[111];
        nArray17[m.llllI[38]] = llllI[112];
        nArray17[m.llllI[36]] = llllI[113];
        bT = nArray17;
        int[] nArray18 = new int[llllI[43]];
        nArray18[m.llllI[15]] = llllI[114];
        nArray18[m.llllI[37]] = llllI[115];
        nArray18[m.llllI[38]] = llllI[116];
        nArray18[m.llllI[36]] = llllI[117];
        bU = nArray18;
        int[] nArray19 = new int[llllI[36]];
        nArray19[m.llllI[15]] = llllI[23];
        nArray19[m.llllI[37]] = llllI[12];
        nArray19[m.llllI[38]] = llllI[21];
        bV = nArray19;
        int[] nArray20 = new int[llllI[45]];
        nArray20[m.llllI[15]] = llllI[33];
        nArray20[m.llllI[37]] = llllI[118];
        nArray20[m.llllI[38]] = llllI[119];
        nArray20[m.llllI[36]] = llllI[120];
        nArray20[m.llllI[43]] = llllI[121];
        bW = nArray20;
        int[] nArray21 = new int[llllI[36]];
        nArray21[m.llllI[15]] = llllI[122];
        nArray21[m.llllI[37]] = llllI[123];
        nArray21[m.llllI[38]] = llllI[124];
        bX = nArray21;
        int[] nArray22 = new int[llllI[43]];
        nArray22[m.llllI[15]] = llllI[125];
        nArray22[m.llllI[37]] = llllI[126];
        nArray22[m.llllI[38]] = llllI[127];
        nArray22[m.llllI[36]] = llllI[128];
        bY = nArray22;
    }
}

