package q.e.u.r.i.u.t.q.p000.e.e.s.r.s;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* renamed from: q.e.u.r.i.u.t.q.-.e.e.s.r.s.a  reason: invalid package and case insensitive filesystem */
/* loaded from: 9740bba2-b19d-4983-898f-2f8083c87d94.jar:q/e/u/r/i/u/t/q/-/e/e/s/r/s/a.class */
public final class EnumC0000a {
    public static final /* synthetic */ EnumC0000a QUEST_WITCHS_POTION;
    public static final /* synthetic */ EnumC0000a QUEST_TEMPLE_OF_IKOV;
    public static final /* synthetic */ EnumC0000a QUEST_MOURNINGS_END_PART_I;
    public static final /* synthetic */ EnumC0000a QUEST_SHEEP_HERDER;
    public static final /* synthetic */ EnumC0000a QUEST_ELEMENTAL_WORKSHOP_I;
    public static final /* synthetic */ EnumC0000a QUEST_SHILO_VILLAGE;
    public static final /* synthetic */ EnumC0000a QUEST_SHIELD_OF_ARRAV_STATE_146;
    public static final /* synthetic */ EnumC0000a QUEST_THE_RESTLESS_GHOST;
    public static final /* synthetic */ EnumC0000a QUEST_HAZEEL_CULT;
    public static final /* synthetic */ EnumC0000a QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
    public static final /* synthetic */ EnumC0000a QUEST_OBSERVATORY_QUEST;
    private final /* synthetic */ int id;
    public static final /* synthetic */ EnumC0000a QUEST_TAI_BWO_WANNAI_TRIO;
    public static final /* synthetic */ EnumC0000a QUEST_FIGHT_ARENA;
    public static final /* synthetic */ EnumC0000a QUEST_SHIELD_OF_ARRAV;
    public static final /* synthetic */ EnumC0000a QUEST_THE_MAGE_ARENA;
    public static final /* synthetic */ EnumC0000a QUEST_ROMEO_AND_JULIET;
    public static final /* synthetic */ EnumC0000a QUEST_CLOCK_TOWER;
    public static final /* synthetic */ EnumC0000a QUEST_JUNGLE_POTION;
    public static final /* synthetic */ EnumC0000a QUEST_RUNE_MYSTERIES;
    public static final /* synthetic */ EnumC0000a QUEST_MONKEY_MADNESS_I;
    public static final /* synthetic */ EnumC0000a QUEST_LEGENDS_QUEST;
    private static /* synthetic */ String[] lIIIllIllIIlI;
    public static final /* synthetic */ EnumC0000a QUEST_BIOHAZARD;
    public static final /* synthetic */ EnumC0000a QUEST_EADGARS_RUSE;
    public static final /* synthetic */ EnumC0000a QUEST_SCORPION_CATCHER;
    public static final /* synthetic */ EnumC0000a QUEST_ONE_SMALL_FAVOUR;
    public static final /* synthetic */ EnumC0000a QUEST_THE_KNIGHTS_SWORD;
    public static final /* synthetic */ EnumC0000a QUEST_HEROES_QUEST;
    public static final /* synthetic */ EnumC0000a QUEST_WITCHS_HOUSE;
    public static final /* synthetic */ EnumC0000a QUEST_ERNEST_THE_CHICKEN;
    public static final /* synthetic */ EnumC0000a QUEST_MURDER_MYSTERY;
    public static final /* synthetic */ EnumC0000a QUEST_DWARF_CANNON;
    public static final /* synthetic */ EnumC0000a QUEST_LOST_CITY;
    public static final /* synthetic */ EnumC0000a QUEST_GERTRUDES_CAT;
    public static final /* synthetic */ EnumC0000a QUEST_SEA_SLUG;
    public static final /* synthetic */ EnumC0000a QUEST_NATURE_SPIRIT;
    public static final /* synthetic */ EnumC0000a QUEST_THE_FREMENNIK_TRIALS;
    private static final /* synthetic */ EnumC0000a[] $VALUES;
    public static final /* synthetic */ EnumC0000a QUEST_REGICIDE;
    public static final /* synthetic */ EnumC0000a QUEST_ENTER_THE_ABYSS;
    public static final /* synthetic */ EnumC0000a QUEST_FISHING_CONTEST;
    public static final /* synthetic */ EnumC0000a QUEST_ROVING_ELVES;
    public static final /* synthetic */ EnumC0000a QUEST_WATCHTOWER;
    public static final /* synthetic */ EnumC0000a QUEST_VAMPYRE_SLAYER;
    public static final /* synthetic */ EnumC0000a QUEST_COOKS_ASSISTANT;
    public static final /* synthetic */ EnumC0000a QUEST_RAG_AND_BONE_MAN_II;
    public static final /* synthetic */ EnumC0000a QUEST_PRIEST_IN_PERIL;
    public static final /* synthetic */ EnumC0000a QUEST_TRIBAL_TOTEM;
    public static final /* synthetic */ EnumC0000a QUEST_PIRATES_TREASURE;
    public static final /* synthetic */ EnumC0000a QUEST_THE_GRAND_TREE;
    public static final /* synthetic */ EnumC0000a QUEST_WATERFALL_QUEST;
    public static final /* synthetic */ EnumC0000a QUEST_DORICS_QUEST;
    public static final /* synthetic */ EnumC0000a QUEST_UNDERGROUND_PASS;
    public static final /* synthetic */ EnumC0000a QUEST_CREATURE_OF_FENKENSTRAIN;
    public static final /* synthetic */ EnumC0000a QUEST_IMP_CATCHER;
    public static final /* synthetic */ EnumC0000a QUEST_BLACK_KNIGHTS_FORTRESS;
    public static final /* synthetic */ EnumC0000a QUEST_CABIN_FEVER;
    public static final /* synthetic */ EnumC0000a QUEST_DRAGON_SLAYER_I;
    public static final /* synthetic */ EnumC0000a QUEST_MERLINS_CRYSTAL;
    public static final /* synthetic */ EnumC0000a QUEST_BIG_CHOMPY_BIRD_HUNTING;
    public static final /* synthetic */ EnumC0000a QUEST_UNDERGROUND_PASS_STATE_162;
    public static final /* synthetic */ EnumC0000a QUEST_THE_DIG_SITE;
    public static final /* synthetic */ EnumC0000a QUEST_RAG_AND_BONE_MAN_I;
    public static final /* synthetic */ EnumC0000a QUEST_SHEEP_SHEARER;
    public static final /* synthetic */ EnumC0000a QUEST_SHADES_OF_MORTTON;
    public static final /* synthetic */ EnumC0000a QUEST_IN_SEARCH_OF_THE_MYREQUE;
    public static final /* synthetic */ EnumC0000a QUEST_HAUNTED_MINE;
    public static final /* synthetic */ EnumC0000a QUEST_DRUIDIC_RITUAL;
    public static final /* synthetic */ EnumC0000a QUEST_FAMILY_CREST;
    public static final /* synthetic */ EnumC0000a QUEST_PRINCE_ALI_RESCUE;
    public static final /* synthetic */ EnumC0000a QUEST_THE_TOURIST_TRAP;
    public static final /* synthetic */ EnumC0000a QUEST_THE_GREAT_BRAIN_ROBBERY;
    public static final /* synthetic */ EnumC0000a QUEST_DEATH_PLATEAU;
    public static final /* synthetic */ EnumC0000a QUEST_RUM_DEAL;
    public static final /* synthetic */ EnumC0000a QUEST_TROLL_ROMANCE;
    public static final /* synthetic */ EnumC0000a QUEST_TREE_GNOME_VILLAGE;
    private static /* synthetic */ int[] lIIIllIllIIll;
    public static final /* synthetic */ EnumC0000a QUEST_HOLY_GRAIL;
    public static final /* synthetic */ EnumC0000a QUEST_TROLL_STRONGHOLD;
    public static final /* synthetic */ EnumC0000a QUEST_MONKS_FRIEND;
    public static final /* synthetic */ EnumC0000a QUEST_ALFRED_GRIMHANDS_BARCRAWL;
    public static final /* synthetic */ EnumC0000a QUEST_THRONE_OF_MISCELLANIA;
    public static final /* synthetic */ EnumC0000a QUEST_PLAGUE_CITY;

    private static void lIlIIIllIIIlIII() {
        lIIIllIllIIll = new int[139];
        lIIIllIllIIll[0] = (118 ^ 125) & ((79 ^ 68) ^ (-1));
        lIIIllIllIIll[1] = ((54 + 75) - 88) + 89;
        lIIIllIllIIll[2] = " ".length();
        lIIIllIllIIll[3] = (237 ^ 173) ^ (43 ^ 118);
        lIIIllIllIIll[4] = "  ".length();
        lIIIllIllIIll[5] = (((113 + 82) - 187) + 135) ^ (((6 + 124) - 55) + 69);
        lIIIllIllIIll[6] = "   ".length();
        lIIIllIllIIll[7] = (((((18 + 33) - 47) + 124) + (24 ^ 70)) - (163 ^ 145)) + (191 ^ 187);
        lIIIllIllIIll[8] = (((42 + 126) - 97) + 120) ^ (((16 + 30) - (-83)) + 58);
        lIIIllIllIIll[9] = (((73 + 126) - 186) + 125) ^ (((149 + 1) - 116) + 136);
        lIIIllIllIIll[10] = 90 ^ 95;
        lIIIllIllIIll[11] = (((174 ^ 197) + (((44 + 43) - 69) + 127)) - (((106 + 6) - (-27)) + 107)) + ((46 + 17) - (-47)) + 44;
        lIIIllIllIIll[12] = 80 ^ 86;
        lIIIllIllIIll[13] = (49 ^ 104) ^ (84 ^ 119);
        lIIIllIllIIll[14] = (245 ^ 144) ^ (255 ^ 157);
        lIIIllIllIIll[15] = (((27 + 110) - 31) + 104) ^ (((99 + 22) - (-17)) + 11);
        lIIIllIllIIll[16] = (81 ^ 112) ^ (144 ^ 185);
        lIIIllIllIIll[17] = (-1703) & 1975;
        lIIIllIllIIll[18] = 130 ^ 139;
        lIIIllIllIIll[19] = 231 ^ 140;
        lIIIllIllIIll[20] = (100 ^ 64) ^ (137 ^ 167);
        lIIIllIllIIll[21] = (((((49 + 67) - 30) + 52) + (105 ^ 49)) - (((198 + 14) - 107) + 96)) + (196 ^ 179);
        lIIIllIllIIll[22] = (95 ^ 88) ^ (36 ^ 40);
        lIIIllIllIIll[23] = 135 ^ 184;
        lIIIllIllIIll[24] = 103 ^ 107;
        lIIIllIllIIll[25] = ((13 + 17) - 22) + 171;
        lIIIllIllIIll[26] = 15 ^ 2;
        lIIIllIllIIll[27] = (((((56 + 16) - 0) + 60) + (((103 + 76) - 146) + 109)) - (((92 + 14) - (-65)) + 31)) + (95 ^ 22);
        lIIIllIllIIll[28] = 34 ^ 44;
        lIIIllIllIIll[29] = (((229 ^ 135) + (14 ^ 105)) - (((138 + 40) - 74) + 35)) + (73 ^ 29);
        lIIIllIllIIll[30] = (64 ^ 23) ^ (254 ^ 166);
        lIIIllIllIIll[31] = ((1 + 118) - 0) + 59;
        lIIIllIllIIll[32] = (((206 + 77) - 174) + 106) ^ (((133 + 151) - 102) + 17);
        lIIIllIllIIll[33] = (((180 + 47) - 104) + 84) ^ (((129 + 102) - 122) + 31);
        lIIIllIllIIll[34] = (((166 + 55) - 190) + 179) ^ (((73 + 49) - 72) + 145);
        lIIIllIllIIll[35] = (-((-12841) & 32489)) & (-3) & 19943;
        lIIIllIllIIll[36] = (((41 + 74) - (-55)) + 4) ^ (((130 + 124) - 167) + 101);
        lIIIllIllIIll[37] = (97 ^ 38) ^ "   ".length();
        lIIIllIllIIll[38] = 25 ^ 10;
        lIIIllIllIIll[39] = (-3393) & 4047;
        lIIIllIllIIll[40] = 157 ^ 137;
        lIIIllIllIIll[41] = 10 ^ 31;
        lIIIllIllIIll[42] = (-((-427) & 23467)) & (-65) & 23503;
        lIIIllIllIIll[43] = (51 ^ 98) ^ (68 ^ 3);
        lIIIllIllIIll[44] = (-((-1411) & 32711)) & (-1) & 31614;
        lIIIllIllIIll[45] = (166 ^ 142) ^ (122 ^ 69);
        lIIIllIllIIll[46] = ((52 + 63) - 0) + 16;
        lIIIllIllIIll[47] = 68 ^ 92;
        lIIIllIllIIll[48] = 16 ^ 64;
        lIIIllIllIIll[49] = 17 ^ 8;
        lIIIllIllIIll[50] = 122 ^ 96;
        lIIIllIllIIll[51] = (-13489) & 13823;
        lIIIllIllIIll[52] = (225 ^ 184) ^ (225 ^ 163);
        lIIIllIllIIll[53] = (-30725) & 31023;
        lIIIllIllIIll[54] = 125 ^ 97;
        lIIIllIllIIll[55] = (((((57 + 6) - (-9)) + 55) + (84 ^ 88)) - (252 ^ 149)) + (183 ^ 197);
        lIIIllIllIIll[56] = (((11 + 69) - (-38)) + 23) ^ (((93 + 57) - 147) + 144);
        lIIIllIllIIll[57] = (-((-541) & 24221)) & (-8197) & 32223;
        lIIIllIllIIll[58] = 216 ^ 153;
        lIIIllIllIIll[59] = 106 ^ 75;
        lIIIllIllIIll[60] = ((40 + 175) - 91) + 56;
        lIIIllIllIIll[61] = 34 ^ 0;
        lIIIllIllIIll[62] = ((24 + 4) - (-92)) + 30;
        lIIIllIllIIll[63] = 0 ^ 35;
        lIIIllIllIIll[64] = (-9345) & 9726;
        lIIIllIllIIll[65] = (0 ^ 57) ^ (166 ^ 187);
        lIIIllIllIIll[66] = ((222 + 22) - 190) + 169;
        lIIIllIllIIll[67] = 22 ^ 51;
        lIIIllIllIIll[68] = (((172 ^ 160) + (((37 + 136) - 161) + 167)) - (190 ^ 173)) + (39 ^ 55);
        lIIIllIllIIll[69] = 40 ^ 14;
        lIIIllIllIIll[70] = 87 ^ 112;
        lIIIllIllIIll[71] = (-28713) & 29099;
        lIIIllIllIIll[72] = ((129 ^ 137) & ((109 ^ 101) ^ (-1))) ^ (157 ^ 181);
        lIIIllIllIIll[73] = ((157 + 133) - 247) + 132;
        lIIIllIllIIll[74] = 74 ^ 99;
        lIIIllIllIIll[75] = ((133 + 92) - 119) + 33;
        lIIIllIllIIll[76] = (209 ^ 185) ^ (116 ^ 54);
        lIIIllIllIIll[77] = (((89 ^ 48) + (72 ^ 117)) - (22 ^ 124)) + (146 ^ 197);
        lIIIllIllIIll[78] = 151 ^ 188;
        lIIIllIllIIll[79] = 113 ^ 93;
        lIIIllIllIIll[80] = (-11409) & 11773;
        lIIIllIllIIll[81] = 110 ^ 67;
        lIIIllIllIIll[82] = 30 ^ 48;
        lIIIllIllIIll[83] = (-((-8325) & 28159)) & (-8193) & 28543;
        lIIIllIllIIll[84] = 30 ^ 49;
        lIIIllIllIIll[85] = ((142 + 182) - 143) + 11;
        lIIIllIllIIll[86] = 61 ^ 13;
        lIIIllIllIIll[87] = (-12809) & 13115;
        lIIIllIllIIll[88] = 37 ^ 20;
        lIIIllIllIIll[89] = (50 ^ 94) ^ (49 ^ 45);
        lIIIllIllIIll[90] = 74 ^ 120;
        lIIIllIllIIll[91] = (-25170) & 25585;
        lIIIllIllIIll[92] = 1 ^ 50;
        lIIIllIllIIll[93] = ((131 + 85) - 144) + 93;
        lIIIllIllIIll[94] = (238 ^ 195) ^ (4 ^ 29);
        lIIIllIllIIll[95] = (-((-24782) & 32479)) & (-24705) & 32703;
        lIIIllIllIIll[96] = 33 ^ 20;
        lIIIllIllIIll[97] = (-8465) & 9178;
        lIIIllIllIIll[98] = (((39 + 84) - 112) + 121) ^ (((138 + 123) - 203) + 120);
        lIIIllIllIIll[99] = (-((-24980) & 26551)) & (-30849) & 32747;
        lIIIllIllIIll[100] = 42 ^ 29;
        lIIIllIllIIll[101] = (-2118) & 2519;
        lIIIllIllIIll[102] = (((86 + 116) - 77) + 5) ^ (((16 + 29) - (-41)) + 100);
        lIIIllIllIIll[103] = (-20773) & 21372;
        lIIIllIllIIll[104] = (22 ^ 113) ^ (6 ^ 88);
        lIIIllIllIIll[105] = (((48 + 15) - 12) + 144) ^ (((52 + 73) - 49) + 67);
        lIIIllIllIIll[106] = (100 ^ 116) ^ (126 ^ 84);
        lIIIllIllIIll[107] = ((140 + 113) - 143) + 49;
        lIIIllIllIIll[108] = 107 ^ 80;
        lIIIllIllIIll[109] = (-((-18639) & 24303)) & (-141) & 6143;
        lIIIllIllIIll[110] = 129 ^ 189;
        lIIIllIllIIll[111] = 254 ^ 195;
        lIIIllIllIIll[112] = 110 ^ 26;
        lIIIllIllIIll[113] = 123 ^ 69;
        lIIIllIllIIll[114] = (-((-449) & 10237)) & (-4100) & 14207;
        lIIIllIllIIll[115] = (241 ^ 193) ^ (25 ^ 105);
        lIIIllIllIIll[116] = (-((-25003) & 31659)) & (-17433) & 24447;
        lIIIllIllIIll[117] = ((55 + 131) - 44) + 55;
        lIIIllIllIIll[118] = 131 ^ 193;
        lIIIllIllIIll[119] = (((((89 + 95) - 73) + 41) + (6 ^ 15)) - (93 ^ 10)) + ((143 + 114) - 105) + 0;
        lIIIllIllIIll[120] = (((99 + 183) - 184) + 127) ^ (((76 + 70) - 6) + 2);
        lIIIllIllIIll[121] = ((169 + 154) - 301) + 178;
        lIIIllIllIIll[122] = (89 ^ 53) ^ (108 ^ 69);
        lIIIllIllIIll[123] = (-((-5401) & 8059)) & (-21525) & 24567;
        lIIIllIllIIll[124] = (((118 + 197) - 241) + 136) ^ (((31 + 97) - 32) + 52);
        lIIIllIllIIll[125] = (-4225) & 4541;
        lIIIllIllIIll[126] = (((196 ^ 181) + (44 ^ 103)) - (125 ^ 72)) + (142 ^ 148);
        lIIIllIllIIll[127] = 196 ^ 140;
        lIIIllIllIIll[128] = (((24 ^ 30) + (((75 + 37) - 30) + 45)) - (251 ^ 143)) + ((7 + 69) - 60) + 129;
        lIIIllIllIIll[129] = (((118 + 104) - 26) + 37) ^ (((139 + 138) - 136) + 19);
        lIIIllIllIIll[130] = ((58 + 2) - (-151)) + 1;
        lIIIllIllIIll[131] = (3 ^ 89) ^ (183 ^ 167);
        lIIIllIllIIll[132] = (-26659) & 27638;
        lIIIllIllIIll[133] = 87 ^ 28;
        lIIIllIllIIll[134] = (-((-1233) & 32467)) & (-18) & 31743;
        lIIIllIllIIll[135] = (198 ^ 154) ^ (166 ^ 183);
        lIIIllIllIIll[136] = (119 ^ 60) ^ (58 ^ 63);
        lIIIllIllIIll[137] = (((73 + 70) - 2) + 111) ^ (((52 + 110) - 151) + 168);
        lIIIllIllIIll[138] = (-26629) & 26895;
    }

    static {
        lIlIIIllIIIlIII();
        lIlIIIllIIIIlll();
        QUEST_BLACK_KNIGHTS_FORTRESS = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[0]], lIIIllIllIIll[0], lIIIllIllIIll[1]);
        QUEST_COOKS_ASSISTANT = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[2]], lIIIllIllIIll[2], lIIIllIllIIll[3]);
        QUEST_DORICS_QUEST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[4]], lIIIllIllIIll[4], lIIIllIllIIll[5]);
        QUEST_DRAGON_SLAYER_I = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[6]], lIIIllIllIIll[6], lIIIllIllIIll[7]);
        QUEST_ERNEST_THE_CHICKEN = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[8]], lIIIllIllIIll[8], lIIIllIllIIll[9]);
        QUEST_IMP_CATCHER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[10]], lIIIllIllIIll[10], lIIIllIllIIll[11]);
        QUEST_THE_KNIGHTS_SWORD = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[12]], lIIIllIllIIll[12], lIIIllIllIIll[13]);
        QUEST_PIRATES_TREASURE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[14]], lIIIllIllIIll[14], lIIIllIllIIll[15]);
        QUEST_PRINCE_ALI_RESCUE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[16]], lIIIllIllIIll[16], lIIIllIllIIll[17]);
        QUEST_THE_RESTLESS_GHOST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[18]], lIIIllIllIIll[18], lIIIllIllIIll[19]);
        QUEST_ROMEO_AND_JULIET = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[20]], lIIIllIllIIll[20], lIIIllIllIIll[21]);
        QUEST_RUNE_MYSTERIES = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[22]], lIIIllIllIIll[22], lIIIllIllIIll[23]);
        QUEST_SHEEP_SHEARER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[24]], lIIIllIllIIll[24], lIIIllIllIIll[25]);
        QUEST_SHIELD_OF_ARRAV = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[26]], lIIIllIllIIll[26], lIIIllIllIIll[27]);
        QUEST_SHIELD_OF_ARRAV_STATE_146 = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[28]], lIIIllIllIIll[28], lIIIllIllIIll[29]);
        QUEST_VAMPYRE_SLAYER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[30]], lIIIllIllIIll[30], lIIIllIllIIll[31]);
        QUEST_WITCHS_POTION = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[32]], lIIIllIllIIll[32], lIIIllIllIIll[33]);
        QUEST_BIG_CHOMPY_BIRD_HUNTING = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[34]], lIIIllIllIIll[34], lIIIllIllIIll[35]);
        QUEST_BIOHAZARD = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[36]], lIIIllIllIIll[36], lIIIllIllIIll[37]);
        QUEST_CABIN_FEVER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[38]], lIIIllIllIIll[38], lIIIllIllIIll[39]);
        QUEST_CLOCK_TOWER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[40]], lIIIllIllIIll[40], lIIIllIllIIll[20]);
        QUEST_CREATURE_OF_FENKENSTRAIN = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[41]], lIIIllIllIIll[41], lIIIllIllIIll[42]);
        QUEST_DEATH_PLATEAU = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[43]], lIIIllIllIIll[43], lIIIllIllIIll[44]);
        QUEST_THE_DIG_SITE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[45]], lIIIllIllIIll[45], lIIIllIllIIll[46]);
        QUEST_DRUIDIC_RITUAL = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[47]], lIIIllIllIIll[47], lIIIllIllIIll[48]);
        QUEST_DWARF_CANNON = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[49]], lIIIllIllIIll[49], lIIIllIllIIll[0]);
        QUEST_EADGARS_RUSE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[50]], lIIIllIllIIll[50], lIIIllIllIIll[51]);
        QUEST_ELEMENTAL_WORKSHOP_I = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[52]], lIIIllIllIIll[52], lIIIllIllIIll[53]);
        QUEST_FAMILY_CREST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[54]], lIIIllIllIIll[54], lIIIllIllIIll[55]);
        QUEST_FIGHT_ARENA = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[3]], lIIIllIllIIll[3], lIIIllIllIIll[34]);
        QUEST_FISHING_CONTEST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[56]], lIIIllIllIIll[56], lIIIllIllIIll[22]);
        QUEST_THE_FREMENNIK_TRIALS = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[5]], lIIIllIllIIll[5], lIIIllIllIIll[57]);
        QUEST_WATERFALL_QUEST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[9]], lIIIllIllIIll[9], lIIIllIllIIll[58]);
        QUEST_GERTRUDES_CAT = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[59]], lIIIllIllIIll[59], lIIIllIllIIll[60]);
        QUEST_THE_GRAND_TREE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[61]], lIIIllIllIIll[61], lIIIllIllIIll[62]);
        QUEST_HAUNTED_MINE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[63]], lIIIllIllIIll[63], lIIIllIllIIll[64]);
        QUEST_HAZEEL_CULT = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[65]], lIIIllIllIIll[65], lIIIllIllIIll[66]);
        QUEST_HEROES_QUEST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[67]], lIIIllIllIIll[67], lIIIllIllIIll[68]);
        QUEST_HOLY_GRAIL = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[69]], lIIIllIllIIll[69], lIIIllIllIIll[10]);
        QUEST_IN_SEARCH_OF_THE_MYREQUE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[70]], lIIIllIllIIll[70], lIIIllIllIIll[71]);
        QUEST_JUNGLE_POTION = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[72]], lIIIllIllIIll[72], lIIIllIllIIll[73]);
        QUEST_LEGENDS_QUEST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[74]], lIIIllIllIIll[74], lIIIllIllIIll[75]);
        QUEST_LOST_CITY = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[76]], lIIIllIllIIll[76], lIIIllIllIIll[77]);
        QUEST_MERLINS_CRYSTAL = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[78]], lIIIllIllIIll[78], lIIIllIllIIll[28]);
        QUEST_MONKEY_MADNESS_I = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[79]], lIIIllIllIIll[79], lIIIllIllIIll[80]);
        QUEST_MONKS_FRIEND = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[81]], lIIIllIllIIll[81], lIIIllIllIIll[56]);
        QUEST_MOURNINGS_END_PART_I = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[82]], lIIIllIllIIll[82], lIIIllIllIIll[83]);
        QUEST_MURDER_MYSTERY = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[84]], lIIIllIllIIll[84], lIIIllIllIIll[85]);
        QUEST_NATURE_SPIRIT = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[86]], lIIIllIllIIll[86], lIIIllIllIIll[87]);
        QUEST_OBSERVATORY_QUEST = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[88]], lIIIllIllIIll[88], lIIIllIllIIll[89]);
        QUEST_ONE_SMALL_FAVOUR = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[90]], lIIIllIllIIll[90], lIIIllIllIIll[91]);
        QUEST_PLAGUE_CITY = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[92]], lIIIllIllIIll[92], lIIIllIllIIll[93]);
        QUEST_PRIEST_IN_PERIL = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[94]], lIIIllIllIIll[94], lIIIllIllIIll[95]);
        QUEST_RAG_AND_BONE_MAN_I = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[96]], lIIIllIllIIll[96], lIIIllIllIIll[97]);
        QUEST_REGICIDE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[98]], lIIIllIllIIll[98], lIIIllIllIIll[99]);
        QUEST_ROVING_ELVES = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[100]], lIIIllIllIIll[100], lIIIllIllIIll[101]);
        QUEST_RUM_DEAL = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[102]], lIIIllIllIIll[102], lIIIllIllIIll[103]);
        QUEST_SCORPION_CATCHER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[104]], lIIIllIllIIll[104], lIIIllIllIIll[105]);
        QUEST_SEA_SLUG = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[106]], lIIIllIllIIll[106], lIIIllIllIIll[107]);
        QUEST_SHADES_OF_MORTTON = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[108]], lIIIllIllIIll[108], lIIIllIllIIll[109]);
        QUEST_SHEEP_HERDER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[110]], lIIIllIllIIll[110], lIIIllIllIIll[110]);
        QUEST_SHILO_VILLAGE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[111]], lIIIllIllIIll[111], lIIIllIllIIll[112]);
        QUEST_TAI_BWO_WANNAI_TRIO = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[113]], lIIIllIllIIll[113], lIIIllIllIIll[114]);
        QUEST_TEMPLE_OF_IKOV = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[23]], lIIIllIllIIll[23], lIIIllIllIIll[50]);
        QUEST_THRONE_OF_MISCELLANIA = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[115]], lIIIllIllIIll[115], lIIIllIllIIll[116]);
        QUEST_THE_TOURIST_TRAP = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[58]], lIIIllIllIIll[58], lIIIllIllIIll[117]);
        QUEST_WITCHS_HOUSE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[118]], lIIIllIllIIll[118], lIIIllIllIIll[119]);
        QUEST_TREE_GNOME_VILLAGE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[33]], lIIIllIllIIll[33], lIIIllIllIIll[120]);
        QUEST_TRIBAL_TOTEM = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[37]], lIIIllIllIIll[37], lIIIllIllIIll[121]);
        QUEST_TROLL_ROMANCE = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[122]], lIIIllIllIIll[122], lIIIllIllIIll[123]);
        QUEST_TROLL_STRONGHOLD = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[124]], lIIIllIllIIll[124], lIIIllIllIIll[125]);
        QUEST_UNDERGROUND_PASS = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[15]], lIIIllIllIIll[15], lIIIllIllIIll[126]);
        QUEST_UNDERGROUND_PASS_STATE_162 = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[127]], lIIIllIllIIll[127], lIIIllIllIIll[128]);
        QUEST_WATCHTOWER = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[129]], lIIIllIllIIll[129], lIIIllIllIIll[130]);
        QUEST_THE_GREAT_BRAIN_ROBBERY = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[131]], lIIIllIllIIll[131], lIIIllIllIIll[132]);
        QUEST_RAG_AND_BONE_MAN_II = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[133]], lIIIllIllIIll[133], lIIIllIllIIll[97]);
        QUEST_ENTER_THE_ABYSS = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[105]], lIIIllIllIIll[105], lIIIllIllIIll[134]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[135]], lIIIllIllIIll[135], lIIIllIllIIll[135]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76 = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[136]], lIIIllIllIIll[136], lIIIllIllIIll[105]);
        QUEST_THE_MAGE_ARENA = new EnumC0000a(lIIIllIllIIlI[lIIIllIllIIll[137]], lIIIllIllIIll[137], lIIIllIllIIll[138]);
        EnumC0000a[] enumC0000aArr = new EnumC0000a[lIIIllIllIIll[48]];
        enumC0000aArr[lIIIllIllIIll[0]] = QUEST_BLACK_KNIGHTS_FORTRESS;
        enumC0000aArr[lIIIllIllIIll[2]] = QUEST_COOKS_ASSISTANT;
        enumC0000aArr[lIIIllIllIIll[4]] = QUEST_DORICS_QUEST;
        enumC0000aArr[lIIIllIllIIll[6]] = QUEST_DRAGON_SLAYER_I;
        enumC0000aArr[lIIIllIllIIll[8]] = QUEST_ERNEST_THE_CHICKEN;
        enumC0000aArr[lIIIllIllIIll[10]] = QUEST_IMP_CATCHER;
        enumC0000aArr[lIIIllIllIIll[12]] = QUEST_THE_KNIGHTS_SWORD;
        enumC0000aArr[lIIIllIllIIll[14]] = QUEST_PIRATES_TREASURE;
        enumC0000aArr[lIIIllIllIIll[16]] = QUEST_PRINCE_ALI_RESCUE;
        enumC0000aArr[lIIIllIllIIll[18]] = QUEST_THE_RESTLESS_GHOST;
        enumC0000aArr[lIIIllIllIIll[20]] = QUEST_ROMEO_AND_JULIET;
        enumC0000aArr[lIIIllIllIIll[22]] = QUEST_RUNE_MYSTERIES;
        enumC0000aArr[lIIIllIllIIll[24]] = QUEST_SHEEP_SHEARER;
        enumC0000aArr[lIIIllIllIIll[26]] = QUEST_SHIELD_OF_ARRAV;
        enumC0000aArr[lIIIllIllIIll[28]] = QUEST_SHIELD_OF_ARRAV_STATE_146;
        enumC0000aArr[lIIIllIllIIll[30]] = QUEST_VAMPYRE_SLAYER;
        enumC0000aArr[lIIIllIllIIll[32]] = QUEST_WITCHS_POTION;
        enumC0000aArr[lIIIllIllIIll[34]] = QUEST_BIG_CHOMPY_BIRD_HUNTING;
        enumC0000aArr[lIIIllIllIIll[36]] = QUEST_BIOHAZARD;
        enumC0000aArr[lIIIllIllIIll[38]] = QUEST_CABIN_FEVER;
        enumC0000aArr[lIIIllIllIIll[40]] = QUEST_CLOCK_TOWER;
        enumC0000aArr[lIIIllIllIIll[41]] = QUEST_CREATURE_OF_FENKENSTRAIN;
        enumC0000aArr[lIIIllIllIIll[43]] = QUEST_DEATH_PLATEAU;
        enumC0000aArr[lIIIllIllIIll[45]] = QUEST_THE_DIG_SITE;
        enumC0000aArr[lIIIllIllIIll[47]] = QUEST_DRUIDIC_RITUAL;
        enumC0000aArr[lIIIllIllIIll[49]] = QUEST_DWARF_CANNON;
        enumC0000aArr[lIIIllIllIIll[50]] = QUEST_EADGARS_RUSE;
        enumC0000aArr[lIIIllIllIIll[52]] = QUEST_ELEMENTAL_WORKSHOP_I;
        enumC0000aArr[lIIIllIllIIll[54]] = QUEST_FAMILY_CREST;
        enumC0000aArr[lIIIllIllIIll[3]] = QUEST_FIGHT_ARENA;
        enumC0000aArr[lIIIllIllIIll[56]] = QUEST_FISHING_CONTEST;
        enumC0000aArr[lIIIllIllIIll[5]] = QUEST_THE_FREMENNIK_TRIALS;
        enumC0000aArr[lIIIllIllIIll[9]] = QUEST_WATERFALL_QUEST;
        enumC0000aArr[lIIIllIllIIll[59]] = QUEST_GERTRUDES_CAT;
        enumC0000aArr[lIIIllIllIIll[61]] = QUEST_THE_GRAND_TREE;
        enumC0000aArr[lIIIllIllIIll[63]] = QUEST_HAUNTED_MINE;
        enumC0000aArr[lIIIllIllIIll[65]] = QUEST_HAZEEL_CULT;
        enumC0000aArr[lIIIllIllIIll[67]] = QUEST_HEROES_QUEST;
        enumC0000aArr[lIIIllIllIIll[69]] = QUEST_HOLY_GRAIL;
        enumC0000aArr[lIIIllIllIIll[70]] = QUEST_IN_SEARCH_OF_THE_MYREQUE;
        enumC0000aArr[lIIIllIllIIll[72]] = QUEST_JUNGLE_POTION;
        enumC0000aArr[lIIIllIllIIll[74]] = QUEST_LEGENDS_QUEST;
        enumC0000aArr[lIIIllIllIIll[76]] = QUEST_LOST_CITY;
        enumC0000aArr[lIIIllIllIIll[78]] = QUEST_MERLINS_CRYSTAL;
        enumC0000aArr[lIIIllIllIIll[79]] = QUEST_MONKEY_MADNESS_I;
        enumC0000aArr[lIIIllIllIIll[81]] = QUEST_MONKS_FRIEND;
        enumC0000aArr[lIIIllIllIIll[82]] = QUEST_MOURNINGS_END_PART_I;
        enumC0000aArr[lIIIllIllIIll[84]] = QUEST_MURDER_MYSTERY;
        enumC0000aArr[lIIIllIllIIll[86]] = QUEST_NATURE_SPIRIT;
        enumC0000aArr[lIIIllIllIIll[88]] = QUEST_OBSERVATORY_QUEST;
        enumC0000aArr[lIIIllIllIIll[90]] = QUEST_ONE_SMALL_FAVOUR;
        enumC0000aArr[lIIIllIllIIll[92]] = QUEST_PLAGUE_CITY;
        enumC0000aArr[lIIIllIllIIll[94]] = QUEST_PRIEST_IN_PERIL;
        enumC0000aArr[lIIIllIllIIll[96]] = QUEST_RAG_AND_BONE_MAN_I;
        enumC0000aArr[lIIIllIllIIll[98]] = QUEST_REGICIDE;
        enumC0000aArr[lIIIllIllIIll[100]] = QUEST_ROVING_ELVES;
        enumC0000aArr[lIIIllIllIIll[102]] = QUEST_RUM_DEAL;
        enumC0000aArr[lIIIllIllIIll[104]] = QUEST_SCORPION_CATCHER;
        enumC0000aArr[lIIIllIllIIll[106]] = QUEST_SEA_SLUG;
        enumC0000aArr[lIIIllIllIIll[108]] = QUEST_SHADES_OF_MORTTON;
        enumC0000aArr[lIIIllIllIIll[110]] = QUEST_SHEEP_HERDER;
        enumC0000aArr[lIIIllIllIIll[111]] = QUEST_SHILO_VILLAGE;
        enumC0000aArr[lIIIllIllIIll[113]] = QUEST_TAI_BWO_WANNAI_TRIO;
        enumC0000aArr[lIIIllIllIIll[23]] = QUEST_TEMPLE_OF_IKOV;
        enumC0000aArr[lIIIllIllIIll[115]] = QUEST_THRONE_OF_MISCELLANIA;
        enumC0000aArr[lIIIllIllIIll[58]] = QUEST_THE_TOURIST_TRAP;
        enumC0000aArr[lIIIllIllIIll[118]] = QUEST_WITCHS_HOUSE;
        enumC0000aArr[lIIIllIllIIll[33]] = QUEST_TREE_GNOME_VILLAGE;
        enumC0000aArr[lIIIllIllIIll[37]] = QUEST_TRIBAL_TOTEM;
        enumC0000aArr[lIIIllIllIIll[122]] = QUEST_TROLL_ROMANCE;
        enumC0000aArr[lIIIllIllIIll[124]] = QUEST_TROLL_STRONGHOLD;
        enumC0000aArr[lIIIllIllIIll[15]] = QUEST_UNDERGROUND_PASS;
        enumC0000aArr[lIIIllIllIIll[127]] = QUEST_UNDERGROUND_PASS_STATE_162;
        enumC0000aArr[lIIIllIllIIll[129]] = QUEST_WATCHTOWER;
        enumC0000aArr[lIIIllIllIIll[131]] = QUEST_THE_GREAT_BRAIN_ROBBERY;
        enumC0000aArr[lIIIllIllIIll[133]] = QUEST_RAG_AND_BONE_MAN_II;
        enumC0000aArr[lIIIllIllIIll[105]] = QUEST_ENTER_THE_ABYSS;
        enumC0000aArr[lIIIllIllIIll[135]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL;
        enumC0000aArr[lIIIllIllIIll[136]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
        enumC0000aArr[lIIIllIllIIll[137]] = QUEST_THE_MAGE_ARENA;
        $VALUES = enumC0000aArr;
    }

    private static boolean lIlIIIllIIIlIIl(int i, int i2) {
        return i < i2;
    }

    private static String lIlIIIllIIIIlII(String lllllllllllllllIIIIlIIIIIlllIIll, String lllllllllllllllIIIIlIIIIIlllIIlI) {
        try {
            SecretKeySpec secretKeySpec = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(lllllllllllllllIIIIlIIIIIlllIIlI.getBytes(StandardCharsets.UTF_8)), lIIIllIllIIll[16]), "DES");
            Cipher cipher = Cipher.getInstance("DES");
            cipher.init(lIIIllIllIIll[4], secretKeySpec);
            return new String(cipher.doFinal(Base64.getDecoder().decode(lllllllllllllllIIIIlIIIIIlllIIll.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        } catch (Exception lllllllllllllllIIIIlIIIIIlllIlII) {
            lllllllllllllllIIIIlIIIIIlllIlII.printStackTrace();
            return null;
        }
    }

    public static EnumC0000a valueOf(String str) {
        return (EnumC0000a) Enum.valueOf(EnumC0000a.class, str);
    }

    private EnumC0000a(String str, int i, int i2) {
        this.id = i2;
    }

    private static void lIlIIIllIIIIlll() {
        lIIIllIllIIlI = new String[lIIIllIllIIll[48]];
        lIIIllIllIIlI[lIIIllIllIIll[0]] = lIlIIIllIIIIlII("HISomdqm/1f+g/nYxHq+MW4Re5axLFdW1iCbsXdlQo4=", "pdmMT");
        lIIIllIllIIlI[lIIIllIllIIll[2]] = lIlIIIllIIIIlIl("MjLKShJO0mfz7GfqAIO73yXeA7O9ZnM6", "QuJiV");
        lIIIllIllIIlI[lIIIllIllIIll[4]] = lIlIIIllIIIIllI("Fi8jBRwYPikEAQQpOQcdAiky", "GzfVH");
        lIIIllIllIIlI[lIIIllIllIIll[6]] = lIlIIIllIIIIlII("BPIcvOj9Nv5De5/2MmS1I26BUnJ9hAuX", "NuYpw");
        lIIIllIllIIlI[lIIIllIllIIll[8]] = lIlIIIllIIIIlII("5wu9pKFGrijLZg2e+xj+0FeSym6eN+wphRLuy6qhCrc=", "qeSSN");
        lIIIllIllIIlI[lIIIllIllIIll[10]] = lIlIIIllIIIIllI("GyEMMQMVPQQyCAk1HSEfDyY=", "JtIbW");
        lIIIllIllIIlI[lIIIllIllIIll[12]] = lIlIIIllIIIIlII("q7z9YO+nBMFObdJXOLKr2XPaDPT2P1+2", "zkEBJ");
        lIIIllIllIIlI[lIIIllIllIIll[14]] = lIlIIIllIIIIlIl("JJe9wmPH+dF76ZfjdhNL6d9Pgzm5tyF4", "vgOpe");
        lIIIllIllIIlI[lIIIllIllIIll[16]] = lIlIIIllIIIIllI("Pz4UHT8xOwMHJS0uDg8nJzQDCzgtPhQ=", "nkQNk");
        lIIIllIllIIlI[lIIIllIllIIll[18]] = lIlIIIllIIIIllI("AT0DKhoPPA48EQItFS0CFTsVJgkYJxUt", "PhFyN");
        lIIIllIllIIlI[lIIIllIllIIll[20]] = lIlIIIllIIIIlII("EMfQ3X3vYXghWN9RspoI3UMsoLSuZZsu", "doqpL");
        lIIIllIllIIlI[lIIIllIllIIll[22]] = lIlIIIllIIIIllI("BSEmGAQLJjYFFQs5OhgEESYqDgM=", "TtcKP");
        lIIIllIllIIlI[lIIIllIllIIll[24]] = lIlIIIllIIIIlIl("RfV8FYSPjoDFNOWWy+pISINFZIUBwXzy", "knVFG");
        lIIIllIllIIlI[lIIIllIllIIll[26]] = lIlIIIllIIIIllI("Nx0yPzc5Gz8lJioMKCMlOQklPiIw", "fHwlc");
        lIIIllIllIIlI[lIIIllIllIIll[28]] = lIlIIIllIIIIllI("NhMiBiA4FS8cMSsCOBoyOAc1BzUxGTQBNTMDOGRAUQ==", "gFgUt");
        lIIIllIllIIlI[lIIIllIllIIll[30]] = lIlIIIllIIIIlII("efqmNIa0aZdBS7eAUXsY9fssURWvuIbC", "OJHwF");
        lIIIllIllIIlI[lIIIllIllIIll[32]] = lIlIIIllIIIIlII("IEIWpxnyAWARZz/2MFpVW8Yj7lnuH0EQ", "yIQfK");
        lIIIllIllIIlI[lIIIllIllIIll[34]] = lIlIIIllIIIIlIl("1C0aA+8neYm/8ty0FFPlp0VcQbfGLrInLjLQMRRCLTk=", "wlBIj");
        lIIIllIllIIlI[lIIIllIllIIll[36]] = lIlIIIllIIIIllI("Iz8xGiwtKD0GMDMwNRs8", "rjtIx");
        lIIIllIllIIlI[lIIIllIllIIll[38]] = lIlIIIllIIIIlII("wkAj3ANbxrVRU5E6tj6lEzNTWMXVTC6b", "wixtX");
        lIIIllIllIIlI[lIIIllIllIIll[40]] = lIlIIIllIIIIlIl("Zy4+j77o46dw9nYjVx+sz4qcAPlDdUEx", "MQTLo");
        lIIIllIllIIlI[lIIIllIllIIll[41]] = lIlIIIllIIIIlII("9XQkahbDMeZIb5Xlzw+JWCtDqst1yAFbakd/+vWZeG0=", "uLSbe");
        lIIIllIllIIlI[lIIIllIllIIll[43]] = lIlIIIllIIIIllI("HCIMMRgSMwwjGAUoGS4NGTIINw==", "MwIbL");
        lIIIllIllIIlI[lIIIllIllIIll[45]] = lIlIIIllIIIIlII("8var13aHNUiktePzQJvHcGV/iF9pnSCM", "nmBZH");
        lIIIllIllIIlI[lIIIllIllIIll[47]] = lIlIIIllIIIIlII("F1+RHEQjy3WBZ0HXSxe6c+18/n00vawH", "wCEky");
        lIIIllIllIIlI[lIIIllIllIIll[49]] = lIlIIIllIIIIllI("AjkuGCQMKDwKIhUzKAo+HSMl", "SlkKp");
        lIIIllIllIIlI[lIIIllIllIIll[50]] = lIlIIIllIIIIllI("JgA1HRIoEDEKATYHIxEUIgY1", "wUpNF");
        lIIIllIllIIlI[lIIIllIllIIll[52]] = lIlIIIllIIIIllI("PzkCMDUxKQsmLCsiEyItMTsIMSo9JAgzPic=", "nlGca");
        lIIIllIllIIlI[lIIIllIllIIll[54]] = lIlIIIllIIIIlIl("JhxOdUmtLJ2zRfhhnUXT1IY67s7s4Jba", "QDMyr");
        lIIIllIllIIlI[lIIIllIllIIll[3]] = lIlIIIllIIIIllI("HD4oOAASLSQsHBk0LDkRAyo=", "MkmkT");
        lIIIllIllIIlI[lIIIllIllIIll[56]] = lIlIIIllIIIIlII("gAyuyLgEBHxroEbPxGXeCL5qDyhVXmqz", "KSiMC");
        lIIIllIllIIlI[lIIIllIllIIll[5]] = lIlIIIllIIIIlII("YpRLTskdi+w5cf/MvlDxEXta//kfaPreciw4tBDbqIo=", "GEPnm");
        lIIIllIllIIlI[lIIIllIllIIll[9]] = lIlIIIllIIIIllI("JSEpOi4rIy09PyYyLSU2KyU5LCkg", "ttliz");
        lIIIllIllIIlI[lIIIllIllIIll[59]] = lIlIIIllIIIIlIl("dI0TjVxPLzm1xrRY5IdSolOT7TxXPTgH", "LXmJw");
        lIIIllIllIIlI[lIIIllIllIIll[61]] = lIlIIIllIIIIllI("OyIcAzg1IxEVMy0lGB4oNSMLFSk=", "jwYPl");
        lIIIllIllIIlI[lIIIllIllIIll[63]] = lIlIIIllIIIIlIl("RhyBmt28KOhLJ3UA0frUZW5tVBfDx7+7", "UrQVZ");
        lIIIllIllIIlI[lIIIllIllIIll[65]] = lIlIIIllIIIIlIl("3nMAFm1BiD2NW1+6KYoE9TEpINfRvY2q", "LrRuG");
        lIIIllIllIIlI[lIIIllIllIIll[67]] = lIlIIIllIIIIlII("WsXRKzt4WLm6VloCekk+FFHRJLBwVQs0", "mLmyt");
        lIIIllIllIIlI[lIIIllIllIIll[69]] = lIlIIIllIIIIllI("BC0oCQQKMCIWCQo/PxsZGQ==", "UxmZP");
        lIIIllIllIIlI[lIIIllIllIIll[70]] = lIlIIIllIIIIlIl("pRVFEPsXO4gTlwmFaw3/6bKWkYHLZ9ublZif1JWWTKE=", "jSvkz");
        lIIIllIllIIlI[lIIIllIllIIll[72]] = lIlIIIllIIIIllI("AhQEGSwMCxQEPx8EHho3BwgOBA==", "SAAJx");
        lIIIllIllIIlI[lIIIllIllIIll[74]] = lIlIIIllIIIIlIl("KfKaYnmQFCA/XCXdmApVLBwIMd2OcVMG", "wKKXW");
        lIIIllIllIIlI[lIIIllIllIIll[76]] = lIlIIIllIIIIlII("tHEsjEHc39xT0edkWKTWXw==", "lBYvy");
        lIIIllIllIIlI[lIIIllIllIIll[78]] = lIlIIIllIIIIlII("m7PalGTOaWiVZIRQunrbFZA4/cDkd8HM", "qUoRq");
        lIIIllIllIIlI[lIIIllIllIIll[79]] = lIlIIIllIIIIlII("S1SSOHNdiq+ZyDBQFXdbobzw1nE2DfMD", "JfjSP");
        lIIIllIllIIlI[lIIIllIllIIll[81]] = lIlIIIllIIIIlII("0hQ0tSHpgLlVbZD+UcEZv1Uqx+urqbrQ", "bpTXQ");
        lIIIllIllIIlI[lIIIllIllIIll[82]] = lIlIIIllIIIIllI("NC8oPwE6NyI5ByszIysGOj8jKAo1Oz84Ciw=", "ezmlU");
        lIIIllIllIIlI[lIIIllIllIIll[84]] = lIlIIIllIIIIllI("BxYQETIJDgAQIhMRCg8/BRcQED8=", "VCUBf");
        lIIIllIllIIlI[lIIIllIllIIll[86]] = lIlIIIllIIIIlII("JLWSubfsWeFDW1EgUX131nV/Zxp8D17r", "IYUBB");
        lIIIllIllIIlI[lIIIllIllIIll[88]] = lIlIIIllIIIIlII("weXyxP34udnJRD6SBo+gA2iOmo70oJQk", "KdiPu");
        lIIIllIllIIlI[lIIIllIllIIll[90]] = lIlIIIllIIIIlII("OkXad7eXMHvZsD7WDD70oGmPe6OrubFd", "nbDul");
        lIIIllIllIIlI[lIIIllIllIIll[92]] = lIlIIIllIIIIlII("wEUMcVzQG1YxeGm8yU4F8o4lQRMBBVmM", "wCFVM");
        lIIIllIllIIlI[lIIIllIllIIll[94]] = lIlIIIllIIIIlII("M86Wi2jjiruhXrFSQCny8D3VypS+ALXu", "JaOZK");
        lIIIllIllIIlI[lIIIllIllIIll[96]] = lIlIIIllIIIIlIl("mW2pP/GPWABuDkOkx/+fDsMW1uyhRyfsa4Ab7xzmWDA=", "YxkMO");
        lIIIllIllIIlI[lIIIllIllIIll[98]] = lIlIIIllIIIIlII("wqSjN66fbi6XIXhFM19IAA==", "zrjsS");
        lIIIllIllIIlI[lIIIllIllIIll[100]] = lIlIIIllIIIIllI("GA8qJwUWCCAiGAcdMDEdHx88", "IZotQ");
        lIIIllIllIIlI[lIIIllIllIIll[102]] = lIlIIIllIIIIlIl("4UW/1v8OMeCFySGo7ZIF+Q==", "NARpf");
        lIIIllIllIIlI[lIIIllIllIIll[104]] = lIlIIIllIIIIlII("CFJWyzkGkb17rheuSx2KmxAGg+oijQVR", "ZmUZk");
        lIIIllIllIIlI[lIIIllIllIIll[106]] = lIlIIIllIIIIlIl("kot6LUHXGj1kyiphoBzY8g==", "TPRRX");
        lIIIllIllIIlI[lIIIllIllIIll[108]] = lIlIIIllIIIIlIl("e9LCzhodkmyPtwxUTbgdDQ8K4bb6+3mx", "WmpVC");
        lIIIllIllIIlI[lIIIllIllIIll[110]] = lIlIIIllIIIIllI("OSArFwc3JiYBFjgqJgEBLDA8", "hunDS");
        lIIIllIllIIlI[lIIIllIllIIll[111]] = lIlIIIllIIIIlIl("rBRo9ukAjvDnAewQtdYYI09nQZw3MDoS", "bjIRO");
        lIIIllIllIIlI[lIIIllIllIIll[113]] = lIlIIIllIIIIllI("GT0tAQQXPCkbDwo/Jw0HCSYmExkXPDobHw==", "HhhRP");
        lIIIllIllIIlI[lIIIllIllIIll[23]] = lIlIIIllIIIIlII("YNq3ZoHfjFXCzp3Jg0qAPkPGWGq39CEP", "QqsBa");
        lIIIllIllIIlI[lIIIllIllIIll[115]] = lIlIIIllIIIIlII("PLm0n/twuTpJUtJATJCZtAs2FiPY8oh68JalicgVrpY=", "KsFQe");
        lIIIllIllIIlI[lIIIllIllIIll[58]] = lIlIIIllIIIIlIl("wP+XGsksORBOStJdIwK+wo6sKyIz2Imu", "KLBvo");
        lIIIllIllIIlI[lIIIllIllIIll[118]] = lIlIIIllIIIIllI("JBAfHQQqEhMaEz0WBQYfIBYf", "uEZNP");
        lIIIllIllIIlI[lIIIllIllIIll[33]] = lIlIIIllIIIIlIl("nEnneIaXZqoYHETW8HwgsVlH3CF74amw3bAcZ0/tFBQ=", "rWlHr");
        lIIIllIllIIlI[lIIIllIllIIll[37]] = lIlIIIllIIIIlIl("QAWlJkoXfmxW25rX1jGoGBztXKIfIV2u", "IvWXO");
        lIIIllIllIIlI[lIIIllIllIIll[122]] = lIlIIIllIIIIlIl("Q0md0FSoAg4iTVmDHU/eWYlzVpdNCQUS", "uFpDf");
        lIIIllIllIIlI[lIIIllIllIIll[124]] = lIlIIIllIIIIllI("BSUCOxELJBUnCRgvFDwXGz4AIAoYNA==", "TpGhE");
        lIIIllIllIIlI[lIIIllIllIIll[15]] = lIlIIIllIIIIlII("Etr2EMI4kJqIqY5YdruEZY1RbBkC7oNh", "zwgrT");
        lIIIllIllIIlI[lIIIllIllIIll[127]] = lIlIIIllIIIIlIl("PNP8bhbvAC+ACqf8/EBTzsZxGuzczoALzDwtxGYufDkZ0dL665dmEw==", "uUuIb");
        lIIIllIllIIlI[lIIIllIllIIll[129]] = lIlIIIllIIIIlII("t5EEc1uCXTl1cVGjaa+9wdCxQblPwtSd", "yImHx");
        lIIIllIllIIlI[lIIIllIllIIll[131]] = lIlIIIllIIIIlIl("4vONN4rBnBn0kgsWyHhvBlOp5Pbl8msVPPXLnjLvRmc=", "jfPjv");
        lIIIllIllIIlI[lIIIllIllIIll[133]] = lIlIIIllIIIIlII("UJ+we7kOCYoZ4LcJNG8361ZhD6e/KFKmPwVD3X3KScQ=", "CGLoi");
        lIIIllIllIIlI[lIIIllIllIIll[105]] = lIlIIIllIIIIllI("HQEuBSQTESUCNR4LPx41ExUpDyMf", "LTkVp");
        lIIIllIllIIlI[lIIIllIllIIll[135]] = lIlIIIllIIIIlII("tKRTagBqlUAAIWsB2cr+04KiyucI4VwXMawekHJulQo=", "mBsoE");
        lIIIllIllIIlI[lIIIllIllIIll[136]] = lIlIIIllIIIIlIl("OoKOBxxPuqxTS81k2PiTxAZLgmhmneboS6cVpN89gRaqf1NutMkgM6K6bQWShap0", "eUGCM");
        lIIIllIllIIlI[lIIIllIllIIll[137]] = lIlIIIllIIIIlII("Dwe95K8hrrMUgWb5FxBdGcTlwgCdafi1", "HTdpB");
    }

    private static String lIlIIIllIIIIllI(String lllllllllllllllIIIIlIIIIlIIIlIII, String lllllllllllllllIIIIlIIIIlIIIIlll) {
        String lllllllllllllllIIIIlIIIIlIIIlIII2 = new String(Base64.getDecoder().decode(lllllllllllllllIIIIlIIIIlIIIlIII.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder lllllllllllllllIIIIlIIIIlIIIIllI = new StringBuilder();
        char[] charArray = lllllllllllllllIIIIlIIIIlIIIIlll.toCharArray();
        int lllllllllllllllIIIIlIIIIlIIIIlII = lIIIllIllIIll[0];
        char[] charArray2 = lllllllllllllllIIIIlIIIIlIIIlIII2.toCharArray();
        int length = charArray2.length;
        int i = lIIIllIllIIll[0];
        while (lIlIIIllIIIlIIl(i, length)) {
            char lllllllllllllllIIIIlIIIIlIIIlIIl = charArray2[i];
            lllllllllllllllIIIIlIIIIlIIIIllI.append((char) (lllllllllllllllIIIIlIIIIlIIIlIIl ^ charArray[lllllllllllllllIIIIlIIIIlIIIIlII % charArray.length]));
            "".length();
            lllllllllllllllIIIIlIIIIlIIIIlII++;
            i++;
            "".length();
            if ((((((160 + 104) - 236) + 177) ^ (((30 + 74) - 2) + 30)) & ((" ".length() ^ (105 ^ 33)) ^ (-" ".length()))) != (((245 ^ 139) ^ (4 ^ 71)) & (((138 ^ 140) ^ (165 ^ 158)) ^ (-" ".length())))) {
                return null;
            }
        }
        return String.valueOf(lllllllllllllllIIIIlIIIIlIIIIllI);
    }

    public int c() {
        return this.id;
    }

    private static String lIlIIIllIIIIlIl(String lllllllllllllllIIIIlIIIIlIIllIII, String lllllllllllllllIIIIlIIIIlIIlIlll) {
        try {
            SecretKeySpec lllllllllllllllIIIIlIIIIlIIllIll = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(lllllllllllllllIIIIlIIIIlIIlIlll.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher lllllllllllllllIIIIlIIIIlIIllIlI = Cipher.getInstance("Blowfish");
            lllllllllllllllIIIIlIIIIlIIllIlI.init(lIIIllIllIIll[4], lllllllllllllllIIIIlIIIIlIIllIll);
            return new String(lllllllllllllllIIIIlIIIIlIIllIlI.doFinal(Base64.getDecoder().decode(lllllllllllllllIIIIlIIIIlIIllIII.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        } catch (Exception lllllllllllllllIIIIlIIIIlIIllIIl) {
            lllllllllllllllIIIIlIIIIlIIllIIl.printStackTrace();
            return null;
        }
    }

    public static EnumC0000a[] values() {
        return (EnumC0000a[]) $VALUES.clone();
    }
}
