/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap$Builder
 *  net.runelite.api.widgets.Widget
 *  net.runelite.api.widgets.WidgetInfo
 *  net.unethicalite.api.widgets.Widgets
 */
package -.a.c.u.c.l.o.d.-.r.e.o.n.b.l.e.i.w.k.b.-.r.i.s.r;

import com.google.common.collect.ImmutableMap;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import java.util.Map;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import net.runelite.api.widgets.Widget;
import net.runelite.api.widgets.WidgetInfo;
import net.unethicalite.api.widgets.Widgets;

public final class HerbType
extends Enum<h> {
    public static final /* synthetic */ /* enum */ h KALPHITE_3;
    private static final /* synthetic */ Map<String, String> MATCHES;
    public static final /* synthetic */ /* enum */ h CAMEL_1;
    public static final /* synthetic */ /* enum */ h WYVERN_3;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_6;
    public static final /* synthetic */ /* enum */ h LEECH_1;
    public static final /* synthetic */ /* enum */ h DRAGON_4;
    public static final /* synthetic */ /* enum */ h LIZARD_1;
    public static final /* synthetic */ /* enum */ h SLUG_6;
    public static final /* synthetic */ /* enum */ h DRAGON_6;
    public static final /* synthetic */ /* enum */ h CAMEL_3;
    public static final /* synthetic */ /* enum */ h MONKEY_6;
    public static final /* synthetic */ /* enum */ h MONKEY_1;
    public static final /* synthetic */ /* enum */ h SLUG_1;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_2;
    public static final /* synthetic */ /* enum */ h KALPHITE_4;
    public static final /* synthetic */ /* enum */ h LEECH_3;
    public static final /* synthetic */ /* enum */ h LEECH_6;
    public static final /* synthetic */ /* enum */ h SLUG_5;
    public static final /* synthetic */ /* enum */ h CAMEL_2;
    public static final /* synthetic */ /* enum */ h CAMEL_4;
    public static final /* synthetic */ /* enum */ h SNAIL_3;
    public static final /* synthetic */ /* enum */ h PENGUIN_1;
    public static final /* synthetic */ /* enum */ h LIZARD_4;
    public static final /* synthetic */ /* enum */ h TORTOISE_6;
    public static final /* synthetic */ /* enum */ h TORTOISE_5;
    public static final /* synthetic */ /* enum */ h MOLE_3;
    public static final /* synthetic */ /* enum */ h MONKEY_5;
    public static final /* synthetic */ /* enum */ h LIZARD_3;
    public static final /* synthetic */ /* enum */ h SNAKE_3;
    public static final /* synthetic */ /* enum */ h PENGUIN_5;
    public static final /* synthetic */ /* enum */ h MONKEY_4;
    public static final /* synthetic */ /* enum */ h MOLE_4;
    private final /* synthetic */ String question;
    public static final /* synthetic */ /* enum */ h CAMEL_5;
    public static final /* synthetic */ /* enum */ h MONKEY_2;
    public static final /* synthetic */ /* enum */ h KALPHITE_6;
    public static final /* synthetic */ /* enum */ h DRAGON_2;
    private static /* synthetic */ String[] lllllIII;
    public static final /* synthetic */ /* enum */ h SNAIL_5;
    public static final /* synthetic */ /* enum */ h SNAIL_1;
    public static final /* synthetic */ /* enum */ h LIZARD_6;
    public static final /* synthetic */ /* enum */ h WYVERN_5;
    public static final /* synthetic */ /* enum */ h SNAIL_6;
    public static final /* synthetic */ /* enum */ h MONKEY_3;
    public static final /* synthetic */ /* enum */ h TORTOISE_1;
    public static final /* synthetic */ /* enum */ h WYVERN_4;
    public static final /* synthetic */ /* enum */ h MOLE_5;
    public static final /* synthetic */ /* enum */ h KALPHITE_2;
    public static final /* synthetic */ /* enum */ h MOLE_1;
    public static final /* synthetic */ /* enum */ h MOLE_6;
    public static final /* synthetic */ /* enum */ h PENGUIN_3;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_5;
    public static final /* synthetic */ /* enum */ h SNAKE_6;
    public static final /* synthetic */ /* enum */ h KALPHITE_5;
    public static final /* synthetic */ /* enum */ h WYVERN_6;
    public static final /* synthetic */ /* enum */ h SLUG_2;
    public static final /* synthetic */ /* enum */ h TORTOISE_4;
    public static final /* synthetic */ /* enum */ h PENGUIN_2;
    public static final /* synthetic */ /* enum */ h LEECH_2;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_3;
    public static final /* synthetic */ /* enum */ h SLUG_4;
    public static final /* synthetic */ /* enum */ h SNAKE_4;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_4;
    public static final /* synthetic */ /* enum */ h LIZARD_2;
    public static final /* synthetic */ /* enum */ h DRAGON_3;
    public static final /* synthetic */ /* enum */ h SNAIL_4;
    public static final /* synthetic */ /* enum */ h DRAGON_5;
    public static final /* synthetic */ /* enum */ h SNAKE_5;
    public static final /* synthetic */ /* enum */ h TORTOISE_2;
    public static final /* synthetic */ /* enum */ h SNAKE_2;
    public static final /* synthetic */ /* enum */ h SNAKE_1;
    public static final /* synthetic */ /* enum */ h LIZARD_5;
    public static final /* synthetic */ /* enum */ h CAMEL_6;
    public static final /* synthetic */ /* enum */ h TORTOISE_3;
    private static final /* synthetic */ h[] $VALUES;
    public static final /* synthetic */ /* enum */ h PENGUIN_6;
    public static final /* synthetic */ /* enum */ h PENGUIN_4;
    public static final /* synthetic */ /* enum */ h DRAGON_1;
    public static final /* synthetic */ /* enum */ h WYVERN_1;
    public static final /* synthetic */ /* enum */ h TERRORBIRD_1;
    public static final /* synthetic */ /* enum */ h SNAIL_2;
    public static final /* synthetic */ /* enum */ h LEECH_4;
    public static final /* synthetic */ /* enum */ h LEECH_5;
    public static final /* synthetic */ /* enum */ h SLUG_3;
    public static final /* synthetic */ /* enum */ h MOLE_2;
    private final /* synthetic */ String answer;
    private static /* synthetic */ int[] lllllllI;
    public static final /* synthetic */ /* enum */ h KALPHITE_1;
    public static final /* synthetic */ /* enum */ h WYVERN_2;

    private h(String string2, String string3) {
        this.question = string2;
        this.answer = string3;
    }

    private static String llIIlllIIlI(String lIIlIlllIIIIIll, String lIIlIlllIIIIlII) {
        try {
            SecretKeySpec lIIlIlllIIIlIII = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(lIIlIlllIIIIlII.getBytes(StandardCharsets.UTF_8)), lllllllI[8]), "DES");
            Cipher lIIlIlllIIIIlll = Cipher.getInstance("DES");
            lIIlIlllIIIIlll.init(lllllllI[2], lIIlIlllIIIlIII);
            return new String(lIIlIlllIIIIlll.doFinal(Base64.getDecoder().decode(lIIlIlllIIIIIll.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lIIlIlllIIIIllI) {
            lIIlIlllIIIIllI.printStackTrace();
            return null;
        }
    }

    public static h valueOf(String string) {
        return Enum.valueOf(h.class, string);
    }

    /*
     * WARNING - void declaration
     */
    static {
        block1: {
            void lIIlIlllIllIlII;
            h.llIlIIlllll();
            h.llIlIIlIIlI();
            LIZARD_1 = new h(lllllIII[lllllllI[1]], lllllIII[lllllllI[2]]);
            LIZARD_2 = new h(lllllIII[lllllllI[4]], lllllIII[lllllllI[5]]);
            LIZARD_3 = new h(lllllIII[lllllllI[7]], lllllIII[lllllllI[8]]);
            LIZARD_4 = new h(lllllIII[lllllllI[10]], lllllIII[lllllllI[11]]);
            LIZARD_5 = new h(lllllIII[lllllllI[13]], lllllIII[lllllllI[14]]);
            LIZARD_6 = new h(lllllIII[lllllllI[16]], lllllIII[lllllllI[17]]);
            TORTOISE_1 = new h(lllllIII[lllllllI[19]], lllllIII[lllllllI[20]]);
            TORTOISE_2 = new h(lllllIII[lllllllI[22]], lllllIII[lllllllI[23]]);
            TORTOISE_3 = new h(lllllIII[lllllllI[25]], lllllIII[lllllllI[26]]);
            TORTOISE_4 = new h(lllllIII[lllllllI[28]], lllllIII[lllllllI[29]]);
            TORTOISE_5 = new h(lllllIII[lllllllI[31]], lllllIII[lllllllI[32]]);
            TORTOISE_6 = new h(lllllIII[lllllllI[34]], lllllIII[lllllllI[35]]);
            DRAGON_1 = new h(lllllIII[lllllllI[37]], lllllIII[lllllllI[38]]);
            DRAGON_2 = new h(lllllIII[lllllllI[40]], lllllIII[lllllllI[41]]);
            DRAGON_3 = new h(lllllIII[lllllllI[43]], lllllIII[lllllllI[44]]);
            DRAGON_4 = new h(lllllIII[lllllllI[46]], lllllIII[lllllllI[47]]);
            DRAGON_5 = new h(lllllIII[lllllllI[49]], lllllIII[lllllllI[50]]);
            DRAGON_6 = new h(lllllIII[lllllllI[52]], lllllIII[lllllllI[53]]);
            WYVERN_1 = new h(lllllIII[lllllllI[55]], lllllIII[lllllllI[56]]);
            WYVERN_2 = new h(lllllIII[lllllllI[58]], lllllIII[lllllllI[59]]);
            WYVERN_3 = new h(lllllIII[lllllllI[61]], lllllIII[lllllllI[62]]);
            WYVERN_4 = new h(lllllIII[lllllllI[64]], lllllIII[lllllllI[65]]);
            WYVERN_5 = new h(lllllIII[lllllllI[67]], lllllIII[lllllllI[68]]);
            WYVERN_6 = new h(lllllIII[lllllllI[70]], lllllIII[lllllllI[71]]);
            SNAIL_1 = new h(lllllIII[lllllllI[73]], lllllIII[lllllllI[74]]);
            SNAIL_2 = new h(lllllIII[lllllllI[76]], lllllIII[lllllllI[77]]);
            SNAIL_3 = new h(lllllIII[lllllllI[79]], lllllIII[lllllllI[80]]);
            SNAIL_4 = new h(lllllIII[lllllllI[82]], lllllIII[lllllllI[83]]);
            SNAIL_5 = new h(lllllIII[lllllllI[85]], lllllIII[lllllllI[86]]);
            SNAIL_6 = new h(lllllIII[lllllllI[88]], lllllIII[lllllllI[89]]);
            SNAKE_1 = new h(lllllIII[lllllllI[91]], lllllIII[lllllllI[92]]);
            SNAKE_2 = new h(lllllIII[lllllllI[94]], lllllIII[lllllllI[95]]);
            SNAKE_3 = new h(lllllIII[lllllllI[97]], lllllIII[lllllllI[98]]);
            SNAKE_4 = new h(lllllIII[lllllllI[100]], lllllIII[lllllllI[101]]);
            SNAKE_5 = new h(lllllIII[lllllllI[103]], lllllIII[lllllllI[104]]);
            SNAKE_6 = new h(lllllIII[lllllllI[106]], lllllIII[lllllllI[107]]);
            SLUG_1 = new h(lllllIII[lllllllI[109]], lllllIII[lllllllI[110]]);
            SLUG_2 = new h(lllllIII[lllllllI[112]], lllllIII[lllllllI[113]]);
            SLUG_3 = new h(lllllIII[lllllllI[115]], lllllIII[lllllllI[116]]);
            SLUG_4 = new h(lllllIII[lllllllI[118]], lllllIII[lllllllI[119]]);
            SLUG_5 = new h(lllllIII[lllllllI[121]], lllllIII[lllllllI[122]]);
            SLUG_6 = new h(lllllIII[lllllllI[124]], lllllIII[lllllllI[125]]);
            MONKEY_1 = new h(lllllIII[lllllllI[127]], lllllIII[lllllllI[128]]);
            MONKEY_2 = new h(lllllIII[lllllllI[130]], lllllIII[lllllllI[131]]);
            MONKEY_3 = new h(lllllIII[lllllllI[133]], lllllIII[lllllllI[134]]);
            MONKEY_4 = new h(lllllIII[lllllllI[136]], lllllIII[lllllllI[137]]);
            MONKEY_5 = new h(lllllIII[lllllllI[139]], lllllIII[lllllllI[140]]);
            MONKEY_6 = new h(lllllIII[lllllllI[142]], lllllIII[lllllllI[143]]);
            KALPHITE_1 = new h(lllllIII[lllllllI[145]], lllllIII[lllllllI[146]]);
            KALPHITE_2 = new h(lllllIII[lllllllI[148]], lllllIII[lllllllI[149]]);
            KALPHITE_3 = new h(lllllIII[lllllllI[151]], lllllIII[lllllllI[152]]);
            KALPHITE_4 = new h(lllllIII[lllllllI[154]], lllllIII[lllllllI[155]]);
            KALPHITE_5 = new h(lllllIII[lllllllI[157]], lllllIII[lllllllI[158]]);
            KALPHITE_6 = new h(lllllIII[lllllllI[160]], lllllIII[lllllllI[161]]);
            TERRORBIRD_1 = new h(lllllIII[lllllllI[163]], lllllIII[lllllllI[164]]);
            TERRORBIRD_2 = new h(lllllIII[lllllllI[166]], lllllIII[lllllllI[167]]);
            TERRORBIRD_3 = new h(lllllIII[lllllllI[169]], lllllIII[lllllllI[170]]);
            TERRORBIRD_4 = new h(lllllIII[lllllllI[172]], lllllIII[lllllllI[173]]);
            TERRORBIRD_5 = new h(lllllIII[lllllllI[175]], lllllIII[lllllllI[176]]);
            TERRORBIRD_6 = new h(lllllIII[lllllllI[178]], lllllIII[lllllllI[179]]);
            PENGUIN_1 = new h(lllllIII[lllllllI[181]], lllllIII[lllllllI[182]]);
            PENGUIN_2 = new h(lllllIII[lllllllI[184]], lllllIII[lllllllI[185]]);
            PENGUIN_3 = new h(lllllIII[lllllllI[187]], lllllIII[lllllllI[188]]);
            PENGUIN_4 = new h(lllllIII[lllllllI[190]], lllllIII[lllllllI[191]]);
            PENGUIN_5 = new h(lllllIII[lllllllI[193]], lllllIII[lllllllI[194]]);
            PENGUIN_6 = new h(lllllIII[lllllllI[196]], lllllIII[lllllllI[197]]);
            MOLE_1 = new h(lllllIII[lllllllI[199]], lllllIII[lllllllI[200]]);
            MOLE_2 = new h(lllllIII[lllllllI[202]], lllllIII[lllllllI[203]]);
            MOLE_3 = new h(lllllIII[lllllllI[205]], lllllIII[lllllllI[206]]);
            MOLE_4 = new h(lllllIII[lllllllI[208]], lllllIII[lllllllI[209]]);
            MOLE_5 = new h(lllllIII[lllllllI[211]], lllllIII[lllllllI[212]]);
            MOLE_6 = new h(lllllIII[lllllllI[214]], lllllIII[lllllllI[215]]);
            CAMEL_1 = new h(lllllIII[lllllllI[217]], lllllIII[lllllllI[218]]);
            CAMEL_2 = new h(lllllIII[lllllllI[220]], lllllIII[lllllllI[221]]);
            CAMEL_3 = new h(lllllIII[lllllllI[223]], lllllIII[lllllllI[224]]);
            CAMEL_4 = new h(lllllIII[lllllllI[226]], lllllIII[lllllllI[227]]);
            CAMEL_5 = new h(lllllIII[lllllllI[229]], lllllIII[lllllllI[230]]);
            CAMEL_6 = new h(lllllIII[lllllllI[232]], lllllIII[lllllllI[233]]);
            LEECH_1 = new h(lllllIII[lllllllI[235]], lllllIII[lllllllI[236]]);
            LEECH_2 = new h(lllllIII[lllllllI[238]], lllllIII[lllllllI[239]]);
            LEECH_3 = new h(lllllIII[lllllllI[241]], lllllIII[lllllllI[242]]);
            LEECH_4 = new h(lllllIII[lllllllI[244]], lllllIII[lllllllI[245]]);
            LEECH_5 = new h(lllllIII[lllllllI[247]], lllllIII[lllllllI[248]]);
            LEECH_6 = new h(lllllIII[lllllllI[250]], lllllIII[lllllllI[251]]);
            h[] hArray = new h[lllllllI[84]];
            hArray[h.lllllllI[0]] = LIZARD_1;
            hArray[h.lllllllI[1]] = LIZARD_2;
            hArray[h.lllllllI[2]] = LIZARD_3;
            hArray[h.lllllllI[3]] = LIZARD_4;
            hArray[h.lllllllI[4]] = LIZARD_5;
            hArray[h.lllllllI[5]] = LIZARD_6;
            hArray[h.lllllllI[6]] = TORTOISE_1;
            hArray[h.lllllllI[7]] = TORTOISE_2;
            hArray[h.lllllllI[8]] = TORTOISE_3;
            hArray[h.lllllllI[9]] = TORTOISE_4;
            hArray[h.lllllllI[10]] = TORTOISE_5;
            hArray[h.lllllllI[11]] = TORTOISE_6;
            hArray[h.lllllllI[12]] = DRAGON_1;
            hArray[h.lllllllI[13]] = DRAGON_2;
            hArray[h.lllllllI[14]] = DRAGON_3;
            hArray[h.lllllllI[15]] = DRAGON_4;
            hArray[h.lllllllI[16]] = DRAGON_5;
            hArray[h.lllllllI[17]] = DRAGON_6;
            hArray[h.lllllllI[18]] = WYVERN_1;
            hArray[h.lllllllI[19]] = WYVERN_2;
            hArray[h.lllllllI[20]] = WYVERN_3;
            hArray[h.lllllllI[21]] = WYVERN_4;
            hArray[h.lllllllI[22]] = WYVERN_5;
            hArray[h.lllllllI[23]] = WYVERN_6;
            hArray[h.lllllllI[24]] = SNAIL_1;
            hArray[h.lllllllI[25]] = SNAIL_2;
            hArray[h.lllllllI[26]] = SNAIL_3;
            hArray[h.lllllllI[27]] = SNAIL_4;
            hArray[h.lllllllI[28]] = SNAIL_5;
            hArray[h.lllllllI[29]] = SNAIL_6;
            hArray[h.lllllllI[30]] = SNAKE_1;
            hArray[h.lllllllI[31]] = SNAKE_2;
            hArray[h.lllllllI[32]] = SNAKE_3;
            hArray[h.lllllllI[33]] = SNAKE_4;
            hArray[h.lllllllI[34]] = SNAKE_5;
            hArray[h.lllllllI[35]] = SNAKE_6;
            hArray[h.lllllllI[36]] = SLUG_1;
            hArray[h.lllllllI[37]] = SLUG_2;
            hArray[h.lllllllI[38]] = SLUG_3;
            hArray[h.lllllllI[39]] = SLUG_4;
            hArray[h.lllllllI[40]] = SLUG_5;
            hArray[h.lllllllI[41]] = SLUG_6;
            hArray[h.lllllllI[42]] = MONKEY_1;
            hArray[h.lllllllI[43]] = MONKEY_2;
            hArray[h.lllllllI[44]] = MONKEY_3;
            hArray[h.lllllllI[45]] = MONKEY_4;
            hArray[h.lllllllI[46]] = MONKEY_5;
            hArray[h.lllllllI[47]] = MONKEY_6;
            hArray[h.lllllllI[48]] = KALPHITE_1;
            hArray[h.lllllllI[49]] = KALPHITE_2;
            hArray[h.lllllllI[50]] = KALPHITE_3;
            hArray[h.lllllllI[51]] = KALPHITE_4;
            hArray[h.lllllllI[52]] = KALPHITE_5;
            hArray[h.lllllllI[53]] = KALPHITE_6;
            hArray[h.lllllllI[54]] = TERRORBIRD_1;
            hArray[h.lllllllI[55]] = TERRORBIRD_2;
            hArray[h.lllllllI[56]] = TERRORBIRD_3;
            hArray[h.lllllllI[57]] = TERRORBIRD_4;
            hArray[h.lllllllI[58]] = TERRORBIRD_5;
            hArray[h.lllllllI[59]] = TERRORBIRD_6;
            hArray[h.lllllllI[60]] = PENGUIN_1;
            hArray[h.lllllllI[61]] = PENGUIN_2;
            hArray[h.lllllllI[62]] = PENGUIN_3;
            hArray[h.lllllllI[63]] = PENGUIN_4;
            hArray[h.lllllllI[64]] = PENGUIN_5;
            hArray[h.lllllllI[65]] = PENGUIN_6;
            hArray[h.lllllllI[66]] = MOLE_1;
            hArray[h.lllllllI[67]] = MOLE_2;
            hArray[h.lllllllI[68]] = MOLE_3;
            hArray[h.lllllllI[69]] = MOLE_4;
            hArray[h.lllllllI[70]] = MOLE_5;
            hArray[h.lllllllI[71]] = MOLE_6;
            hArray[h.lllllllI[72]] = CAMEL_1;
            hArray[h.lllllllI[73]] = CAMEL_2;
            hArray[h.lllllllI[74]] = CAMEL_3;
            hArray[h.lllllllI[75]] = CAMEL_4;
            hArray[h.lllllllI[76]] = CAMEL_5;
            hArray[h.lllllllI[77]] = CAMEL_6;
            hArray[h.lllllllI[78]] = LEECH_1;
            hArray[h.lllllllI[79]] = LEECH_2;
            hArray[h.lllllllI[80]] = LEECH_3;
            hArray[h.lllllllI[81]] = LEECH_4;
            hArray[h.lllllllI[82]] = LEECH_5;
            hArray[h.lllllllI[83]] = LEECH_6;
            $VALUES = hArray;
            ImmutableMap.Builder builder = new ImmutableMap.Builder();
            h[] hArray2 = h.values();
            int n2 = hArray2.length;
            int lIIlIlllIllIIll = lllllllI[0];
            while (h.llIlIlIIIII(lIIlIlllIllIIll, (int)lIIlIlllIllIlII)) {
                void lIIlIlllIllIllI;
                void lIIlIlllIllIlIl;
                void lIIlIlllIllIIlI = lIIlIlllIllIlIl[lIIlIlllIllIIll];
                lIIlIlllIllIllI.put((Object)lIIlIlllIllIIlI.question, (Object)lIIlIlllIllIIlI.answer);
                0;
                ++lIIlIlllIllIIll;
                0;
                if (-1 == -1) continue;
                break block1;
            }
            MATCHES = builder.build();
        }
    }

    /*
     * WARNING - void declaration
     */
    public static Widget a(String string, WidgetInfo ... widgetInfoArray) {
        void lIIlIlllIllllll;
        String string2 = MATCHES.get(string);
        WidgetInfo[] widgetInfoArray2 = widgetInfoArray;
        int n2 = widgetInfoArray.length;
        int lIIlIlllIlllllI = lllllllI[0];
        while (h.llIlIlIIIII(lIIlIlllIlllllI, (int)lIIlIlllIllllll)) {
            void lIIlIllllIIIIIl;
            void lIIlIllllIIIIII;
            void lIIlIlllIllllIl = lIIlIllllIIIIII[lIIlIlllIlllllI];
            Widget lIIlIlllIllllII = Widgets.get((WidgetInfo)lIIlIlllIllllIl);
            if (h.llIlIlIIIIl(lIIlIlllIllllII) && h.llIlIlIIIlI(lIIlIlllIllllII.getText().equals(lIIlIllllIIIIIl) ? 1 : 0)) {
                return lIIlIlllIllllII;
            }
            ++lIIlIlllIlllllI;
            0;
            if (-3 < 0) continue;
            return null;
        }
        return null;
    }

    private static String llIIlllIIII(String lIIlIlllIlIlIlI, String lIIlIlllIlIlIIl) {
        try {
            SecretKeySpec lIIlIlllIlIllIl = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(lIIlIlllIlIlIIl.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher lIIlIlllIlIllII = Cipher.getInstance("Blowfish");
            lIIlIlllIlIllII.init(lllllllI[2], lIIlIlllIlIllIl);
            return new String(lIIlIlllIlIllII.doFinal(Base64.getDecoder().decode(lIIlIlllIlIlIlI.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lIIlIlllIlIlIll) {
            lIIlIlllIlIlIll.printStackTrace();
            return null;
        }
    }

    private static String llIIlllIIIl(String lIIlIlllIIllIlI, String lIIlIlllIIllIIl) {
        lIIlIlllIIllIlI = new String(Base64.getDecoder().decode(lIIlIlllIIllIlI.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder lIIlIlllIIllIII = new StringBuilder();
        char[] lIIlIlllIIlIlll = lIIlIlllIIllIIl.toCharArray();
        int lIIlIlllIIlIllI = lllllllI[0];
        char[] lIIlIlllIIlIIII = lIIlIlllIIllIlI.toCharArray();
        int lIIlIlllIIIllll = lIIlIlllIIlIIII.length;
        int lIIlIlllIIIlllI = lllllllI[0];
        while (h.llIlIlIIIII(lIIlIlllIIIlllI, lIIlIlllIIIllll)) {
            char lIIlIlllIIllIll = lIIlIlllIIlIIII[lIIlIlllIIIlllI];
            lIIlIlllIIllIII.append((char)(lIIlIlllIIllIll ^ lIIlIlllIIlIlll[lIIlIlllIIlIllI % lIIlIlllIIlIlll.length]));
            0;
            ++lIIlIlllIIlIllI;
            ++lIIlIlllIIIlllI;
            0;
            if (1 <= (0x2C ^ 0x27 ^ (0x3C ^ 0x33))) continue;
            return null;
        }
        return String.valueOf(lIIlIlllIIllIII);
    }

    private static boolean llIlIlIIIlI(int n2) {
        return n2 != 0;
    }

    private static boolean llIlIlIIIIl(Object object) {
        return object != null;
    }

    public static h[] values() {
        return (h[])$VALUES.clone();
    }

    public String P() {
        return this.question;
    }

    private static void llIlIIlllll() {
        lllllllI = new int[253];
        h.lllllllI[0] = (0x89 ^ 0xB9) & ~(0xBC ^ 0x8C);
        h.lllllllI[1] = 1;
        h.lllllllI[2] = 2;
        h.lllllllI[3] = 3;
        h.lllllllI[4] = 93 + 0 - -23 + 11 ^ (0x63 ^ 0x18);
        h.lllllllI[5] = 0x54 ^ 0x51;
        h.lllllllI[6] = 2 + 109 - 16 + 43 ^ 103 + 58 - 144 + 123;
        h.lllllllI[7] = 0xBC ^ 0x86 ^ (0 ^ 0x3D);
        h.lllllllI[8] = 0xC9 ^ 0xA0 ^ (0xD5 ^ 0xB4);
        h.lllllllI[9] = (2 ^ 0x1B) & ~(4 ^ 0x1D) ^ (0x8B ^ 0x82);
        h.lllllllI[10] = 0x19 ^ 0x40 ^ (0 ^ 0x53);
        h.lllllllI[11] = 137 + 57 - 160 + 123 ^ 28 + 112 - 107 + 117;
        h.lllllllI[12] = 0x3E ^ 0x32;
        h.lllllllI[13] = 0x8F ^ 0x82;
        h.lllllllI[14] = 0x5B ^ 0x55;
        h.lllllllI[15] = 0x81 ^ 0x8E;
        h.lllllllI[16] = 0xB7 ^ 0xA7;
        h.lllllllI[17] = 0x2D ^ 0x3C;
        h.lllllllI[18] = 0x1C ^ 0xE;
        h.lllllllI[19] = 0x28 ^ 0x3B;
        h.lllllllI[20] = 4 ^ 0x10;
        h.lllllllI[21] = 0xBC ^ 0xA9;
        h.lllllllI[22] = 85 + 33 - 2 + 18 ^ 95 + 52 - 122 + 119;
        h.lllllllI[23] = 88 + 97 - 79 + 62 ^ 132 + 6 - 23 + 76;
        h.lllllllI[24] = 0x51 ^ 0x49;
        h.lllllllI[25] = 55 + 49 - -35 + 26 ^ 148 + 164 - 239 + 115;
        h.lllllllI[26] = 0xB8 ^ 0xA2;
        h.lllllllI[27] = 12 + 177 - 177 + 211 ^ 148 + 34 - 110 + 124;
        h.lllllllI[28] = 36 + 117 - 149 + 128 ^ 36 + 6 - -8 + 102;
        h.lllllllI[29] = 0x4A ^ 0x24 ^ (0xF5 ^ 0x86);
        h.lllllllI[30] = 0x10 ^ 0xE;
        h.lllllllI[31] = 0x9C ^ 0x83;
        h.lllllllI[32] = 67 + 61 - -51 + 0 ^ 0 + 62 - -22 + 63;
        h.lllllllI[33] = 0x72 ^ 0x53;
        h.lllllllI[34] = 0x62 ^ 0x72 ^ (9 ^ 0x3B);
        h.lllllllI[35] = 0xAE ^ 0x8D;
        h.lllllllI[36] = 56 + 137 - 182 + 167 ^ 146 + 132 - 210 + 82;
        h.lllllllI[37] = 0x54 ^ 0x71;
        h.lllllllI[38] = 0 ^ 0x26;
        h.lllllllI[39] = 0x48 ^ 0x2E ^ (0xCE ^ 0x8F);
        h.lllllllI[40] = 0x24 ^ 0x20 ^ (0x51 ^ 0x7D);
        h.lllllllI[41] = 0x1D ^ 0x34;
        h.lllllllI[42] = 0x71 ^ 0x5B;
        h.lllllllI[43] = 183 + 0 - 10 + 13 ^ 75 + 19 - 2 + 53;
        h.lllllllI[44] = 0x10 ^ 0x5F ^ (0xEB ^ 0x88);
        h.lllllllI[45] = 0x84 ^ 0x80 ^ (0xC ^ 0x25);
        h.lllllllI[46] = 0x2E ^ 0;
        h.lllllllI[47] = 0x84 ^ 0xAB;
        h.lllllllI[48] = 0x65 ^ 0x55;
        h.lllllllI[49] = 0xF2 ^ 0xC3;
        h.lllllllI[50] = 88 + 73 - 13 + 94 ^ 120 + 155 - 183 + 100;
        h.lllllllI[51] = 0x10 ^ 0x23;
        h.lllllllI[52] = 63 + 45 - 96 + 148 ^ 75 + 46 - -26 + 1;
        h.lllllllI[53] = 0xA9 ^ 0x9C;
        h.lllllllI[54] = 0x9E ^ 0xA8;
        h.lllllllI[55] = 96 + 49 - 134 + 123 ^ 105 + 32 - 90 + 130;
        h.lllllllI[56] = 0xC ^ 0x34;
        h.lllllllI[57] = 0x90 ^ 0xA9;
        h.lllllllI[58] = 0x95 ^ 0xAF;
        h.lllllllI[59] = 0x6A ^ 0x1A ^ (0x88 ^ 0xC3);
        h.lllllllI[60] = 0xF8 ^ 0xA7 ^ (0x3D ^ 0x5E);
        h.lllllllI[61] = 0xAA ^ 0x97;
        h.lllllllI[62] = 0x9A ^ 0xA4;
        h.lllllllI[63] = 0x30 ^ 0xF;
        h.lllllllI[64] = 0x21 ^ 0x2D ^ (0x3B ^ 0x77);
        h.lllllllI[65] = 0x35 ^ 0x74;
        h.lllllllI[66] = 0x79 ^ 0x71 ^ (0x2A ^ 0x60);
        h.lllllllI[67] = 0xA7 ^ 0x8E ^ (0xC ^ 0x66);
        h.lllllllI[68] = 0x6C ^ 0x34 ^ (0x71 ^ 0x6D);
        h.lllllllI[69] = 0xC ^ 0x49;
        h.lllllllI[70] = 134 + 146 - 72 + 2 ^ 19 + 143 - 23 + 9;
        h.lllllllI[71] = 0x74 ^ 0x58 ^ (0x57 ^ 0x3C);
        h.lllllllI[72] = 168 + 214 - 248 + 109 ^ 83 + 60 - 140 + 184;
        h.lllllllI[73] = 0xF3 ^ 0xBA;
        h.lllllllI[74] = 0x71 ^ 0x3B;
        h.lllllllI[75] = 0x16 ^ 0x5D;
        h.lllllllI[76] = 0xC1 ^ 0x8D;
        h.lllllllI[77] = 0x28 ^ 0x65;
        h.lllllllI[78] = 0x2D ^ 0x46 ^ (0xE7 ^ 0xC2);
        h.lllllllI[79] = 96 + 136 - 168 + 79 ^ 34 + 23 - 51 + 186;
        h.lllllllI[80] = 51 + 83 - -40 + 28 ^ 38 + 88 - 22 + 50;
        h.lllllllI[81] = 0xE6 ^ 0xB7;
        h.lllllllI[82] = 5 ^ 0x57;
        h.lllllllI[83] = 0x37 ^ 0x52 ^ (0x5A ^ 0x6C);
        h.lllllllI[84] = 0x3C ^ 0x68;
        h.lllllllI[85] = 0x7C ^ 0x5A ^ (0x48 ^ 0x3B);
        h.lllllllI[86] = 0xE5 ^ 0xB3;
        h.lllllllI[87] = 1 ^ (0xF0 ^ 0xA6);
        h.lllllllI[88] = 0x9A ^ 0x8B ^ (0xF6 ^ 0xBF);
        h.lllllllI[89] = 0xDB ^ 0x82;
        h.lllllllI[90] = 0xE8 ^ 0xAF ^ (0x9E ^ 0x83);
        h.lllllllI[91] = 0x46 ^ 0x1D;
        h.lllllllI[92] = 0xF3 ^ 0x80 ^ (0x52 ^ 0x7D);
        h.lllllllI[93] = 0x71 ^ 0x2C;
        h.lllllllI[94] = 0x2F ^ 0x71;
        h.lllllllI[95] = 7 ^ 0x58;
        h.lllllllI[96] = 0xD6 ^ 0xB6;
        h.lllllllI[97] = 0xE6 ^ 0x87;
        h.lllllllI[98] = 0x2B ^ 0x49;
        h.lllllllI[99] = 0x11 ^ 0x72;
        h.lllllllI[100] = 0x20 ^ 0x4F ^ (0x25 ^ 0x2E);
        h.lllllllI[101] = 0x69 ^ 0xC;
        h.lllllllI[102] = 5 + 96 - 56 + 115 ^ 61 + 195 - 186 + 128;
        h.lllllllI[103] = 0xEB ^ 0x8C;
        h.lllllllI[104] = 0x34 ^ 0x5C;
        h.lllllllI[105] = 0x3D ^ 0x54;
        h.lllllllI[106] = 0xDA ^ 0xB0;
        h.lllllllI[107] = 0x1E ^ 0x44 ^ (0xBF ^ 0x8E);
        h.lllllllI[108] = 96 + 59 - 76 + 145 ^ 111 + 33 - 90 + 86;
        h.lllllllI[109] = 0x53 ^ 0x3E;
        h.lllllllI[110] = 0xF4 ^ 0x9A;
        h.lllllllI[111] = 79 + 207 - 209 + 153 ^ 22 + 102 - 7 + 20;
        h.lllllllI[112] = 0x3A ^ 0x7F ^ (0x95 ^ 0xA0);
        h.lllllllI[113] = 96 + 194 - 145 + 57 ^ 11 + 108 - -42 + 26;
        h.lllllllI[114] = 0x30 ^ 0x36 ^ (0xE8 ^ 0x9C);
        h.lllllllI[115] = 0x4A ^ 0x39;
        h.lllllllI[116] = 142 + 237 - 262 + 126 ^ 61 + 51 - 78 + 101;
        h.lllllllI[117] = 0x53 ^ 0x27 ^ 1;
        h.lllllllI[118] = 0x6E ^ 0x18;
        h.lllllllI[119] = 0xE2 ^ 0xBE ^ (0x6C ^ 0x47);
        h.lllllllI[120] = 0xE1 ^ 0x99;
        h.lllllllI[121] = 0x76 ^ 0xF;
        h.lllllllI[122] = 0xD8 ^ 0xA2;
        h.lllllllI[123] = 0x8A ^ 0x98 ^ (0xE4 ^ 0x8D);
        h.lllllllI[124] = 2 ^ 0x7E;
        h.lllllllI[125] = 0x1B ^ 0x66;
        h.lllllllI[126] = 0xDF ^ 0xA1;
        h.lllllllI[127] = (0x2C ^ 0x60) + (0x4A ^ 0x14) - (35 + 52 - 40 + 84) + (0xED ^ 0xB5);
        h.lllllllI[128] = 80 + 92 - 50 + 6;
        h.lllllllI[129] = 38 + 113 - 67 + 45;
        h.lllllllI[130] = (0xA2 ^ 0x9B) + 2 - -(0x9C ^ 0x92) + (0x28 ^ 0x11);
        h.lllllllI[131] = 106 + 18 - 116 + 123;
        h.lllllllI[132] = (0x95 ^ 0xB4) + (0x67 ^ 0x5D) - -(0x88 ^ 0x9F) + (0xA2 ^ 0xB0);
        h.lllllllI[133] = 111 + 62 - 43 + 3;
        h.lllllllI[134] = (0x7C ^ 0x2F) + (0x1B ^ 9) - -(0x7E ^ 0x69) + (0xA7 ^ 0xAD);
        h.lllllllI[135] = 73 + 102 - 74 + 34;
        h.lllllllI[136] = (0 ^ 0x41) + (0x65 ^ 0x33) - (0x11 ^ 0x27) + (6 ^ 0x21);
        h.lllllllI[137] = 91 + 50 - 33 + 29;
        h.lllllllI[138] = (0x48 ^ 0x46) + (0x30 ^ 0x25) - -3 + (0x66 ^ 2);
        h.lllllllI[139] = 14 + 67 - -30 + 28;
        h.lllllllI[140] = 32 + 139 - 122 + 91;
        h.lllllllI[141] = 102 + 90 - 64 + 13;
        h.lllllllI[142] = (0x2C ^ 0x36) + (0x69 ^ 0x1C) - (0x70 ^ 0xA) + (0xD6 ^ 0xAF);
        h.lllllllI[143] = (0x54 ^ 0x7D) + (0x43 ^ 0x54) - -(0x93 ^ 0xB4) + (0x3B ^ 0x13);
        h.lllllllI[144] = 82 + 8 - 66 + 120;
        h.lllllllI[145] = (0xEB ^ 0xC2) + (0x66 ^ 9) - (0x76 ^ 0x44) + (0x9C ^ 0xB7);
        h.lllllllI[146] = 74 + 94 - 138 + 116;
        h.lllllllI[147] = 127 + 115 - 195 + 100;
        h.lllllllI[148] = 71 + 41 - -26 + 10;
        h.lllllllI[149] = (0xDC ^ 0xC7) + (4 ^ 0x7F) - (0x11 ^ 0x7D) + (0x6B ^ 0);
        h.lllllllI[150] = 50 + 117 - 109 + 92;
        h.lllllllI[151] = ((0x5A ^ 0xA) & ~(0x5A ^ 0xA)) + (0xA2 ^ 0xB7) - -(0x11 ^ 0x2B) + (0x6F ^ 0x27);
        h.lllllllI[152] = 69 + 121 - 108 + 70;
        h.lllllllI[153] = 141 + 130 - 198 + 80;
        h.lllllllI[154] = 33 + 96 - 78 + 103;
        h.lllllllI[155] = 113 + 57 - 81 + 48 + (0xAA ^ 0xB8) - (43 + 48 - 13 + 62) + (79 + 92 - 131 + 100);
        h.lllllllI[156] = 1 + 77 - -61 + 8 + (0xA6 ^ 0x82) - (39 + 129 - 99 + 75) + (0x15 ^ 0x60);
        h.lllllllI[157] = (0xAB ^ 0x9D) + (0x29 ^ 0x67) - (0x32 ^ 0x14) + (0x56 ^ 0x69);
        h.lllllllI[158] = 127 + 155 - 184 + 60;
        h.lllllllI[159] = 105 + 28 - 111 + 137;
        h.lllllllI[160] = 102 + 22 - -21 + 15;
        h.lllllllI[161] = 56 + 156 - 103 + 52;
        h.lllllllI[162] = (0xDC ^ 0xB0) + (33 + 70 - 40 + 81) - (29 + 6 - 28 + 235) + (129 + 94 - 82 + 11);
        h.lllllllI[163] = 51 + 60 - 105 + 138 + (11 + 141 - 94 + 97) - (187 + 8 - 153 + 151) + (0x83 ^ 0xBA);
        h.lllllllI[164] = 159 + 93 - 239 + 151;
        h.lllllllI[165] = 157 + 44 - 80 + 44;
        h.lllllllI[166] = 68 + 58 - 13 + 21 + (40 + 11 - 49 + 125) - (237 + 18 - 92 + 81) + (141 + 1 - 4 + 11);
        h.lllllllI[167] = (0x2E ^ 0x56) + (78 + 105 - 56 + 20) - (0xF9 ^ 0x81) + (0x47 ^ 0x53);
        h.lllllllI[168] = (0xBF ^ 0x9B) + (141 + 75 - 208 + 136) - (0x56 ^ 0x40) + (0xAC ^ 0xA6);
        h.lllllllI[169] = 21 + 88 - 98 + 158;
        h.lllllllI[170] = 162 + 23 - 93 + 78;
        h.lllllllI[171] = 92 + 125 - 133 + 87;
        h.lllllllI[172] = 18 + 151 - 49 + 52;
        h.lllllllI[173] = 94 + 75 - 115 + 82 + (0xBC ^ 0xBA) - (0xFA ^ 0xA4) + (0x2D ^ 0x50);
        h.lllllllI[174] = 103 + 131 - 98 + 38;
        h.lllllllI[175] = (0xD1 ^ 0x82) + (0xAA ^ 0x97) - (0xCC ^ 0xC0) + (0x92 ^ 0xB9);
        h.lllllllI[176] = 46 + 18 - -8 + 104;
        h.lllllllI[177] = 143 + 175 - 310 + 169;
        h.lllllllI[178] = 37 + 48 - 28 + 121;
        h.lllllllI[179] = 37 + 45 - 23 + 93 + (0x7F ^ 0x5D) - (19 + 11 - -15 + 106) + (97 + 31 - 67 + 83);
        h.lllllllI[180] = 116 + 80 - 64 + 16 + (23 + 31 - 16 + 133) - (85 + 157 - 15 + 28) + (0x41 ^ 0x35);
        h.lllllllI[181] = (0x95 ^ 0x81) + (0x18 ^ 0x1C) - ((0x8D ^ 0xBA) & ~(0x67 ^ 0x50)) + (20 + 81 - 9 + 65);
        h.lllllllI[182] = 179 + 177 - 337 + 163;
        h.lllllllI[183] = 163 + 113 - 102 + 9;
        h.lllllllI[184] = 11 + 172 - 144 + 145;
        h.lllllllI[185] = 27 + 99 - -10 + 49;
        h.lllllllI[186] = 109 + 167 - 183 + 93;
        h.lllllllI[187] = 135 + 138 - 261 + 175;
        h.lllllllI[188] = (0xD6 ^ 0xAF) + (0x18 ^ 0x31) - (0xB4 ^ 0xAB) + (0x33 ^ 0xA);
        h.lllllllI[189] = 71 + 135 - 152 + 100 + (5 ^ 1) - -(0x34 ^ 0x32) + (0x21 ^ 0x38);
        h.lllllllI[190] = (0x89 ^ 0xAD) + (0x84 ^ 0xA5) - -(0xAC ^ 0xC1) + (0x8B ^ 0x87);
        h.lllllllI[191] = (0xE6 ^ 0x9E) + (0x14 ^ 5) - (0xEF ^ 0xC6) + (7 ^ 0x58);
        h.lllllllI[192] = 1 + 65 - -17 + 61 + (96 + 149 - 100 + 5) - (0xFFFFABCD & 0x553B) + (127 + 21 - 33 + 48);
        h.lllllllI[193] = 72 + 98 - 28 + 51;
        h.lllllllI[194] = 132 + 178 - 144 + 28;
        h.lllllllI[195] = (9 ^ 0x27) + (0x32 ^ 0x4B) - (10 + 139 - 101 + 93) + (71 + 86 - 1 + 13);
        h.lllllllI[196] = 178 + 87 - 261 + 192;
        h.lllllllI[197] = 99 + 118 - 169 + 104 + (43 + 120 - 56 + 75) - (214 + 79 - 90 + 26) + (0x46 ^ 0x1A);
        h.lllllllI[198] = 10 + 93 - 19 + 64 + (0xD1 ^ 0x8A) - (0xC0 ^ 0xBC) + (0x71 ^ 0x22);
        h.lllllllI[199] = (0x26 ^ 0x1D) + (0xF6 ^ 0x9A) - (0x53 ^ 0x4E) + (0x4E ^ 0x73);
        h.lllllllI[200] = 101 + 34 - 124 + 149 + (26 + 103 - 17 + 24) - (14 + 68 - -5 + 86) + (0x49 ^ 4);
        h.lllllllI[201] = 21 + 41 - 25 + 164;
        h.lllllllI[202] = 126 + 26 - 28 + 78;
        h.lllllllI[203] = (0x47 ^ 0x28) + (0x23 ^ 0x7C) - (165 + 55 - 73 + 41) + (4 + 132 - -4 + 45);
        h.lllllllI[204] = (0x2C ^ 0x6D) + (0x3D ^ 0x62) - -(0x99 ^ 0x85) + (0x8F ^ 0x9F);
        h.lllllllI[205] = 85 + 49 - -9 + 62;
        h.lllllllI[206] = 96 + 161 - 51 + 0;
        h.lllllllI[207] = 8 + 129 - 108 + 178;
        h.lllllllI[208] = (0x50 ^ 0x13) + (0x30 ^ 0xA) - (0x6E ^ 0x7D) + (0x2B ^ 0x4D);
        h.lllllllI[209] = 44 + 70 - -23 + 72;
        h.lllllllI[210] = 197 + 84 - 245 + 174;
        h.lllllllI[211] = 41 + 92 - 39 + 117;
        h.lllllllI[212] = 107 + 187 - 119 + 37;
        h.lllllllI[213] = (0xF9 ^ 0x93) + (0x9B ^ 0xB8) - (0x64 ^ 0x45) + (0x14 ^ 0x7D);
        h.lllllllI[214] = (0xBB ^ 0xB4) + (140 + 19 - 50 + 102) - (3 ^ 0x18) + (0x89 ^ 0x86);
        h.lllllllI[215] = 107 + 162 - 162 + 108;
        h.lllllllI[216] = 154 + 200 - 312 + 174;
        h.lllllllI[217] = 116 + 52 - 4 + 53;
        h.lllllllI[218] = 60 + 186 - 228 + 200;
        h.lllllllI[219] = (0x79 ^ 0x4A) + (0x7C ^ 0xB) - (0xA ^ 0x10) + (0x49 ^ 2);
        h.lllllllI[220] = 2 + 56 - 51 + 133 + (0xC ^ 0x13) - (8 + 116 - 106 + 146) + (76 + 16 - -35 + 86);
        h.lllllllI[221] = 172 + 202 - 296 + 143;
        h.lllllllI[222] = 3 + (6 + 91 - -40 + 2) - 2 + (0x2D ^ 0x7F);
        h.lllllllI[223] = 14 + 136 - -30 + 43;
        h.lllllllI[224] = (0x3A ^ 0x28) + (4 + 20 - -91 + 36) - (44 + 13 - -52 + 26) + (103 + 91 - 118 + 114);
        h.lllllllI[225] = 59 + 179 - 96 + 83;
        h.lllllllI[226] = 17 + 175 - 40 + 74;
        h.lllllllI[227] = (0x57 ^ 0x36) + (80 + 25 - 29 + 75) - (0x55 ^ 0x66) + (0x3E ^ 0x20);
        h.lllllllI[228] = 63 + 135 - 29 + 8 + (183 + 184 - 199 + 21) - (0xFFFF897F & 0x77BF) + (103 + 54 - -12 + 12);
        h.lllllllI[229] = 50 + 63 - 66 + 118 + ((0xAC ^ 0xBB) & ~(0x57 ^ 0x40)) - (0xC2 ^ 0xAD) + (68 + 164 - 99 + 42);
        h.lllllllI[230] = 124 + 95 - 204 + 215;
        h.lllllllI[231] = 118 + 227 - 279 + 165;
        h.lllllllI[232] = 209 + 203 - 226 + 46;
        h.lllllllI[233] = (0x8E ^ 0xBB) + (1 + 131 - 66 + 85) - (104 + 58 - -3 + 25) + (65 + 161 - 9 + 2);
        h.lllllllI[234] = 139 + 139 - 49 + 5;
        h.lllllllI[235] = 9 + 205 - 6 + 27;
        h.lllllllI[236] = 137 + 48 - 7 + 58;
        h.lllllllI[237] = 81 + 107 - 17 + 16 + (0x36 ^ 0x47) - (148 + 144 - 218 + 114) + (0x14 ^ 0x69);
        h.lllllllI[238] = (0x27 ^ 0x6F) + (0xB7 ^ 0x84) - (0x42 ^ 0x19) + (151 + 30 - -18 + 7);
        h.lllllllI[239] = 120 + 117 - 173 + 175;
        h.lllllllI[240] = 178 + 176 - 242 + 128;
        h.lllllllI[241] = 77 + 122 - 131 + 69 + (0x4A ^ 0x3B) - (0x7F ^ 0x54) + (0x67 ^ 0x45);
        h.lllllllI[242] = 183 + 67 - 225 + 217;
        h.lllllllI[243] = (0x98 ^ 0xB7) + (0x1C ^ 0x71) - (0xB3 ^ 0x81) + (82 + 77 - 95 + 73);
        h.lllllllI[244] = 130 + 36 - -55 + 23;
        h.lllllllI[245] = 15 + 83 - 91 + 205 + (0xF1 ^ 0xA8) - (0xFFFFF907 & 0x7FF) + (147 + 15 - 150 + 195);
        h.lllllllI[246] = 115 + 215 - 211 + 127;
        h.lllllllI[247] = 187 + 85 - 215 + 190;
        h.lllllllI[248] = (0x71 ^ 0x50) + (94 + 99 - 123 + 147) - (78 + 63 - 11 + 34) + (88 + 59 - 41 + 56);
        h.lllllllI[249] = 9 + 59 - 9 + 190;
        h.lllllllI[250] = (0x4A ^ 0x47) + (135 + 81 - 101 + 83) - (0xD6 ^ 0x9A) + (0x49 ^ 0x3A);
        h.lllllllI[251] = (0x74 ^ 0x1F) + (0x66 ^ 0xD) - (0x67 ^ 0xE) + (84 + 62 - 110 + 106);
        h.lllllllI[252] = 132 + 120 - 87 + 87;
    }

    private static void llIlIIlIIlI() {
        lllllIII = new String[lllllllI[252]];
        h.lllllIII[h.lllllllI[0]] = h."LIZARD_1";
        h.lllllIII[h.lllllllI[1]] = h."How does a lizard regulate body heat?";
        h.lllllIII[h.lllllllI[2]] = h."Sunlight.";
        h.lllllIII[h.lllllllI[3]] = h."LIZARD_2";
        h.lllllIII[h.lllllllI[4]] = h."Who discovered how to kill lizards?";
        h.lllllIII[h.lllllllI[5]] = h."The Slayer Masters.";
        h.lllllIII[h.lllllllI[6]] = h."LIZARD_3";
        h.lllllIII[h.lllllllI[7]] = h."How many eyes does a lizard have?";
        h.lllllIII[h.lllllllI[8]] = h."Three.";
        h.lllllIII[h.lllllllI[9]] = h."LIZARD_4";
        h.lllllIII[h.lllllllI[10]] = h."What order do lizards belong to?";
        h.lllllIII[h.lllllllI[11]] = h."Squamata.";
        h.lllllIII[h.lllllllI[12]] = h."LIZARD_5";
        h.lllllIII[h.lllllllI[13]] = h."What happens when a lizard becomes cold?";
        h.lllllIII[h.lllllllI[14]] = h."It becomes sleepy.";
        h.lllllIII[h.lllllllI[15]] = h."LIZARD_6";
        h.lllllIII[h.lllllllI[16]] = h."Lizard skin is made of the same substance as?";
        h.lllllIII[h.lllllllI[17]] = h."Hair.";
        h.lllllIII[h.lllllllI[18]] = h."TORTOISE_1";
        h.lllllIII[h.lllllllI[19]] = h."What is the name of the oldest tortoise ever recorded?";
        h.lllllIII[h.lllllllI[20]] = h."Mibbiwocket.";
        h.lllllIII[h.lllllllI[21]] = h."TORTOISE_2";
        h.lllllIII[h.lllllllI[22]] = h."What is a tortoise's favourite food?";
        h.lllllIII[h.lllllllI[23]] = h."Vegetables.";
        h.lllllIII[h.lllllllI[24]] = h."TORTOISE_3";
        h.lllllIII[h.lllllllI[25]] = h."Name the explorer who discovered the world's oldest tortoise.";
        h.lllllIII[h.lllllllI[26]] = h."Admiral Bake.";
        h.lllllIII[h.lllllllI[27]] = h."TORTOISE_4";
        h.lllllIII[h.lllllllI[28]] = h."How does the tortoise protect itself?";
        h.lllllIII[h.lllllllI[29]] = h."Hard shell.";
        h.lllllIII[h.lllllllI[30]] = h."TORTOISE_5";
        h.lllllIII[h.lllllllI[31]] = h."If a tortoise had twenty rings on its shell, how old would it be?";
        h.lllllIII[h.lllllllI[32]] = h."Twenty years.";
        h.lllllIII[h.lllllllI[33]] = h."TORTOISE_6";
        h.lllllIII[h.lllllllI[34]] = h."Which race breeds tortoises for battle?";
        h.lllllIII[h.lllllllI[35]] = h."Gnomes.";
        h.lllllIII[h.lllllllI[36]] = h."DRAGON_1";
        h.lllllIII[h.lllllllI[37]] = h."What is considered a delicacy by dragons?";
        h.lllllIII[h.lllllllI[38]] = h."Runite.";
        h.lllllIII[h.lllllllI[39]] = h."DRAGON_2";
        h.lllllIII[h.lllllllI[40]] = h."What is the best defence against a dragon's attack?";
        h.lllllIII[h.lllllllI[41]] = h."Anti dragon-breath shield.";
        h.lllllIII[h.lllllllI[42]] = h."DRAGON_3";
        h.lllllIII[h.lllllllI[43]] = h."How long do dragons live?";
        h.lllllIII[h.lllllllI[44]] = h."Unknown.";
        h.lllllIII[h.lllllllI[45]] = h."DRAGON_4";
        h.lllllIII[h.lllllllI[46]] = h."Which of these is not a type of dragon?";
        h.lllllIII[h.lllllllI[47]] = h."Elemental.";
        h.lllllIII[h.lllllllI[48]] = h."DRAGON_5";
        h.lllllIII[h.lllllllI[49]] = h."What is the favoured territory of a dragon?";
        h.lllllIII[h.lllllllI[50]] = h."Old battle sites.";
        h.lllllIII[h.lllllllI[51]] = h."DRAGON_6";
        h.lllllIII[h.lllllllI[52]] = h."Approximately how many feet tall do dragons stand?";
        h.lllllIII[h.lllllllI[53]] = h."Twelve.";
        h.lllllIII[h.lllllllI[54]] = h."WYVERN_1";
        h.lllllIII[h.lllllllI[55]] = h."How did the wyverns die out?";
        h.lllllIII[h.lllllllI[56]] = h."Climate change.";
        h.lllllIII[h.lllllllI[57]] = h."WYVERN_2";
        h.lllllIII[h.lllllllI[58]] = h."How many legs does a wyvern have?";
        h.lllllIII[h.lllllllI[59]] = h."Two.";
        h.lllllIII[h.lllllllI[60]] = h."WYVERN_3";
        h.lllllIII[h.lllllllI[61]] = h."Where have wyvern bones been found?";
        h.lllllIII[h.lllllllI[62]] = h."Asgarnia.";
        h.lllllIII[h.lllllllI[63]] = h."WYVERN_4";
        h.lllllIII[h.lllllllI[64]] = h."Which genus does the wyvern theoretically belong to?";
        h.lllllIII[h.lllllllI[65]] = h."Reptiles.";
        h.lllllIII[h.lllllllI[66]] = h."WYVERN_5";
        h.lllllIII[h.lllllllI[67]] = h."What are the wyverns' closest relations?";
        h.lllllIII[h.lllllllI[68]] = h."Dragons.";
        h.lllllIII[h.lllllllI[69]] = h."WYVERN_6";
        h.lllllIII[h.lllllllI[70]] = h."What is the ambient temperature of wyvern bones?";
        h.lllllIII[h.lllllllI[71]] = h."Below room temperature.";
        h.lllllIII[h.lllllllI[72]] = h."SNAIL_1";
        h.lllllIII[h.lllllllI[73]] = h."What is special about the shell of the giant Morytanian snail?";
        h.lllllIII[h.lllllllI[74]] = h."It is resistant to acid.";
        h.lllllIII[h.lllllllI[75]] = h."SNAIL_2";
        h.lllllIII[h.lllllllI[76]] = h."How do Morytanian snails capture their prey?";
        h.lllllIII[h.lllllllI[77]] = h."Spitting acid.";
        h.lllllIII[h.lllllllI[78]] = h."SNAIL_3";
        h.lllllIII[h.lllllllI[79]] = h."Which of these is a snail byproduct?";
        h.lllllIII[h.lllllllI[80]] = h."Fireproof oil.";
        h.lllllIII[h.lllllllI[81]] = h."SNAIL_4";
        h.lllllIII[h.lllllllI[82]] = h."What does 'Achatina Acidia' mean?";
        h.lllllIII[h.lllllllI[83]] = h."Acid-spitting snail.";
        h.lllllIII[h.lllllllI[84]] = h."SNAIL_5";
        h.lllllIII[h.lllllllI[85]] = h."How do snails move?";
        h.lllllIII[h.lllllllI[86]] = h."Contracting and stretching.";
        h.lllllIII[h.lllllllI[87]] = h."SNAIL_6";
        h.lllllIII[h.lllllllI[88]] = h."What is the 'trapdoor', which snails use to cover the entrance to their shells called?";
        h.lllllIII[h.lllllllI[89]] = h."An operculum.";
        h.lllllIII[h.lllllllI[90]] = h."SNAKE_1";
        h.lllllIII[h.lllllllI[91]] = h."What is snake venom adapted from?";
        h.lllllIII[h.lllllllI[92]] = h."Stomach acid.";
        h.lllllIII[h.lllllllI[93]] = h."SNAKE_2";
        h.lllllIII[h.lllllllI[94]] = h."Aside from their noses, what do snakes use to smell?";
        h.lllllIII[h.lllllllI[95]] = h."Tongue.";
        h.lllllIII[h.lllllllI[96]] = h."SNAKE_3";
        h.lllllIII[h.lllllllI[97]] = h."If a snake sticks its tongue out at you, what is it doing?";
        h.lllllIII[h.lllllllI[98]] = h."Seeing how you smell.";
        h.lllllIII[h.lllllllI[99]] = h."SNAKE_4";
        h.lllllIII[h.lllllllI[100]] = h."If some snakes use venom to kill their prey, what do other snakes use?";
        h.lllllIII[h.lllllllI[101]] = h."Constriction.";
        h.lllllIII[h.lllllllI[102]] = h."SNAKE_5";
        h.lllllIII[h.lllllllI[103]] = h."Lizards and snakes belong to the same order - what is it?";
        h.lllllIII[h.lllllllI[104]] = h."Squamata.";
        h.lllllIII[h.lllllllI[105]] = h."SNAKE_6";
        h.lllllIII[h.lllllllI[106]] = h."Which habitat do snakes prefer?";
        h.lllllIII[h.lllllllI[107]] = h."Anywhere.";
        h.lllllIII[h.lllllllI[108]] = h."SLUG_1";
        h.lllllIII[h.lllllllI[109]] = h."We assume that sea slugs have a stinging organ on their soft skin - what is it called?";
        h.lllllIII[h.lllllllI[110]] = h."Nematocysts.";
        h.lllllIII[h.lllllllI[111]] = h."SLUG_2";
        h.lllllIII[h.lllllllI[112]] = h."Why has the museum never examined a live sea slug?";
        h.lllllIII[h.lllllllI[113]] = h."The researchers keep vanishing.";
        h.lllllIII[h.lllllllI[114]] = h."SLUG_3";
        h.lllllIII[h.lllllllI[115]] = h."What do we think the sea slug feeds upon?";
        h.lllllIII[h.lllllllI[116]] = h."Seaweed.";
        h.lllllIII[h.lllllllI[117]] = h."SLUG_4";
        h.lllllIII[h.lllllllI[118]] = h."What are the two fangs presumed to be used for?";
        h.lllllIII[h.lllllllI[119]] = h."Defense or display.";
        h.lllllIII[h.lllllllI[120]] = h."SLUG_5";
        h.lllllIII[h.lllllllI[121]] = h."Off of which coastline would you find sea slugs?";
        h.lllllIII[h.lllllllI[122]] = h."Ardougne.";
        h.lllllIII[h.lllllllI[123]] = h."SLUG_6";
        h.lllllIII[h.lllllllI[124]] = h."In what way are sea slugs similar to snails?";
        h.lllllIII[h.lllllllI[125]] = h."They have a hard shell.";
        h.lllllIII[h.lllllllI[126]] = h."MONKEY_1";
        h.lllllIII[h.lllllllI[127]] = h."Which type of primates do monkeys belong to?";
        h.lllllIII[h.lllllllI[128]] = h."Simian.";
        h.lllllIII[h.lllllllI[129]] = h."MONKEY_2";
        h.lllllIII[h.lllllllI[130]] = h."Which have the lighter colour: Karamjan or Harmless monkeys?";
        h.lllllIII[h.lllllllI[131]] = h."Harmless.";
        h.lllllIII[h.lllllllI[132]] = h."MONKEY_3";
        h.lllllIII[h.lllllllI[133]] = h."Monkeys love bananas. What else do they like to eat?";
        h.lllllIII[h.lllllllI[134]] = h."Bitternuts.";
        h.lllllIII[h.lllllllI[135]] = h."MONKEY_4";
        h.lllllIII[h.lllllllI[136]] = h."There are two known families of monkeys. One is Karamjan, the other is...?";
        h.lllllIII[h.lllllllI[137]] = h."Harmless.";
        h.lllllIII[h.lllllllI[138]] = h."MONKEY_5";
        h.lllllIII[h.lllllllI[139]] = h."What colour mohawk do Karamjan monkeys have?";
        h.lllllIII[h.lllllllI[140]] = h."Red.";
        h.lllllIII[h.lllllllI[141]] = h."MONKEY_6";
        h.lllllIII[h.lllllllI[142]] = h."What have Karamjan monkeys taken a deep dislike to?";
        h.lllllIII[h.lllllllI[143]] = h."Seaweed.";
        h.lllllIII[h.lllllllI[144]] = h."KALPHITE_1";
        h.lllllIII[h.lllllllI[145]] = h."Kalphites are ruled by a...?";
        h.lllllIII[h.lllllllI[146]] = h."Pasha.";
        h.lllllIII[h.lllllllI[147]] = h."KALPHITE_2";
        h.lllllIII[h.lllllllI[148]] = h."What is the lowest caste in kalphite society?";
        h.lllllIII[h.lllllllI[149]] = h."Worker.";
        h.lllllIII[h.lllllllI[150]] = h."KALPHITE_3";
        h.lllllIII[h.lllllllI[151]] = h."What are the armoured plates on a kalphite called?";
        h.lllllIII[h.lllllllI[152]] = h."Lamellae.";
        h.lllllIII[h.lllllllI[153]] = h."KALPHITE_4";
        h.lllllIII[h.lllllllI[154]] = h."Are kalphites carnivores, herbivores or omnivores?";
        h.lllllIII[h.lllllllI[155]] = h."Carnivores.";
        h.lllllIII[h.lllllllI[156]] = h."KALPHITE_5";
        h.lllllIII[h.lllllllI[157]] = h."What are kalphites assumed to have evolved from?";
        h.lllllIII[h.lllllllI[158]] = h."Scarab beetles.";
        h.lllllIII[h.lllllllI[159]] = h."KALPHITE_6";
        h.lllllIII[h.lllllllI[160]] = h."Name the prominent figure in kalphite mythology?";
        h.lllllIII[h.lllllllI[161]] = h."Scabaras.";
        h.lllllIII[h.lllllllI[162]] = h."TERRORBIRD_1";
        h.lllllIII[h.lllllllI[163]] = h."What is a terrorbird's preferred food?";
        h.lllllIII[h.lllllllI[164]] = h."Anything.";
        h.lllllIII[h.lllllllI[165]] = h."TERRORBIRD_2";
        h.lllllIII[h.lllllllI[166]] = h."Who use terrorbirds as mounts?";
        h.lllllIII[h.lllllllI[167]] = h."Gnomes.";
        h.lllllIII[h.lllllllI[168]] = h."TERRORBIRD_3";
        h.lllllIII[h.lllllllI[169]] = h."Where do terrorbirds get most of their water?";
        h.lllllIII[h.lllllllI[170]] = h."Eating plants.";
        h.lllllIII[h.lllllllI[171]] = h."TERRORBIRD_4";
        h.lllllIII[h.lllllllI[172]] = h."How many claws do terrorbirds have?";
        h.lllllIII[h.lllllllI[173]] = h."Four.";
        h.lllllIII[h.lllllllI[174]] = h."TERRORBIRD_5";
        h.lllllIII[h.lllllllI[175]] = h."What do terrorbirds eat to aid digestion?";
        h.lllllIII[h.lllllllI[176]] = h."Stones.";
        h.lllllIII[h.lllllllI[177]] = h."TERRORBIRD_6";
        h.lllllIII[h.lllllllI[178]] = h."How many teeth do terrorbirds have?";
        h.lllllIII[h.lllllllI[179]] = h."0.";
        h.lllllIII[h.lllllllI[180]] = h."PENGUIN_1";
        h.lllllIII[h.lllllllI[181]] = h."Which sense do penguins rely on when hunting?";
        h.lllllIII[h.lllllllI[182]] = h."Sight.";
        h.lllllIII[h.lllllllI[183]] = h."PENGUIN_2";
        h.lllllIII[h.lllllllI[184]] = h."Which skill seems unusual for the penguins to possess?";
        h.lllllIII[h.lllllllI[185]] = h."Planning.";
        h.lllllIII[h.lllllllI[186]] = h."PENGUIN_3";
        h.lllllIII[h.lllllllI[187]] = h."How do penguins keep warm?";
        h.lllllIII[h.lllllllI[188]] = h."A layer of fat.";
        h.lllllIII[h.lllllllI[189]] = h."PENGUIN_4";
        h.lllllIII[h.lllllllI[190]] = h."What is the preferred climate for penguins?";
        h.lllllIII[h.lllllllI[191]] = h."Cold.";
        h.lllllIII[h.lllllllI[192]] = h."PENGUIN_5";
        h.lllllIII[h.lllllllI[193]] = h."Describe the behaviour of penguins?";
        h.lllllIII[h.lllllllI[194]] = h."Social.";
        h.lllllIII[h.lllllllI[195]] = h."PENGUIN_6";
        h.lllllIII[h.lllllllI[196]] = h."When do penguins fast?";
        h.lllllIII[h.lllllllI[197]] = h."During breeding.";
        h.lllllIII[h.lllllllI[198]] = h."MOLE_1";
        h.lllllIII[h.lllllllI[199]] = h."What habitat do moles prefer?";
        h.lllllIII[h.lllllllI[200]] = h."Subterranean.";
        h.lllllIII[h.lllllllI[201]] = h."MOLE_2";
        h.lllllIII[h.lllllllI[202]] = h."Why are moles considered to be an agricultural pest?";
        h.lllllIII[h.lllllllI[203]] = h."They dig holes.";
        h.lllllIII[h.lllllllI[204]] = h."MOLE_3";
        h.lllllIII[h.lllllllI[205]] = h."Who discovered giant moles?";
        h.lllllIII[h.lllllllI[206]] = h."Wyson the Gardener.";
        h.lllllIII[h.lllllllI[207]] = h."MOLE_4";
        h.lllllIII[h.lllllllI[208]] = h."What would you call a group of young moles?";
        h.lllllIII[h.lllllllI[209]] = h."A labour.";
        h.lllllIII[h.lllllllI[210]] = h."MOLE_5";
        h.lllllIII[h.lllllllI[211]] = h."What is a mole's favourite food?";
        h.lllllIII[h.lllllllI[212]] = h."Insects and other invertebrates.";
        h.lllllIII[h.lllllllI[213]] = h."MOLE_6";
        h.lllllIII[h.lllllllI[214]] = h."Which family do moles belong to?";
        h.lllllIII[h.lllllllI[215]] = h."The Talpidae family.";
        h.lllllIII[h.lllllllI[216]] = h."CAMEL_1";
        h.lllllIII[h.lllllllI[217]] = h."What is produced by feeding chilli to a camel?";
        h.lllllIII[h.lllllllI[218]] = h."Toxic dung.";
        h.lllllIII[h.lllllllI[219]] = h."CAMEL_2";
        h.lllllIII[h.lllllllI[220]] = h."If an ugthanki has one, how many does a bactrian have?";
        h.lllllIII[h.lllllllI[221]] = h."Two.";
        h.lllllIII[h.lllllllI[222]] = h."CAMEL_3";
        h.lllllIII[h.lllllllI[223]] = h."Camels: herbivore, carnivore or omnivore?";
        h.lllllIII[h.lllllllI[224]] = h."Omnivore.";
        h.lllllIII[h.lllllllI[225]] = h."CAMEL_4";
        h.lllllIII[h.lllllllI[226]] = h."What is the usual mood for a camel?";
        h.lllllIII[h.lllllllI[227]] = h."Annoyed.";
        h.lllllIII[h.lllllllI[228]] = h."CAMEL_5";
        h.lllllIII[h.lllllllI[229]] = h."Where would you find an ugthanki?";
        h.lllllIII[h.lllllllI[230]] = h."Al Kharid.";
        h.lllllIII[h.lllllllI[231]] = h."CAMEL_6";
        h.lllllIII[h.lllllllI[232]] = h."Which camel byproduct is known to be very nutritious?";
        h.lllllIII[h.lllllllI[233]] = h."Milk.";
        h.lllllIII[h.lllllllI[234]] = h."LEECH_1";
        h.lllllIII[h.lllllllI[235]] = h."What is the favoured habitat of leeches?";
        h.lllllIII[h.lllllllI[236]] = h."Water.";
        h.lllllIII[h.lllllllI[237]] = h."LEECH_2";
        h.lllllIII[h.lllllllI[238]] = h."What shape is the inside of a leech's mouth?";
        h.lllllIII[h.lllllllI[239]] = h."'Y'-shaped.";
        h.lllllIII[h.lllllllI[240]] = h."LEECH_3";
        h.lllllIII[h.lllllllI[241]] = h."Which of these is not eaten by leeches?";
        h.lllllIII[h.lllllllI[242]] = h."Apples.";
        h.lllllIII[h.lllllllI[243]] = h."LEECH_4";
        h.lllllIII[h.lllllllI[244]] = h."What contributed to the giant growth of Morytanian leeches?";
        h.lllllIII[h.lllllllI[245]] = h."Environment.";
        h.lllllIII[h.lllllllI[246]] = h."LEECH_5";
        h.lllllIII[h.lllllllI[247]] = h."What is special about Morytanian leeches?";
        h.lllllIII[h.lllllllI[248]] = h."They attack by jumping.";
        h.lllllIII[h.lllllllI[249]] = h."LEECH_6";
        h.lllllIII[h.lllllllI[250]] = h."How does a leech change when it feeds?";
        h.lllllIII[h.lllllllI[251]] = h."It doubles in size.";
    }

    private static boolean llIlIlIIIII(int n2, int n3) {
        return n2 < n3;
    }

    public String Q() {
        return this.answer;
    }
}

