/*
 * Decompiled with CFR 0.152.
 */
package s.r.s.o.l.t.t.l.r.a.-.i.n.d.u.-.q.i.i.e.a.u;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

public final class AEnum
extends Enum<a> {
    public static final /* synthetic */ /* enum */ a QUEST_PIRATES_TREASURE;
    public static final /* synthetic */ /* enum */ a QUEST_DEATH_PLATEAU;
    public static final /* synthetic */ /* enum */ a QUEST_TRIBAL_TOTEM;
    public static final /* synthetic */ /* enum */ a QUEST_RUNE_MYSTERIES;
    public static final /* synthetic */ /* enum */ a QUEST_WITCHS_POTION;
    private final /* synthetic */ int id;
    public static final /* synthetic */ /* enum */ a QUEST_SHIELD_OF_ARRAV;
    public static final /* synthetic */ /* enum */ a QUEST_ERNEST_THE_CHICKEN;
    public static final /* synthetic */ /* enum */ a QUEST_THE_RESTLESS_GHOST;
    public static final /* synthetic */ /* enum */ a QUEST_MURDER_MYSTERY;
    public static final /* synthetic */ /* enum */ a QUEST_ROVING_ELVES;
    public static final /* synthetic */ /* enum */ a QUEST_TREE_GNOME_VILLAGE;
    public static final /* synthetic */ /* enum */ a QUEST_RAG_AND_BONE_MAN_II;
    public static final /* synthetic */ /* enum */ a QUEST_COOKS_ASSISTANT;
    public static final /* synthetic */ /* enum */ a QUEST_CABIN_FEVER;
    public static final /* synthetic */ /* enum */ a QUEST_MERLINS_CRYSTAL;
    public static final /* synthetic */ /* enum */ a QUEST_THE_GREAT_BRAIN_ROBBERY;
    public static final /* synthetic */ /* enum */ a QUEST_HOLY_GRAIL;
    public static final /* synthetic */ /* enum */ a QUEST_TROLL_ROMANCE;
    public static final /* synthetic */ /* enum */ a QUEST_DORICS_QUEST;
    public static final /* synthetic */ /* enum */ a QUEST_ENTER_THE_ABYSS;
    public static final /* synthetic */ /* enum */ a QUEST_RAG_AND_BONE_MAN_I;
    public static final /* synthetic */ /* enum */ a QUEST_THE_KNIGHTS_SWORD;
    public static final /* synthetic */ /* enum */ a QUEST_UNDERGROUND_PASS;
    public static final /* synthetic */ /* enum */ a QUEST_TAI_BWO_WANNAI_TRIO;
    public static final /* synthetic */ /* enum */ a QUEST_PLAGUE_CITY;
    public static final /* synthetic */ /* enum */ a QUEST_NATURE_SPIRIT;
    public static final /* synthetic */ /* enum */ a QUEST_BLACK_KNIGHTS_FORTRESS;
    private static /* synthetic */ int[] lIlIIIlllIIlI;
    public static final /* synthetic */ /* enum */ a QUEST_CLOCK_TOWER;
    public static final /* synthetic */ /* enum */ a QUEST_SHEEP_SHEARER;
    public static final /* synthetic */ /* enum */ a QUEST_UNDERGROUND_PASS_STATE_162;
    public static final /* synthetic */ /* enum */ a QUEST_THE_GRAND_TREE;
    public static final /* synthetic */ /* enum */ a QUEST_PRINCE_ALI_RESCUE;
    public static final /* synthetic */ /* enum */ a QUEST_DRUIDIC_RITUAL;
    public static final /* synthetic */ /* enum */ a QUEST_VAMPYRE_SLAYER;
    public static final /* synthetic */ /* enum */ a QUEST_EADGARS_RUSE;
    public static final /* synthetic */ /* enum */ a QUEST_DWARF_CANNON;
    public static final /* synthetic */ /* enum */ a QUEST_HAZEEL_CULT;
    public static final /* synthetic */ /* enum */ a QUEST_ONE_SMALL_FAVOUR;
    public static final /* synthetic */ /* enum */ a QUEST_GERTRUDES_CAT;
    public static final /* synthetic */ /* enum */ a QUEST_SHILO_VILLAGE;
    public static final /* synthetic */ /* enum */ a QUEST_HEROES_QUEST;
    public static final /* synthetic */ /* enum */ a QUEST_WATCHTOWER;
    public static final /* synthetic */ /* enum */ a QUEST_REGICIDE;
    public static final /* synthetic */ /* enum */ a QUEST_THE_TOURIST_TRAP;
    public static final /* synthetic */ /* enum */ a QUEST_WITCHS_HOUSE;
    public static final /* synthetic */ /* enum */ a QUEST_FIGHT_ARENA;
    public static final /* synthetic */ /* enum */ a QUEST_BIG_CHOMPY_BIRD_HUNTING;
    public static final /* synthetic */ /* enum */ a QUEST_THRONE_OF_MISCELLANIA;
    public static final /* synthetic */ /* enum */ a QUEST_THE_MAGE_ARENA;
    public static final /* synthetic */ /* enum */ a QUEST_ELEMENTAL_WORKSHOP_I;
    private static /* synthetic */ String[] lIlIIIllIIIII;
    public static final /* synthetic */ /* enum */ a QUEST_SEA_SLUG;
    public static final /* synthetic */ /* enum */ a QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
    public static final /* synthetic */ /* enum */ a QUEST_THE_DIG_SITE;
    public static final /* synthetic */ /* enum */ a QUEST_HAUNTED_MINE;
    public static final /* synthetic */ /* enum */ a QUEST_IMP_CATCHER;
    public static final /* synthetic */ /* enum */ a QUEST_MOURNINGS_END_PART_I;
    public static final /* synthetic */ /* enum */ a QUEST_JUNGLE_POTION;
    public static final /* synthetic */ /* enum */ a QUEST_RUM_DEAL;
    public static final /* synthetic */ /* enum */ a QUEST_LEGENDS_QUEST;
    public static final /* synthetic */ /* enum */ a QUEST_BIOHAZARD;
    public static final /* synthetic */ /* enum */ a QUEST_SHADES_OF_MORTTON;
    public static final /* synthetic */ /* enum */ a QUEST_TROLL_STRONGHOLD;
    public static final /* synthetic */ /* enum */ a QUEST_LOST_CITY;
    public static final /* synthetic */ /* enum */ a QUEST_FAMILY_CREST;
    public static final /* synthetic */ /* enum */ a QUEST_TEMPLE_OF_IKOV;
    public static final /* synthetic */ /* enum */ a QUEST_MONKEY_MADNESS_I;
    public static final /* synthetic */ /* enum */ a QUEST_THE_FREMENNIK_TRIALS;
    public static final /* synthetic */ /* enum */ a QUEST_FISHING_CONTEST;
    public static final /* synthetic */ /* enum */ a QUEST_OBSERVATORY_QUEST;
    public static final /* synthetic */ /* enum */ a QUEST_SHEEP_HERDER;
    public static final /* synthetic */ /* enum */ a QUEST_SHIELD_OF_ARRAV_STATE_146;
    public static final /* synthetic */ /* enum */ a QUEST_MONKS_FRIEND;
    public static final /* synthetic */ /* enum */ a QUEST_ROMEO_AND_JULIET;
    public static final /* synthetic */ /* enum */ a QUEST_DRAGON_SLAYER_I;
    private static final /* synthetic */ a[] $VALUES;
    public static final /* synthetic */ /* enum */ a QUEST_PRIEST_IN_PERIL;
    public static final /* synthetic */ /* enum */ a QUEST_ALFRED_GRIMHANDS_BARCRAWL;
    public static final /* synthetic */ /* enum */ a QUEST_CREATURE_OF_FENKENSTRAIN;
    public static final /* synthetic */ /* enum */ a QUEST_SCORPION_CATCHER;
    public static final /* synthetic */ /* enum */ a QUEST_IN_SEARCH_OF_THE_MYREQUE;
    public static final /* synthetic */ /* enum */ a QUEST_WATERFALL_QUEST;

    public static a[] values() {
        return (a[])$VALUES.clone();
    }

    private static String lIlllIIIIIlIlII(String var5, String var1) {
        var5 = new String(Base64.getDecoder().decode(var5.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        StringBuilder var15 = new StringBuilder();
        char[] var14 = var1.toCharArray();
        int var19 = lIlIIIlllIIlI[0];
        char[] var12 = var5.toCharArray();
        int var17 = var12.length;
        int var18 = lIlIIIlllIIlI[0];
        while (a.lIlllIIIlIIIllI(var18, var17)) {
            char var11 = var12[var18];
            var15.append((char)(var11 ^ var14[var19 % var14.length]));
            0;
            ++var19;
            ++var18;
            0;
            if (-3 < 0) continue;
            return null;
        }
        return String.valueOf(var15);
    }

    private static void lIlllIIIlIIIlIl() {
        lIlIIIlllIIlI = new int[139];
        a.lIlIIIlllIIlI[0] = (0x28 ^ 0x7E) & ~(0x19 ^ 0x4F);
        a.lIlIIIlllIIlI[1] = (0x75 ^ 0x4C) + (0x5F ^ 4) - (54 + 102 - 126 + 109) + (0x78 ^ 1);
        a.lIlIIIlllIIlI[2] = 1;
        a.lIlIIIlllIIlI[3] = 0xDB ^ 0xC6;
        a.lIlIIIlllIIlI[4] = 2;
        a.lIlIIIlllIIlI[5] = 3 ^ 0x1C;
        a.lIlIIIlllIIlI[6] = 3;
        a.lIlIIIlllIIlI[7] = 97 + 89 - 137 + 127;
        a.lIlIIIlllIIlI[8] = 107 + 110 - 204 + 146 ^ 24 + 85 - 102 + 148;
        a.lIlIIIlllIIlI[9] = 0x2E ^ 0x4B ^ (0x42 ^ 7);
        a.lIlIIIlllIIlI[10] = 8 ^ 0xD;
        a.lIlIIIlllIIlI[11] = 74 + 93 - 33 + 26;
        a.lIlIIIlllIIlI[12] = 0x61 ^ 0x1D ^ (0x33 ^ 0x49);
        a.lIlIIIlllIIlI[13] = 0x3A ^ 0x61 ^ (0x81 ^ 0xA0);
        a.lIlIIIlllIIlI[14] = 0x5E ^ 0x59;
        a.lIlIIIlllIIlI[15] = 0x6D ^ 0x2A;
        a.lIlIIIlllIIlI[16] = 0x46 ^ 0x4E;
        a.lIlIIIlllIIlI[17] = -(0xFFFFBEF7 & 0x4FAD) & (0xFFFFBFFF & 0x4FB5);
        a.lIlIIIlllIIlI[18] = 0xC9 ^ 0xC0;
        a.lIlIIIlllIIlI[19] = 0x2E ^ 0x45;
        a.lIlIIIlllIIlI[20] = 0x1D ^ 0x17;
        a.lIlIIIlllIIlI[21] = 37 + 120 - 49 + 36;
        a.lIlIIIlllIIlI[22] = 0x6D ^ 0x55 ^ (0x1E ^ 0x2D);
        a.lIlIIIlllIIlI[23] = 0x4A ^ 0x75;
        a.lIlIIIlllIIlI[24] = 0x8B ^ 0xC2 ^ (0x3A ^ 0x7F);
        a.lIlIIIlllIIlI[25] = 92 + 37 - -21 + 29;
        a.lIlIIIlllIIlI[26] = 0x96 ^ 0xC2 ^ (0xF3 ^ 0xAA);
        a.lIlIIIlllIIlI[27] = 52 + 24 - 55 + 124;
        a.lIlIIIlllIIlI[28] = 18 + 135 - 114 + 122 ^ 49 + 121 - 85 + 90;
        a.lIlIIIlllIIlI[29] = 3 + 55 - -53 + 35;
        a.lIlIIIlllIIlI[30] = 8 ^ 7;
        a.lIlIIIlllIIlI[31] = 96 + 130 - 68 + 7 + (0x35 ^ 0x63) - (117 + 38 - 37 + 27) + (0x49 ^ 1);
        a.lIlIIIlllIIlI[32] = 0xFF ^ 0xB9 ^ (0xD3 ^ 0x85);
        a.lIlIIIlllIIlI[33] = 0x67 ^ 0x24;
        a.lIlIIIlllIIlI[34] = 0xB0 ^ 0xA1;
        a.lIlIIIlllIIlI[35] = -(0xFFFFFFFF & 0x1ECB) & (0xFFFFFFEF & 0x1FFF);
        a.lIlIIIlllIIlI[36] = 0x6C ^ 0x7E;
        a.lIlIIIlllIIlI[37] = 0x1A ^ 0x5E;
        a.lIlIIIlllIIlI[38] = 0x2C ^ 0x72 ^ (0 ^ 0x4D);
        a.lIlIIIlllIIlI[39] = 0xFFFFF7BF & 0xACF;
        a.lIlIIIlllIIlI[40] = 0xAF ^ 0xBB;
        a.lIlIIIlllIIlI[41] = 0x5A ^ 0x4F;
        a.lIlIIIlllIIlI[42] = 0xFFFFA7CF & 0x59BF;
        a.lIlIIIlllIIlI[43] = 2 ^ 0x14;
        a.lIlIIIlllIIlI[44] = 0xFFFFF73E & 0x9FB;
        a.lIlIIIlllIIlI[45] = 0xE5 ^ 0xA2 ^ (0x46 ^ 0x16);
        a.lIlIIIlllIIlI[46] = (0x29 ^ 0x1E) + (0x5C ^ 0x6B) - (0xA0 ^ 0xB1) + (9 ^ 0x2F);
        a.lIlIIIlllIIlI[47] = 0x2E ^ 0x66 ^ (0x20 ^ 0x70);
        a.lIlIIIlllIIlI[48] = 0x37 ^ 0x67;
        a.lIlIIIlllIIlI[49] = 0x5D ^ 0x44;
        a.lIlIIIlllIIlI[50] = 0xE ^ 0x3E ^ (0x86 ^ 0xAC);
        a.lIlIIIlllIIlI[51] = 0xFFFFFFEF & 0x15F;
        a.lIlIIIlllIIlI[52] = 0x4F ^ 0x1E ^ (0x5B ^ 0x11);
        a.lIlIIIlllIIlI[53] = -(0xFFFF95DD & 0x7EB7) & (0xFFFF95BF & Short.MAX_VALUE);
        a.lIlIIIlllIIlI[54] = 6 ^ 0x1A;
        a.lIlIIIlllIIlI[55] = 83 + 126 - 154 + 93;
        a.lIlIIIlllIIlI[56] = 0x14 ^ 0x1C ^ (0xBB ^ 0xAD);
        a.lIlIIIlllIIlI[57] = 0xFFFFA9DB & 0x577F;
        a.lIlIIIlllIIlI[58] = 58 + 127 - 17 + 36 ^ 121 + 8 - 18 + 30;
        a.lIlIIIlllIIlI[59] = 0x49 ^ 0x7A ^ (0x5C ^ 0x4E);
        a.lIlIIIlllIIlI[60] = 28 + 146 - 7 + 13;
        a.lIlIIIlllIIlI[61] = 0xA8 ^ 0x8A;
        a.lIlIIIlllIIlI[62] = 117 + 40 - 9 + 2;
        a.lIlIIIlllIIlI[63] = 0xC ^ 0x2B ^ (0x7B ^ 0x7F);
        a.lIlIIIlllIIlI[64] = 0xFFFFFD7E & 0x3FF;
        a.lIlIIIlllIIlI[65] = 0xF ^ 0x29 ^ 2;
        a.lIlIIIlllIIlI[66] = 136 + 162 - 84 + 9;
        a.lIlIIIlllIIlI[67] = 0x70 ^ 0x79 ^ (0x1E ^ 0x32);
        a.lIlIIIlllIIlI[68] = 53 + 15 - -65 + 20 + (0x6E ^ 0x47) - (189 + 11 - 194 + 185) + (133 + 102 - 70 + 20);
        a.lIlIIIlllIIlI[69] = 0xAF ^ 0x89;
        a.lIlIIIlllIIlI[70] = 0xB7 ^ 0x90;
        a.lIlIIIlllIIlI[71] = -(0xFFFFFAF3 & 0x7D4D) & (0xFFFFFFFF & 0x79C3);
        a.lIlIIIlllIIlI[72] = 0x52 ^ 0x7A;
        a.lIlIIIlllIIlI[73] = 145 + 19 - 30 + 41;
        a.lIlIIIlllIIlI[74] = 0x73 ^ 0x5A;
        a.lIlIIIlllIIlI[75] = 16 + 40 - 49 + 132;
        a.lIlIIIlllIIlI[76] = 0x8C ^ 0xA6;
        a.lIlIIIlllIIlI[77] = 128 + 69 - 179 + 129;
        a.lIlIIIlllIIlI[78] = 0x89 ^ 0xA2;
        a.lIlIIIlllIIlI[79] = 7 ^ 0x2B;
        a.lIlIIIlllIIlI[80] = -(0xFFFFF7C3 & 0x3C3F) & (0xFFFFB7FF & 0x7D6F);
        a.lIlIIIlllIIlI[81] = 0x55 ^ 0x78;
        a.lIlIIIlllIIlI[82] = 170 + 155 - 277 + 130 ^ 138 + 49 - 46 + 15;
        a.lIlIIIlllIIlI[83] = 0xFFFFA77D & 0x5A87;
        a.lIlIIIlllIIlI[84] = 0x25 ^ 0x2E ^ (0x3B ^ 0x1F);
        a.lIlIIIlllIIlI[85] = 51 + 79 - 83 + 145;
        a.lIlIIIlllIIlI[86] = 0x69 ^ 0x7D ^ (0xAF ^ 0x8B);
        a.lIlIIIlllIIlI[87] = 0xFFFFDB3B & 0x25F7;
        a.lIlIIIlllIIlI[88] = 0x80 ^ 0x93 ^ (0xBC ^ 0x9E);
        a.lIlIIIlllIIlI[89] = 0x52 ^ 0x6C ^ (0xE6 ^ 0xA8);
        a.lIlIIIlllIIlI[90] = 5 ^ 0x37;
        a.lIlIIIlllIIlI[91] = 0xFFFF8DB1 & 0x73EE;
        a.lIlIIIlllIIlI[92] = 7 + 108 - -15 + 6 ^ 140 + 86 - 126 + 87;
        a.lIlIIIlllIIlI[93] = 101 + 133 - 92 + 23;
        a.lIlIIIlllIIlI[94] = 0x87 ^ 0xA1 ^ (0x17 ^ 5);
        a.lIlIIIlllIIlI[95] = 0xFFFFE5EF & 0x1B3E;
        a.lIlIIIlllIIlI[96] = 0x47 ^ 0x72;
        a.lIlIIIlllIIlI[97] = -(0xFFFFDD91 & 0x727F) & (0xFFFFDFDA & 0x72FF);
        a.lIlIIIlllIIlI[98] = 0x97 ^ 0xA1;
        a.lIlIIIlllIIlI[99] = -(0xFFFFFEF6 & 0x271B) & (0xFFFFA77D & 0x7FDB);
        a.lIlIIIlllIIlI[100] = 0x86 ^ 0xB5 ^ (0x5F ^ 0x5B);
        a.lIlIIIlllIIlI[101] = 0xFFFFDF9F & 0x21F2;
        a.lIlIIIlllIIlI[102] = 0x55 ^ 5 ^ (2 ^ 0x6A);
        a.lIlIIIlllIIlI[103] = 0xFFFFA25E & 0x5FF9;
        a.lIlIIIlllIIlI[104] = 0xD6 ^ 0xB8 ^ (0x23 ^ 0x74);
        a.lIlIIIlllIIlI[105] = 0x6A ^ 0x26;
        a.lIlIIIlllIIlI[106] = 0xE7 ^ 0xA5 ^ (5 ^ 0x7D);
        a.lIlIIIlllIIlI[107] = 68 + 20 - -26 + 45;
        a.lIlIIIlllIIlI[108] = 0x24 ^ 0x46 ^ (0xC7 ^ 0x9E);
        a.lIlIIIlllIIlI[109] = 0xFFFF9573 & 0x6BDF;
        a.lIlIIIlllIIlI[110] = 0x95 ^ 0xA9;
        a.lIlIIIlllIIlI[111] = 0x3B ^ 6;
        a.lIlIIIlllIIlI[112] = 0x1A ^ 0x6E;
        a.lIlIIIlllIIlI[113] = 0x59 ^ 0x67;
        a.lIlIIIlllIIlI[114] = -(0xFFFFBFFB & 0x4CA4) & (0xFFFFDDDF & 0x2FFF);
        a.lIlIIIlllIIlI[115] = 32 + 121 - 62 + 38 ^ 77 + 11 - -29 + 76;
        a.lIlIIIlllIIlI[116] = -(0xFFFFBEDB & 0x73B5) & (0xFFFFB7F7 & 0x7BFF);
        a.lIlIIIlllIIlI[117] = 128 + 173 - 122 + 18;
        a.lIlIIIlllIIlI[118] = 0x1F ^ 0x5D;
        a.lIlIIIlllIIlI[119] = 124 + 38 - 138 + 160 + (90 + 101 - 87 + 121) - (0xFFFFDD77 & 0x23EB) + (36 + 56 - -11 + 69);
        a.lIlIIIlllIIlI[120] = 0x1E ^ 0x71;
        a.lIlIIIlllIIlI[121] = 47 + 85 - 85 + 153;
        a.lIlIIIlllIIlI[122] = 0x22 ^ 0x67;
        a.lIlIIIlllIIlI[123] = 0xFFFFC9EB & 0x3795;
        a.lIlIIIlllIIlI[124] = 0xDE ^ 0x98;
        a.lIlIIIlllIIlI[125] = 0xFFFFF1BD & 0xF7F;
        a.lIlIIIlllIIlI[126] = 147 + 44 - 82 + 52;
        a.lIlIIIlllIIlI[127] = 0x24 ^ 0x37 ^ (0x62 ^ 0x39);
        a.lIlIIIlllIIlI[128] = 18 + 70 - 21 + 95;
        a.lIlIIIlllIIlI[129] = 0xC1 ^ 0x88;
        a.lIlIIIlllIIlI[130] = (0x7C ^ 0x4A) + (0x80 ^ 0xAB) - -(0x6C ^ 5) + (0xBD ^ 0xB7);
        a.lIlIIIlllIIlI[131] = 0x60 ^ 0x2A;
        a.lIlIIIlllIIlI[132] = 0xFFFFBBD7 & 0x47FC;
        a.lIlIIIlllIIlI[133] = 0xF ^ 0x44;
        a.lIlIIIlllIIlI[134] = 0xFFFF89FF & 0x77EC;
        a.lIlIIIlllIIlI[135] = 0xE3 ^ 0xAE;
        a.lIlIIIlllIIlI[136] = 12 + 53 - 28 + 186 ^ 101 + 116 - 171 + 99;
        a.lIlIIIlllIIlI[137] = 0xC4 ^ 0x8B;
        a.lIlIIIlllIIlI[138] = -(0xFFFFEAF9 & 0x5F67) & (0xFFFFDBEF & 0x6F7B);
    }

    static {
        a.lIlllIIIlIIIlIl();
        a.lIlllIIIlIIIlII();
        QUEST_BLACK_KNIGHTS_FORTRESS = new a(lIlIIIlllIIlI[1]);
        QUEST_COOKS_ASSISTANT = new a(lIlIIIlllIIlI[3]);
        QUEST_DORICS_QUEST = new a(lIlIIIlllIIlI[5]);
        QUEST_DRAGON_SLAYER_I = new a(lIlIIIlllIIlI[7]);
        QUEST_ERNEST_THE_CHICKEN = new a(lIlIIIlllIIlI[9]);
        QUEST_IMP_CATCHER = new a(lIlIIIlllIIlI[11]);
        QUEST_THE_KNIGHTS_SWORD = new a(lIlIIIlllIIlI[13]);
        QUEST_PIRATES_TREASURE = new a(lIlIIIlllIIlI[15]);
        QUEST_PRINCE_ALI_RESCUE = new a(lIlIIIlllIIlI[17]);
        QUEST_THE_RESTLESS_GHOST = new a(lIlIIIlllIIlI[19]);
        QUEST_ROMEO_AND_JULIET = new a(lIlIIIlllIIlI[21]);
        QUEST_RUNE_MYSTERIES = new a(lIlIIIlllIIlI[23]);
        QUEST_SHEEP_SHEARER = new a(lIlIIIlllIIlI[25]);
        QUEST_SHIELD_OF_ARRAV = new a(lIlIIIlllIIlI[27]);
        QUEST_SHIELD_OF_ARRAV_STATE_146 = new a(lIlIIIlllIIlI[29]);
        QUEST_VAMPYRE_SLAYER = new a(lIlIIIlllIIlI[31]);
        QUEST_WITCHS_POTION = new a(lIlIIIlllIIlI[33]);
        QUEST_BIG_CHOMPY_BIRD_HUNTING = new a(lIlIIIlllIIlI[35]);
        QUEST_BIOHAZARD = new a(lIlIIIlllIIlI[37]);
        QUEST_CABIN_FEVER = new a(lIlIIIlllIIlI[39]);
        QUEST_CLOCK_TOWER = new a(lIlIIIlllIIlI[20]);
        QUEST_CREATURE_OF_FENKENSTRAIN = new a(lIlIIIlllIIlI[42]);
        QUEST_DEATH_PLATEAU = new a(lIlIIIlllIIlI[44]);
        QUEST_THE_DIG_SITE = new a(lIlIIIlllIIlI[46]);
        QUEST_DRUIDIC_RITUAL = new a(lIlIIIlllIIlI[48]);
        QUEST_DWARF_CANNON = new a(lIlIIIlllIIlI[0]);
        QUEST_EADGARS_RUSE = new a(lIlIIIlllIIlI[51]);
        QUEST_ELEMENTAL_WORKSHOP_I = new a(lIlIIIlllIIlI[53]);
        QUEST_FAMILY_CREST = new a(lIlIIIlllIIlI[55]);
        QUEST_FIGHT_ARENA = new a(lIlIIIlllIIlI[34]);
        QUEST_FISHING_CONTEST = new a(lIlIIIlllIIlI[22]);
        QUEST_THE_FREMENNIK_TRIALS = new a(lIlIIIlllIIlI[57]);
        QUEST_WATERFALL_QUEST = new a(lIlIIIlllIIlI[58]);
        QUEST_GERTRUDES_CAT = new a(lIlIIIlllIIlI[60]);
        QUEST_THE_GRAND_TREE = new a(lIlIIIlllIIlI[62]);
        QUEST_HAUNTED_MINE = new a(lIlIIIlllIIlI[64]);
        QUEST_HAZEEL_CULT = new a(lIlIIIlllIIlI[66]);
        QUEST_HEROES_QUEST = new a(lIlIIIlllIIlI[68]);
        QUEST_HOLY_GRAIL = new a(lIlIIIlllIIlI[10]);
        QUEST_IN_SEARCH_OF_THE_MYREQUE = new a(lIlIIIlllIIlI[71]);
        QUEST_JUNGLE_POTION = new a(lIlIIIlllIIlI[73]);
        QUEST_LEGENDS_QUEST = new a(lIlIIIlllIIlI[75]);
        QUEST_LOST_CITY = new a(lIlIIIlllIIlI[77]);
        QUEST_MERLINS_CRYSTAL = new a(lIlIIIlllIIlI[28]);
        QUEST_MONKEY_MADNESS_I = new a(lIlIIIlllIIlI[80]);
        QUEST_MONKS_FRIEND = new a(lIlIIIlllIIlI[56]);
        QUEST_MOURNINGS_END_PART_I = new a(lIlIIIlllIIlI[83]);
        QUEST_MURDER_MYSTERY = new a(lIlIIIlllIIlI[85]);
        QUEST_NATURE_SPIRIT = new a(lIlIIIlllIIlI[87]);
        QUEST_OBSERVATORY_QUEST = new a(lIlIIIlllIIlI[89]);
        QUEST_ONE_SMALL_FAVOUR = new a(lIlIIIlllIIlI[91]);
        QUEST_PLAGUE_CITY = new a(lIlIIIlllIIlI[93]);
        QUEST_PRIEST_IN_PERIL = new a(lIlIIIlllIIlI[95]);
        QUEST_RAG_AND_BONE_MAN_I = new a(lIlIIIlllIIlI[97]);
        QUEST_REGICIDE = new a(lIlIIIlllIIlI[99]);
        QUEST_ROVING_ELVES = new a(lIlIIIlllIIlI[101]);
        QUEST_RUM_DEAL = new a(lIlIIIlllIIlI[103]);
        QUEST_SCORPION_CATCHER = new a(lIlIIIlllIIlI[105]);
        QUEST_SEA_SLUG = new a(lIlIIIlllIIlI[107]);
        QUEST_SHADES_OF_MORTTON = new a(lIlIIIlllIIlI[109]);
        QUEST_SHEEP_HERDER = new a(lIlIIIlllIIlI[110]);
        QUEST_SHILO_VILLAGE = new a(lIlIIIlllIIlI[112]);
        QUEST_TAI_BWO_WANNAI_TRIO = new a(lIlIIIlllIIlI[114]);
        QUEST_TEMPLE_OF_IKOV = new a(lIlIIIlllIIlI[50]);
        QUEST_THRONE_OF_MISCELLANIA = new a(lIlIIIlllIIlI[116]);
        QUEST_THE_TOURIST_TRAP = new a(lIlIIIlllIIlI[117]);
        QUEST_WITCHS_HOUSE = new a(lIlIIIlllIIlI[119]);
        QUEST_TREE_GNOME_VILLAGE = new a(lIlIIIlllIIlI[120]);
        QUEST_TRIBAL_TOTEM = new a(lIlIIIlllIIlI[121]);
        QUEST_TROLL_ROMANCE = new a(lIlIIIlllIIlI[123]);
        QUEST_TROLL_STRONGHOLD = new a(lIlIIIlllIIlI[125]);
        QUEST_UNDERGROUND_PASS = new a(lIlIIIlllIIlI[126]);
        QUEST_UNDERGROUND_PASS_STATE_162 = new a(lIlIIIlllIIlI[128]);
        QUEST_WATCHTOWER = new a(lIlIIIlllIIlI[130]);
        QUEST_THE_GREAT_BRAIN_ROBBERY = new a(lIlIIIlllIIlI[132]);
        QUEST_RAG_AND_BONE_MAN_II = new a(lIlIIIlllIIlI[97]);
        QUEST_ENTER_THE_ABYSS = new a(lIlIIIlllIIlI[134]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL = new a(lIlIIIlllIIlI[135]);
        QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76 = new a(lIlIIIlllIIlI[105]);
        QUEST_THE_MAGE_ARENA = new a(lIlIIIlllIIlI[138]);
        a[] aArray = new a[lIlIIIlllIIlI[48]];
        aArray[a.lIlIIIlllIIlI[0]] = QUEST_BLACK_KNIGHTS_FORTRESS;
        aArray[a.lIlIIIlllIIlI[2]] = QUEST_COOKS_ASSISTANT;
        aArray[a.lIlIIIlllIIlI[4]] = QUEST_DORICS_QUEST;
        aArray[a.lIlIIIlllIIlI[6]] = QUEST_DRAGON_SLAYER_I;
        aArray[a.lIlIIIlllIIlI[8]] = QUEST_ERNEST_THE_CHICKEN;
        aArray[a.lIlIIIlllIIlI[10]] = QUEST_IMP_CATCHER;
        aArray[a.lIlIIIlllIIlI[12]] = QUEST_THE_KNIGHTS_SWORD;
        aArray[a.lIlIIIlllIIlI[14]] = QUEST_PIRATES_TREASURE;
        aArray[a.lIlIIIlllIIlI[16]] = QUEST_PRINCE_ALI_RESCUE;
        aArray[a.lIlIIIlllIIlI[18]] = QUEST_THE_RESTLESS_GHOST;
        aArray[a.lIlIIIlllIIlI[20]] = QUEST_ROMEO_AND_JULIET;
        aArray[a.lIlIIIlllIIlI[22]] = QUEST_RUNE_MYSTERIES;
        aArray[a.lIlIIIlllIIlI[24]] = QUEST_SHEEP_SHEARER;
        aArray[a.lIlIIIlllIIlI[26]] = QUEST_SHIELD_OF_ARRAV;
        aArray[a.lIlIIIlllIIlI[28]] = QUEST_SHIELD_OF_ARRAV_STATE_146;
        aArray[a.lIlIIIlllIIlI[30]] = QUEST_VAMPYRE_SLAYER;
        aArray[a.lIlIIIlllIIlI[32]] = QUEST_WITCHS_POTION;
        aArray[a.lIlIIIlllIIlI[34]] = QUEST_BIG_CHOMPY_BIRD_HUNTING;
        aArray[a.lIlIIIlllIIlI[36]] = QUEST_BIOHAZARD;
        aArray[a.lIlIIIlllIIlI[38]] = QUEST_CABIN_FEVER;
        aArray[a.lIlIIIlllIIlI[40]] = QUEST_CLOCK_TOWER;
        aArray[a.lIlIIIlllIIlI[41]] = QUEST_CREATURE_OF_FENKENSTRAIN;
        aArray[a.lIlIIIlllIIlI[43]] = QUEST_DEATH_PLATEAU;
        aArray[a.lIlIIIlllIIlI[45]] = QUEST_THE_DIG_SITE;
        aArray[a.lIlIIIlllIIlI[47]] = QUEST_DRUIDIC_RITUAL;
        aArray[a.lIlIIIlllIIlI[49]] = QUEST_DWARF_CANNON;
        aArray[a.lIlIIIlllIIlI[50]] = QUEST_EADGARS_RUSE;
        aArray[a.lIlIIIlllIIlI[52]] = QUEST_ELEMENTAL_WORKSHOP_I;
        aArray[a.lIlIIIlllIIlI[54]] = QUEST_FAMILY_CREST;
        aArray[a.lIlIIIlllIIlI[3]] = QUEST_FIGHT_ARENA;
        aArray[a.lIlIIIlllIIlI[56]] = QUEST_FISHING_CONTEST;
        aArray[a.lIlIIIlllIIlI[5]] = QUEST_THE_FREMENNIK_TRIALS;
        aArray[a.lIlIIIlllIIlI[9]] = QUEST_WATERFALL_QUEST;
        aArray[a.lIlIIIlllIIlI[59]] = QUEST_GERTRUDES_CAT;
        aArray[a.lIlIIIlllIIlI[61]] = QUEST_THE_GRAND_TREE;
        aArray[a.lIlIIIlllIIlI[63]] = QUEST_HAUNTED_MINE;
        aArray[a.lIlIIIlllIIlI[65]] = QUEST_HAZEEL_CULT;
        aArray[a.lIlIIIlllIIlI[67]] = QUEST_HEROES_QUEST;
        aArray[a.lIlIIIlllIIlI[69]] = QUEST_HOLY_GRAIL;
        aArray[a.lIlIIIlllIIlI[70]] = QUEST_IN_SEARCH_OF_THE_MYREQUE;
        aArray[a.lIlIIIlllIIlI[72]] = QUEST_JUNGLE_POTION;
        aArray[a.lIlIIIlllIIlI[74]] = QUEST_LEGENDS_QUEST;
        aArray[a.lIlIIIlllIIlI[76]] = QUEST_LOST_CITY;
        aArray[a.lIlIIIlllIIlI[78]] = QUEST_MERLINS_CRYSTAL;
        aArray[a.lIlIIIlllIIlI[79]] = QUEST_MONKEY_MADNESS_I;
        aArray[a.lIlIIIlllIIlI[81]] = QUEST_MONKS_FRIEND;
        aArray[a.lIlIIIlllIIlI[82]] = QUEST_MOURNINGS_END_PART_I;
        aArray[a.lIlIIIlllIIlI[84]] = QUEST_MURDER_MYSTERY;
        aArray[a.lIlIIIlllIIlI[86]] = QUEST_NATURE_SPIRIT;
        aArray[a.lIlIIIlllIIlI[88]] = QUEST_OBSERVATORY_QUEST;
        aArray[a.lIlIIIlllIIlI[90]] = QUEST_ONE_SMALL_FAVOUR;
        aArray[a.lIlIIIlllIIlI[92]] = QUEST_PLAGUE_CITY;
        aArray[a.lIlIIIlllIIlI[94]] = QUEST_PRIEST_IN_PERIL;
        aArray[a.lIlIIIlllIIlI[96]] = QUEST_RAG_AND_BONE_MAN_I;
        aArray[a.lIlIIIlllIIlI[98]] = QUEST_REGICIDE;
        aArray[a.lIlIIIlllIIlI[100]] = QUEST_ROVING_ELVES;
        aArray[a.lIlIIIlllIIlI[102]] = QUEST_RUM_DEAL;
        aArray[a.lIlIIIlllIIlI[104]] = QUEST_SCORPION_CATCHER;
        aArray[a.lIlIIIlllIIlI[106]] = QUEST_SEA_SLUG;
        aArray[a.lIlIIIlllIIlI[108]] = QUEST_SHADES_OF_MORTTON;
        aArray[a.lIlIIIlllIIlI[110]] = QUEST_SHEEP_HERDER;
        aArray[a.lIlIIIlllIIlI[111]] = QUEST_SHILO_VILLAGE;
        aArray[a.lIlIIIlllIIlI[113]] = QUEST_TAI_BWO_WANNAI_TRIO;
        aArray[a.lIlIIIlllIIlI[23]] = QUEST_TEMPLE_OF_IKOV;
        aArray[a.lIlIIIlllIIlI[115]] = QUEST_THRONE_OF_MISCELLANIA;
        aArray[a.lIlIIIlllIIlI[58]] = QUEST_THE_TOURIST_TRAP;
        aArray[a.lIlIIIlllIIlI[118]] = QUEST_WITCHS_HOUSE;
        aArray[a.lIlIIIlllIIlI[33]] = QUEST_TREE_GNOME_VILLAGE;
        aArray[a.lIlIIIlllIIlI[37]] = QUEST_TRIBAL_TOTEM;
        aArray[a.lIlIIIlllIIlI[122]] = QUEST_TROLL_ROMANCE;
        aArray[a.lIlIIIlllIIlI[124]] = QUEST_TROLL_STRONGHOLD;
        aArray[a.lIlIIIlllIIlI[15]] = QUEST_UNDERGROUND_PASS;
        aArray[a.lIlIIIlllIIlI[127]] = QUEST_UNDERGROUND_PASS_STATE_162;
        aArray[a.lIlIIIlllIIlI[129]] = QUEST_WATCHTOWER;
        aArray[a.lIlIIIlllIIlI[131]] = QUEST_THE_GREAT_BRAIN_ROBBERY;
        aArray[a.lIlIIIlllIIlI[133]] = QUEST_RAG_AND_BONE_MAN_II;
        aArray[a.lIlIIIlllIIlI[105]] = QUEST_ENTER_THE_ABYSS;
        aArray[a.lIlIIIlllIIlI[135]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL;
        aArray[a.lIlIIIlllIIlI[136]] = QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76;
        aArray[a.lIlIIIlllIIlI[137]] = QUEST_THE_MAGE_ARENA;
        $VALUES = aArray;
    }

    private a(int n3) {
        this.id = n3;
    }

    public int d() {
        return this.id;
    }

    public static a valueOf(String string) {
        return Enum.valueOf(a.class, string);
    }

    private static void lIlllIIIlIIIlII() {
        lIlIIIllIIIII = new String[lIlIIIlllIIlI[48]];
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[0]] = a."QUEST_BLACK_KNIGHTS_FORTRESS";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[2]] = a."QUEST_COOKS_ASSISTANT";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[4]] = a."QUEST_DORICS_QUEST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[6]] = a."QUEST_DRAGON_SLAYER_I";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[8]] = a."QUEST_ERNEST_THE_CHICKEN";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[10]] = a."QUEST_IMP_CATCHER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[12]] = a."QUEST_THE_KNIGHTS_SWORD";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[14]] = a."QUEST_PIRATES_TREASURE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[16]] = a."QUEST_PRINCE_ALI_RESCUE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[18]] = a."QUEST_THE_RESTLESS_GHOST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[20]] = a."QUEST_ROMEO_AND_JULIET";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[22]] = a."QUEST_RUNE_MYSTERIES";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[24]] = a."QUEST_SHEEP_SHEARER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[26]] = a."QUEST_SHIELD_OF_ARRAV";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[28]] = a."QUEST_SHIELD_OF_ARRAV_STATE_146";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[30]] = a."QUEST_VAMPYRE_SLAYER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[32]] = a."QUEST_WITCHS_POTION";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[34]] = a."QUEST_BIG_CHOMPY_BIRD_HUNTING";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[36]] = a."QUEST_BIOHAZARD";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[38]] = a."QUEST_CABIN_FEVER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[40]] = a."QUEST_CLOCK_TOWER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[41]] = a."QUEST_CREATURE_OF_FENKENSTRAIN";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[43]] = a."QUEST_DEATH_PLATEAU";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[45]] = a."QUEST_THE_DIG_SITE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[47]] = a."QUEST_DRUIDIC_RITUAL";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[49]] = a."QUEST_DWARF_CANNON";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[50]] = a."QUEST_EADGARS_RUSE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[52]] = a."QUEST_ELEMENTAL_WORKSHOP_I";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[54]] = a."QUEST_FAMILY_CREST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[3]] = a."QUEST_FIGHT_ARENA";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[56]] = a."QUEST_FISHING_CONTEST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[5]] = a."QUEST_THE_FREMENNIK_TRIALS";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[9]] = a."QUEST_WATERFALL_QUEST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[59]] = a."QUEST_GERTRUDES_CAT";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[61]] = a."QUEST_THE_GRAND_TREE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[63]] = a."QUEST_HAUNTED_MINE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[65]] = a."QUEST_HAZEEL_CULT";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[67]] = a."QUEST_HEROES_QUEST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[69]] = a."QUEST_HOLY_GRAIL";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[70]] = a."QUEST_IN_SEARCH_OF_THE_MYREQUE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[72]] = a."QUEST_JUNGLE_POTION";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[74]] = a."QUEST_LEGENDS_QUEST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[76]] = a."QUEST_LOST_CITY";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[78]] = a."QUEST_MERLINS_CRYSTAL";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[79]] = a."QUEST_MONKEY_MADNESS_I";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[81]] = a."QUEST_MONKS_FRIEND";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[82]] = a."QUEST_MOURNINGS_END_PART_I";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[84]] = a."QUEST_MURDER_MYSTERY";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[86]] = a."QUEST_NATURE_SPIRIT";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[88]] = a."QUEST_OBSERVATORY_QUEST";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[90]] = a."QUEST_ONE_SMALL_FAVOUR";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[92]] = a."QUEST_PLAGUE_CITY";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[94]] = a."QUEST_PRIEST_IN_PERIL";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[96]] = a."QUEST_RAG_AND_BONE_MAN_I";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[98]] = a."QUEST_REGICIDE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[100]] = a."QUEST_ROVING_ELVES";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[102]] = a."QUEST_RUM_DEAL";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[104]] = a."QUEST_SCORPION_CATCHER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[106]] = a."QUEST_SEA_SLUG";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[108]] = a."QUEST_SHADES_OF_MORTTON";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[110]] = a."QUEST_SHEEP_HERDER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[111]] = a."QUEST_SHILO_VILLAGE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[113]] = a."QUEST_TAI_BWO_WANNAI_TRIO";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[23]] = a."QUEST_TEMPLE_OF_IKOV";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[115]] = a."QUEST_THRONE_OF_MISCELLANIA";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[58]] = a."QUEST_THE_TOURIST_TRAP";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[118]] = a."QUEST_WITCHS_HOUSE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[33]] = a."QUEST_TREE_GNOME_VILLAGE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[37]] = a."QUEST_TRIBAL_TOTEM";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[122]] = a."QUEST_TROLL_ROMANCE";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[124]] = a."QUEST_TROLL_STRONGHOLD";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[15]] = a."QUEST_UNDERGROUND_PASS";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[127]] = a."QUEST_UNDERGROUND_PASS_STATE_162";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[129]] = a."QUEST_WATCHTOWER";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[131]] = a."QUEST_THE_GREAT_BRAIN_ROBBERY";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[133]] = a."QUEST_RAG_AND_BONE_MAN_II";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[105]] = a."QUEST_ENTER_THE_ABYSS";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[135]] = a."QUEST_ALFRED_GRIMHANDS_BARCRAWL";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[136]] = a."QUEST_ALFRED_GRIMHANDS_BARCRAWL_STATE_76";
        a.lIlIIIllIIIII[a.lIlIIIlllIIlI[137]] = a."QUEST_THE_MAGE_ARENA";
    }

    private static String lIlllIIIIIlIllI(String var9, String var16) {
        try {
            SecretKeySpec var4 = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(var16.getBytes(StandardCharsets.UTF_8)), lIlIIIlllIIlI[16]), "DES");
            Cipher var13 = Cipher.getInstance("DES");
            var13.init(lIlIIIlllIIlI[4], var4);
            return new String(var13.doFinal(Base64.getDecoder().decode(var9.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception var10) {
            var10.printStackTrace();
            return null;
        }
    }

    private static String lIlllIIIIIlIlIl(String var7, String var3) {
        try {
            SecretKeySpec var6 = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(var3.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            Cipher var8 = Cipher.getInstance("Blowfish");
            var8.init(lIlIIIlllIIlI[4], var6);
            return new String(var8.doFinal(Base64.getDecoder().decode(var7.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception var2) {
            var2.printStackTrace();
            return null;
        }
    }

    private static boolean lIlllIIIlIIIllI(int n2, int n3) {
        return n2 < n3;
    }
}

